package com.aoo.bcg.inventory;

import com.fasterxml.jackson.databind.ObjectMapper;import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import java.sql.*;import java.time.*;import static org.junit.jupiter.api.Assertions.*;

final class JdbcInventoryStoreServiceTest {
 private JdbcDataSource db;private FakeBilling billing;private JdbcInventoryStoreService service;private final Instant now=Instant.parse("2026-08-24T00:00:00Z");
 @BeforeEach void setup()throws Exception{db=new JdbcDataSource();db.setURL("jdbc:h2:mem:inventory;MODE=MySQL;DB_CLOSE_DELAY=-1");try(var c=db.getConnection();var s=c.createStatement()){s.execute("DROP ALL OBJECTS");s.execute("CREATE TABLE aoo_item_catalog(item_code VARCHAR(64) PRIMARY KEY,item_name VARCHAR(120),item_type VARCHAR(32),consumable BOOLEAN,active_from TIMESTAMP,active_until TIMESTAMP,attributes_json VARCHAR(1000))");s.execute("CREATE TABLE aoo_store_offer(offer_code VARCHAR(64) PRIMARY KEY,item_code VARCHAR(64),item_quantity BIGINT,currency_code VARCHAR(32),price_minor BIGINT,active_from TIMESTAMP,active_until TIMESTAMP)");s.execute("CREATE TABLE aoo_inventory_command(command_id VARCHAR(128) PRIMARY KEY,command_kind VARCHAR(24),command_state VARCHAR(32),player_id BIGINT,reference_code VARCHAR(128),error_message VARCHAR(500),created_at TIMESTAMP,updated_at TIMESTAMP)");s.execute("CREATE TABLE aoo_inventory_lot(id BIGINT AUTO_INCREMENT PRIMARY KEY,player_id BIGINT,item_code VARCHAR(64),quantity BIGINT,expires_at TIMESTAMP,row_version BIGINT,created_at TIMESTAMP)");s.execute("CREATE TABLE aoo_inventory_movement(id BIGINT AUTO_INCREMENT PRIMARY KEY,command_id VARCHAR(128),player_id BIGINT,item_code VARCHAR(64),quantity_delta BIGINT,movement_type VARCHAR(24),source_reference VARCHAR(128),created_at TIMESTAMP)");s.execute("CREATE TABLE aoo_redemption_campaign(id BIGINT AUTO_INCREMENT PRIMARY KEY,campaign_code VARCHAR(64),item_code VARCHAR(64),item_quantity BIGINT,grant_expires_at TIMESTAMP,active_from TIMESTAMP,active_until TIMESTAMP)");s.execute("CREATE TABLE aoo_redemption_code(code_hash CHAR(64) PRIMARY KEY,campaign_id BIGINT,status VARCHAR(16))");s.execute("CREATE TABLE aoo_redemption_claim(id BIGINT AUTO_INCREMENT PRIMARY KEY,campaign_id BIGINT,code_hash CHAR(64) UNIQUE,player_id BIGINT,command_id VARCHAR(128),claimed_at TIMESTAMP,UNIQUE(campaign_id,player_id))");s.execute("INSERT INTO aoo_item_catalog VALUES('ticket','Room Ticket','CONSUMABLE',TRUE,TIMESTAMP '2026-01-01 00:00:00',NULL,'{}')");s.execute("INSERT INTO aoo_store_offer VALUES('ticket-5','ticket',5,'GOLD',100,TIMESTAMP '2026-01-01 00:00:00',NULL)");}
 billing=new FakeBilling();service=new JdbcInventoryStoreService(db,billing,new ObjectMapper(),Clock.fixed(now,ZoneOffset.UTC));}
 @Test void grantUseAndIdempotencyAreDurable(){var first=service.grant("grant-1",7,"ticket",3,null,"MISSION");var replay=service.grant("grant-1",7,"ticket",99,null,"MISSION");assertEquals(first,replay);service.use("use-1",7,"ticket",2);assertEquals(1,service.inventory(7,now).getFirst().quantity());assertThrows(IllegalStateException.class,()->service.use("use-2",7,"ticket",2));}
 @Test void purchaseDebitsBillingOnceAndCanBeRevoked(){service.purchase("buy-1",7,"ticket-5");service.purchase("buy-1",7,"ticket-5");assertEquals(1,billing.debits);assertEquals(5,service.inventory(7,now).getFirst().quantity());service.revoke("undo-1","buy-1","OPERATOR_REVERSAL");assertTrue(service.inventory(7,now).isEmpty());}
 @Test void failedGrantAfterDebitRequestsBillingCompensation()throws Exception{try(var c=db.getConnection();var s=c.createStatement()){s.execute("DROP TABLE aoo_inventory_lot");}assertThrows(IllegalStateException.class,()->service.purchase("buy-broken",7,"ticket-5"));assertEquals(1,billing.debits);assertEquals(1,billing.refunds);}
 private static final class FakeBilling implements BillingPort{int debits,refunds;public void debit(String k,long p,String c,long a,String r){debits++;}public void refund(String k,long p,String c,long a,String r){refunds++;}}
}
