package com.aoo.bcg.referral;

import javax.sql.DataSource;
import java.math.*;
import java.sql.*;
import java.time.*;
import java.util.*;

/** JDBC adapter over the legacy authoritative club-member and room-performance tables. */
public final class JdbcPromoterRepository {
    private final DataSource source;private final Clock clock;
    public JdbcPromoterRepository(DataSource source,Clock clock){this.source=Objects.requireNonNull(source);this.clock=Objects.requireNonNull(clock);}
    public Map<String,Object> bind(long clubId,long playerId,long promoterId){if(playerId==promoterId)throw new IllegalArgumentException("self binding is forbidden");try(Connection c=source.getConnection()){c.setAutoCommit(false);try{
        Member promoter=lock(c,clubId,promoterId),player=lock(c,clubId,playerId);if(promoter.level<=0&&promoter.promotion!=1)throw new IllegalStateException("target promoter is not appointed");if(player.upLevelId!=0&&player.upLevelId!=promoterId)throw new IllegalStateException("promotion relationship already bound");
        try(PreparedStatement q=c.prepareStatement("UPDATE dbClubmember SET upLevelId=?,updatetime=? WHERE id=?")){q.setLong(1,promoterId);q.setLong(2,clock.instant().getEpochSecond());q.setLong(3,player.id);q.executeUpdate();}c.commit();return relation(clubId,playerId,promoterId);
    }catch(Exception e){c.rollback();throw e;}}catch(SQLException e){throw new IllegalStateException("promotion binding persistence failed",e);}}
    public Map<String,Object> relation(long clubId,long playerId){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("SELECT upLevelId FROM dbClubmember WHERE clubID=? AND playerID=? AND status=4")){q.setLong(1,clubId);q.setLong(2,playerId);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("active club member not found");return relation(clubId,playerId,r.getLong(1));}}catch(SQLException e){throw new IllegalStateException("promotion relationship query failed",e);}}
    public Map<String,Object> summary(long clubId,long promoterId,int fromDate,int toDate){if(fromDate>toDate)throw new IllegalArgumentException("invalid date range");String sql="SELECT COUNT(DISTINCT p.pid),COALESCE(SUM(p.setCount),0),COALESCE(SUM(p.roomSportsConsume),0),COALESCE(SUM(p.sportsPoint),0) FROM PlayerRoomAlone p JOIN dbClubmember m ON m.clubID=p.clubID AND m.playerID=p.pid AND m.status=4 WHERE p.clubID=? AND m.upLevelId=? AND p.dateTime BETWEEN ? AND ?";try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement(sql)){q.setLong(1,clubId);q.setLong(2,promoterId);q.setInt(3,fromDate);q.setInt(4,toDate);try(ResultSet r=q.executeQuery()){r.next();return Map.of("clubId",clubId,"promoterId",promoterId,"fromDate",fromDate,"toDate",toDate,"players",r.getLong(1),"rounds",r.getLong(2),"consumption",r.getBigDecimal(3),"performance",r.getBigDecimal(4));}}catch(SQLException e){throw new IllegalStateException("performance summary failed",e);}}
    public Map<String,Object> calculate(String commandId,long clubId,long promoterId,int fromDate,int toDate,BigDecimal rate,String currency){if(rate.signum()<0||rate.compareTo(BigDecimal.ONE)>0)throw new IllegalArgumentException("rate must be between 0 and 1");Map<String,Object>s=summary(clubId,promoterId,fromDate,toDate);BigDecimal base=(BigDecimal)s.get("consumption"),amount=base.multiply(rate).setScale(0,RoundingMode.DOWN);try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("INSERT INTO promoter_commission_instruction(command_id,club_id,promoter_id,from_date,to_date,base_amount,rate,commission_amount,currency,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'CALCULATED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)")){q.setString(1,commandId);q.setLong(2,clubId);q.setLong(3,promoterId);q.setInt(4,fromDate);q.setInt(5,toDate);q.setBigDecimal(6,base);q.setBigDecimal(7,rate);q.setBigDecimal(8,amount);q.setString(9,currency);q.executeUpdate();return status(commandId);}catch(SQLIntegrityConstraintViolationException e){return status(commandId);}catch(SQLException e){throw new IllegalStateException("commission instruction persistence failed",e);}}
    public Map<String,Object> status(String id){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("SELECT club_id,promoter_id,from_date,to_date,base_amount,rate,commission_amount,currency,status,billing_reference FROM promoter_commission_instruction WHERE command_id=?")){q.setString(1,id);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("commission instruction not found");Map<String,Object> m=new LinkedHashMap<>();m.put("commandId",id);m.put("clubId",r.getLong(1));m.put("promoterId",r.getLong(2));m.put("fromDate",r.getInt(3));m.put("toDate",r.getInt(4));m.put("baseAmount",r.getBigDecimal(5));m.put("rate",r.getBigDecimal(6));m.put("commissionAmount",r.getBigDecimal(7));m.put("currency",r.getString(8));m.put("status",r.getString(9));m.put("billingReference",r.getString(10));return m;}}catch(SQLException e){throw new IllegalStateException("commission status query failed",e);}}
    public Map<String,Object> markSettled(String id){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("UPDATE promoter_commission_instruction SET status='SETTLED',billing_reference=?,updated_at=CURRENT_TIMESTAMP WHERE command_id=? AND status='CALCULATED'")){q.setString(1,"commission:"+id);q.setString(2,id);if(q.executeUpdate()!=1)throw new IllegalStateException("commission is not settleable");return status(id);}catch(SQLException e){throw new IllegalStateException("commission settlement state failed",e);}}
    public Map<String,Object> reserveInviteReward(String key,long consumption,long invite,long issuer,long consumer,String kind,long target){try(Connection c=source.getConnection()){try(PreparedStatement q=c.prepareStatement("INSERT INTO referral_invite_reward_instruction(idempotency_key,consumption_id,invite_id,issuer_account_id,consumer_account_id,kind,target_id,currency,reward_amount,status,created_at,updated_at) SELECT ?,?,?,?,?,?,?,currency,reward_amount,'RESERVED',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3) FROM referral_invite_reward_policy WHERE kind=? AND enabled=1")){q.setString(1,key);q.setLong(2,consumption);q.setLong(3,invite);q.setLong(4,issuer);q.setLong(5,consumer);q.setString(6,kind);q.setLong(7,target);q.setString(8,kind);if(q.executeUpdate()!=1)throw new IllegalStateException("invite reward policy unavailable");}catch(SQLIntegrityConstraintViolationException ignored){}return inviteReward(key);}catch(SQLException e){throw new IllegalStateException("invite reward persistence failed",e);}}
    public Map<String,Object> inviteReward(String key){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("SELECT consumer_account_id,target_id,currency,reward_amount,status,billing_reference FROM referral_invite_reward_instruction WHERE idempotency_key=?")){q.setString(1,key);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("invite reward not found");Map<String,Object>m=new LinkedHashMap<>();m.put("consumerId",r.getLong(1));m.put("targetId",r.getLong(2));m.put("currency",r.getString(3));m.put("amount",r.getBigDecimal(4));m.put("status",r.getString(5));m.put("reference",Objects.toString(r.getString(6),"invite-reward:"+key));return m;}}catch(SQLException e){throw new IllegalStateException("invite reward query failed",e);}}
    public Map<String,Object> completeInviteReward(String key){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("UPDATE referral_invite_reward_instruction SET status='GRANTED',billing_reference=?,updated_at=CURRENT_TIMESTAMP(3) WHERE idempotency_key=? AND status='RESERVED'")){q.setString(1,"invite-reward:"+key);q.setString(2,key);q.executeUpdate();return inviteReward(key);}catch(SQLException e){throw new IllegalStateException("invite reward completion failed",e);}}
    private Member lock(Connection c,long club,long player)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT id,upLevelId,level,promotion FROM dbClubmember WHERE clubID=? AND playerID=? AND status=4 FOR UPDATE")){q.setLong(1,club);q.setLong(2,player);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("active club member not found");return new Member(r.getLong(1),r.getLong(2),r.getInt(3),r.getInt(4));}}}
    private static Map<String,Object> relation(long club,long player,long promoter){return Map.of("clubId",club,"playerId",player,"promoterId",promoter,"bound",promoter>0);}
    private record Member(long id,long upLevelId,int level,int promotion){}
}
