package com.aoo.bcg.referral;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.*;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

/** Internal versioned surface for the verified legacy promoter call chain. */
public final class ReferralHttpRoutes {
    private final PromoterService service;private final ObjectMapper json;private final byte[] token;
    public ReferralHttpRoutes(PromoterService service,ObjectMapper json,String token){this.service=Objects.requireNonNull(service);this.json=Objects.requireNonNull(json);if(token==null||token.length()<32)throw new IllegalArgumentException("referral token must be at least 32 characters");this.token=token.getBytes(StandardCharsets.UTF_8);}
    public void mount(HttpServer server){server.createContext("/health/referral",e->reply(e,200,Map.of("status","UP","persistence","jdbc","apiVersion","1")));server.createContext("/v1/promoters",this::handle);server.createContext("/v1/commissions",this::handle);server.createContext("/v1/invite-rewards",this::handle);}
    private void handle(HttpExchange ex)throws IOException{try{if(!"POST".equals(ex.getRequestMethod()))throw new Api(405,"METHOD_NOT_ALLOWED","POST required");if(!"1".equals(ex.getRequestHeaders().getFirst("X-API-Version")))throw new Api(426,"API_VERSION_REQUIRED","X-API-Version: 1 required");authenticate(ex);Map<String,Object> f=body(ex);String action=text(f,"action");Object data=switch(action){case "bind"->service.bind(number(f,"clubId"),number(f,"playerId"),number(f,"promoterId"));case "relationship"->service.relation(number(f,"clubId"),number(f,"playerId"));case "summary"->service.summary(number(f,"clubId"),number(f,"promoterId"),integer(f,"fromDate"),integer(f,"toDate"));case "calculate"->service.calculate(command(ex),number(f,"clubId"),number(f,"promoterId"),integer(f,"fromDate"),integer(f,"toDate"),decimal(f,"rate"),text(f,"currency"));case "status"->service.status(text(f,"commandId"));case "settle"->service.settle(text(f,"commandId"));case "inviteReward"->service.inviteReward(command(ex),number(f,"consumptionId"),number(f,"inviteId"),number(f,"issuerId"),number(f,"consumerId"),text(f,"kind"),number(f,"targetId"));default->throw new IllegalArgumentException("unknown action");};reply(ex,200,Map.of("code","OK","data",data));}catch(Api e){reply(ex,e.status,Map.of("code",e.code,"message",e.getMessage()));}catch(SecurityException e){reply(ex,401,Map.of("code","UNAUTHORIZED","message",e.getMessage()));}catch(IllegalArgumentException e){reply(ex,400,Map.of("code","INVALID_REQUEST","message",String.valueOf(e.getMessage())));}catch(IllegalStateException e){reply(ex,409,Map.of("code","CONFLICT","message",String.valueOf(e.getMessage())));}catch(Exception e){reply(ex,503,Map.of("code","DEPENDENCY_UNAVAILABLE","message","reward dependency unavailable"));}}
    private void authenticate(HttpExchange e){String h=e.getRequestHeaders().getFirst("Authorization");byte[] supplied=h!=null&&h.startsWith("Bearer ")?h.substring(7).getBytes(StandardCharsets.UTF_8):new byte[0];if(!MessageDigest.isEqual(token,supplied))throw new SecurityException("invalid referral credential");}
    @SuppressWarnings("unchecked")private Map<String,Object> body(HttpExchange e)throws IOException{return json.readValue(e.getRequestBody(),Map.class);}private String command(HttpExchange e){String v=e.getRequestHeaders().getFirst("Idempotency-Key");if(v==null||!v.matches("[A-Za-z0-9_.:-]{1,128}"))throw new IllegalArgumentException("valid Idempotency-Key required");return v;}
    private static String text(Map<String,Object>f,String k){Object v=f.get(k);if(!(v instanceof String s)||s.isBlank())throw new IllegalArgumentException(k+" required");return s;}private static long number(Map<String,Object>f,String k){Object v=f.get(k);if(v instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+" required");}private static int integer(Map<String,Object>f,String k){return Math.toIntExact(number(f,k));}private static BigDecimal decimal(Map<String,Object>f,String k){Object v=f.get(k);if(v instanceof Number||v instanceof String)return new BigDecimal(String.valueOf(v));throw new IllegalArgumentException(k+" required");}
    private void reply(HttpExchange e,int status,Object value)throws IOException{byte[] b=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,b.length);try(var o=e.getResponseBody()){o.write(b);}}
    private static final class Api extends RuntimeException{final int status;final String code;Api(int status,String code,String message){super(message);this.status=status;this.code=code;}}
}
