package com.aoo.bcg.media;

import org.junit.jupiter.api.Test;
import java.io.*;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class MediaUploadServiceTest {
    @Test void closesUploadVerifiesHashAndDeduplicatesAcrossAuthorizedOwners()throws Exception{
        var repo=new Repo();var store=new Store();var service=new MediaUploadService(repo,store,new MediaPolicy(),Clock.systemUTC(),Duration.ofMinutes(10));byte[] bytes="real-image".getBytes();String hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
        var ticket=service.initiate(7,MediaPolicy.Kind.AVATAR,"image/png",bytes.length,0,hash);assertFalse(ticket.deduplicated());service.upload(7,ticket.ticketId(),1,bytes);var done=service.complete(7,ticket.ticketId());assertArrayEquals(bytes,service.open(service.authorizeRead(7,done.assetId())).readAllBytes());
        var dedupe=service.initiate(8,MediaPolicy.Kind.AVATAR,"image/png",bytes.length,0,hash);assertTrue(dedupe.deduplicated());assertEquals(done.assetId(),dedupe.assetId());assertDoesNotThrow(()->service.authorizeRead(8,done.assetId()));assertThrows(SecurityException.class,()->service.authorizeRead(9,done.assetId()));
    }
    @Test void rejectsPolicyAndPartViolations(){var service=new MediaUploadService(new Repo(),new Store(),new MediaPolicy(),Clock.systemUTC(),Duration.ofMinutes(10));assertThrows(IllegalArgumentException.class,()->service.initiate(1,MediaPolicy.Kind.AVATAR,"image/svg+xml",5,0,"0".repeat(64)));var t=service.initiate(1,MediaPolicy.Kind.VOICE,"audio/ogg",4,1000,"0".repeat(64));assertThrows(IllegalArgumentException.class,()->service.upload(1,t.ticketId(),1,new byte[3]));assertThrows(SecurityException.class,()->service.upload(2,t.ticketId(),1,new byte[4]));}
    @Test void abortsMultipartWhenTicketPersistenceFails(){var repo=new Repo();repo.failCreate=true;var store=new Store();var service=new MediaUploadService(repo,store,new MediaPolicy(),Clock.systemUTC(),Duration.ofMinutes(10));assertThrows(IllegalStateException.class,()->service.initiate(1,MediaPolicy.Kind.AVATAR,"image/png",1,0,"0".repeat(64)));assertTrue(store.aborted);}
    @Test void expiresAndAbortsOpenTickets(){Instant now=Instant.parse("2026-08-24T00:00:00Z");var mutable=new MutableClock(now);var repo=new Repo();var store=new Store();var service=new MediaUploadService(repo,store,new MediaPolicy(),mutable,Duration.ofSeconds(1));service.initiate(1,MediaPolicy.Kind.AVATAR,"image/png",1,0,"0".repeat(64));mutable.instant=now.plusSeconds(2);assertEquals(1,service.cleanupExpired(10));assertTrue(store.aborted);}
    @Test void roomAuthorizationRequiresOwnedReadyVoiceAndUsesAuthoritativeDuration()throws Exception{var repo=new Repo();var service=new MediaUploadService(repo,new Store(),new MediaPolicy(),Clock.systemUTC(),Duration.ofMinutes(10));byte[] bytes="voice".getBytes();String hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));var t=service.initiate(7,MediaPolicy.Kind.VOICE,"audio/ogg",bytes.length,2345,hash);service.upload(7,t.ticketId(),1,bytes);long id=service.complete(7,t.ticketId()).assetId();assertEquals(2345,service.authorizeVoice(7,id,List.of(7L,8L)).durationMillis());assertDoesNotThrow(()->service.authorizeRead(8,id));assertThrows(SecurityException.class,()->service.authorizeVoice(9,id,List.of(9L)));assertThrows(SecurityException.class,()->service.authorizeVoice(7,id,List.of(8L)));}
    private static final class MutableClock extends Clock{Instant instant;MutableClock(Instant i){instant=i;}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}public Instant instant(){return instant;}}
    private static final class Store implements ObjectStorage{final Map<String,byte[]> objects=new HashMap<>();final Map<Integer,byte[]> parts=new HashMap<>();boolean aborted;public String begin(String k,String m){return "upload";}public String uploadPart(String k,String u,int n,byte[] b){parts.put(n,b.clone());return "etag-"+n;}public void complete(String k,String u,List<UploadedPart> p){var out=new ByteArrayOutputStream();p.forEach(x->{try{out.write(parts.get(x.number()));}catch(IOException e){throw new UncheckedIOException(e);}});objects.put(k,out.toByteArray());}public void abort(String k,String u){aborted=true;parts.clear();}public InputStream open(String k){return new ByteArrayInputStream(objects.get(k));}public void delete(String k){objects.remove(k);}}
    private static final class Repo implements MediaRepository{final Map<String,Ticket> tickets=new HashMap<>();final Map<String,List<Part>> parts=new HashMap<>();final Map<Long,Asset> assets=new HashMap<>();final Set<String> grants=new HashSet<>();long ids;boolean failCreate;public Optional<Asset> findReadyByHash(String h,long s,String m){return assets.values().stream().filter(a->a.sha256().equals(h)&&a.size()==s&&a.mime().equals(m)).findFirst();}public boolean canRead(long a,long o){return grants.contains(a+":"+o);}public void grant(long a,long o){grants.add(a+":"+o);}public Asset authorizeVoice(long a,long sender,List<Long> members){Asset x=assets.get(a);if(x==null||x.kind()!=MediaPolicy.Kind.VOICE||!canRead(a,sender))throw new SecurityException();members.forEach(m->grant(a,m));return x;}public void create(Ticket t){if(failCreate)throw new IllegalStateException("db down");tickets.put(t.id(),t);}public Optional<Ticket> ticket(String id){return Optional.ofNullable(tickets.get(id));}public void addPart(String id,Part p){parts.computeIfAbsent(id,x->new ArrayList<>()).removeIf(x->x.number()==p.number());parts.get(id).add(p);parts.get(id).sort(Comparator.comparingInt(Part::number));}public List<Part> parts(String id){return List.copyOf(parts.getOrDefault(id,List.of()));}public boolean transition(String id,TicketState e,TicketState n){Ticket t=tickets.get(id);if(t.state()!=e)return false;tickets.put(id,copy(t,n,t.assetId()));return true;}public long finish(String id,String k,MediaPolicy.Kind kind,String mime,long size,long d,String h,long owner){Asset existing=findReadyByHash(h,size,mime).orElse(null);long aid;if(existing==null){aid=++ids;assets.put(aid,new Asset(aid,k,kind,mime,size,d,h));}else aid=existing.id();grant(aid,owner);Ticket t=tickets.get(id);tickets.put(id,copy(t,TicketState.READY,aid));return aid;}public void fail(String id,TicketState s,String r){Ticket t=tickets.get(id);if(t!=null)tickets.put(id,copy(t,s,t.assetId()));}public List<Ticket> expired(Instant n,int l){return tickets.values().stream().filter(t->t.state()==TicketState.OPEN&&!n.isBefore(t.expiresAt())).limit(l).toList();}public Optional<Asset> asset(long id){return Optional.ofNullable(assets.get(id));}private Ticket copy(Ticket t,TicketState s,Long a){return new Ticket(t.id(),t.ownerId(),t.objectKey(),t.storageUploadId(),t.kind(),t.mime(),t.size(),t.durationMillis(),t.sha256(),t.chunkBytes(),t.expectedParts(),t.expiresAt(),s,a);}}
}
