package com.aoo.bcg.identity;
import com.fasterxml.jackson.databind.ObjectMapper;import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import java.security.SecureRandom;import java.sql.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class JdbcIdentityVerificationServiceTest {
 JdbcDataSource db;CapturingSender sms;JdbcIdentityVerificationService service;
 @BeforeEach void setUp()throws Exception{db=new JdbcDataSource();db.setURL("jdbc:h2:mem:identity;MODE=MySQL;DB_CLOSE_DELAY=-1");try(Connection c=db.getConnection();Statement s=c.createStatement()){s.execute("DROP ALL OBJECTS");s.execute("CREATE TABLE aoo_identity_verification(account_id BIGINT PRIMARY KEY,real_name_status VARCHAR(24) NOT NULL,legal_name_cipher VARCHAR(1024),id_number_cipher VARCHAR(1024),id_token VARCHAR(64) UNIQUE,masked_name VARCHAR(64),masked_id_number VARCHAR(32),phone_verified BOOLEAN DEFAULT FALSE,phone_token VARCHAR(64),masked_phone VARCHAR(32),updated_at TIMESTAMP)");s.execute("CREATE TABLE aoo_phone_challenge(challenge_id VARCHAR(36) PRIMARY KEY,account_id BIGINT,phone_cipher VARCHAR(1024),phone_token VARCHAR(64),masked_phone VARCHAR(32),code_hash VARCHAR(64),attempts INT,expires_at TIMESTAMP,verified_at TIMESTAMP,created_at TIMESTAMP)");s.execute("CREATE TABLE aoo_identity_credential(credential_token VARCHAR(64) PRIMARY KEY,account_id BIGINT,purpose VARCHAR(32),expires_at TIMESTAMP,consumed_at TIMESTAMP,created_at TIMESTAMP)");s.execute("CREATE TABLE aoo_identity_idempotency(account_id BIGINT,operation_scope VARCHAR(32),idempotency_key VARCHAR(128),request_fingerprint VARCHAR(64),response_cipher VARCHAR(4096),created_at TIMESTAMP,PRIMARY KEY(account_id,operation_scope,idempotency_key))");s.execute("CREATE TABLE aoo_identity_audit(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT,action VARCHAR(48),ip_token VARCHAR(64),details_json VARCHAR(4096),created_at TIMESTAMP)");}sms=new CapturingSender();SecureRandom random=new SecureRandom(new byte[]{1,2,3});String encryption=Base64.getEncoder().encodeToString(new byte[32]);service=new JdbcIdentityVerificationService(db,new IdentityCrypto(encryption,"01234567890123456789012345678901",random),sms,new ObjectMapper().findAndRegisterModules(),Clock.fixed(Instant.parse("2026-08-24T12:00:00Z"),ZoneOffset.UTC),random);}
 @Test void closesRealNamePhoneCredentialAndAuditFlow()throws Exception{var status=service.submitRealName(7,"real-name-key-01",new JdbcIdentityVerificationService.RealNameRequest("张三","11010119900101123X"),"127.0.0.1");assertEquals("PENDING",status.realNameStatus());assertEquals("张*",status.maskedName());try(Connection c=db.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT legal_name_cipher,id_number_cipher FROM aoo_identity_verification")){assertTrue(r.next());assertFalse(r.getString(1).contains("张三"));assertFalse(r.getString(2).contains("110101"));}
   var challenge=service.sendPhone(7,"phone-send-key-01",new JdbcIdentityVerificationService.PhoneRequest("+8613812345678"),"127.0.0.1");assertEquals("+8613812345678",sms.phone);assertNotNull(challenge.challengeId());var credential=service.verifyPhone(7,"phone-verify-key-01",new JdbcIdentityVerificationService.VerifyRequest(challenge.challengeId(),sms.code),"127.0.0.1");assertFalse(credential.credential().isBlank());assertTrue(service.status(7).phoneVerified());try(Connection c=db.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT COUNT(*),MIN(action),MAX(action) FROM aoo_identity_audit")){assertTrue(r.next());assertEquals(3,r.getInt(1));}}
 @Test void enforcesIdempotencyFingerprintAndInvalidAttemptPersistence(){service.submitRealName(8,"same-key-0001",new JdbcIdentityVerificationService.RealNameRequest("李四","110101199101011234"),"ip");assertThrows(IdentityError.class,()->service.submitRealName(8,"same-key-0001",new JdbcIdentityVerificationService.RealNameRequest("王五","110101199201011235"),"ip"));var c=service.sendPhone(8,"send-key-0001",new JdbcIdentityVerificationService.PhoneRequest("+8613900000000"),"ip");IdentityError error=assertThrows(IdentityError.class,()->service.verifyPhone(8,"verify-key-0001",new JdbcIdentityVerificationService.VerifyRequest(c.challengeId(),"000000"),"ip"));assertEquals("IDENTITY_CODE_INVALID",error.code);}
 static final class CapturingSender implements PhoneCodeSender{String phone,code;public void send(String phone,String code,String id){this.phone=phone;this.code=code;}}
}
