package com.aoo.bcg.matchmaking;

import com.aoo.bcg.hall.http.HallRequestAuthenticator;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

/** Authenticated public API; no caller-supplied player identity is trusted. */
public final class CompetitionHttpRoutes {
 private final JdbcCompetitionService service;private final HallRequestAuthenticator auth;private final ObjectMapper json;private final byte[] internalToken;
 public CompetitionHttpRoutes(JdbcCompetitionService service,HallRequestAuthenticator auth,ObjectMapper json,String internalToken){this.service=service;this.auth=auth;this.json=json;if(internalToken==null||internalToken.length()<32)throw new IllegalArgumentException("competition internal token must contain at least 32 characters");this.internalToken=internalToken.getBytes(StandardCharsets.UTF_8);}
 public void mount(HttpServer server){server.createContext("/health/competition",e->reply(e,200,Map.of("status","UP","persistence","jdbc")));server.createContext("/v1/matchmaking",this::match);server.createContext("/v1/tournaments",this::tournament);server.createContext("/v1/competition/events",this::events);server.createContext("/internal/v1/tournaments",this::operateTournament);}
 private void match(HttpExchange e)throws IOException{if("GET".equals(e.getRequestMethod())){read(e,p->service.matchStatus(p,queryLong(e,"gameId",0)));return;}handle(e,()->{long player=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));Map<String,Object>b=body(e);String action=text(b,"action"),key=e.getRequestHeaders().getFirst("Idempotency-Key");return switch(action){case"queue"->service.enqueue(player,key,num(b,"gameId"),num(b,"timeoutSeconds"));case"cancel"->service.cancel(player,key,num(b,"gameId"));case"confirm"->service.confirm(player,key,num(b,"matchId"));default->throw new IllegalArgumentException("unknown matchmaking action");};});}
 private void tournament(HttpExchange e)throws IOException{if("GET".equals(e.getRequestMethod())){read(e,p->service.tournaments(p));return;}handle(e,()->{long player=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));Map<String,Object>b=body(e);String action=text(b,"action"),key=e.getRequestHeaders().getFirst("Idempotency-Key");return switch(action){case"register"->service.register(player,key,num(b,"tournamentId"));case"withdraw"->service.withdraw(player,key,num(b,"tournamentId"));default->throw new IllegalArgumentException("unknown tournament action");};});}
 private void events(HttpExchange e)throws IOException{if(!"GET".equals(e.getRequestMethod())){reply(e,405,Map.of("error","method_not_allowed"));return;}read(e,p->service.events(p,queryLong(e,"after",0),100));}
 private void operateTournament(HttpExchange e)throws IOException{handle(e,()->{byte[] supplied=String.valueOf(e.getRequestHeaders().getFirst("X-Internal-Token")).getBytes(StandardCharsets.UTF_8);if(!MessageDigest.isEqual(internalToken,supplied))throw new SecurityException("invalid internal token");Map<String,Object>b=body(e);long tournament=num(b,"tournamentId");return switch(text(b,"action")){case"group"->service.group(tournament,Math.toIntExact(num(b,"groupSize")));case"advance"->service.advance(tournament,num(b,"playerId"),num(b,"score"));case"rank"->{Object raw=b.get("rewards");if(!(raw instanceof List<?> list))throw new IllegalArgumentException("rewards is required");List<Long> amounts=list.stream().map(v->Long.parseLong(String.valueOf(v))).toList();yield service.rankAndReward(tournament,text(b,"currency"),amounts);}case"expire"->Map.of("expired",service.expire());default->throw new IllegalArgumentException("unknown tournament operation");};});}
 private void handle(HttpExchange e,Action a)throws IOException{try{if(!"POST".equals(e.getRequestMethod())){reply(e,405,Map.of("error","method_not_allowed"));return;}reply(e,200,a.run());}catch(SecurityException x){reply(e,403,error(x));}catch(com.aoo.bcg.hall.http.HallError x){reply(e,x.status(),Map.of("error",x.code(),"message",x.getMessage()));}catch(IllegalArgumentException x){reply(e,400,error(x));}catch(IllegalStateException x){reply(e,409,error(x));}catch(Exception x){reply(e,500,Map.of("error","internal_error"));}}
 private void read(HttpExchange e,PlayerAction a)throws IOException{try{long p=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));reply(e,200,a.run(p));}catch(SecurityException x){reply(e,403,error(x));}catch(IllegalArgumentException x){reply(e,400,error(x));}catch(Exception x){reply(e,500,Map.of("error","internal_error"));}}
 private static long queryLong(HttpExchange e,String name,long fallback){String q=e.getRequestURI().getRawQuery();if(q==null)return fallback;for(String part:q.split("&")){String[]kv=part.split("=",2);if(kv[0].equals(name))return Long.parseLong(kv.length==2?kv[1]:"");}return fallback;}
 private Map<String,Object> body(HttpExchange e)throws IOException{return json.readValue(e.getRequestBody(),new TypeReference<>(){});}private static long num(Map<String,Object>b,String k){if(!b.containsKey(k))throw new IllegalArgumentException(k+" is required");return Long.parseLong(String.valueOf(b.get(k)));}private static String text(Map<String,Object>b,String k){String v=String.valueOf(b.getOrDefault(k,""));if(v.isBlank())throw new IllegalArgumentException(k+" is required");return v;}private static Map<String,Object> error(Exception x){return Map.of("error",x.getMessage()==null?"request_failed":x.getMessage());}private void reply(HttpExchange e,int status,Object value)throws IOException{byte[]bytes=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,bytes.length);e.getResponseBody().write(bytes);e.close();}@FunctionalInterface private interface Action{Object run()throws Exception;}@FunctionalInterface private interface PlayerAction{Object run(long player)throws Exception;}
}
