package com.aoo.bcg.matchmaking;

import com.fasterxml.jackson.databind.ObjectMapper;
import javax.sql.DataSource;
import java.sql.*;
import java.time.*;
import java.util.*;
import static com.aoo.bcg.matchmaking.MatchmakingPorts.*;

/** Authoritative JDBC state machine for ordinary queues and tournaments. */
public final class JdbcCompetitionService {
 private final DataSource db; private final HallRoomPort hall; private final BillingRewardPort billing; private final Clock clock; private final ObjectMapper json;
 public JdbcCompetitionService(DataSource db,HallRoomPort hall,BillingRewardPort billing,Clock clock,ObjectMapper json){this.db=Objects.requireNonNull(db);this.hall=Objects.requireNonNull(hall);this.billing=Objects.requireNonNull(billing);this.clock=Objects.requireNonNull(clock);this.json=Objects.requireNonNull(json);}
 public Map<String,Object> enqueue(long player,String key,long game,long timeoutSeconds){positive(player,game);required(key);if(timeoutSeconds<5||timeoutSeconds>1800)throw new IllegalArgumentException("timeoutSeconds out of range");return tx(c->{Map<String,Object> replay=replay(c,player,key,"QUEUE");if(replay!=null)return replay;String play=activePlay(c,game);Queue current=queue(c,player,game,true);if(current!=null&&Set.of("WAITING","MATCHED").contains(current.state))throw new IllegalStateException("player is already queued");Instant now=clock.instant(),expires=now.plusSeconds(timeoutSeconds);try(var s=c.prepareStatement("INSERT INTO aoo_match_queue(player_id,game_id,play_version,state,enqueued_at,expires_at,match_id,updated_at) VALUES(?,?,?,'WAITING',?,?,NULL,?) ON DUPLICATE KEY UPDATE play_version=VALUES(play_version),state='WAITING',enqueued_at=VALUES(enqueued_at),expires_at=VALUES(expires_at),match_id=NULL,updated_at=VALUES(updated_at)")){s.setLong(1,player);s.setLong(2,game);s.setString(3,play);ts(s,4,now);ts(s,5,expires);ts(s,6,now);s.executeUpdate();}
   Queue opponent=null;try(var s=c.prepareStatement("SELECT player_id,game_id,play_version,state,expires_at,match_id FROM aoo_match_queue WHERE game_id=? AND play_version=? AND state='WAITING' AND player_id<>? AND expires_at>? ORDER BY enqueued_at,player_id LIMIT 1 FOR UPDATE")){s.setLong(1,game);s.setString(2,play);s.setLong(3,player);ts(s,4,now);try(var r=s.executeQuery()){if(r.next())opponent=readQueue(r);}}
   Map<String,Object> out;if(opponent==null){out=Map.of("state","WAITING","playerId",player,"gameId",game,"expiresAt",expires.toString());event(c,player,"MATCHMAKING_WAITING",out);}else{long matchId=nextId(c,"aoo_match_seq");Map<String,Object> room=hall.create(player,"match-"+matchId,Map.of("gameId",game,"playVersion",play,"clientVersion","999.0.0","rules",Map.of("source","MATCHMAKING","matchId",matchId)));AuthorityRoom authority=authorityRoom(room);long roomId=authority.roomId();String route=authority.route();Instant deadline=now.plusSeconds(30);try(var s=c.prepareStatement("INSERT INTO aoo_match(match_id,game_id,room_id,room_route,state,confirm_deadline,created_at) VALUES(?,?,?,?,'PENDING_CONFIRM',?,?)")){s.setLong(1,matchId);s.setLong(2,game);s.setLong(3,roomId);s.setString(4,route);ts(s,5,deadline);ts(s,6,now);s.executeUpdate();}try(var s=c.prepareStatement("INSERT INTO aoo_match_member(match_id,player_id,confirmed_at) VALUES(?,?,NULL),(?,?,NULL)")){s.setLong(1,matchId);s.setLong(2,player);s.setLong(3,matchId);s.setLong(4,opponent.player);s.executeUpdate();}try(var s=c.prepareStatement("UPDATE aoo_match_queue SET state='MATCHED',match_id=?,updated_at=? WHERE game_id=? AND player_id IN (?,?)")){s.setLong(1,matchId);ts(s,2,now);s.setLong(3,game);s.setLong(4,player);s.setLong(5,opponent.player);s.executeUpdate();}out=Map.of("state","MATCHED","gameId",game,"matchId",matchId,"roomId",roomId,"confirmDeadline",deadline.toString(),"route",route);event(c,player,"MATCH_FOUND",out);event(c,opponent.player,"MATCH_FOUND",out);}save(c,player,key,"QUEUE",out);return out;});}
 public Map<String,Object> cancel(long player,String key,long game){positive(player,game);required(key);return tx(c->{Map<String,Object> old=replay(c,player,key,"CANCEL");if(old!=null)return old;Queue q=queue(c,player,game,true);if(q==null||!"WAITING".equals(q.state))throw new IllegalStateException("only a waiting queue entry can be cancelled");updateQueue(c,player,game,"CANCELLED");Map<String,Object> out=Map.of("state","CANCELLED","playerId",player,"gameId",game);event(c,player,"MATCHMAKING_CANCELLED",out);save(c,player,key,"CANCEL",out);return out;});}
 public Map<String,Object> confirm(long player,String key,long matchId){positive(player,matchId);required(key);return tx(c->{Map<String,Object> old=replay(c,player,key,"CONFIRM");if(old!=null)return old;String state,route;Instant deadline;long room,game;try(var s=c.prepareStatement("SELECT state,confirm_deadline,room_id,game_id,room_route FROM aoo_match WHERE match_id=? FOR UPDATE")){s.setLong(1,matchId);try(var r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("match not found");state=r.getString(1);deadline=r.getTimestamp(2).toInstant();room=r.getLong(3);game=r.getLong(4);route=r.getString(5);}}if(!"PENDING_CONFIRM".equals(state)||!clock.instant().isBefore(deadline))throw new IllegalStateException("match confirmation expired");try(var s=c.prepareStatement("UPDATE aoo_match_member SET confirmed_at=? WHERE match_id=? AND player_id=? AND confirmed_at IS NULL")){ts(s,1,clock.instant());s.setLong(2,matchId);s.setLong(3,player);int changed=s.executeUpdate();if(changed==0&&!member(c,matchId,player))throw new SecurityException("player is not a match member");}int pending;try(var s=c.prepareStatement("SELECT COUNT(*) FROM aoo_match_member WHERE match_id=? AND confirmed_at IS NULL")){s.setLong(1,matchId);try(var r=s.executeQuery()){r.next();pending=r.getInt(1);}}if(pending==0){try(var s=c.prepareStatement("UPDATE aoo_match SET state='CONFIRMED' WHERE match_id=?")){s.setLong(1,matchId);s.executeUpdate();}try(var s=c.prepareStatement("UPDATE aoo_match_queue SET state='COMPLETED',updated_at=? WHERE match_id=?")){ts(s,1,clock.instant());s.setLong(2,matchId);s.executeUpdate();}}Map<String,Object> out=Map.of("matchId",matchId,"roomId",room,"gameId",game,"route",route,"state",pending==0?"CONFIRMED":"PENDING_CONFIRM");if(pending==0)for(long member:members(c,matchId))event(c,member,"ROOM_READY",out);else event(c,player,"MATCH_CONFIRMED",out);save(c,player,key,"CONFIRM",out);return out;});}
 public int expire(){return tx(c->{Instant now=clock.instant();List<long[]>waiting=new ArrayList<>();try(var s=c.prepareStatement("SELECT player_id,game_id FROM aoo_match_queue WHERE state='WAITING' AND expires_at<=? FOR UPDATE")){ts(s,1,now);try(var r=s.executeQuery()){while(r.next())waiting.add(new long[]{r.getLong(1),r.getLong(2)});}}int n;try(var s=c.prepareStatement("UPDATE aoo_match_queue SET state='TIMED_OUT',updated_at=? WHERE state='WAITING' AND expires_at<=?")){ts(s,1,now);ts(s,2,now);n=s.executeUpdate();}for(long[]q:waiting)event(c,q[0],"MATCHMAKING_TIMED_OUT",Map.of("state","TIMED_OUT","gameId",q[1]));List<Long> expired=new ArrayList<>();try(var s=c.prepareStatement("SELECT match_id FROM aoo_match WHERE state='PENDING_CONFIRM' AND confirm_deadline<=? FOR UPDATE")){ts(s,1,now);try(var r=s.executeQuery()){while(r.next())expired.add(r.getLong(1));}}for(long id:expired){try(var s=c.prepareStatement("UPDATE aoo_match SET state='EXPIRED' WHERE match_id=?")){s.setLong(1,id);s.executeUpdate();}try(var s=c.prepareStatement("UPDATE aoo_match_queue SET state='TIMED_OUT',updated_at=? WHERE match_id=?")){ts(s,1,now);s.setLong(2,id);n+=s.executeUpdate();}for(long p:members(c,id))event(c,p,"MATCH_CONFIRM_EXPIRED",Map.of("state","TIMED_OUT","matchId",id));}return n;});}
 public Map<String,Object> register(long player,String key,long tournament){return tournamentMember(player,key,tournament,"REGISTERED","REGISTER");}
 public Map<String,Object> withdraw(long player,String key,long tournament){return tournamentMember(player,key,tournament,"WITHDRAWN","WITHDRAW");}
 private Map<String,Object> tournamentMember(long player,String key,long tournament,String target,String op){positive(player,tournament);required(key);return tx(c->{Map<String,Object> old=replay(c,player,key,op);if(old!=null)return old;String phase=tournamentPhase(c,tournament,true);if(!"REGISTRATION".equals(phase))throw new IllegalStateException("tournament registration is closed");try(var s=c.prepareStatement("INSERT INTO aoo_tournament_entry(tournament_id,player_id,status,registered_at) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),registered_at=VALUES(registered_at)")){s.setLong(1,tournament);s.setLong(2,player);s.setString(3,target);ts(s,4,clock.instant());s.executeUpdate();}Map<String,Object> out=Map.of("tournamentId",tournament,"playerId",player,"status",target,"phase",phase);event(c,player,"TOURNAMENT_"+target,out);save(c,player,key,op,out);return out;});}
 public List<Map<String,Object>> group(long tournament,int size){if(size<2||size>64)throw new IllegalArgumentException("group size out of range");return tx(c->{if(!"REGISTRATION".equals(tournamentPhase(c,tournament,true)))throw new IllegalStateException("invalid tournament phase");List<Long> ids=new ArrayList<>();try(var s=c.prepareStatement("SELECT player_id FROM aoo_tournament_entry WHERE tournament_id=? AND status='REGISTERED' ORDER BY registered_at,player_id FOR UPDATE")){s.setLong(1,tournament);try(var r=s.executeQuery()){while(r.next())ids.add(r.getLong(1));}}if(ids.size()<2)throw new IllegalStateException("not enough entrants");List<Map<String,Object>> out=new ArrayList<>();for(int i=0;i<ids.size();i++){int group=i/size+1,seed=i%size+1;try(var s=c.prepareStatement("UPDATE aoo_tournament_entry SET group_no=?,seed_no=? WHERE tournament_id=? AND player_id=?")){s.setInt(1,group);s.setInt(2,seed);s.setLong(3,tournament);s.setLong(4,ids.get(i));s.executeUpdate();}out.add(Map.of("playerId",ids.get(i),"group",group,"seed",seed));}phase(c,tournament,"GROUPED");return out;});}
 public Map<String,Object> advance(long tournament,long player,long score){positive(tournament,player);return tx(c->{if(!Set.of("GROUPED","RUNNING").contains(tournamentPhase(c,tournament,true)))throw new IllegalStateException("tournament is not running");try(var s=c.prepareStatement("UPDATE aoo_tournament_entry SET status='ADVANCED',score=? WHERE tournament_id=? AND player_id=? AND status IN ('REGISTERED','ADVANCED')")){s.setLong(1,score);s.setLong(2,tournament);s.setLong(3,player);if(s.executeUpdate()!=1)throw new IllegalArgumentException("entrant not found");}phase(c,tournament,"RUNNING");return Map.of("tournamentId",tournament,"playerId",player,"status","ADVANCED","score",score);});}
 public List<Map<String,Object>> rankAndReward(long tournament,String currency,List<Long> rewards){required(currency);return tx(c->{String p=tournamentPhase(c,tournament,true);if(!Set.of("GROUPED","RUNNING").contains(p))throw new IllegalStateException("tournament cannot be ranked");List<Map<String,Object>> out=new ArrayList<>();try(var s=c.prepareStatement("SELECT player_id,score FROM aoo_tournament_entry WHERE tournament_id=? AND status='ADVANCED' ORDER BY score DESC,registered_at,player_id FOR UPDATE")){s.setLong(1,tournament);try(var r=s.executeQuery()){int rank=0;while(r.next()){rank++;long player=r.getLong(1),score=r.getLong(2),amount=rank<=rewards.size()?rewards.get(rank-1):0;try(var u=c.prepareStatement("UPDATE aoo_tournament_entry SET rank_no=? WHERE tournament_id=? AND player_id=?")){u.setInt(1,rank);u.setLong(2,tournament);u.setLong(3,player);u.executeUpdate();}if(amount>0)billing.credit("tournament-"+tournament+"-rank-"+rank,player,currency,amount,"TOURNAMENT_REWARD");out.add(Map.of("rank",rank,"playerId",player,"score",score,"reward",amount));}}}phase(c,tournament,"COMPLETED");return out;});}

 public Map<String,Object> matchStatus(long player,long game){positive(player,game);return tx(c->{Queue q=queue(c,player,game,false);if(q==null)return Map.of("state","IDLE","gameId",game);if(q.match==null)return Map.of("state",q.state,"gameId",game,"expiresAt",q.expires.toString());try(var s=c.prepareStatement("SELECT m.match_id,m.room_id,m.room_route,m.state,m.confirm_deadline,mm.confirmed_at FROM aoo_match m JOIN aoo_match_member mm ON mm.match_id=m.match_id WHERE m.match_id=? AND mm.player_id=?")){s.setLong(1,q.match);s.setLong(2,player);try(var r=s.executeQuery()){if(!r.next())throw new SecurityException("player is not a match member");return Map.of("state",r.getString(4),"gameId",game,"matchId",r.getLong(1),"roomId",r.getLong(2),"route",r.getString(3),"confirmDeadline",r.getTimestamp(5).toInstant().toString(),"confirmed",r.getTimestamp(6)!=null);}}});}
 public List<Map<String,Object>> tournaments(long player){positive(player);return tx(c->{List<Map<String,Object>>out=new ArrayList<>();try(var s=c.prepareStatement("SELECT t.tournament_id,t.game_id,t.name,t.phase,e.status,e.group_no,e.seed_no,e.score,e.rank_no FROM aoo_tournament t LEFT JOIN aoo_tournament_entry e ON e.tournament_id=t.tournament_id AND e.player_id=? WHERE t.phase<>'CANCELLED' ORDER BY t.updated_at DESC,t.tournament_id")){s.setLong(1,player);try(var r=s.executeQuery()){while(r.next()){Map<String,Object>row=new LinkedHashMap<>();row.put("tournamentId",r.getLong(1));row.put("gameId",r.getLong(2));row.put("name",r.getString(3));row.put("phase",r.getString(4));row.put("status",r.getString(5)==null?"NOT_REGISTERED":r.getString(5));row.put("group",r.getObject(6));row.put("seed",r.getObject(7));row.put("score",r.getLong(8));row.put("rank",r.getObject(9));out.add(row);}}}return out;});}
 public List<Map<String,Object>> events(long player,long after,int limit){positive(player);if(after<0)throw new IllegalArgumentException("after out of range");return tx(c->{List<Map<String,Object>>out=new ArrayList<>();try(var s=c.prepareStatement("SELECT event_id,event_type,payload_json,created_at FROM aoo_competition_event WHERE player_id=? AND event_id>? ORDER BY event_id LIMIT ?")){s.setLong(1,player);s.setLong(2,after);s.setInt(3,Math.max(1,Math.min(limit,100)));try(var r=s.executeQuery()){while(r.next())out.add(Map.of("eventId",r.getLong(1),"type",r.getString(2),"payload",json.readValue(r.getString(3),Map.class),"createdAt",r.getTimestamp(4).toInstant().toString()));}}return out;});}
 private String tournamentPhase(Connection c,long id,boolean lock)throws SQLException{try(var s=c.prepareStatement("SELECT phase FROM aoo_tournament WHERE tournament_id=?"+(lock?" FOR UPDATE":""))){s.setLong(1,id);try(var r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("tournament not found");return r.getString(1);}}}private void phase(Connection c,long id,String p)throws SQLException{try(var s=c.prepareStatement("UPDATE aoo_tournament SET phase=?,updated_at=? WHERE tournament_id=?")){s.setString(1,p);ts(s,2,clock.instant());s.setLong(3,id);s.executeUpdate();}}
 private String activePlay(Connection c,long game)throws SQLException{try(var s=c.prepareStatement("SELECT a.play_version FROM aoo_compiled_index_active a JOIN aoo_play_version p ON p.game_id=a.game_id AND p.play_version=a.play_version WHERE a.game_id=? AND p.status='ACTIVE' AND EXISTS(SELECT 1 FROM aoo_game_service_route r WHERE r.game_id=a.game_id AND r.play_version=a.play_version AND r.status='ACTIVE') ORDER BY p.activated_at DESC,a.play_version LIMIT 1")){s.setLong(1,game);try(var r=s.executeQuery()){if(!r.next())throw new IllegalStateException("game is not published or routable");return r.getString(1);}}}
 private Queue queue(Connection c,long player,long game,boolean lock)throws SQLException{try(var s=c.prepareStatement("SELECT player_id,game_id,play_version,state,expires_at,match_id FROM aoo_match_queue WHERE player_id=? AND game_id=?"+(lock?" FOR UPDATE":""))){s.setLong(1,player);s.setLong(2,game);try(var r=s.executeQuery()){return r.next()?readQueue(r):null;}}}private static Queue readQueue(ResultSet r)throws SQLException{return new Queue(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getTimestamp(5).toInstant(),(Long)r.getObject(6));}private void updateQueue(Connection c,long player,long game,String state)throws SQLException{try(var s=c.prepareStatement("UPDATE aoo_match_queue SET state=?,updated_at=? WHERE player_id=? AND game_id=?")){s.setString(1,state);ts(s,2,clock.instant());s.setLong(3,player);s.setLong(4,game);s.executeUpdate();}}
 private boolean member(Connection c,long match,long player)throws SQLException{try(var s=c.prepareStatement("SELECT 1 FROM aoo_match_member WHERE match_id=? AND player_id=?")){s.setLong(1,match);s.setLong(2,player);try(var r=s.executeQuery()){return r.next();}}}
 private List<Long> members(Connection c,long match)throws SQLException{List<Long>out=new ArrayList<>();try(var s=c.prepareStatement("SELECT player_id FROM aoo_match_member WHERE match_id=? ORDER BY player_id")){s.setLong(1,match);try(var r=s.executeQuery()){while(r.next())out.add(r.getLong(1));}}return out;}
 private void event(Connection c,long player,String type,Object payload)throws Exception{try(var s=c.prepareStatement("INSERT INTO aoo_competition_event(player_id,event_type,payload_json,created_at) VALUES(?,?,?,?)")){s.setLong(1,player);s.setString(2,type);s.setString(3,json.writeValueAsString(payload));ts(s,4,clock.instant());s.executeUpdate();}}
 private long nextId(Connection c,String name)throws SQLException{try(var s=c.prepareStatement("UPDATE aoo_sequence SET next_value=LAST_INSERT_ID(next_value+1) WHERE sequence_name=?")){s.setString(1,name);if(s.executeUpdate()!=1)throw new IllegalStateException("missing sequence "+name);}try(var s=c.prepareStatement("SELECT LAST_INSERT_ID()" );var r=s.executeQuery()){r.next();return r.getLong(1);}}
 private static AuthorityRoom authorityRoom(Map<String,Object> room){if(room==null)throw new IllegalStateException("Hall room saga returned no authority result");Object rawId=room.get("roomId"),rawRoute=room.get("route");if(!(rawId instanceof Number number)||number.longValue()<=0)throw new IllegalStateException("Hall room saga response is missing a positive roomId");if(!(rawRoute instanceof String route)||route.isBlank())throw new IllegalStateException("Hall room saga response is missing an authority route");return new AuthorityRoom(number.longValue(),route);}
 @SuppressWarnings("unchecked") private Map<String,Object> replay(Connection c,long player,String key,String op)throws Exception{try(var s=c.prepareStatement("SELECT operation,response_json FROM aoo_competition_idempotency WHERE player_id=? AND idempotency_key=? FOR UPDATE")){s.setLong(1,player);s.setString(2,key);try(var r=s.executeQuery()){if(!r.next())return null;if(!op.equals(r.getString(1)))throw new IllegalStateException("idempotency key conflict");return json.readValue(r.getString(2),Map.class);}}}private void save(Connection c,long player,String key,String op,Map<String,Object> out)throws Exception{try(var s=c.prepareStatement("INSERT INTO aoo_competition_idempotency(player_id,idempotency_key,operation,response_json,created_at) VALUES(?,?,?,?,?)")){s.setLong(1,player);s.setString(2,key);s.setString(3,op);s.setString(4,json.writeValueAsString(out));ts(s,5,clock.instant());s.executeUpdate();}}
 private <T>T tx(Sql<T> work){try(var c=db.getConnection()){c.setAutoCommit(false);try{T out=work.run(c);c.commit();return out;}catch(Exception e){c.rollback();if(e instanceof RuntimeException x)throw x;throw new IllegalStateException(e);}}catch(SQLException e){throw new IllegalStateException("competition persistence failure",e);}}private static void ts(PreparedStatement s,int i,Instant v)throws SQLException{s.setTimestamp(i,Timestamp.from(v));}private static void positive(long... values){for(long v:values)if(v<=0)throw new IllegalArgumentException("positive id required");}private static void required(String... values){for(String v:values)if(v==null||v.isBlank())throw new IllegalArgumentException("required value missing");}private record Queue(long player,long game,String play,String state,Instant expires,Long match){}private record AuthorityRoom(long roomId,String route){}@FunctionalInterface private interface Sql<T>{T run(Connection c)throws Exception;}
}
