package com.aoo.bcg.gifting;

import com.fasterxml.jackson.databind.*;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.time.Duration;import java.util.*;
/** Asset mutations only through Billing/Inventory production HTTP authority ports. */
public final class HttpAssetAuthority implements GiftingPorts.AssetAuthority {
 private final URI billing,inventory,inventoryInternal;private final String billingToken,inventoryToken;private final ObjectMapper json;private final HttpClient client;
 public HttpAssetAuthority(URI billing,URI inventory,String bt,String it,ObjectMapper json){this.billing=billing.resolve("/v1/billing");this.inventory=inventory.resolve("/v1/inventory");this.inventoryInternal=inventory.resolve("/internal/v1/inventory");billingToken=valid(bt);inventoryToken=valid(it);this.json=json;client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(3)).build();}
 public void debit(String key,long player,String asset,long quantity)throws Exception{if(asset.startsWith("item:"))invoke(inventory,inventoryToken,key,player,Map.of("itemCode",asset.substring(5),"quantity",quantity));else invoke(billing,billingToken,key,player,Map.of("action","debit","playerId",player,"currency",asset,"scopeId",0,"amount",quantity,"reasonCode","PLAYER_GIFT"));}
 public void credit(String key,long player,String asset,long quantity)throws Exception{if(asset.startsWith("item:"))invoke(inventoryInternal,inventoryToken,key,player,Map.of("action","grant","playerId",player,"itemCode",asset.substring(5),"quantity",quantity,"source","PLAYER_GIFT"));else invoke(billing,billingToken,key,player,Map.of("action","credit","playerId",player,"currency",asset,"scopeId",0,"amount",quantity,"reasonCode","PLAYER_GIFT"));}
 private void invoke(URI uri,String token,String key,long player,Object body)throws Exception{var request=HttpRequest.newBuilder(uri).timeout(Duration.ofSeconds(8)).header("Authorization","Bearer "+token).header("X-API-Version","1").header("X-Player-Id",Long.toString(player)).header("Idempotency-Key",key).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofByteArray(json.writeValueAsBytes(body))).build();var response=client.send(request,HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if(response.statusCode()/100!=2)throw new IllegalStateException("asset authority rejected operation: HTTP "+response.statusCode());}
 private static String valid(String s){if(s==null||s.length()<32)throw new IllegalArgumentException("authority token must be at least 32 characters");return s;}
}
