package com.aoo.bcg.gifting;
import com.fasterxml.jackson.databind.ObjectMapper;import javax.sql.DataSource;import java.sql.*;import java.time.*;import java.util.*;

/** Durable idempotency, quota reservation, bilateral ledger and hash-chained audit repository. */
public final class JdbcGiftRepository {
 private final DataSource source;private final ObjectMapper json;private final Clock clock;
 public JdbcGiftRepository(DataSource s,ObjectMapper j,Clock c){source=Objects.requireNonNull(s);json=Objects.requireNonNull(j);clock=Objects.requireNonNull(c);}
 public Gift reserve(String key,long sender,long recipient,String asset,long quantity,String requestHash,String device,String ip,GiftingPorts.Decision risk){if(sender==recipient)throw new GiftError("GIFT_SELF_FORBIDDEN","cannot gift to self");if(quantity<=0)throw new GiftError("GIFT_INVALID_QUANTITY","quantity must be positive");try(Connection c=source.getConnection()){c.setAutoCommit(false);try{
   Gift prior=find(c,key,true);if(prior!=null){if(!prior.requestHash.equals(requestHash))throw new GiftError("IDEMPOTENCY_CONFLICT","idempotency key reused with different request");c.commit();return prior;}
   Policy p=policy(c,asset);eligibility(c,sender,recipient,p);LocalDate day=LocalDate.now(clock);long used=usage(c,sender,recipient,asset,day);if(quantity>p.perGift||used+quantity>p.daily)throw new GiftError("GIFT_LIMIT_EXCEEDED","gift limit exceeded");if(!risk.allowed())throw new GiftError("GIFT_RISK_REJECTED",risk.code());
   String id=UUID.randomUUID().toString();try(PreparedStatement q=c.prepareStatement("INSERT INTO gift_transfer(gift_id,idempotency_key,request_hash,sender_id,recipient_id,asset_code,quantity,state,risk_code,risk_score,device_id,ip_address,business_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'RESERVED',?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)")){q.setString(1,id);q.setString(2,key);q.setString(3,requestHash);q.setLong(4,sender);q.setLong(5,recipient);q.setString(6,asset);q.setLong(7,quantity);q.setString(8,risk.code());q.setInt(9,risk.score());q.setString(10,device);q.setString(11,ip);q.setDate(12,java.sql.Date.valueOf(day));q.executeUpdate();}audit(c,id,"RESERVED",sender,Map.of("riskCode",risk.code(),"riskScore",risk.score()));c.commit();return find(id);
  }catch(Exception e){c.rollback();throw e;}}catch(GiftError e){throw e;}catch(Exception e){throw new IllegalStateException("gift persistence unavailable",e);}}
 public Gift find(String id){try(Connection c=source.getConnection()){Gift g=findById(c,id);if(g==null)throw new GiftError("GIFT_NOT_FOUND","gift not found");return g;}catch(SQLException e){throw new IllegalStateException("gift query failed",e);}}
 public List<Map<String,Object>> ledger(long player,int limit){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("SELECT ledger_id,gift_id,counterparty_id,direction,asset_code,quantity,created_at FROM gift_ledger WHERE player_id=? ORDER BY ledger_id DESC LIMIT ?")){q.setLong(1,player);q.setInt(2,Math.max(1,Math.min(limit,100)));try(ResultSet r=q.executeQuery()){List<Map<String,Object>> out=new ArrayList<>();while(r.next())out.add(entry(r));return out;}}catch(SQLException e){throw new IllegalStateException("gift ledger query failed",e);}}
 public List<Map<String,Object>> inboundAfter(long player,long after,int limit){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("SELECT ledger_id,gift_id,counterparty_id,direction,asset_code,quantity,created_at FROM gift_ledger WHERE player_id=? AND direction='IN' AND ledger_id>? ORDER BY ledger_id LIMIT ?")){q.setLong(1,player);q.setLong(2,Math.max(0,after));q.setInt(3,Math.max(1,Math.min(limit,100)));try(ResultSet r=q.executeQuery()){List<Map<String,Object>> out=new ArrayList<>();while(r.next())out.add(entry(r));return out;}}catch(SQLException e){throw new IllegalStateException("gift inbox query failed",e);}}
 private static Map<String,Object> entry(ResultSet r)throws SQLException{return Map.of("sequence",r.getLong(1),"giftId",r.getString(2),"counterpartyId",r.getLong(3),"direction",r.getString(4),"asset",r.getString(5),"quantity",r.getLong(6),"createdAt",r.getTimestamp(7).toInstant());}
 public Gift transition(String id,String expected,String next,String failure){try(Connection c=source.getConnection()){c.setAutoCommit(false);try{Gift g=findById(c,id);if(g==null)throw new GiftError("GIFT_NOT_FOUND","gift not found");if(!g.state.equals(expected)){c.commit();return g;}try(PreparedStatement q=c.prepareStatement("UPDATE gift_transfer SET state=?,failure_code=?,updated_at=CURRENT_TIMESTAMP WHERE gift_id=? AND state=?")){q.setString(1,next);q.setString(2,failure);q.setString(3,id);q.setString(4,expected);if(q.executeUpdate()!=1)throw new IllegalStateException("concurrent gift transition");}if("COMPLETED".equals(next)){insertLedger(c,g,g.sender,g.recipient,"OUT");insertLedger(c,g,g.recipient,g.sender,"IN");}audit(c,id,next,g.sender,Map.of("failureCode",failure==null?"":failure));c.commit();return find(id);}catch(Exception e){c.rollback();throw e;}}catch(Exception e){if(e instanceof GiftError x)throw x;throw new IllegalStateException("gift transition failed",e);}}
 public boolean claim(String id){try(Connection c=source.getConnection();PreparedStatement q=c.prepareStatement("UPDATE gift_transfer SET state='PROCESSING',updated_at=CURRENT_TIMESTAMP WHERE gift_id=? AND state='RESERVED'")){q.setString(1,id);return q.executeUpdate()==1;}catch(SQLException e){throw new IllegalStateException("gift claim failed",e);}}
 private void insertLedger(Connection c,Gift g,long player,long counterparty,String direction)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT INTO gift_ledger(gift_id,player_id,counterparty_id,direction,asset_code,quantity,created_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)")){q.setString(1,g.id);q.setLong(2,player);q.setLong(3,counterparty);q.setString(4,direction);q.setString(5,g.asset);q.setLong(6,g.quantity);q.executeUpdate();}}
 private void eligibility(Connection c,long sender,long recipient,Policy p)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT p.player_id,a.banned_until,a.created_at FROM player_profile p JOIN aoo_account a ON a.account_id=p.player_id WHERE p.player_id IN (?,?)")){q.setLong(1,sender);q.setLong(2,recipient);Set<Long> ok=new HashSet<>();try(ResultSet r=q.executeQuery()){while(r.next()){Timestamp banned=r.getTimestamp(2);if((banned==null||!banned.toInstant().isAfter(clock.instant()))&&!r.getTimestamp(3).toInstant().isAfter(clock.instant().minus(Duration.ofHours(p.minAgeHours))))ok.add(r.getLong(1));}}if(!ok.contains(sender))throw new GiftError("GIFT_SENDER_INELIGIBLE","sender is not eligible");if(!ok.contains(recipient))throw new GiftError("GIFT_RECIPIENT_INELIGIBLE","recipient is not eligible");}}
 private Policy policy(Connection c,String asset)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT per_gift_limit,daily_sender_limit,min_account_age_hours,enabled FROM gift_policy WHERE asset_code=? FOR UPDATE")){q.setString(1,asset);try(ResultSet r=q.executeQuery()){if(!r.next()||!r.getBoolean(4))throw new GiftError("GIFT_ASSET_NOT_ALLOWED","asset is not giftable");return new Policy(r.getLong(1),r.getLong(2),r.getLong(3));}}}
 private long usage(Connection c,long s,long r,String a,LocalDate d)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT COALESCE(SUM(quantity),0) FROM gift_transfer WHERE sender_id=? AND asset_code=? AND business_date=? AND state NOT IN ('FAILED','COMPENSATED')")){q.setLong(1,s);q.setString(2,a);q.setDate(3,java.sql.Date.valueOf(d));try(ResultSet x=q.executeQuery()){x.next();return x.getLong(1);}}}
 private Gift find(Connection c,String key,boolean byKey)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT gift_id,idempotency_key,request_hash,sender_id,recipient_id,asset_code,quantity,state,failure_code FROM gift_transfer WHERE idempotency_key=?")){q.setString(1,key);try(ResultSet r=q.executeQuery()){return r.next()?gift(r):null;}}}
 private Gift findById(Connection c,String id)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT gift_id,idempotency_key,request_hash,sender_id,recipient_id,asset_code,quantity,state,failure_code FROM gift_transfer WHERE gift_id=?")){q.setString(1,id);try(ResultSet r=q.executeQuery()){return r.next()?gift(r):null;}}}
 private Gift gift(ResultSet r)throws SQLException{return new Gift(r.getString(1),r.getString(2),r.getString(3),r.getLong(4),r.getLong(5),r.getString(6),r.getLong(7),r.getString(8),r.getString(9));}
 private void audit(Connection c,String id,String event,long actor,Object detail)throws Exception{String prev="";try(PreparedStatement q=c.prepareStatement("SELECT event_hash FROM gift_audit WHERE gift_id=? ORDER BY sequence_no DESC LIMIT 1 FOR UPDATE")){q.setString(1,id);try(ResultSet r=q.executeQuery()){if(r.next())prev=r.getString(1);}}String payload=json.writeValueAsString(detail),hash=hex(java.security.MessageDigest.getInstance("SHA-256").digest((prev+"|"+id+"|"+event+"|"+actor+"|"+payload).getBytes(java.nio.charset.StandardCharsets.UTF_8)));try(PreparedStatement q=c.prepareStatement("INSERT INTO gift_audit(gift_id,event_type,actor_id,payload_json,previous_hash,event_hash,created_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)")){q.setString(1,id);q.setString(2,event);q.setLong(3,actor);q.setString(4,payload);q.setString(5,prev);q.setString(6,hash);q.executeUpdate();}}
 private static String hex(byte[] b){return java.util.HexFormat.of().formatHex(b);}private record Policy(long perGift,long daily,long minAgeHours){}
 public record Gift(String id,String idempotencyKey,String requestHash,long sender,long recipient,String asset,long quantity,String state,String failureCode){}
 public static final class GiftError extends RuntimeException{public final String code;public GiftError(String c,String m){super(m);code=c;}}
}
