package com.aoo.bcg.common.event;

import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

public final class InMemoryOutboxRepository implements OutboxRepository {
    private final ConcurrentHashMap<String, State> events = new ConcurrentHashMap<>();
    @Override public void append(OutboxEvent event) { if(event==null||event.eventId()==null||event.eventId().isBlank())throw new IllegalArgumentException("eventId is required");if(events.putIfAbsent(event.eventId(),new State(event,"PENDING",0,"",null,null,null,null))!=null)throw new IllegalStateException("duplicate outbox event: "+event.eventId()); }
    @Override public List<OutboxClaim> claim(int limit,String workerId,java.time.Instant now,java.time.Duration lease){if(limit<=0||workerId==null||workerId.isBlank()||now==null||lease==null||lease.isNegative()||lease.isZero())return List.of();return events.entrySet().stream().sorted(java.util.Comparator.comparing(e->e.getValue().event().createdAt())).filter(e->{State s=e.getValue();return("PENDING".equals(s.status())||("PROCESSING".equals(s.status())&&s.lockedUntil()!=null&&!s.lockedUntil().isAfter(now)))&&(s.nextAttemptAt()==null||!s.nextAttemptAt().isAfter(now));}).limit(limit).map(e->{State c=events.compute(e.getKey(),(id,s)->new State(s.event(),"PROCESSING",com.aoo.bcg.common.math.ExactDomainMath.increment(s.retryCount(),"outbox retry count"),s.lastError(),s.nextAttemptAt(),workerId,java.util.UUID.randomUUID().toString(),now.plus(lease)));return new OutboxClaim(c.event(),workerId,c.claimToken(),c.lockedUntil(),c.retryCount());}).toList();}
    @Override public void markPublished(OutboxClaim claim){events.compute(claim.event().eventId(),(id,s)->{requireOwner(s,claim);return new State(s.event(),"PUBLISHED",s.retryCount(),s.lastError(),s.nextAttemptAt(),null,null,null);});}
    @Override public boolean recordFailure(OutboxClaim claim,String error,java.time.Instant nextAttemptAt,int maxAttempts){if(claim==null||nextAttemptAt==null||maxAttempts<=0)throw new IllegalArgumentException("failure event and retry time are required");String safe=error==null?"unknown":error.substring(0,Math.min(error.length(),500));boolean[] dead={false};events.compute(claim.event().eventId(),(id,s)->{requireOwner(s,claim);dead[0]=s.retryCount()>=maxAttempts;return new State(s.event(),dead[0]?"DEAD":"PENDING",s.retryCount(),safe,dead[0]?null:nextAttemptAt,null,null,null);});return dead[0];}
    @Override public int purgeTerminalBefore(java.time.Instant cutoff,int limit){if(cutoff==null||limit<=0)return 0;int[] removed={0};events.entrySet().removeIf(e->removed[0]<limit&&("PUBLISHED".equals(e.getValue().status())||"DEAD".equals(e.getValue().status()))&&e.getValue().event().createdAt().isBefore(cutoff)&&++removed[0]>0);return removed[0];}
    @Override public long deadLetterCount(){return events.values().stream().filter(s->"DEAD".equals(s.status())).count();}
    @Override public OutboxBacklog backlog(){long pending=0,failed=0;java.time.Instant oldest=null;for(State s:events.values()){if("PUBLISHED".equals(s.status()))continue;pending++;if(s.retryCount()>0||"DEAD".equals(s.status()))failed++;if(oldest==null||s.event().createdAt().isBefore(oldest))oldest=s.event().createdAt();}return new OutboxBacklog(pending,failed,java.util.Optional.ofNullable(oldest));}
    private static void requireOwner(State s,OutboxClaim c){if(s==null||!"PROCESSING".equals(s.status())||!c.workerId().equals(s.workerId())||!c.claimToken().equals(s.claimToken()))throw new IllegalStateException("outbox claim ownership lost");}
    private record State(OutboxEvent event,String status,int retryCount,String lastError,java.time.Instant nextAttemptAt,String workerId,String claimToken,java.time.Instant lockedUntil){}
}
