package com.aoo.bcg.common.event;

import java.time.Clock;import java.time.Duration;import java.util.Objects;import java.util.concurrent.Executors;import java.util.concurrent.ScheduledExecutorService;import java.util.concurrent.TimeUnit;import java.util.concurrent.atomic.AtomicBoolean;import java.util.function.Consumer;

/** Owns relay lifecycle, dead-letter alerting and bounded terminal retention. */
public final class ScheduledOutboxRelay implements AutoCloseable {
    private final OutboxRelay relay;private final OutboxRepository repository;private final Clock clock;private final Duration interval;private final int batchSize;private final Consumer<Health> healthSink;private final Duration retention;private final ScheduledExecutorService executor;private final AtomicBoolean started=new AtomicBoolean();
    public ScheduledOutboxRelay(OutboxRelay relay,OutboxRepository repository,Clock clock,Duration interval,int batchSize,Consumer<Health> healthSink){this(relay,repository,clock,interval,batchSize,healthSink,Duration.ofDays(30));}
    public ScheduledOutboxRelay(OutboxRelay relay,OutboxRepository repository,Clock clock,Duration interval,int batchSize,Consumer<Health> healthSink,Duration retention){this.relay=Objects.requireNonNull(relay,"relay");this.repository=Objects.requireNonNull(repository,"repository");this.clock=Objects.requireNonNull(clock,"clock");this.interval=Objects.requireNonNull(interval,"interval");this.healthSink=Objects.requireNonNull(healthSink,"healthSink");this.retention=Objects.requireNonNull(retention,"retention");if(interval.isNegative()||interval.isZero())throw new IllegalArgumentException("interval must be positive");if(batchSize<1||batchSize>500)throw new IllegalArgumentException("batchSize must be 1..500");if(retention.isNegative()||retention.isZero())throw new IllegalArgumentException("retention must be positive");this.batchSize=batchSize;this.executor=Executors.newSingleThreadScheduledExecutor(Thread.ofPlatform().name("aoo-outbox-relay").daemon(true).factory());}
    public void start(){if(started.compareAndSet(false, true))executor.scheduleWithFixedDelay(this::runSafely,0,interval.toMillis(),TimeUnit.MILLISECONDS);}
    private void runSafely(){Throwable failure=null;int published=0;try{published=relay.publishBatch(batchSize);}catch(Throwable error){failure=error;}try{OutboxBacklog backlog=repository.backlog();long deadLetters=repository.deadLetterCount();repository.purgeTerminalBefore(clock.instant().minus(retention),batchSize);healthSink.accept(new Health(clock.instant(),published,backlog,failure==null?null:failure.getClass().getSimpleName(),deadLetters,deadLetters>0||failure!=null));}catch(Throwable ignored){/* Scheduler must survive monitoring and database outages. */}}
    @Override public void close(){executor.shutdown();try{if(!executor.awaitTermination(Math.max(100,interval.toMillis()),TimeUnit.MILLISECONDS))executor.shutdownNow();}catch(InterruptedException interrupted){executor.shutdownNow();Thread.currentThread().interrupt();}}
    public record Health(java.time.Instant observedAt,int published,OutboxBacklog backlog,String relayFailure,long deadLetters,boolean alertRequired){}
}
