package com.aoo.bcg.support;

import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.HttpServer;import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.sql.Statement;import java.time.*;import java.util.HexFormat;import static org.junit.jupiter.api.Assertions.*;

/** Proves the production case and live routes coexist on one authenticated Support listener. */
class SupportRouteAssemblyTest {
 static final String SECRET="01234567890123456789012345678901",HANDOFF="abcdefghijklmnopqrstuvwxyz0123456789";HttpServer server;String bearer;
 @BeforeEach void mount()throws Exception{var ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:routes"+System.nanoTime()+";MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");try(var c=ds.getConnection(); Statement s=c.createStatement()){
  s.execute("CREATE TABLE support_case(id BIGINT AUTO_INCREMENT PRIMARY KEY,player_id BIGINT NOT NULL,case_kind VARCHAR(20),subject VARCHAR(120),description VARCHAR(4000),status VARCHAR(20),resolution_summary VARCHAR(1000),created_at TIMESTAMP,updated_at TIMESTAMP,row_version BIGINT)");s.execute("CREATE TABLE support_case_evidence(id BIGINT AUTO_INCREMENT PRIMARY KEY,case_id BIGINT,evidence_type VARCHAR(20),reference_id VARCHAR(256),label VARCHAR(80))");s.execute("CREATE TABLE support_case_event(id BIGINT AUTO_INCREMENT PRIMARY KEY,case_id BIGINT,actor_type VARCHAR(20),actor_id BIGINT,event_type VARCHAR(40),case_status VARCHAR(20),created_at TIMESTAMP)");s.execute("CREATE TABLE replay_participant(room_id BIGINT,set_id INT,player_id BIGINT)");s.execute("CREATE TABLE replay_participant_archive(room_id BIGINT,set_id INT,player_id BIGINT)");s.execute("CREATE TABLE support_live_session(id BIGINT AUTO_INCREMENT PRIMARY KEY,case_id BIGINT,player_id BIGINT,agent_id BIGINT,status VARCHAR(20),last_message_id BIGINT,close_reason VARCHAR(500),created_at TIMESTAMP,updated_at TIMESTAMP,closed_at TIMESTAMP,row_version BIGINT)");s.execute("CREATE UNIQUE INDEX uq_live_open ON support_live_session(case_id,status)");s.execute("CREATE TABLE support_live_message(id BIGINT AUTO_INCREMENT PRIMARY KEY,session_id BIGINT,sender_type VARCHAR(20),sender_id BIGINT,body VARCHAR(2000),media_reference VARCHAR(160),created_at TIMESTAMP)");s.execute("CREATE TABLE support_live_audit(id BIGINT AUTO_INCREMENT PRIMARY KEY,session_id BIGINT,actor_type VARCHAR(20),actor_id BIGINT,event_type VARCHAR(40),event_detail VARCHAR(500),created_at TIMESTAMP)");s.execute("CREATE TABLE support_live_idempotency(actor_id BIGINT,operation_key VARCHAR(80),idempotency_key VARCHAR(128),session_id BIGINT,created_at TIMESTAMP,PRIMARY KEY(actor_id,operation_key,idempotency_key))");s.execute("CREATE TABLE media_asset(id BIGINT PRIMARY KEY,state VARCHAR(16),kind VARCHAR(16))");s.execute("CREATE TABLE media_asset_access(asset_id BIGINT,owner_id BIGINT)");}
  var clock=Clock.fixed(Instant.parse("2026-08-24T12:00:00Z"),ZoneOffset.UTC);var json=new ObjectMapper().findAndRegisterModules();var auth=new PlayerBearerAuthenticator(SECRET,clock);server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);new SupportHttpRoutes(new JdbcSupportRepository(ds,json,clock),auth,json,HANDOFF).mount(server);new SupportLiveHttpRoutes(new JdbcSupportLiveRepository(ds,clock),auth,new SupportAgentAuthenticator(HANDOFF),json).mount(server);server.start();bearer=token(7,clock.instant().plusSeconds(60).getEpochSecond());}
 @AfterEach void stop(){server.stop(0);}
 @Test void caseAndLiveContextsShareTheProductionListener()throws Exception{var client=HttpClient.newHttpClient();var cases=client.send(HttpRequest.newBuilder(uri("/v1/support/cases")).header("X-API-Version","1").GET().build(),HttpResponse.BodyHandlers.ofString());assertEquals(401,cases.statusCode());assertTrue(cases.body().contains("UNAUTHORIZED"));var live=client.send(HttpRequest.newBuilder(uri("/v1/support/live-sessions")).header("X-API-Version","1").POST(HttpRequest.BodyPublishers.ofString("{\"caseId\":1}")).build(),HttpResponse.BodyHandlers.ofString());assertEquals(401,live.statusCode());assertTrue(live.body().contains("SUPPORT_UNAUTHORIZED"));}
 private URI uri(String path){return URI.create("http://127.0.0.1:"+server.getAddress().getPort()+path);}
 private HttpResponse<String> send(HttpClient client,String path,String body,String key)throws Exception{return client.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+server.getAddress().getPort()+path)).header("Authorization","Bearer "+bearer).header("X-API-Version","1").header("Idempotency-Key",key).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());}
 private static String token(long id,long exp)throws Exception{String value=id+"."+exp;Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(SECRET.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return value+"."+HexFormat.of().formatHex(mac.doFinal(value.getBytes(StandardCharsets.UTF_8)));}
}
