package com.aoo.bcg.admin;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.*;
import java.util.*;

/** Transactional workflow, immutable audit, masked artifact, and fixed read-only source. */
public final class JdbcSensitiveExportRepository implements SensitiveExportService.Repository, SensitiveExportService.Source {
 private final JdbcAdminResourceRepository.ConnectionFactory connections;private final ObjectMapper json;
 public JdbcSensitiveExportRepository(JdbcAdminResourceRepository.ConnectionFactory connections,ObjectMapper json){this.connections=Objects.requireNonNull(connections);this.json=Objects.requireNonNull(json);}
 public Optional<SensitiveExportService.Request> find(String id){try(Connection c=connections.open();PreparedStatement s=c.prepareStatement("SELECT definition_code,scope_code,row_limit,requester_id,approver_id,reason,state,updated_at FROM admin_sensitive_export WHERE export_id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(request(id,r)):Optional.empty();}}catch(Exception e){throw failure("read export",e);}}
 public Optional<SensitiveExportService.Request> findByRequestId(String id){try(Connection c=connections.open();PreparedStatement s=c.prepareStatement("SELECT e.export_id,e.definition_code,e.scope_code,e.row_limit,e.requester_id,e.approver_id,e.reason,e.state,e.updated_at FROM admin_sensitive_export_request d JOIN admin_sensitive_export e ON e.export_id=d.export_id WHERE d.request_id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(request(r.getString(1),r,2)):Optional.empty();}}catch(Exception e){throw failure("read export idempotency",e);}}
 public void create(String id,SensitiveExportService.Request value,SensitiveExportService.Audit audit){tx(c->{try(PreparedStatement s=c.prepareStatement("INSERT INTO admin_sensitive_export(export_id,definition_code,scope_code,row_limit,requester_id,reason,state,updated_at) VALUES(?,?,?,?,?,?,?,?)")){s.setString(1,value.exportId());s.setString(2,value.definitionCode());s.setString(3,value.scope());s.setInt(4,value.rowLimit());s.setLong(5,value.requesterId());s.setString(6,value.reason());s.setString(7,value.state().name());s.setObject(8,value.updatedAt());s.executeUpdate();}dedup(c,id,value.exportId());audit(c,audit);});}
 public void transition(String id,SensitiveExportService.Request expected,SensitiveExportService.Request updated,SensitiveExportService.Audit audit,SensitiveExportService.Artifact artifact){tx(c->{try(PreparedStatement lock=c.prepareStatement("SELECT state,updated_at FROM admin_sensitive_export WHERE export_id=? FOR UPDATE")){lock.setString(1,expected.exportId());try(ResultSet r=lock.executeQuery()){if(!r.next()||!r.getString(1).equals(expected.state().name())||!r.getTimestamp(2).toInstant().equals(expected.updatedAt()))throw new IllegalStateException("export changed concurrently");}}try(PreparedStatement s=c.prepareStatement("UPDATE admin_sensitive_export SET approver_id=?,state=?,updated_at=? WHERE export_id=?")){if(updated.approverId()==null)s.setNull(1,Types.BIGINT);else s.setLong(1,updated.approverId());s.setString(2,updated.state().name());s.setObject(3,updated.updatedAt());s.setString(4,updated.exportId());s.executeUpdate();}dedup(c,id,updated.exportId());if(artifact!=null)try(PreparedStatement s=c.prepareStatement("INSERT INTO admin_sensitive_export_artifact(export_id,artifact_json,content_hash,generated_at,expires_at) VALUES(?,?,?,?,?)")){s.setString(1,artifact.exportId());s.setString(2,json.writeValueAsString(artifact));s.setString(3,artifact.contentHash());s.setObject(4,artifact.generatedAt());s.setObject(5,artifact.expiresAt());s.executeUpdate();}audit(c,audit);});}
 public Optional<SensitiveExportService.Artifact> artifact(String id){String sql="SELECT artifact_json,content_hash,generated_at,expires_at FROM admin_sensitive_export_artifact WHERE export_id=?";try(Connection c=connections.open();PreparedStatement s=c.prepareStatement(sql)){s.setString(1,id);try(ResultSet r=s.executeQuery()){if(!r.next())return Optional.empty();SensitiveExportService.Artifact value=json.readValue(r.getString(1),SensitiveExportService.Artifact.class);if(!value.contentHash().equals(r.getString(2))||!value.generatedAt().equals(r.getTimestamp(3).toInstant())||!value.expiresAt().equals(r.getTimestamp(4).toInstant()))throw new IllegalStateException("artifact metadata integrity failure");return Optional.of(value);}}catch(Exception e){throw failure("read artifact",e);}}
 public List<SensitiveExportService.Audit> audit(){try(Connection c=connections.open();PreparedStatement s=c.prepareStatement("SELECT export_id,operator_id,action,scope_code,row_count,content_hash,occurred_at FROM admin_sensitive_export_audit ORDER BY audit_id");ResultSet r=s.executeQuery()){List<SensitiveExportService.Audit> values=new ArrayList<>();while(r.next())values.add(new SensitiveExportService.Audit(r.getString(1),r.getLong(2),r.getString(3),r.getString(4),r.getInt(5),r.getString(6),r.getTimestamp(7).toInstant()));return List.copyOf(values);}catch(Exception e){throw failure("read export audit",e);}}
 public void appendAudit(SensitiveExportService.Audit value){tx(c->audit(c,value));}
 public List<Map<String,Object>> rows(SensitiveExportService.Definition d,String scope,int limit){if(!d.code().equals("club-member-support")||!scope.startsWith("CLUB:"))throw new IllegalArgumentException("export definition not allowed");long club=Long.parseLong(scope.substring("CLUB:".length()));String sql="SELECT player_id,member_status,member_role,JSON_UNQUOTE(JSON_EXTRACT(profile_payload,'$.phone')) phone,JSON_UNQUOTE(JSON_EXTRACT(profile_payload,'$.email')) email,joined_at FROM aoo_club_member WHERE club_id=? ORDER BY player_id LIMIT ?";try(Connection c=connections.open()){c.setReadOnly(true);try(PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,club);s.setInt(2,limit);try(ResultSet r=s.executeQuery()){List<Map<String,Object>> values=new ArrayList<>();while(r.next()){Map<String,Object> row=new LinkedHashMap<>();for(String key:List.of("player_id","member_status","member_role","phone","email","joined_at")){Object item=r.getObject(key);row.put(key,item==null?"":item);}values.add(Map.copyOf(row));}return List.copyOf(values);}}}catch(Exception e){throw failure("read authoritative export source",e);}}
 private SensitiveExportService.Request request(String id,ResultSet r)throws Exception{return request(id,r,1);}private SensitiveExportService.Request request(String id,ResultSet r,int o)throws Exception{return new SensitiveExportService.Request(id,r.getString(o),r.getString(o+1),r.getInt(o+2),r.getLong(o+3),(Long)r.getObject(o+4),r.getString(o+5),SensitiveExportService.State.valueOf(r.getString(o+6)),r.getTimestamp(o+7).toInstant());}
 private void dedup(Connection c,String id,String export)throws Exception{try(PreparedStatement s=c.prepareStatement("INSERT INTO admin_sensitive_export_request(request_id,export_id) VALUES(?,?)")){s.setString(1,id);s.setString(2,export);s.executeUpdate();}}
 private void audit(Connection c,SensitiveExportService.Audit a)throws Exception{try(PreparedStatement s=c.prepareStatement("INSERT INTO admin_sensitive_export_audit(export_id,operator_id,action,scope_code,row_count,content_hash,occurred_at) VALUES(?,?,?,?,?,?,?)")){s.setString(1,a.exportId());s.setLong(2,a.operatorId());s.setString(3,a.action());s.setString(4,a.scope());s.setInt(5,a.rowCount());s.setString(6,a.contentHash());s.setObject(7,a.occurredAt());s.executeUpdate();}}
 @FunctionalInterface private interface Work{void run(Connection c)throws Exception;}private void tx(Work work){try(Connection c=connections.open()){c.setAutoCommit(false);try{work.run(c);c.commit();}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw failure("persist export workflow",e);}}
 private IllegalStateException failure(String action,Exception e){return new IllegalStateException("cannot "+action,e);}
}
