package com.aoo.bcg.admin;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/** Whitelist-only, approved, masked, watermarked export workflow. */
public final class SensitiveExportService {
 public enum State { PENDING_APPROVAL, APPROVED, EXPORTED }
 public enum Mask { NONE, PHONE, EMAIL, IDENTITY, IP, TOKEN }
 public record Definition(String code,Set<String> allowedScopes,int maximumRows,Map<String,Mask> columns){public Definition{if(blank(code)||allowedScopes==null||allowedScopes.isEmpty()||maximumRows<1||maximumRows>100_000||columns==null||columns.isEmpty())throw new IllegalArgumentException("safe export definition required");allowedScopes=Set.copyOf(allowedScopes);columns=Map.copyOf(columns);}}
 public record Request(String exportId,String definitionCode,String scope,int rowLimit,long requesterId,Long approverId,String reason,State state,Instant updatedAt){}
 public record Artifact(String exportId,List<Map<String,String>> rows,String watermark,String contentHash,Instant generatedAt,Instant expiresAt){public Artifact{rows=List.copyOf(rows);}}
 public record Audit(String exportId,long operatorId,String action,String scope,int rowCount,String contentHash,Instant occurredAt){}
 @FunctionalInterface public interface Source{List<Map<String,Object>> rows(Definition definition,String scope,int limit);}
 public interface Repository{Optional<Request> find(String id);Optional<Request> findByRequestId(String id);void create(String id,Request request,Audit audit);void transition(String id,Request expected,Request updated,Audit audit,Artifact artifact);Optional<Artifact> artifact(String id);void appendAudit(Audit audit);List<Audit> audit();}
 public static final class InMemoryRepository implements Repository{
  private final Map<String,Request> requests=new ConcurrentHashMap<>(),dedup=new ConcurrentHashMap<>();private final Map<String,Artifact> artifacts=new ConcurrentHashMap<>();private final List<Audit> audits=new ArrayList<>();
  public Optional<Request> find(String id){return Optional.ofNullable(requests.get(id));}public Optional<Request> findByRequestId(String id){return Optional.ofNullable(dedup.get(id));}
  public synchronized void create(String id,Request value,Audit audit){if(requests.putIfAbsent(value.exportId(),value)!=null||dedup.putIfAbsent(id,value)!=null)throw new IllegalStateException("export or request id already exists");audits.add(audit);}
  public synchronized void transition(String id,Request expected,Request updated,Audit audit,Artifact artifact){if(dedup.containsKey(id)||!requests.replace(expected.exportId(),expected,updated))throw new IllegalStateException("export changed concurrently or request id used");dedup.put(id,updated);if(artifact!=null)artifacts.put(updated.exportId(),artifact);audits.add(audit);}
  public Optional<Artifact> artifact(String id){return Optional.ofNullable(artifacts.get(id));}public synchronized void appendAudit(Audit audit){audits.add(audit);}public synchronized List<Audit> audit(){return List.copyOf(audits);}
 }
 private final Map<String,Definition> definitions;private final Source source;private final Repository repository;private final Clock clock;private final Duration ttl;
 public SensitiveExportService(List<Definition> definitions,Source source,Clock clock){this(definitions,source,new InMemoryRepository(),clock,Duration.ofMinutes(10));}
 public SensitiveExportService(List<Definition> definitions,Source source,Repository repository,Clock clock,Duration ttl){Map<String,Definition> values=new LinkedHashMap<>();for(Definition d:definitions)if(values.put(d.code(),d)!=null)throw new IllegalArgumentException("duplicate export definition");if(ttl==null||ttl.isZero()||ttl.isNegative()||ttl.compareTo(Duration.ofHours(1))>0)throw new IllegalArgumentException("safe download ttl required");this.definitions=Map.copyOf(values);this.source=Objects.requireNonNull(source);this.repository=Objects.requireNonNull(repository);this.clock=Objects.requireNonNull(clock);this.ttl=ttl;}
 public Request request(String requestId,String exportId,String code,String scope,int limit,long operator,String reason){Request repeat=repeat(requestId,exportId);if(repeat!=null)return repeat;Definition d=definition(code);if(!scopeAllowed(d,scope)||limit<1||limit>d.maximumRows()||operator<=0||blank(reason))throw new IllegalArgumentException("invalid export request");Instant now=now();Request value=new Request(exportId,code,scope,limit,operator,null,reason,State.PENDING_APPROVAL,now);repository.create(requestId,value,new Audit(exportId,operator,"REQUESTED",scope,0,"",now));return value;}
 public Request approve(String requestId,String exportId,long operator,String reason){Request repeat=repeat(requestId,exportId);if(repeat!=null)return repeat;Request current=required(exportId,State.PENDING_APPROVAL);if(operator<=0||operator==current.requesterId()||blank(reason))throw new IllegalArgumentException("independent approver required");Instant now=now();Request value=copy(current,operator,State.APPROVED,now);repository.transition(requestId,current,value,new Audit(exportId,operator,"APPROVED",current.scope(),0,"",now),null);return value;}
 public Artifact export(String requestId,String exportId,long operator,String reason){if(repository.findByRequestId(requestId).isPresent())throw new IllegalStateException("request id already used; export is one-time");Request current=required(exportId,State.APPROVED);if((operator!=current.requesterId()&&operator!=current.approverId())||blank(reason))throw new IllegalArgumentException("workflow participant required");Definition d=definition(current.definitionCode());List<Map<String,Object>> raw=source.rows(d,current.scope(),current.rowLimit());if(raw.size()>current.rowLimit())throw new IllegalStateException("export source exceeded approved range");Instant now=now();String watermark="AOO-ADMIN export="+exportId+" operator="+operator+" scope="+current.scope()+" generated="+now;List<Map<String,String>> rows=raw.stream().map(row->mask(row,d,watermark)).toList();String hash=hash(canonical(rows),watermark,now.toString());Artifact artifact=new Artifact(exportId,rows,watermark,hash,now,now.plus(ttl));Request value=copy(current,current.approverId(),State.EXPORTED,now);repository.transition(requestId,current,value,new Audit(exportId,operator,"EXPORTED",current.scope(),rows.size(),hash,now),artifact);return artifact;}
 public Artifact download(String id,long operator){Request request=required(id,State.EXPORTED);if(operator!=request.requesterId()&&operator!=request.approverId())throw new IllegalArgumentException("workflow participant required");Artifact value=repository.artifact(id).orElseThrow(()->new IllegalStateException("artifact unavailable"));if(!clock.instant().isBefore(value.expiresAt()))throw new IllegalStateException("export download expired");if(!hash(canonical(value.rows()),value.watermark(),value.generatedAt().toString()).equals(value.contentHash()))throw new IllegalStateException("export artifact integrity failure");repository.appendAudit(new Audit(id,operator,"DOWNLOADED",request.scope(),value.rows().size(),value.contentHash(),now()));return value;}
 public List<Audit> audit(){return repository.audit();}public Optional<Request> find(String id){return repository.find(id);}
 private Map<String,String> mask(Map<String,Object> row,Definition d,String watermark){Map<String,String> value=new LinkedHashMap<>();d.columns().forEach((key,type)->value.put(key,masked(String.valueOf(row.getOrDefault(key,"")),type)));value.put("_watermark",watermark);return Map.copyOf(value);}
 private String masked(String value,Mask mask){return switch(mask){case NONE->value;case PHONE->value.length()<7?"***":value.substring(0,3)+"****"+value.substring(value.length()-4);case EMAIL->{int at=value.indexOf('@');yield at<1?"***":value.charAt(0)+"***"+value.substring(at);}case IDENTITY->value.length()<8?"***":value.substring(0,4)+"**********"+value.substring(value.length()-4);case IP->{int dot=value.lastIndexOf('.');yield dot<0?"***":value.substring(0,dot+1)+"*";}case TOKEN->"[REDACTED]";};}
 private Request repeat(String requestId,String exportId){if(blank(requestId)||blank(exportId))throw new IllegalArgumentException("requestId and exportId required");Request value=repository.findByRequestId(requestId).orElse(null);if(value!=null&&!value.exportId().equals(exportId))throw new IllegalArgumentException("requestId already used by another export");return value;}
 private Request required(String id,State state){Request value=repository.find(id).orElseThrow(()->new IllegalArgumentException("export not found"));if(value.state()!=state)throw new IllegalStateException("export state does not permit action");return value;}
 private Request copy(Request v,Long approver,State state,Instant now){return new Request(v.exportId(),v.definitionCode(),v.scope(),v.rowLimit(),v.requesterId(),approver,v.reason(),state,now);}
 private Definition definition(String code){return Optional.ofNullable(definitions.get(code)).orElseThrow(()->new IllegalArgumentException("export definition not allowed"));}
 private boolean scopeAllowed(Definition d,String scope){if(scope==null)return false;if(d.allowedScopes().contains(scope))return true;int split=scope.indexOf(':');return split>0&&scope.substring(split+1).matches("[1-9][0-9]{0,18}")&&d.allowedScopes().contains(scope.substring(0,split));}
 private String hash(String... values){try{MessageDigest d=MessageDigest.getInstance("SHA-256");for(String value:values)d.update(value.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(d.digest());}catch(Exception e){throw new IllegalStateException(e);}}
 private String canonical(List<Map<String,String>> rows){StringBuilder b=new StringBuilder();for(Map<String,String> row:rows){new TreeMap<>(row).forEach((k,v)->b.append(k).append('=').append(v.length()).append(':').append(v).append(';'));b.append('\n');}return b.toString();}
 private Instant now(){return clock.instant().truncatedTo(java.time.temporal.ChronoUnit.MILLIS);}
 private static boolean blank(String value){return value==null||value.isBlank();}
}
