package com.aoo.bcg.ranking;

import javax.sql.DataSource;import java.sql.*;import java.time.*;import java.util.*;import java.nio.charset.StandardCharsets;

/** Authoritative JDBC ranking/achievement workflow. All mutations are transactionally serialized. */
public final class RankingAchievementService {
 private final DataSource db;private final RewardPort rewards;private final Clock clock;
 public RankingAchievementService(DataSource db,RewardPort rewards,Clock clock){this.db=Objects.requireNonNull(db);this.rewards=Objects.requireNonNull(rewards);this.clock=Objects.requireNonNull(clock);}
 public void addScore(String season,long player,long delta){if(player<=0||delta<=0)throw new IllegalArgumentException("positive player and delta required");tx(c->{requireActive(c,season);Timestamp now=Timestamp.from(clock.instant());int n;try(var q=c.prepareStatement("UPDATE aoo_rank_score SET score=score+?,updated_at=? WHERE season_id=? AND player_id=?")){q.setLong(1,delta);q.setTimestamp(2,now);q.setString(3,season);q.setLong(4,player);n=q.executeUpdate();}if(n==0)try(var q=c.prepareStatement("INSERT INTO aoo_rank_score(season_id,player_id,score,updated_at) VALUES(?,?,?,?)")){q.setString(1,season);q.setLong(2,player);q.setLong(3,delta);q.setTimestamp(4,now);q.executeUpdate();}return null;});}
 public Page leaderboard(String season,String cursor,int limit){if(limit<1||limit>100)throw new IllegalArgumentException("limit must be 1..100");Cursor after=decode(cursor);return tx(c->{requireSeason(c,season);String sql="SELECT player_id,score FROM aoo_rank_score WHERE season_id=?"+(after==null?"":" AND (score<? OR (score=? AND player_id>?))")+" ORDER BY score DESC,player_id ASC LIMIT ?";List<Entry> rows=new ArrayList<>();try(var q=c.prepareStatement(sql)){int i=1;q.setString(i++,season);if(after!=null){q.setLong(i++,after.score);q.setLong(i++,after.score);q.setLong(i++,after.player);}q.setInt(i,limit+1);try(var r=q.executeQuery()){while(r.next())rows.add(new Entry(r.getLong(1),r.getLong(2)));}}String next=null;if(rows.size()>limit){rows.remove(limit);Entry e=rows.getLast();next=encode(e.score,e.playerId);}return new Page(List.copyOf(rows),next);});}
 public Standing standing(String season,long player){return tx(c->{requireSeason(c,season);try(var q=c.prepareStatement("SELECT score,1+(SELECT COUNT(*) FROM aoo_rank_score x WHERE x.season_id=s.season_id AND (x.score>s.score OR (x.score=s.score AND x.player_id<s.player_id))) FROM aoo_rank_score s WHERE season_id=? AND player_id=?")){q.setString(1,season);q.setLong(2,player);try(var r=q.executeQuery()){return r.next()?new Standing(player,r.getLong(1),r.getLong(2)):new Standing(player,0,0);}}});}
 public void advance(long player,String code,long delta){if(player<=0||delta<=0)throw new IllegalArgumentException("positive player and delta required");tx(c->{definition(c,code);Timestamp now=Timestamp.from(clock.instant());int n;try(var q=c.prepareStatement("UPDATE aoo_achievement_progress SET progress=progress+?,updated_at=? WHERE player_id=? AND achievement_code=?")){q.setLong(1,delta);q.setTimestamp(2,now);q.setLong(3,player);q.setString(4,code);n=q.executeUpdate();}if(n==0)try(var q=c.prepareStatement("INSERT INTO aoo_achievement_progress(player_id,achievement_code,progress,updated_at) VALUES(?,?,?,?)")){q.setLong(1,player);q.setString(2,code);q.setLong(3,delta);q.setTimestamp(4,now);q.executeUpdate();}return null;});}
 public List<Achievement> achievements(long player){return tx(c->{List<Achievement> out=new ArrayList<>();try(var q=c.prepareStatement("SELECT d.code,d.target_value,COALESCE(p.progress,0),d.reward_kind,d.reward_code,d.reward_amount,(cl.player_id IS NOT NULL) FROM aoo_achievement_definition d LEFT JOIN aoo_achievement_progress p ON p.achievement_code=d.code AND p.player_id=? LEFT JOIN aoo_achievement_claim cl ON cl.achievement_code=d.code AND cl.player_id=? WHERE d.enabled=TRUE ORDER BY d.code")){q.setLong(1,player);q.setLong(2,player);try(var r=q.executeQuery()){while(r.next())out.add(new Achievement(r.getString(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getLong(6),r.getBoolean(7)));}}return List.copyOf(out);});}
 public Claim claim(long player,String code){return tx(c->{Definition d=definition(c,code);long progress=0;try(var q=c.prepareStatement("SELECT progress FROM aoo_achievement_progress WHERE player_id=? AND achievement_code=? FOR UPDATE")){q.setLong(1,player);q.setString(2,code);try(var r=q.executeQuery()){if(r.next())progress=r.getLong(1);}}if(progress<d.target)throw new IllegalStateException("achievement incomplete");String business="achievement:"+player+":"+code;try(var q=c.prepareStatement("INSERT INTO aoo_achievement_claim(player_id,achievement_code,business_id,claimed_at) VALUES(?,?,?,?)")){q.setLong(1,player);q.setString(2,code);q.setString(3,business);q.setTimestamp(4,Timestamp.from(clock.instant()));q.executeUpdate();}catch(SQLIntegrityConstraintViolationException duplicate){return new Claim(business,true);}if("CURRENCY".equals(d.kind))rewards.creditCurrency(business,player,d.rewardCode,d.amount);else rewards.grantItem(business,player,d.rewardCode,d.amount);return new Claim(business,false);});}
 public void transitionSeason(String season,String target){if(!Set.of("FROZEN","CLOSED").contains(target))throw new IllegalArgumentException("target must be FROZEN or CLOSED");tx(c->{String current=requireSeason(c,season);if(("ACTIVE".equals(current)&&"FROZEN".equals(target))||("FROZEN".equals(current)&&"CLOSED".equals(target))){try(var q=c.prepareStatement("UPDATE aoo_rank_season SET state=? WHERE id=? AND state=?")){q.setString(1,target);q.setString(2,season);q.setString(3,current);q.executeUpdate();}}else if(!current.equals(target))throw new IllegalStateException("invalid season transition");return null;});}
 private void requireActive(Connection c,String season)throws SQLException{if(!"ACTIVE".equals(requireSeason(c,season)))throw new IllegalStateException("season is frozen");}
 private String requireSeason(Connection c,String id)throws SQLException{try(var q=c.prepareStatement("SELECT state FROM aoo_rank_season WHERE id=?")){q.setString(1,id);try(var r=q.executeQuery()){if(!r.next())throw new NoSuchElementException("season not found");return r.getString(1);}}}
 private Definition definition(Connection c,String code)throws SQLException{try(var q=c.prepareStatement("SELECT target_value,reward_kind,reward_code,reward_amount FROM aoo_achievement_definition WHERE code=? AND enabled=TRUE")){q.setString(1,code);try(var r=q.executeQuery()){if(!r.next())throw new NoSuchElementException("achievement not found");return new Definition(r.getLong(1),r.getString(2),r.getString(3),r.getLong(4));}}}
 private <T>T tx(Sql<T> work){try(var c=db.getConnection()){c.setAutoCommit(false);try{T value=work.run(c);c.commit();return value;}catch(Exception x){c.rollback();throw x;}}catch(RuntimeException x){throw x;}catch(Exception x){throw new IllegalStateException("ranking persistence failed",x);}}
 private static String encode(long score,long player){return Base64.getUrlEncoder().withoutPadding().encodeToString((score+":"+player).getBytes(StandardCharsets.UTF_8));}private static Cursor decode(String v){if(v==null||v.isBlank())return null;try{String[] p=new String(Base64.getUrlDecoder().decode(v),StandardCharsets.UTF_8).split(":",2);return new Cursor(Long.parseLong(p[0]),Long.parseLong(p[1]));}catch(Exception x){throw new IllegalArgumentException("invalid cursor");}}
 @FunctionalInterface interface Sql<T>{T run(Connection c)throws Exception;}private record Cursor(long score,long player){}private record Definition(long target,String kind,String rewardCode,long amount){}
 public interface RewardPort{void creditCurrency(String businessId,long playerId,String currency,long amount);void grantItem(String businessId,long playerId,String itemCode,long amount);}
 public record Entry(long playerId,long score){}public record Page(List<Entry> entries,String nextCursor){}public record Standing(long playerId,long score,long rank){}public record Achievement(String code,long target,long progress,String rewardKind,String rewardCode,long rewardAmount,boolean claimed){}public record Claim(String businessId,boolean alreadyClaimed){}
}
