package com.aoo.bcg.ranking;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;

public final class RankingAchievementHttpRoutes{
 private final RankingAchievementService service;private final PlayerAuth auth;private final ObjectMapper json;private final byte[] internal;
 public RankingAchievementHttpRoutes(RankingAchievementService service,PlayerAuth auth,ObjectMapper json,String internalToken){this.service=service;this.auth=auth;this.json=json;if(internalToken==null||internalToken.length()<32)throw new IllegalArgumentException("internal token too short");internal=internalToken.getBytes(StandardCharsets.UTF_8);}
 public void mount(HttpServer s){s.createContext("/health/ranking",e->reply(e,200,Map.of("status","UP","persistence","jdbc")));s.createContext("/v1/rankings",this::rankings);s.createContext("/v1/achievements",this::achievements);s.createContext("/internal/v1/ranking",this::internal);}
 private void rankings(HttpExchange e)throws IOException{handle(e,()->{long player=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));String[] p=parts(e,"/v1/rankings");if(p.length<1)throw api(404,"ROUTE_NOT_FOUND");String season=p[0];if(p.length==1&&"GET".equals(e.getRequestMethod()))return service.leaderboard(season,query(e,"cursor"),intQuery(e,"limit",50));if(p.length==2&&"me".equals(p[1])&&"GET".equals(e.getRequestMethod()))return service.standing(season,player);throw api(404,"ROUTE_NOT_FOUND");});}
 private void achievements(HttpExchange e)throws IOException{handle(e,()->{long player=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));String[] p=parts(e,"/v1/achievements");if(p.length==0&&"GET".equals(e.getRequestMethod()))return service.achievements(player);if(p.length==2&&"claim".equals(p[1])&&"POST".equals(e.getRequestMethod()))return service.claim(player,p[0]);throw api(404,"ROUTE_NOT_FOUND");});}
 private void internal(HttpExchange e)throws IOException{handle(e,()->{authorizeInternal(e);Map<String,Object>b=body(e);String[]p=parts(e,"/internal/v1/ranking");if(p.length==1&&"score".equals(p[0])&&"POST".equals(e.getRequestMethod())){service.addScore(text(b,"seasonId"),number(b,"playerId"),number(b,"delta"));return Map.of("accepted",true);}if(p.length==1&&"progress".equals(p[0])&&"POST".equals(e.getRequestMethod())){service.advance(number(b,"playerId"),text(b,"achievementCode"),number(b,"delta"));return Map.of("accepted",true);}if(p.length==2&&"seasons".equals(p[0])&&"POST".equals(e.getRequestMethod())){service.transitionSeason(p[1],text(b,"state"));return Map.of("updated",true);}throw api(404,"ROUTE_NOT_FOUND");});}
 private void authorizeInternal(HttpExchange e){String h=e.getRequestHeaders().getFirst("Authorization");byte[]v=h!=null&&h.startsWith("Bearer ")?h.substring(7).getBytes(StandardCharsets.UTF_8):new byte[0];if(!MessageDigest.isEqual(internal,v))throw new SecurityException("internal credential required");}
 private void handle(HttpExchange e,Action a)throws IOException{try{if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw api(426,"API_VERSION_REQUIRED");reply(e,200,Map.of("code","OK","data",a.run()));}catch(Api x){reply(e,x.status,Map.of("code",x.code));}catch(SecurityException x){reply(e,401,Map.of("code","UNAUTHORIZED"));}catch(NoSuchElementException x){reply(e,404,Map.of("code","NOT_FOUND"));}catch(IllegalArgumentException x){reply(e,400,Map.of("code","INVALID_REQUEST","message",String.valueOf(x.getMessage())));}catch(IllegalStateException x){reply(e,409,Map.of("code","CONFLICT","message",String.valueOf(x.getMessage())));}}
 private Map<String,Object>body(HttpExchange e)throws IOException{return json.readValue(e.getRequestBody(),new TypeReference<>(){});}private static String text(Map<String,Object>b,String k){Object v=b.get(k);if(v instanceof String s&&!s.isBlank())return s;throw new IllegalArgumentException(k+" required");}private static long number(Map<String,Object>b,String k){Object v=b.get(k);if(v instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+" required");}private static String[]parts(HttpExchange e,String root){String v=e.getRequestURI().getPath().substring(root.length());return v.isBlank()||"/".equals(v)?new String[0]:v.substring(1).split("/");}private static String query(HttpExchange e,String key){String q=e.getRequestURI().getRawQuery();if(q!=null)for(String pair:q.split("&")){String[]p=pair.split("=",2);if(p[0].equals(key))return p.length==2?java.net.URLDecoder.decode(p[1],StandardCharsets.UTF_8):"";}return null;}private static int intQuery(HttpExchange e,String k,int d){String v=query(e,k);return v==null?d:Integer.parseInt(v);}
 private void reply(HttpExchange e,int status,Object value)throws IOException{byte[]b=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,b.length);try(var o=e.getResponseBody()){o.write(b);}}private static Api api(int s,String c){return new Api(s,c);}@FunctionalInterface private interface Action{Object run()throws IOException;}@FunctionalInterface public interface PlayerAuth{long authenticate(String authorization);}private static final class Api extends RuntimeException{final int status;final String code;Api(int s,String c){status=s;code=c;}}
}
