package com.aoo.bcg.account;
import static org.junit.jupiter.api.Assertions.*;
import java.time.*;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.Test;
class SecurityPrimitivesTest {
 @Test void passwordsAreSaltedAndPlaintextIsRejected(){var h=new PasswordHasher();char[] p="correct horse battery".toCharArray();var a=h.hash(p);var b=h.hash(p);assertNotEquals(a,b);assertTrue(h.verify(p,a));assertThrows(IllegalArgumentException.class,()->h.requireModernEncoding("plaintext"));}
 @Test void signedContextEnforcesSkewAndReplay(){var now=Instant.parse("2026-08-24T00:00:00Z");var v=new TrustedClientContextVerifier(new byte[32],Clock.fixed(now,ZoneOffset.UTC),Duration.ofSeconds(30));var c=new TrustedClientContextVerifier.TrustedClientContext("d","c","v","ip");var signed=v.sign(c,now,"nonce");assertEquals(c,v.verify(signed));assertThrows(SecurityException.class,()->v.verify(signed));assertThrows(SecurityException.class,()->v.verify(v.sign(c,now.minusSeconds(31),"old")));}
 @Test void verificationCodesAreOneTimeAndRateLimited(){var now=Instant.parse("2026-08-24T00:00:00Z");var delivered=new AtomicReference<String>();var codes=new VerificationCodeService(Clock.fixed(now,ZoneOffset.UTC),(destination,purpose,code,expires)->delivered.set(code));codes.issue("User@Example.com",VerificationCodeService.Purpose.LOGIN);var wrong=delivered.get().equals("000000")?"000001":"000000";assertThrows(VerificationCodeService.InvalidCode.class,()->codes.consume("user@example.com",VerificationCodeService.Purpose.LOGIN,wrong));codes.consume("user@example.com",VerificationCodeService.Purpose.LOGIN,delivered.get());assertThrows(VerificationCodeService.InvalidCode.class,()->codes.consume("user@example.com",VerificationCodeService.Purpose.LOGIN,delivered.get()));codes.issue("other@example.com",VerificationCodeService.Purpose.LOGIN);assertThrows(VerificationCodeService.RateLimited.class,()->codes.issue("other@example.com",VerificationCodeService.Purpose.LOGIN));}
 @Test void webPolicyRejectsCrossOriginCsrfAndSocketTicketReplay(){var now=Instant.parse("2026-08-24T00:00:00Z");var web=new WebSessionSecurity(Set.of("https://game.example"),Clock.fixed(now,ZoneOffset.UTC));var csrf="01234567890123456789012345678901";web.authorizeMutation("https://game.example",csrf,csrf);assertThrows(SecurityException.class,()->web.authorizeMutation("https://evil.example",csrf,csrf));var opaque="01234567890123456789012345678901";assertTrue(web.hardenedRefreshCookie(opaque,Duration.ofDays(1)).contains("Secure; HttpOnly; SameSite=Strict"));assertThrows(IllegalArgumentException.class,()->web.hardenedRefreshCookie("x; SameSite=None",Duration.ofDays(1)));assertThrows(IllegalArgumentException.class,()->new WebSessionSecurity(Set.of("https://game.example/path"),Clock.fixed(now,ZoneOffset.UTC)));var ticket=web.issueSocketTicket(7,"https://game.example");assertEquals(7,web.consumeSocketTicket(ticket,"https://game.example"));assertThrows(SecurityException.class,()->web.consumeSocketTicket(ticket,"https://game.example"));}
}
