package com.aoo.bcg.account;
import com.aoo.bcg.account.wechat.*;import com.aoo.bcg.common.persistence.DriverManagerDataSource;import com.fasterxml.jackson.databind.*;import com.sun.net.httpserver.HttpServer;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.sql.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import static org.junit.jupiter.api.Assertions.*;
@EnabledIfEnvironmentVariable(named="AOO_DB_IT_URL",matches=".+")
class UnifiedIdentityMysqlHttpIntegrationTest{
 static final String OP="ch14-operator-token",MFA="ch14-second-factor";static DriverManagerDataSource ds;static HttpServer server;static HttpClient http;static ObjectMapper json;static String base;static int seq;
 @BeforeAll static void start()throws Exception{ds=new DriverManagerDataSource(System.getenv("AOO_DB_IT_URL"),System.getenv("AOO_DB_IT_USER"),System.getenv("AOO_DB_IT_PASSWORD"));json=new ObjectMapper().findAndRegisterModules();Clock clock=Clock.systemUTC();var sessions=new JdbcAccountSessionService(ds,clock);server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),32);AccountHttpRoutes.mount(server,sessions,json,OP);new IdentityHttpRoutes(ds,new UnifiedIdentityService(ds,clock),new TrustedDevicePinService(ds,clock),sessions,json,OP,MFA).mount(server);server.setExecutor(java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor());server.start();base="http://127.0.0.1:"+server.getAddress().getPort();http=HttpClient.newHttpClient();try(Connection c=ds.getConnection();Statement s=c.createStatement()){s.executeUpdate("INSERT IGNORE INTO admin_role(role_code,display_name,enabled,created_at) VALUES('ch14_identity_admin','Chapter14 IT',1,CURRENT_TIMESTAMP(3))");for(String p:List.of("account.identity.read","account.identity.mutate","account.identity.migrate"))s.executeUpdate("INSERT IGNORE INTO admin_role_permission(role_code,permission_code,granted_at) VALUES('ch14_identity_admin','"+p+"',CURRENT_TIMESTAMP(3))");s.executeUpdate("INSERT IGNORE INTO admin_operator_role(operator_id,role_code,enabled,granted_by,granted_at) VALUES(14001,'ch14_identity_admin',1,14001,CURRENT_TIMESTAMP(3))");}}
 @AfterAll static void stop(){if(server!=null)server.stop(0);}
 @Test void realMysqlHttpIdentityLifecycle()throws Exception{String suffix=Long.toString(System.nanoTime());JsonNode a=post("/api/v2/account/register",Map.of("login","alpha"+suffix,"password","correct horse battery staple","recovery","recovery-a-"+suffix),false);long aid=a.get("accountId").asLong();String old=a.get("displayId").asText();JsonNode b=post("/api/v2/account/register",Map.of("login","beta"+suffix,"password","another correct battery staple","recovery","recovery-b-"+suffix),false);long bid=b.get("accountId").asLong();String access=post("/api/v2/account/login",Map.of("identity",old,"password","correct horse battery staple","mode","multi"),false).get("accessToken").asText();
 admin("/admin/bind",Map.of("accountId",aid+"","identityType","ALIAS","value","hero"+suffix,"verified","true"));admin("/admin/bind",Map.of("accountId",aid+"","identityType","PHONE","value","+86138"+suffix.substring(Math.max(0,suffix.length()-8)),"verified","true"));String phone="+86138"+suffix.substring(Math.max(0,suffix.length()-8));assertTrue(post("/api/v2/account/login",Map.of("identity","hero"+suffix,"password","correct horse battery staple"),false).has("accessToken"));assertTrue(post("/api/v2/account/login",Map.of("identity",phone,"password","correct horse battery staple"),false).has("accessToken"));
 var repo=new JdbcWeChatBindingRepository(ds);assertEquals(WeChatBindingService.ClaimStatus.CREATED,repo.claim(new WeChatBindingService.Binding(aid,"wx-ch14","open-"+suffix,"union-"+suffix,1,Instant.now())).status());assertEquals(aid,new UnifiedIdentityService(ds,Clock.systemUTC()).resolve("wechat-open:wx-ch14:open-"+suffix));
 admin("/admin/display/change",Map.of("accountId",aid+"","displayId","888"+suffix.substring(Math.max(0,suffix.length()-6))));assertEquals(401,getSession(access).statusCode());admin("/admin/display/change",Map.of("accountId",bid+"","displayId",old));assertEquals(bid,new UnifiedIdentityService(ds,Clock.systemUTC()).resolve(old));JsonNode owners=admin("/admin/display/owners",Map.of("displayId",old));assertEquals(2,owners.size());
 KeyPairGenerator generator=KeyPairGenerator.getInstance("EC");generator.initialize(256);KeyPair keys=generator.generateKeyPair();String pem="-----BEGIN PUBLIC KEY-----\n"+Base64.getEncoder().encodeToString(keys.getPublic().getEncoded())+"\n-----END PUBLIC KEY-----";admin("/admin/pin/bind",Map.of("accountId",aid+"","deviceId","it-device","pin","7","publicKeyPem",pem));long sequence=System.nanoTime();JsonNode challenge=post("/pin/challenge",Map.of("accountId",aid+"","sequence",sequence+""),false);String message=challenge.get("challengeId").asText()+":"+challenge.get("challenge").asText()+":"+sequence+":127.0.0.1";Signature signer=Signature.getInstance("SHA256withECDSA");signer.initSign(keys.getPrivate());signer.update(message.getBytes(StandardCharsets.UTF_8));JsonNode pin=post("/pin/login",Map.of("challengeId",challenge.get("challengeId").asText(),"challenge",challenge.get("challenge").asText(),"sequence",sequence+"","pin","7","signature",Base64.getEncoder().encodeToString(signer.sign())),false);assertTrue(pin.has("accessToken"));assertEquals(401,postRaw("/pin/login",Map.of("challengeId",challenge.get("challengeId").asText(),"challenge",challenge.get("challenge").asText(),"sequence",sequence+"","pin","7","signature","AA=="),false).statusCode());}
 static HttpResponse<String> getSession(String access)throws Exception{return http.send(HttpRequest.newBuilder(URI.create(base+"/api/v2/account/session")).header("X-Aoo-Api-Version","1").header("X-Device-Id","it-device").header("X-Client-Channel","it").header("X-Client-Version","1").header("Authorization","Bearer "+access).GET().build(),HttpResponse.BodyHandlers.ofString());}
 static JsonNode admin(String path,Map<String,String> values)throws Exception{return json.readTree(send(path,values,true).body());}static JsonNode post(String path,Map<String,String> values,boolean admin)throws Exception{HttpResponse<String> response=send(path,values,admin);assertEquals(200,response.statusCode(),response.body());return json.readTree(response.body());}static HttpResponse<String> postRaw(String path,Map<String,String> values,boolean admin)throws Exception{return send(path,values,admin);}
 static HttpResponse<String> send(String path,Map<String,String> values,boolean privileged)throws Exception{StringJoiner body=new StringJoiner("&");for(var e:values.entrySet())body.add(URLEncoder.encode(e.getKey(),StandardCharsets.UTF_8)+"="+URLEncoder.encode(e.getValue(),StandardCharsets.UTF_8));var b=HttpRequest.newBuilder(URI.create(base+(path.startsWith("/api/")?path:"/api/v2/account/identity"+path))).header("X-Aoo-Api-Version","1").header("X-Device-Id","it-device").header("X-Client-Channel","it").header("X-Client-Version","1").header("Content-Type","application/x-www-form-urlencoded");if(privileged)b.header("X-Account-Operator-Token",OP).header("X-Admin-Second-Factor",MFA).header("X-Admin-Id","14001").header("X-Request-Id","ch14-"+(++seq)).header("X-Trace-Id","trace-"+seq).header("X-Admin-Reason","chapter14 integration verification");HttpResponse<String> response=http.send(b.POST(HttpRequest.BodyPublishers.ofString(body.toString())).build(),HttpResponse.BodyHandlers.ofString());if(privileged)assertEquals(200,response.statusCode(),response.body());return response;}
}
