package com.aoo.bcg.poker;
import com.aoo.bcg.gamespi.GameCommandRequest;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
final class PokerAuthoritativeSessionTest{
 @Test void creatorOwnsSeatZeroAndCanonicalStateReadsAuthority(){var s=new PokerAuthoritativeSession(2,20,4,9,new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults()));@SuppressWarnings("unchecked")var players=(Map<Integer,Long>)s.authoritativeState().get("players");assertEquals(Map.of(0,20L),players);var result=s.execute(req("state_req","state",1,"20",0,Map.of()));assertEquals(2L,result.body().get("roomId"));}
 @Test void routesAndHidesHands(){var s=new PokerAuthoritativeSession(2,20,4,9,new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults()));for(int i=1;i<4;i++)s.execute(req("join_req","j"+i,i,String.valueOf(20+i),i,Map.of()));s.execute(req("ready_req","owner-ready",4,"20",0,Map.of()));s.execute(req("start_req","s",5,"20",0,Map.of()));@SuppressWarnings("unchecked")var seats=(Map<Integer,Object>)s.viewFor(20).get("seats");@SuppressWarnings("unchecked")var other=(Map<String,Object>)seats.get(1);assertTrue(((List<?>)other.get("cards")).stream().allMatch(v->((Number)v).intValue()==0));}
 @Test void viewPublishesAuthoritativeLayoutVersionAndDisabledVariantCapabilities(){var s=new PokerAuthoritativeSession(2,20,3,9,new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults()));var view=s.viewFor(20);assertEquals(20L,view.get("ownerId"));assertEquals(3,view.get("playerCount"));assertEquals(3,view.get("seatLimit"));assertEquals("pdk-v1",view.get("playVersion"));assertEquals("WAITING",view.get("phase"));assertEquals(0L,view.get("stateVersion"));assertEquals(Map.of("addDouble",false,"robDoor",false,"openCard",false),view.get("capabilities"));}
 @Test void restoresStatsAndRejectsVersionMismatch(){var family=new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults());Map<String,Object>saved=finished();var a=PokerAuthoritativeSession.restore(saved,family);var b=PokerAuthoritativeSession.restore(a.authoritativeState(),family);assertEquals(a.settlementDetail(),b.settlementDetail());assertEquals(a.settlement(1,"pdk-v1").scoreDelta(),b.settlement(1,"pdk-v1").scoreDelta());assertThrows(IllegalArgumentException.class,()->a.settlement(1,"other"));saved.put("ruleVersion","other");assertThrows(IllegalStateException.class,()->PokerAuthoritativeSession.restore(saved,family));}
 @Test void mandatoryBeatAndCountAreAuthoritative(){var family=new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults());Map<String,Object>s=base();s.put("state",state(Map.of(0,List.of(104),1,List.of(105,106)),1,4));var session=PokerAuthoritativeSession.restore(s,family);assertThrows(IllegalStateException.class,()->session.execute(req("pass_req","p",1,"21",1,Map.of())));assertThrows(IllegalArgumentException.class,()->session.execute(req("hint_req","h",2,"21",1,Map.of("nextPlayerCardCount","one"))));s.put("state",state(Map.of(0,List.of(104),1,List.of(103)),1,4));assertDoesNotThrow(()->PokerAuthoritativeSession.restore(s,family).execute(req("pass_req","p2",3,"21",1,Map.of())));}
 @Test void rejectsCorruptPassedAndStatsSnapshot(){Map<String,Object>s=base();s.put("plays",Map.of(0,-1));s.put("state",Map.of("hands",Map.of(0,List.of(104),1,List.of(103)),"currentSeat",1,"previousSeat",0,"passed",List.of(0,1),"finished",false,"winnerSeat",-1,"previous",Map.of("type","SINGLE","primaryRank",4,"cards",List.of(104))));assertThrows(IllegalStateException.class,()->PokerAuthoritativeSession.restore(s,new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults())));}
 @Test void clearedTrickDoesNotReapplyRequiredFirstCard(){var config=new PaoDeKuaiConfig(5,true,true,false,103,false);var family=new PaoDeKuaiFamily(config);Map<String,Object>s=base();s.put("ruleSnapshotKey",family.ruleSnapshotKey());s.put("plays",Map.of(0,1,1,0,2,0,3,0));s.put("state",Map.of("hands",Map.of(0,List.of(104),1,List.of(105),2,List.of(107),3,List.of(108)),"currentSeat",1,"previousSeat",-1,"passed",List.of(),"finished",false,"winnerSeat",-1));var restored=PokerAuthoritativeSession.restore(s,family);assertDoesNotThrow(()->restored.execute(req("play_req","new-trick",9,"21",1,Map.of("cards",List.of(105)))));}
 private static Map<String,Object>base(){Map<String,Object>s=new LinkedHashMap<>();s.put("roomId",2L);s.put("ownerId",20L);s.put("seatLimit",4);s.put("seed",9L);s.put("ruleVersion","pdk-v1");s.put("ruleSnapshotKey",new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults()).ruleSnapshotKey());s.put("initialLeadSeat",0);s.put("players",Map.of(0,20L,1,21L,2,22L,3,23L));s.put("plays",Map.of(0,1,1,0,2,0,3,0));s.put("bombs",Map.of(0,0,1,0,2,0,3,0));s.put("playedCards",List.of());s.put("operationDeadline",Map.of());return s;}
 private static Map<String,Object>finished(){Map<String,Object>s=base();s.put("plays",Map.of(0,3,1,0,2,0,3,0));s.put("bombs",Map.of(0,2,1,0,2,0,3,0));s.put("state",Map.of("hands",Map.of(0,List.of(),1,List.of(103,104,105),2,List.of(107),3,List.of(108)),"currentSeat",0,"previousSeat",0,"passed",List.of(),"finished",true,"winnerSeat",0,"previous",Map.of("type","SINGLE","primaryRank",15,"cards",List.of(115))));return s;}
 private static Map<String,Object>state(Map<Integer,List<Integer>>hands,int current,int previousRank){Map<Integer,List<Integer>>all=new LinkedHashMap<>(hands);all.put(2,List.of(107));all.put(3,List.of(108));return Map.of("hands",all,"currentSeat",current,"previousSeat",0,"passed",List.of(),"finished",false,"winnerSeat",-1,"previous",Map.of("type","SINGLE","primaryRank",previousRank,"cards",List.of(104)));}
 @Test void waitingSnapshotRoundTrips(){var family=new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults());var s=new PokerAuthoritativeSession(2,20,4,9,family);assertEquals(s.authoritativeState(),PokerAuthoritativeSession.restore(s.authoritativeState(),family).authoritativeState());}
 @Test void startedRoomRequiresMajorityVoteAndPersistsLifecycle(){var family=new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults());var s=new PokerAuthoritativeSession(2,20,4,9,family);s.execute(req("join_req","join-1",1,"21",1,Map.of()));s.execute(req("join_req","join-2",2,"22",2,Map.of()));s.execute(req("join_req","join-3",3,"23",3,Map.of()));s.execute(req("ready_req","ready",4,"20",0,Map.of()));s.execute(req("start_req","start",5,"20",0,Map.of()));s.execute(req("dissolve_req","vote",6,"21",1,Map.of()));assertFalse(s.isTerminal());assertNotNull(s.authoritativeState().get("dissolveVote"));s.execute(req("dissolve_agree_req","agree-owner",7,"20",0,Map.of()));assertFalse(s.isTerminal());s.execute(req("dissolve_agree_req","agree-third",8,"22",2,Map.of()));assertTrue(s.isTerminal());assertEquals("VOTE_APPROVED",s.terminalReason());var restored=PokerAuthoritativeSession.restore(s.authoritativeState(),family);assertTrue(restored.isTerminal());assertEquals("VOTE_APPROVED",restored.terminalReason());}
 @Test void sameVersionDifferentCapabilityCannotRestore(){Map<String,Object>s=base();var different=new PaoDeKuaiFamily(new PaoDeKuaiConfig(5,true,true,true,null,true));assertThrows(IllegalStateException.class,()->PokerAuthoritativeSession.restore(s,different));}
 @Test void rejectsPassedStateWithoutActiveTrick(){Map<String,Object>s=base();s.put("state",Map.of("hands",Map.of(0,List.of(104),1,List.of(105),2,List.of(107),3,List.of(108)),"currentSeat",1,"previousSeat",0,"passed",List.of(2),"finished",false,"winnerSeat",-1));assertThrows(IllegalStateException.class,()->PokerAuthoritativeSession.restore(s,new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults())));}
 @Test void reverseSpringSurvivesRestore(){Map<String,Object>s=base();s.put("initialLeadSeat",0);s.put("plays",Map.of(0,1,1,3,2,0,3,0));s.put("state",Map.of("hands",Map.of(0,List.of(104),1,List.of(),2,List.of(107),3,List.of(108)),"currentSeat",1,"previousSeat",1,"passed",List.of(),"finished",true,"winnerSeat",1,"previous",Map.of("type","SINGLE","primaryRank",15,"cards",List.of(115))));var family=new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults());var first=PokerAuthoritativeSession.restore(s,family);var second=PokerAuthoritativeSession.restore(first.authoritativeState(),family);assertEquals(first.settlementDetail(),second.settlementDetail());assertTrue(first.settlementDetail().lines().stream().allMatch(l->l.tags().contains("REVERSE_SPRING")));}
 @Test void customCutIsActuallyDealtAndChoosesRequiredHolder(){List<Integer>deck=new ArrayList<>(PokerCardCodec.deck(48));deck.set(deck.indexOf(104),403);var profile=new PokerRuleProfile("cut",48,3,3,PokerRuleProfile.FirstLead.REQUIRED_CARD_HOLDER,403,5,2,false,false,true,false,1,16,2,20,deck);var family=new PaoDeKuaiFamily(new PaoDeKuaiConfig(5,true,true,false,403,false),profile);var s=new PokerAuthoritativeSession(8,30,3,5,family);for(int i=1;i<3;i++)s.execute(new GameCommandRequest("join_req","j"+i,i,8,1,"cut",String.valueOf(30+i),i,Map.of()));s.execute(new GameCommandRequest("ready_req","owner-ready",3,8,1,"cut","30",0,Map.of()));s.execute(new GameCommandRequest("start_req","s",4,8,1,"cut","30",0,Map.of()));int holder=-1;for(int i=0;i<3;i++){@SuppressWarnings("unchecked")var seats=(Map<Integer,Object>)s.viewFor(30+i).get("seats");@SuppressWarnings("unchecked")var own=(Map<String,Object>)seats.get(i);@SuppressWarnings("unchecked")var cards=(List<Integer>)own.get("cards");assertFalse(cards.contains(104));if(cards.contains(403))holder=i;}assertEquals(holder,s.viewFor(30).get("currentSeat"));}
 @Test void completesRealRoundPersistsSettlementAndStartsNextRoundAfterEveryPlayerContinues(){var family=new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults());var s=new PokerAuthoritativeSession(2,20,4,9,family);long seq=1;for(int seat=1;seat<4;seat++)s.execute(req("join_req","join-"+seat,seq++,String.valueOf(20+seat),seat,Map.of()));s.execute(req("ready_req","ready-owner",seq++,"20",0,Map.of()));s.execute(req("start_req","start-round-1",seq++,"20",0,Map.of()));int guard=0;while(!Boolean.TRUE.equals(s.viewFor(20).get("finished"))){assertTrue(guard++<300,"authoritative round did not converge");int seat=((Number)s.viewFor(20).get("currentSeat")).intValue();long player=20L+seat;var hint=s.execute(req("hint_req","hint-"+seq,seq++,String.valueOf(player),seat,Map.of()));@SuppressWarnings("unchecked")var hints=(List<CardCombination>)hint.body().get("hints");if(hints.isEmpty())s.execute(req("pass_req","pass-"+seq,seq++,String.valueOf(player),seat,Map.of()));else s.execute(req("play_req","play-"+seq,seq++,String.valueOf(player),seat,Map.of("cards",hints.getFirst().cards())));}assertEquals(1,s.viewFor(20).get("roundNo"));assertFalse(s.settlement(1,"pdk-v1").scoreDelta().isEmpty());Map<String,Object>saved=s.authoritativeState();var restored=PokerAuthoritativeSession.restore(saved,family);assertEquals(saved,restored.authoritativeState());for(int seat=0;seat<4;seat++)restored.execute(req("continue_req","continue-"+seat,seq++,String.valueOf(20+seat),seat,Map.of()));assertEquals("PLAYING",restored.viewFor(20).get("phase"));assertEquals(2,restored.viewFor(20).get("roundNo"));assertFalse(Boolean.TRUE.equals(restored.viewFor(20).get("finished")));}
 @Test void finalRoundStopsContinuationAndSurvivesRestore(){var family=new PaoDeKuaiFamily(PaoDeKuaiConfig.defaults());Map<String,Object>saved=finished();saved.put("roundNo",1);saved.put("roundLimit",1);saved.put("roundScored",true);var s=PokerAuthoritativeSession.restore(saved,family);assertEquals(1,s.viewFor(20).get("roundLimit"));assertEquals(true,s.viewFor(20).get("matchFinished"));assertEquals(false,s.viewFor(20).get("canContinue"));assertThrows(IllegalStateException.class,()->s.execute(req("continue_req","final-continue",1,"20",0,Map.of())));assertEquals(saved.get("roundLimit"),PokerAuthoritativeSession.restore(s.authoritativeState(),family).authoritativeState().get("roundLimit"));}
 private static GameCommandRequest req(String id,String request,long seq,String player,int seat,Map<String,Object>body){return new GameCommandRequest(id,request,seq,2,1,"pdk-v1",player,seat,body);}
}
