package com.aoo.bcg.activity;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.util.*;

public final class ActivityHttpRoutes {
 @FunctionalInterface public interface Authenticator{long authenticate(String authorization);}
 private final ActivityService service;private final Authenticator auth;private final ObjectMapper json;
 public ActivityHttpRoutes(ActivityService service,Authenticator auth,ObjectMapper json){this.service=Objects.requireNonNull(service);this.auth=Objects.requireNonNull(auth);this.json=Objects.requireNonNull(json);}
 public void mount(HttpServer server){server.createContext("/health/activity",e->reply(e,200,Map.of("status","UP","persistence","jdbc","apiVersion","1")));server.createContext("/v1/activities",this::handle);}
 private void handle(HttpExchange e)throws IOException{try{if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw new Api(426,"API_VERSION_REQUIRED","X-API-Version: 1 required");long player=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));String suffix=e.getRequestURI().getPath().substring("/v1/activities".length());if((suffix.isEmpty()||"/".equals(suffix))&&"GET".equals(e.getRequestMethod())){ok(e,service.catalog());return;}String[] p=suffix.substring(1).split("/");if(p.length==2&&"check-in".equals(p[1])&&"POST".equals(e.getRequestMethod())){ok(e,service.checkIn(player,p[0]));return;}if(p.length==4&&"missions".equals(p[1])&&"progress".equals(p[3])&&"POST".equals(e.getRequestMethod())){Map<String,Object>b=body(e);ok(e,service.progress(player,p[0],p[2],text(b,"eventId"),number(b,"delta")));return;}if(p.length==4&&"missions".equals(p[1])&&"claim".equals(p[3])&&"POST".equals(e.getRequestMethod())){ok(e,service.claim(player,p[0],p[2]));return;}throw new Api(404,"ROUTE_NOT_FOUND","route not found");}catch(Api x){reply(e,x.status,Map.of("code",x.code,"message",x.getMessage()));}catch(SecurityException x){reply(e,401,Map.of("code","UNAUTHORIZED","message",x.getMessage()));}catch(NoSuchElementException x){reply(e,404,Map.of("code","NOT_FOUND","message",x.getMessage()));}catch(IllegalArgumentException x){reply(e,400,Map.of("code","INVALID_REQUEST","message",x.getMessage()));}catch(IllegalStateException x){reply(e,409,Map.of("code","ACTIVITY_CONFLICT","message",x.getMessage()));}}
 private void ok(HttpExchange e,Object data)throws IOException{reply(e,200,Map.of("code","OK","data",data));}private Map<String,Object> body(HttpExchange e)throws IOException{return json.readValue(e.getRequestBody(),new TypeReference<>(){});}private static String text(Map<String,Object>b,String k){Object v=b.get(k);if(v instanceof String s&&!s.isBlank())return s;throw new IllegalArgumentException(k+" required");}private static long number(Map<String,Object>b,String k){Object v=b.get(k);if(v instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+" required");}
 private void reply(HttpExchange e,int status,Object value)throws IOException{byte[] bytes=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,bytes.length);try(OutputStream out=e.getResponseBody()){out.write(bytes);}}private static final class Api extends RuntimeException{final int status;final String code;Api(int status,String code,String message){super(message);this.status=status;this.code=code;}}
}
