package com.aoo.bcg.activity;

import com.fasterxml.jackson.databind.ObjectMapper;import javax.sql.DataSource;import java.sql.*;import java.time.*;import java.util.*;

/** Durable activity repository. Row locks and unique business keys make progress and reward claims idempotent. */
public final class JdbcActivityRepository implements ActivityRepository {
 private final DataSource source;private final ObjectMapper json;
 public JdbcActivityRepository(DataSource source,ObjectMapper json){this.source=Objects.requireNonNull(source);this.json=Objects.requireNonNull(json);}
 public List<ActivityModels.Activity> active(Instant now){String sql="SELECT activity_code,version,title,starts_at_ms,ends_at_ms,time_zone FROM activity_version WHERE published=TRUE AND starts_at_ms<=? AND ends_at_ms>? ORDER BY activity_code";try(Connection c=source.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,now.toEpochMilli());p.setLong(2,now.toEpochMilli());try(ResultSet r=p.executeQuery()){List<ActivityModels.Activity> out=new ArrayList<>();while(r.next())out.add(readActivity(c,r));return out;}}catch(SQLException e){throw failure(e);}}
 public Optional<ActivityModels.Activity> find(String code,long version){try(Connection c=source.getConnection();PreparedStatement p=c.prepareStatement("SELECT activity_code,version,title,starts_at_ms,ends_at_ms,time_zone FROM activity_version WHERE activity_code=? AND version=?")){p.setString(1,code);p.setLong(2,version);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(readActivity(c,r)):Optional.empty();}}catch(SQLException e){throw failure(e);}}
 private ActivityModels.Activity readActivity(Connection c,ResultSet r)throws SQLException{String code=r.getString(1);long version=r.getLong(2);List<ActivityModels.Mission> missions=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT mission_code,event_type,target_value,reward_currency,reward_amount FROM activity_mission_version WHERE activity_code=? AND activity_version=? ORDER BY mission_code")){p.setString(1,code);p.setLong(2,version);try(ResultSet m=p.executeQuery()){while(m.next())missions.add(new ActivityModels.Mission(m.getString(1),m.getString(2),m.getLong(3),new ActivityModels.Reward(m.getString(4),m.getLong(5))));}}return new ActivityModels.Activity(code,version,r.getString(3),Instant.ofEpochMilli(r.getLong(4)),Instant.ofEpochMilli(r.getLong(5)),ZoneId.of(r.getString(6)),missions);}
 public ActivityModels.CheckIn checkIn(long player,ActivityModels.Activity a,LocalDate day,ActivityModels.Reward reward){return tx(c->{String key="checkin:"+a.code()+":"+a.version()+":"+player+":"+day;ClaimRow old=claim(c,key);if(old!=null)return checkInResult(c,player,a,day,reward,old.state);LocalDate previous=null;int streak=0;try(PreparedStatement p=c.prepareStatement("SELECT business_date,streak FROM activity_check_in WHERE player_id=? AND activity_code=? ORDER BY business_date DESC LIMIT 1 FOR UPDATE")){p.setLong(1,player);p.setString(2,a.code());try(ResultSet r=p.executeQuery()){if(r.next()){previous=r.getObject(1,LocalDate.class);streak=r.getInt(2);}}}int next=day.minusDays(1).equals(previous)?streak+1:1;try(PreparedStatement p=c.prepareStatement("INSERT INTO activity_check_in(player_id,activity_code,activity_version,business_date,streak,created_at_ms) VALUES(?,?,?,?,?,?)")){p.setLong(1,player);p.setString(2,a.code());p.setLong(3,a.version());p.setObject(4,day);p.setInt(5,next);p.setLong(6,System.currentTimeMillis());p.executeUpdate();}insertClaim(c,key,player,a.code(),a.version(),"CHECK_IN",day.toString(),reward);return new ActivityModels.CheckIn(day,next,reward,"RESERVED");});}
 private ActivityModels.CheckIn checkInResult(Connection c,long player,ActivityModels.Activity a,LocalDate day,ActivityModels.Reward reward,String state)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT streak FROM activity_check_in WHERE player_id=? AND activity_code=? AND business_date=?")){p.setLong(1,player);p.setString(2,a.code());p.setObject(3,day);try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalStateException("claim exists without check-in");return new ActivityModels.CheckIn(day,r.getInt(1),reward,state);}}}
 public ActivityModels.Progress addProgress(long player,ActivityModels.Activity a,String missionCode,String eventId,long delta){var mission=mission(a,missionCode);return tx(c->{try(PreparedStatement p=c.prepareStatement("INSERT INTO activity_progress_event(event_id,player_id,activity_code,activity_version,mission_code,delta_value,created_at_ms) VALUES(?,?,?,?,?,?,?)")){p.setString(1,eventId);p.setLong(2,player);p.setString(3,a.code());p.setLong(4,a.version());p.setString(5,missionCode);p.setLong(6,delta);p.setLong(7,System.currentTimeMillis());p.executeUpdate();}catch(SQLException duplicate){if(!duplicate(duplicate))throw duplicate;return progress(c,player,a,mission);}try(PreparedStatement p=c.prepareStatement("INSERT INTO activity_mission_progress(player_id,activity_code,activity_version,mission_code,progress_value) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE progress_value=LEAST(?,progress_value+VALUES(progress_value))")){p.setLong(1,player);p.setString(2,a.code());p.setLong(3,a.version());p.setString(4,missionCode);p.setLong(5,delta);p.setLong(6,mission.target());p.executeUpdate();}return progress(c,player,a,mission);});}
 private ActivityModels.Progress progress(Connection c,long player,ActivityModels.Activity a,ActivityModels.Mission m)throws SQLException{long value=0;try(PreparedStatement p=c.prepareStatement("SELECT progress_value FROM activity_mission_progress WHERE player_id=? AND activity_code=? AND activity_version=? AND mission_code=?")){p.setLong(1,player);p.setString(2,a.code());p.setLong(3,a.version());p.setString(4,m.code());try(ResultSet r=p.executeQuery()){if(r.next())value=r.getLong(1);}}String key=missionKey(a,player,m.code());ClaimRow claim=claim(c,key);return new ActivityModels.Progress(a.code(),a.version(),m.code(),value,m.target(),value>=m.target(),claim!=null&&"COMPLETED".equals(claim.state));}
 public ActivityModels.Claim reserveMissionClaim(long player,ActivityModels.Activity a,String missionCode){var m=mission(a,missionCode);return tx(c->{var progress=progress(c,player,a,m);if(!progress.claimable())throw new IllegalStateException("mission target not reached");String key=missionKey(a,player,missionCode);ClaimRow old=claim(c,key);if(old==null){insertClaim(c,key,player,a.code(),a.version(),"MISSION",missionCode,m.reward());return new ActivityModels.Claim(key,"RESERVED",m.reward());}return new ActivityModels.Claim(key,old.state,m.reward());});}
 public void completeClaim(String key){updateClaim(key,"COMPLETED",null);}public void failClaim(String key,String reason){updateClaim(key,"FAILED",reason);}
 private void updateClaim(String key,String state,String failure){try(Connection c=source.getConnection();PreparedStatement p=c.prepareStatement("UPDATE activity_reward_claim SET state=?,failure_code=?,updated_at_ms=? WHERE claim_key=? AND state<>'COMPLETED'")){p.setString(1,state);p.setString(2,failure);p.setLong(3,System.currentTimeMillis());p.setString(4,key);p.executeUpdate();}catch(SQLException e){throw failure(e);}}
 private void insertClaim(Connection c,String key,long player,String activity,long version,String type,String subject,ActivityModels.Reward reward)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO activity_reward_claim(claim_key,player_id,activity_code,activity_version,claim_type,subject_code,reward_currency,reward_amount,state,created_at_ms,updated_at_ms) VALUES(?,?,?,?,?,?,?,?,?,?,?)")){p.setString(1,key);p.setLong(2,player);p.setString(3,activity);p.setLong(4,version);p.setString(5,type);p.setString(6,subject);p.setString(7,reward.currency());p.setLong(8,reward.amount());p.setString(9,"RESERVED");long now=System.currentTimeMillis();p.setLong(10,now);p.setLong(11,now);p.executeUpdate();}}
 private ClaimRow claim(Connection c,String key)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT state FROM activity_reward_claim WHERE claim_key=? FOR UPDATE")){p.setString(1,key);try(ResultSet r=p.executeQuery()){return r.next()?new ClaimRow(r.getString(1)):null;}}}
 private static ActivityModels.Mission mission(ActivityModels.Activity a,String code){return a.missions().stream().filter(m->m.code().equals(code)).findFirst().orElseThrow(()->new NoSuchElementException("mission not found in activity snapshot"));}private static String missionKey(ActivityModels.Activity a,long p,String m){return "mission:"+a.code()+":"+a.version()+":"+p+":"+m;}
 private <T>T tx(Sql<T> work){try(Connection c=source.getConnection()){boolean auto=c.getAutoCommit();c.setAutoCommit(false);try{T v=work.run(c);c.commit();return v;}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(auto);}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure(e);}}
 private static boolean duplicate(SQLException e){return "23000".equals(e.getSQLState())||"23505".equals(e.getSQLState());}private static IllegalStateException failure(Exception e){return new IllegalStateException("activity persistence failure",e);}@FunctionalInterface private interface Sql<T>{T run(Connection c)throws Exception;}private record ClaimRow(String state){}
}
