package com.aoo.bcg.support;

import javax.sql.DataSource;
import java.sql.*;
import java.time.Clock;
import java.time.Instant;
import java.util.*;

/** Transactional live-support repository. Ownership, audit and idempotency are enforced in storage. */
public final class JdbcSupportLiveRepository {
    private final DataSource source; private final Clock clock;
    public JdbcSupportLiveRepository(DataSource source, Clock clock) { this.source=Objects.requireNonNull(source); this.clock=Objects.requireNonNull(clock); }

    public SupportLiveSession enqueue(long playerId,long caseId,String key) { return idempotent(playerId,"ENQUEUE",key,c->{
        requireOwnedOpenCase(c,playerId,caseId); long id; Instant now=clock.instant();
        try(var q=c.prepareStatement("INSERT INTO support_live_session(case_id,player_id,status,last_message_id,created_at,updated_at,row_version) VALUES(?,?,'QUEUED',0,?,?,1)",Statement.RETURN_GENERATED_KEYS)){
            q.setLong(1,caseId);q.setLong(2,playerId);q.setTimestamp(3,Timestamp.from(now));q.setTimestamp(4,Timestamp.from(now));q.executeUpdate();
            try(var r=q.getGeneratedKeys()){if(!r.next())throw new SQLException("session id unavailable");id=r.getLong(1);}
        } audit(c,id,"PLAYER",playerId,"QUEUED",null); return load(c,id,0);
    }); }
    public List<SupportLiveSession> queue(int limit){try(var c=source.getConnection();var q=c.prepareStatement("SELECT id FROM support_live_session WHERE status='QUEUED' ORDER BY id LIMIT ?")){q.setInt(1,Math.max(1,Math.min(limit,100)));try(var r=q.executeQuery()){List<SupportLiveSession> out=new ArrayList<>();while(r.next())out.add(load(c,r.getLong(1),0));return List.copyOf(out);}}catch(Exception e){throw failure(e);}}
    public SupportLiveSession claim(long agent,long id,long version,String key){return idempotent(agent,"CLAIM:"+id,key,c->{try(var q=c.prepareStatement("UPDATE support_live_session SET agent_id=?,status='ACTIVE',updated_at=?,row_version=row_version+1 WHERE id=? AND status='QUEUED' AND row_version=?")){q.setLong(1,agent);q.setTimestamp(2,Timestamp.from(clock.instant()));q.setLong(3,id);q.setLong(4,version);if(q.executeUpdate()!=1)throw new Conflict("session already claimed or stale");}audit(c,id,"SUPPORT",agent,"CLAIMED",null);return load(c,id,0);});}
    public SupportLiveSession playerView(long player,long id,long after){try(var c=source.getConnection()){SupportLiveSession s=load(c,id,after);if(s.playerId()!=player)throw new Missing("session not found");return s;}catch(RuntimeException e){throw e;}catch(Exception e){throw failure(e);}}
    public SupportLiveSession agentView(long agent,long id,long after){try(var c=source.getConnection()){SupportLiveSession s=load(c,id,after);if(!Objects.equals(s.agentId(),agent))throw new Missing("session not assigned to agent");return s;}catch(RuntimeException e){throw e;}catch(Exception e){throw failure(e);}}
    public SupportLiveSession send(long actor,String actorType,long id,String body,String media,String key){return idempotent(actor,"MESSAGE:"+id,key,c->{SupportLiveSession s=load(c,id,0);authorize(s,actor,actorType);if(s.status()==SupportLiveSession.Status.CLOSED)throw new Conflict("session is closed");String clean=text(body,2000,"body");validateMedia(c,s.playerId(),media);long messageId;try(var q=c.prepareStatement("INSERT INTO support_live_message(session_id,sender_type,sender_id,body,media_reference,created_at) VALUES(?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){q.setLong(1,id);q.setString(2,actorType);q.setLong(3,actor);q.setString(4,clean);q.setString(5,media==null||media.isBlank()?null:media);q.setTimestamp(6,Timestamp.from(clock.instant()));q.executeUpdate();try(var r=q.getGeneratedKeys()){if(!r.next())throw new SQLException("message id unavailable");messageId=r.getLong(1);}}try(var q=c.prepareStatement("UPDATE support_live_session SET status=CASE WHEN status='DISCONNECTED' THEN 'ACTIVE' ELSE status END,last_message_id=?,updated_at=?,row_version=row_version+1 WHERE id=?")){q.setLong(1,messageId);q.setTimestamp(2,Timestamp.from(clock.instant()));q.setLong(3,id);q.executeUpdate();}audit(c,id,actorType,actor,"MESSAGE_SENT",Long.toString(messageId));return load(c,id,messageId-1);});}
    public SupportLiveSession disconnect(long player,long id,long version,String key){return state(player,"PLAYER",id,version,key,"DISCONNECTED","DISCONNECTED");}
    public SupportLiveSession reconnect(long player,long id,long after,String key){return idempotent(player,"RECONNECT:"+id,key,c->{SupportLiveSession s=load(c,id,after);if(s.playerId()!=player)throw new Missing("session not found");if(s.status()==SupportLiveSession.Status.CLOSED)throw new Conflict("session is closed");try(var q=c.prepareStatement("UPDATE support_live_session SET status=CASE WHEN agent_id IS NULL THEN 'QUEUED' ELSE 'ACTIVE' END,updated_at=?,row_version=row_version+1 WHERE id=?")){q.setTimestamp(1,Timestamp.from(clock.instant()));q.setLong(2,id);q.executeUpdate();}audit(c,id,"PLAYER",player,"RECONNECTED",Long.toString(after));return load(c,id,after);});}
    public SupportLiveSession close(long agent,long id,long version,String key,String reason){return idempotent(agent,"CLOSE:"+id,key,c->{SupportLiveSession s=load(c,id,0);authorize(s,agent,"SUPPORT");if(s.status()==SupportLiveSession.Status.CLOSED)return s;try(var q=c.prepareStatement("UPDATE support_live_session SET status='CLOSED',close_reason=?,closed_at=?,updated_at=?,row_version=row_version+1 WHERE id=? AND row_version=? AND status<>'CLOSED'")){Instant now=clock.instant();q.setString(1,text(reason,500,"reason"));q.setTimestamp(2,Timestamp.from(now));q.setTimestamp(3,Timestamp.from(now));q.setLong(4,id);q.setLong(5,version);if(q.executeUpdate()!=1)throw new Conflict("stale session version");}audit(c,id,"SUPPORT",agent,"CLOSED",reason);return load(c,id,0);});}
    private SupportLiveSession state(long actor,String type,long id,long version,String key,String state,String event){return idempotent(actor,event+":"+id,key,c->{SupportLiveSession s=load(c,id,0);authorize(s,actor,type);try(var q=c.prepareStatement("UPDATE support_live_session SET status=?,updated_at=?,row_version=row_version+1 WHERE id=? AND row_version=? AND status<>'CLOSED'")){q.setString(1,state);q.setTimestamp(2,Timestamp.from(clock.instant()));q.setLong(3,id);q.setLong(4,version);if(q.executeUpdate()!=1)throw new Conflict("stale session version");}audit(c,id,type,actor,event,null);return load(c,id,0);});}
    private void authorize(SupportLiveSession s,long actor,String type){if("PLAYER".equals(type)){if(s.playerId()!=actor)throw new Missing("session not found");}else if(!Objects.equals(s.agentId(),actor))throw new Missing("session not assigned to agent");}
    private SupportLiveSession load(Connection c,long id,long after)throws SQLException{try(var q=c.prepareStatement("SELECT case_id,player_id,agent_id,status,last_message_id,created_at,updated_at,closed_at,row_version FROM support_live_session WHERE id=?")){q.setLong(1,id);try(var r=q.executeQuery()){if(!r.next())throw new Missing("session not found");Long agent=(Long)r.getObject(3);Timestamp closed=r.getTimestamp(8);return new SupportLiveSession(id,r.getLong(1),r.getLong(2),agent,SupportLiveSession.Status.valueOf(r.getString(4)),r.getLong(5),r.getTimestamp(6).toInstant(),r.getTimestamp(7).toInstant(),closed==null?null:closed.toInstant(),r.getLong(9),messages(c,id,after));}}}
    private List<SupportLiveSession.Message> messages(Connection c,long id,long after)throws SQLException{try(var q=c.prepareStatement("SELECT id,sender_type,sender_id,body,media_reference,created_at FROM support_live_message WHERE session_id=? AND id>? ORDER BY id LIMIT 200")){q.setLong(1,id);q.setLong(2,after);try(var r=q.executeQuery()){List<SupportLiveSession.Message> out=new ArrayList<>();while(r.next())out.add(new SupportLiveSession.Message(r.getLong(1),SupportLiveSession.Sender.valueOf(r.getString(2)),r.getLong(3),r.getString(4),r.getString(5),r.getTimestamp(6).toInstant()));return List.copyOf(out);}}}
    private void requireOwnedOpenCase(Connection c,long player,long caseId)throws SQLException{try(var q=c.prepareStatement("SELECT 1 FROM support_case WHERE id=? AND player_id=? AND status IN ('OPEN','IN_REVIEW')")){q.setLong(1,caseId);q.setLong(2,player);try(var r=q.executeQuery()){if(!r.next())throw new Missing("open support case not found");}}}
    private void validateMedia(Connection c,long player,String reference)throws SQLException{if(reference==null||reference.isBlank())return;if(!reference.matches("media:[1-9][0-9]{0,19}"))throw new IllegalArgumentException("mediaReference must contain a Media asset id");long id;try{id=Long.parseLong(reference.substring(6));}catch(NumberFormatException e){throw new IllegalArgumentException("mediaReference invalid");}try(var q=c.prepareStatement("SELECT 1 FROM media_asset a JOIN media_asset_access x ON x.asset_id=a.id WHERE a.id=? AND x.owner_id=? AND a.state='READY' AND a.kind IN ('VOICE','EVIDENCE')")){q.setLong(1,id);q.setLong(2,player);try(var r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("Media asset is unavailable or not owned by player");}}}
    private void audit(Connection c,long id,String actorType,long actor,String event,String detail)throws SQLException{try(var q=c.prepareStatement("INSERT INTO support_live_audit(session_id,actor_type,actor_id,event_type,event_detail,created_at) VALUES(?,?,?,?,?,?)")){q.setLong(1,id);q.setString(2,actorType);q.setLong(3,actor);q.setString(4,event);q.setString(5,detail);q.setTimestamp(6,Timestamp.from(clock.instant()));q.executeUpdate();}}
    private SupportLiveSession idempotent(long actor,String operation,String key,Tx tx){if(key==null||!key.matches("[A-Za-z0-9_-]{8,128}"))throw new IllegalArgumentException("valid Idempotency-Key required");try(var c=source.getConnection()){c.setAutoCommit(false);try{try(var q=c.prepareStatement("SELECT session_id FROM support_live_idempotency WHERE actor_id=? AND operation_key=? AND idempotency_key=?")){q.setLong(1,actor);q.setString(2,operation);q.setString(3,key);try(var r=q.executeQuery()){if(r.next()){SupportLiveSession out=load(c,r.getLong(1),0);c.rollback();return out;}}}SupportLiveSession out=tx.run(c);try(var q=c.prepareStatement("INSERT INTO support_live_idempotency(actor_id,operation_key,idempotency_key,session_id,created_at) VALUES(?,?,?,?,?)")){q.setLong(1,actor);q.setString(2,operation);q.setString(3,key);q.setLong(4,out.id());q.setTimestamp(5,Timestamp.from(clock.instant()));q.executeUpdate();}c.commit();return out;}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw failure(e);}}
    private static String text(String v,int max,String name){if(v==null||v.isBlank()||v.length()>max)throw new IllegalArgumentException(name+" invalid");return v.replaceAll("[\\p{Cntrl}&&[^\\n\\t]]"," ").strip();}
    private static RuntimeException failure(Exception e){return e instanceof RuntimeException r?r:new IllegalStateException("support persistence unavailable",e);}
    @FunctionalInterface private interface Tx{SupportLiveSession run(Connection c)throws Exception;}
    public static final class Missing extends RuntimeException{public Missing(String m){super(m);}}
    public static final class Conflict extends RuntimeException{public Conflict(String m){super(m);}}
}
