package com.aoo.bcg.support;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;

/** Player-owned HTTP API plus a separate, token-protected read-only customer-service handoff. */
public final class SupportHttpRoutes {
 private final JdbcSupportRepository repository;private final PlayerBearerAuthenticator auth;private final ObjectMapper json;private final byte[] handoffToken;
 public SupportHttpRoutes(JdbcSupportRepository repository,PlayerBearerAuthenticator auth,ObjectMapper json,String handoffToken){this.repository=Objects.requireNonNull(repository);this.auth=Objects.requireNonNull(auth);this.json=Objects.requireNonNull(json);if(handoffToken==null||handoffToken.length()<32)throw new IllegalArgumentException("handoff token must contain at least 32 characters");this.handoffToken=handoffToken.getBytes(StandardCharsets.UTF_8);}
 public void mount(HttpServer server){server.createContext("/health/support",e->reply(e,200,Map.of("status","UP","persistence","jdbc","apiVersion","1")));server.createContext("/v1/support/cases",this::cases);server.createContext("/v1/support/events",this::events);server.createContext("/internal/v1/support/handoff",this::handoff);}
 private void cases(HttpExchange e)throws IOException{handle(e,()->{long player=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));String suffix=e.getRequestURI().getPath().substring("/v1/support/cases".length());if(suffix.isEmpty()||"/".equals(suffix)){if("GET".equals(e.getRequestMethod()))return repository.list(player,intQuery(e,"limit",50));if("POST".equals(e.getRequestMethod())){Map<String,Object> b=body(e);var kind=SupportCase.Kind.valueOf(text(b,"kind"));List<SupportCase.Evidence> evidence=json.convertValue(b.getOrDefault("evidence",List.of()),new TypeReference<>(){});return created(repository.create(player,kind,text(b,"subject"),text(b,"description"),evidence));}throw api(405,"METHOD_NOT_ALLOWED","GET or POST required");}String[] p=suffix.substring(1).split("/");long id=positive(p[0]);if(p.length==1&&"GET".equals(e.getRequestMethod()))return repository.find(player,id).orElseThrow(()->api(404,"CASE_NOT_FOUND","case not found"));if(p.length==2&&"withdraw".equals(p[1])&&"POST".equals(e.getRequestMethod()))return repository.withdraw(player,id,longValue(body(e),"version"));throw api(404,"ROUTE_NOT_FOUND","route not found");});}
 private void events(HttpExchange e)throws IOException{handle(e,()->{if(!"GET".equals(e.getRequestMethod()))throw api(405,"METHOD_NOT_ALLOWED","GET required");return repository.events(auth.authenticate(e.getRequestHeaders().getFirst("Authorization")),longQuery(e,"after",0));});}
 private void handoff(HttpExchange e)throws IOException{handle(e,()->{if(!"GET".equals(e.getRequestMethod()))throw api(405,"READ_ONLY_HANDOFF","customer-service handoff is read-only");String h=e.getRequestHeaders().getFirst("Authorization");byte[] supplied=h!=null&&h.startsWith("Bearer ")?h.substring(7).getBytes(StandardCharsets.UTF_8):new byte[0];if(!MessageDigest.isEqual(handoffToken,supplied))throw new SecurityException("valid handoff credential required");return repository.handoff(longQuery(e,"after",0),intQuery(e,"limit",50)).stream().map(this::handoffView).toList();});}
 private Map<String,Object> handoffView(SupportCase c){return Map.ofEntries(Map.entry("id",c.id()),Map.entry("playerRef",playerRef(c.playerId())),Map.entry("kind",c.kind()),Map.entry("subject",redact(c.subject())),Map.entry("description",redact(c.description())),Map.entry("status",c.status()),Map.entry("resolutionSummary",redact(Objects.toString(c.resolutionSummary(),""))),Map.entry("evidence",c.evidence()),Map.entry("createdAt",c.createdAt()),Map.entry("updatedAt",c.updatedAt()),Map.entry("version",c.version()));}
 private String playerRef(long playerId){try{MessageDigest d=MessageDigest.getInstance("SHA-256");d.update(handoffToken);return HexFormat.of().formatHex(d.digest(Long.toString(playerId).getBytes(StandardCharsets.UTF_8))).substring(0,24);}catch(Exception impossible){throw new IllegalStateException(impossible);}}
 private static String redact(String value){return value.replaceAll("(?i)[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}","[redacted-email]").replaceAll("(?<!\\d)1[3-9]\\d{9}(?!\\d)","[redacted-phone]");}
 private void handle(HttpExchange e,Action action)throws IOException{try{if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw api(426,"API_VERSION_REQUIRED","X-API-Version: 1 required");Object value=action.run();if(value instanceof Created c)reply(e,201,Map.of("code","OK","data",c.value));else reply(e,200,Map.of("code","OK","data",value));}catch(Api x){reply(e,x.status,Map.of("code",x.code,"message",x.getMessage()));}catch(SecurityException x){reply(e,401,Map.of("code","UNAUTHORIZED","message",x.getMessage()));}catch(IllegalArgumentException x){reply(e,400,Map.of("code","INVALID_REQUEST","message",String.valueOf(x.getMessage())));}catch(IllegalStateException x){reply(e,409,Map.of("code","CASE_CONFLICT","message",String.valueOf(x.getMessage())));}}
 private Map<String,Object> body(HttpExchange e)throws IOException{return json.readValue(e.getRequestBody(),new TypeReference<>(){});}private static String text(Map<String,Object>b,String k){Object v=b.get(k);if(!(v instanceof String s)||s.isBlank())throw new IllegalArgumentException(k+" required");return s;}private static long longValue(Map<String,Object>b,String k){Object v=b.get(k);if(v instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+" required");}
 private static long positive(String v){try{long n=Long.parseLong(v);if(n<=0)throw new NumberFormatException();return n;}catch(Exception x){throw new IllegalArgumentException("positive case id required");}}private static Map<String,String> query(HttpExchange e){Map<String,String> out=new HashMap<>();String q=e.getRequestURI().getRawQuery();if(q!=null)for(String pair:q.split("&")){String[] p=pair.split("=",2);out.put(p[0],p.length==2?p[1]:"");}return out;}private static long longQuery(HttpExchange e,String k,long d){String v=query(e).get(k);return v==null?d:Long.parseLong(v);}private static int intQuery(HttpExchange e,String k,int d){return Math.toIntExact(longQuery(e,k,d));}
 private void reply(HttpExchange e,int status,Object value)throws IOException{byte[] b=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.getResponseHeaders().set("X-Content-Type-Options","nosniff");e.sendResponseHeaders(status,b.length);try(var out=e.getResponseBody()){out.write(b);}}private static Api api(int s,String c,String m){return new Api(s,c,m);}private static Created created(Object o){return new Created(o);}@FunctionalInterface private interface Action{Object run()throws IOException;}private record Created(Object value){}private static final class Api extends RuntimeException{final int status;final String code;Api(int s,String c,String m){super(m);status=s;code=c;}}
}
