package com.aoo.bcg.support;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.*;
import java.io.IOException;
import java.util.*;

/** Production live-session ingress; player and agent routes have separate authentication domains. */
public final class SupportLiveHttpRoutes {
    private final JdbcSupportLiveRepository repository; private final PlayerBearerAuthenticator players;
    private final SupportAgentAuthenticator agents; private final ObjectMapper json;
    public SupportLiveHttpRoutes(JdbcSupportLiveRepository repository,PlayerBearerAuthenticator players,SupportAgentAuthenticator agents,ObjectMapper json){this.repository=repository;this.players=players;this.agents=agents;this.json=json;}
    public void mount(HttpServer server){server.createContext("/v1/support/live-sessions",this::player);server.createContext("/internal/v1/support/live-sessions",this::agent);}
    private void player(HttpExchange e)throws IOException{handle(e,()->{long actor=players.authenticate(header(e,"Authorization"));String suffix=suffix(e,"/v1/support/live-sessions");if(suffix.isEmpty()||"/".equals(suffix)){if("POST".equals(e.getRequestMethod())){Map<String,Object>b=body(e);return created(repository.enqueue(actor,number(b,"caseId"),key(e)));}throw api(405,"SUPPORT_METHOD_NOT_ALLOWED","POST required");}String[] p=parts(suffix);long id=positive(p[0]);if(p.length==1&&"GET".equals(e.getRequestMethod()))return repository.playerView(actor,id,longQuery(e,"afterMessageId",0));if(p.length==2&&"messages".equals(p[1])&&"POST".equals(e.getRequestMethod())){Map<String,Object>b=body(e);return created(repository.send(actor,"PLAYER",id,string(b,"body"),optional(b,"mediaReference"),key(e)));}if(p.length==2&&"disconnect".equals(p[1])&&"POST".equals(e.getRequestMethod()))return repository.disconnect(actor,id,number(body(e),"version"),key(e));if(p.length==2&&"reconnect".equals(p[1])&&"POST".equals(e.getRequestMethod()))return repository.reconnect(actor,id,number(body(e),"afterMessageId"),key(e));throw api(404,"SUPPORT_ROUTE_NOT_FOUND","route not found");});}
    private void agent(HttpExchange e)throws IOException{handle(e,()->{long actor=agents.authenticate(header(e,"Authorization"),header(e,"X-Support-Agent-Id"));String suffix=suffix(e,"/internal/v1/support/live-sessions");if(suffix.isEmpty()||"/".equals(suffix)){if("GET".equals(e.getRequestMethod()))return repository.queue((int)longQuery(e,"limit",50));throw api(405,"SUPPORT_METHOD_NOT_ALLOWED","GET required");}String[] p=parts(suffix);long id=positive(p[0]);if(p.length==1&&"GET".equals(e.getRequestMethod()))return repository.agentView(actor,id,longQuery(e,"afterMessageId",0));if(p.length==2&&"claim".equals(p[1])&&"POST".equals(e.getRequestMethod()))return repository.claim(actor,id,number(body(e),"version"),key(e));if(p.length==2&&"messages".equals(p[1])&&"POST".equals(e.getRequestMethod())){Map<String,Object>b=body(e);return created(repository.send(actor,"SUPPORT",id,string(b,"body"),optional(b,"mediaReference"),key(e)));}if(p.length==2&&"close".equals(p[1])&&"POST".equals(e.getRequestMethod())){Map<String,Object>b=body(e);return repository.close(actor,id,number(b,"version"),key(e),string(b,"reason"));}throw api(404,"SUPPORT_ROUTE_NOT_FOUND","route not found");});}
    private void handle(HttpExchange e,Action action)throws IOException{try{if(!"1".equals(header(e,"X-API-Version")))throw api(426,"SUPPORT_API_VERSION_REQUIRED","X-API-Version: 1 required");Object value=action.run();if(value instanceof Created c)reply(e,201,"SUPPORT_OK",c.value);else reply(e,200,"SUPPORT_OK",value);}catch(Api x){error(e,x.status,x.code,x.getMessage());}catch(SecurityException x){error(e,401,"SUPPORT_UNAUTHORIZED",x.getMessage());}catch(JdbcSupportLiveRepository.Missing x){error(e,404,"SUPPORT_SESSION_NOT_FOUND",x.getMessage());}catch(JdbcSupportLiveRepository.Conflict x){error(e,409,"SUPPORT_SESSION_CONFLICT",x.getMessage());}catch(IllegalArgumentException x){error(e,400,"SUPPORT_INVALID_REQUEST",x.getMessage());}catch(IllegalStateException x){error(e,503,"SUPPORT_STORAGE_UNAVAILABLE","support service unavailable");}}
    private void error(HttpExchange e,int status,String code,String message)throws IOException{replyRaw(e,status,Map.of("code",code,"message",Objects.toString(message,"request failed")));}
    private void reply(HttpExchange e,int status,String code,Object data)throws IOException{replyRaw(e,status,Map.of("code",code,"data",data));}
    private void replyRaw(HttpExchange e,int status,Object value)throws IOException{byte[] bytes=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.getResponseHeaders().set("X-Content-Type-Options","nosniff");e.sendResponseHeaders(status,bytes.length);try(var out=e.getResponseBody()){out.write(bytes);}}
    private Map<String,Object> body(HttpExchange e)throws IOException{return json.readValue(e.getRequestBody(),new TypeReference<>(){});}private static String header(HttpExchange e,String name){return e.getRequestHeaders().getFirst(name);}private static String key(HttpExchange e){return header(e,"Idempotency-Key");}
    private static String suffix(HttpExchange e,String root){return e.getRequestURI().getPath().substring(root.length());}private static String[] parts(String suffix){return suffix.substring(1).split("/");}private static long positive(String value){try{long id=Long.parseLong(value);if(id<=0)throw new NumberFormatException();return id;}catch(Exception e){throw new IllegalArgumentException("positive session id required");}}
    private static long number(Map<String,Object>b,String key){Object v=b.get(key);if(v instanceof Number n&&n.longValue()>=0)return n.longValue();throw new IllegalArgumentException(key+" required");}private static String string(Map<String,Object>b,String key){Object v=b.get(key);if(v instanceof String s)return s;throw new IllegalArgumentException(key+" required");}private static String optional(Map<String,Object>b,String key){Object v=b.get(key);return v instanceof String s?s:null;}
    private static long longQuery(HttpExchange e,String key,long fallback){String raw=e.getRequestURI().getRawQuery();if(raw==null)return fallback;for(String pair:raw.split("&")){String[] p=pair.split("=",2);if(p[0].equals(key))try{return Long.parseLong(p.length==2?p[1]:"");}catch(Exception failure){throw new IllegalArgumentException(key+" invalid");}}return fallback;}
    private static Api api(int status,String code,String message){return new Api(status,code,message);}private static Created created(Object value){return new Created(value);}@FunctionalInterface private interface Action{Object run()throws IOException;}private record Created(Object value){}private static final class Api extends RuntimeException{final int status;final String code;Api(int status,String code,String message){super(message);this.status=status;this.code=code;}}
}
