<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.aoo.bcg</groupId><artifactId>aoo-server-parent</artifactId><version>${revision}</version><relativePath>../../pom.xml</relativePath></parent><artifactId>aoo-kernel</artifactId><name>Aoo Native Kernel Compatibility Layer</name><dependencies><dependency><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId></dependency><dependency><groupId>ch.qos.logback</groupId><artifactId>logback-classic</artifactId><optional>true</optional></dependency><dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency></dependencies></project>
