package com.aoo.bcg.privacy;
import com.fasterxml.jackson.databind.ObjectMapper;import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import java.sql.*;import java.time.*;import static org.junit.jupiter.api.Assertions.*;
class JdbcPrivacyServiceTest {
 JdbcDataSource db;MutableClock clock;JdbcPrivacyService service;
 @BeforeEach void setup()throws Exception{db=new JdbcDataSource();db.setURL("jdbc:h2:mem:p"+System.nanoTime()+";MODE=MySQL;DB_CLOSE_DELAY=-1");try(Connection c=db.getConnection();Statement s=c.createStatement()){s.execute("CREATE TABLE aoo_account(account_id BIGINT PRIMARY KEY,login_name VARCHAR(64),password_hash VARCHAR(255),guest_credential_hash VARCHAR(64),recovery_credential_hash VARCHAR(64),guest BOOLEAN,auth_generation BIGINT,banned_until TIMESTAMP,ban_reason VARCHAR(255),created_at TIMESTAMP,updated_at TIMESTAMP)");s.execute("CREATE TABLE aoo_account_device(account_id BIGINT,device_id VARCHAR(128),channel_name VARCHAR(64),client_version VARCHAR(64),first_seen_at TIMESTAMP,last_seen_at TIMESTAMP,revoked_at TIMESTAMP)");s.execute("CREATE TABLE aoo_account_session(session_id VARCHAR(36),account_id BIGINT,device_id VARCHAR(128),token_family VARCHAR(36),access_hash VARCHAR(64),refresh_hash VARCHAR(64),access_expires_at TIMESTAMP,refresh_expires_at TIMESTAMP,auth_generation BIGINT,revoked_at TIMESTAMP,revoke_reason VARCHAR(64),created_at TIMESTAMP)");s.execute("CREATE TABLE aoo_account_audit(audit_id BIGINT AUTO_INCREMENT,account_id BIGINT,action_name VARCHAR(64),detail_value VARCHAR(255),source_ip VARCHAR(64),occurred_at TIMESTAMP)");s.execute("CREATE TABLE aoo_data_rights_request(request_id VARCHAR(36) PRIMARY KEY,account_id BIGINT,request_type VARCHAR(16),status VARCHAR(24),requested_at TIMESTAMP,cooling_off_until TIMESTAMP,cancelled_at TIMESTAMP,completed_at TIMESTAMP,result_manifest CLOB,failure_reason VARCHAR(255),version BIGINT DEFAULT 0)");s.execute("CREATE TABLE aoo_account_legal_hold(hold_id VARCHAR(36),account_id BIGINT,authority_reference VARCHAR(128),reason VARCHAR(500),placed_by VARCHAR(128),placed_at TIMESTAMP,released_by VARCHAR(128),released_at TIMESTAMP)");s.execute("CREATE TABLE aoo_data_rights_audit(audit_id BIGINT AUTO_INCREMENT,request_id VARCHAR(36),account_id BIGINT,action_name VARCHAR(64),actor_type VARCHAR(16),actor_ref VARCHAR(128),detail_json CLOB,occurred_at TIMESTAMP)");s.execute("INSERT INTO aoo_account VALUES(7,'me','hash',NULL,'recover',FALSE,0,NULL,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");}clock=new MutableClock(Instant.parse("2026-08-24T00:00:00Z"));service=new JdbcPrivacyService(db,clock,new ObjectMapper());}
 @Test void exportIsSubjectOnlyAndCompletes(){var r=service.requestExport(7);assertEquals("PENDING",r.status());assertEquals(1,service.processDue());var done=service.list(7).getFirst();assertEquals("COMPLETED",done.status());assertTrue(done.resultManifest().contains("SUBJECT_ONLY_NO_GAMEPLAY_OR_HIDDEN_CARDS"));}
 @Test void deletionHonorsCoolingOffCancellationAndVersion(){var r=service.requestDeletion(7);assertEquals("COOLING_OFF",r.status());assertEquals(0,r.version());assertEquals(0,service.processDue());var cancelled=service.cancel(7,r.id(),r.version());assertEquals("CANCELLED",cancelled.status());assertEquals(1,cancelled.version());assertThrows(JdbcPrivacyService.Conflict.class,()->service.cancel(7,r.id(),r.version()));}
 @Test void legalHoldStopsThenReleaseAllowsAnonymization()throws Exception{var r=service.requestDeletion(7);service.placeHold(7,"CASE-1","litigation","legal");clock.now=clock.now.plus(Duration.ofDays(8));service.processDue();assertEquals("ON_HOLD",service.list(7).getFirst().status());try(Connection c=db.getConnection();Statement s=c.createStatement();ResultSet q=s.executeQuery("SELECT hold_id FROM aoo_account_legal_hold")){q.next();service.releaseHold(q.getString(1),"legal");}service.processDue();assertEquals("COMPLETED",service.list(7).getFirst().status());try(Connection c=db.getConnection();Statement s=c.createStatement();ResultSet q=s.executeQuery("SELECT login_name,password_hash FROM aoo_account WHERE account_id=7")){q.next();assertNull(q.getString(1));assertNull(q.getString(2));}}
 static final class MutableClock extends Clock{Instant now;MutableClock(Instant n){now=n;}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}public Instant instant(){return now;}}
}
