package com.aoo.bcg.gifting;
import com.fasterxml.jackson.databind.ObjectMapper;import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import java.sql.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
final class GiftingServiceTest {JdbcDataSource ds;JdbcGiftRepository repo;List<String> calls;
 @BeforeEach void setup()throws Exception{ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:gift;MODE=MySQL;DB_CLOSE_DELAY=-1");try(Connection c=ds.getConnection();Statement s=c.createStatement()){for(String sql:List.of("DROP ALL OBJECTS","CREATE TABLE aoo_account(account_id BIGINT PRIMARY KEY,banned_until TIMESTAMP NULL,created_at TIMESTAMP NOT NULL)","CREATE TABLE player_profile(player_id BIGINT PRIMARY KEY)","CREATE TABLE gift_policy(asset_code VARCHAR(64) PRIMARY KEY,per_gift_limit BIGINT,daily_sender_limit BIGINT,min_account_age_hours BIGINT,enabled BOOLEAN)","CREATE TABLE gift_transfer(gift_id VARCHAR(36) PRIMARY KEY,idempotency_key VARCHAR(128) UNIQUE,request_hash VARCHAR(64),sender_id BIGINT,recipient_id BIGINT,asset_code VARCHAR(64),quantity BIGINT,state VARCHAR(24),risk_code VARCHAR(64),risk_score INT,failure_code VARCHAR(64),device_id VARCHAR(128),ip_address VARCHAR(64),business_date DATE,created_at TIMESTAMP,updated_at TIMESTAMP)","CREATE TABLE gift_ledger(ledger_id BIGINT AUTO_INCREMENT PRIMARY KEY,gift_id VARCHAR(36),player_id BIGINT,counterparty_id BIGINT,direction VARCHAR(3),asset_code VARCHAR(64),quantity BIGINT,created_at TIMESTAMP,UNIQUE(gift_id,player_id,direction))","CREATE TABLE gift_audit(sequence_no BIGINT AUTO_INCREMENT PRIMARY KEY,gift_id VARCHAR(36),event_type VARCHAR(32),actor_id BIGINT,payload_json JSON,previous_hash VARCHAR(64),event_hash VARCHAR(64) UNIQUE,created_at TIMESTAMP)"))s.execute(sql);s.execute("INSERT INTO aoo_account VALUES(1,NULL,TIMESTAMP '2020-01-01 00:00:00'),(2,NULL,TIMESTAMP '2020-01-01 00:00:00')");s.execute("INSERT INTO player_profile VALUES(1),(2)");s.execute("INSERT INTO gift_policy VALUES('GOLD',100,150,24,TRUE)");}repo=new JdbcGiftRepository(ds,new ObjectMapper(),Clock.fixed(Instant.parse("2026-08-24T00:00:00Z"),ZoneOffset.UTC));calls=new ArrayList<>();}
 @Test void completesIdempotentlyAndWritesBothLedgers()throws Exception{var assets=new GiftingPorts.AssetAuthority(){public void debit(String k,long p,String a,long q){calls.add("D"+p);}public void credit(String k,long p,String a,long q){calls.add("C"+p);}};var service=new GiftingService(repo,assets,(a,b,c,d,e,f)->new GiftingPorts.Decision(true,"ALLOW",0));var first=service.gift("request-1",1,2,"GOLD",50,"dev","127.0.0.1");var replay=service.gift("request-1",1,2,"GOLD",50,"dev","127.0.0.1");assertEquals("COMPLETED",first.state());assertEquals(first.id(),replay.id());assertEquals(List.of("D1","C2"),calls);assertEquals(1,repo.ledger(1,10).size());assertEquals(1,repo.ledger(2,10).size());}
 @Test void compensatesDebitWhenRecipientCreditFails(){var assets=new GiftingPorts.AssetAuthority(){public void debit(String k,long p,String a,long q){calls.add("D"+p);}public void credit(String k,long p,String a,long q){calls.add("C"+p);if(p==2)throw new IllegalStateException("down");}};var service=new GiftingService(repo,assets,(a,b,c,d,e,f)->new GiftingPorts.Decision(true,"ALLOW",0));assertThrows(Exception.class,()->service.gift("request-2",1,2,"GOLD",20,"dev","127.0.0.1"));assertEquals(List.of("D1","C2","C1"),calls);}
 @Test void enforcesDailyLimit()throws Exception{var assets=new GiftingPorts.AssetAuthority(){public void debit(String k,long p,String a,long q){}public void credit(String k,long p,String a,long q){}};var service=new GiftingService(repo,assets,(a,b,c,d,e,f)->new GiftingPorts.Decision(true,"ALLOW",0));service.gift("a",1,2,"GOLD",100,"d","i");var e=assertThrows(JdbcGiftRepository.GiftError.class,()->service.gift("b",1,2,"GOLD",60,"d","i"));assertEquals("GIFT_LIMIT_EXCEEDED",e.code);}
 @Test void exposesCompletedGiftOnceThroughDurableRecipientCursor()throws Exception{var assets=new GiftingPorts.AssetAuthority(){public void debit(String k,long p,String a,long q){}public void credit(String k,long p,String a,long q){}};var service=new GiftingService(repo,assets,(a,b,c,d,e,f)->new GiftingPorts.Decision(true,"ALLOW",0));var gift=service.gift("push-1",1,2,"GOLD",10,"d","i");var first=repo.inboundAfter(2,0,50);assertEquals(1,first.size());assertEquals(gift.id(),first.get(0).get("giftId"));assertEquals("IN",first.get(0).get("direction"));long cursor=((Number)first.get(0).get("sequence")).longValue();assertTrue(repo.inboundAfter(2,cursor,50).isEmpty());assertTrue(repo.inboundAfter(1,0,50).isEmpty());}
}
