package com.aoo.bcg.wordcard;
import com.aoo.bcg.gamespi.*;import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class ByzpNineStageAcceptanceTest{
 @Test void createJoinReadyStartOperateRotateReconnectAndReplay(){ByzpGameProvider p=new ByzpGameProvider();GameRoomHandle room=p.roomFactory().create(new RoomCreationContext(13601,10,Map.of()));ByzpSession s=(ByzpSession)room.requireAuthoritativeSession();StatePayload empty=StatePayload.copyOf(s.authoritativeState());assertEquals(13601L,s.viewFor(10).get("roomId"));s.execute(cmd(1,1,20,"join",Map.of()));s.execute(cmd(2,1,20,"ready",Map.of()));Map<String,Object>started=s.execute(cmd(3,0,10,"start",Map.of())).body().asMap();assertEquals("PLAYING",started.get("phase"));@SuppressWarnings("unchecked")Map<Integer,Object>seats=(Map<Integer,Object>)started.get("seats");@SuppressWarnings("unchecked")Map<String,Object>mine=(Map<String,Object>)seats.get(0);int card=(Integer)((List<?>)mine.get("cards")).getFirst();s.execute(cmd(4,0,10,"operation",Map.of("operation","DISCARD","cards",List.of(card))));assertEquals(0,s.execute(cmd(5,1,20,"operation",Map.of("operation","PASS"))).body().asMap().get("currentSeat"));@SuppressWarnings("unchecked")Map<Integer,Object>hidden=(Map<Integer,Object>)s.viewFor(20).get("seats");@SuppressWarnings("unchecked")Map<String,Object>opponent=(Map<String,Object>)hidden.get(0);assertTrue(((List<?>)opponent.get("cards")).stream().allMatch(x->x.equals(0)));StatePayload replay=p.eventReplayProvider().orElseThrow().replay(empty,s.events());assertEquals(s.authoritativeState(),replay.asMap());assertEquals(s.viewFor(20),p.restoreAuthoritativeSession(replay).orElseThrow().viewFor(20));}
 @Test void legalHuProducesAuthoritativeSettlement(){ByzpGameProvider p=new ByzpGameProvider();Map<String,Object>game=Map.of("hands",Map.of(0,List.of(1001,1002,1003,1101,1201,1301,1401,1402),1,List.of(1501)),"deck",List.of(1601),"discards",List.of(),"huXi",Map.of(0,15,1,0),"currentSeat",0,"phase","PLAYING","exposed",-1,"winner",-1);Map<String,Object>snapshot=Map.of("schemaVersion",1,"roomId",13602L,"ownerId",10L,"players",Map.of(0,10L,1,20L),"ready",List.of(1),"rules",Map.of(),"sequence",0L,"stateVersion",0L,"game",game);ByzpSession s=(ByzpSession)p.restoreAuthoritativeSession(snapshot).orElseThrow();s.execute(new GameCommandRequest("wordcard.byzp.dispatch","hu",1,13602,0,"1.0.0","10",0,Map.of("action","operation","payload",Map.of("operation","HU","huXi",15))));SettlementPayload settlement=s.settlement(1,"1.0.0");assertEquals(1L,settlement.scoreDelta().get(10L));assertEquals(-1L,settlement.scoreDelta().get(20L));}
 @Test void rejectsSeatSpoofSequenceReplayAndWrongFamily(){ByzpGameProvider p=new ByzpGameProvider();ByzpSession s=(ByzpSession)p.roomFactory().create(new RoomCreationContext(13601,10,Map.of())).requireAuthoritativeSession();s.execute(cmd(1,1,20,"join",Map.of()));assertThrows(SecurityException.class,()->s.execute(cmd(2,1,30,"ready",Map.of())));assertThrows(IllegalArgumentException.class,()->s.execute(cmd(1,1,20,"ready",Map.of())));assertFalse(p.ruleComponents().getFirst().execute(new GameCommandRequest("poker.dispatch","x",2,13601,0,"1.0.0","20",1,Map.of())).accepted());}
 @Test void moduleServiceLoaderUsesCatalogFamilyRouting(){List<GameProvider>providers=ServiceLoader.load(GameProvider.class).stream().map(ServiceLoader.Provider::get).toList();assertEquals(0,providers.stream().filter(p->p.getClass()==ByzpGameProvider.class).count());}
 private static GameCommandRequest cmd(long n,int seat,long player,String action,Map<String,Object>payload){return new GameCommandRequest("wordcard.byzp.dispatch","byzp-"+n,n,13601,0,"1.0.0",String.valueOf(player),seat,Map.of("action",action,"payload",payload));}
}
