package com.aoo.bcg.wordcard;
import com.aoo.bcg.gamespi.*;import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class BzpNineStageAcceptanceTest{
 @Test void lifecycleRecoveryReplayAndBaoPhases(){BzpGameProvider p=new BzpGameProvider();BzpSession s=(BzpSession)p.roomFactory().create(new RoomCreationContext(46201,10,Map.of("baoZhuang",true,"baoPai",true))).requireAuthoritativeSession();StatePayload empty=StatePayload.copyOf(s.authoritativeState());s.execute(cmd(1,1,20,"join",Map.of()));s.execute(cmd(2,1,20,"ready",Map.of()));assertEquals("BAO_ZHUANG",s.execute(cmd(3,0,10,"start",Map.of())).body().asMap().get("phase"));assertEquals("BAO_PAI",s.execute(cmd(4,0,10,"operation",Map.of("operation","SU_BAO"))).body().asMap().get("phase"));assertEquals("PLAYING",s.execute(cmd(5,0,10,"operation",Map.of("operation","FAN_BAO"))).body().asMap().get("phase"));StatePayload replay=p.eventReplayProvider().orElseThrow().replay(empty,s.events());assertEquals(s.authoritativeState(),replay.asMap());assertEquals(s.viewFor(20),p.restoreAuthoritativeSession(replay).orElseThrow().viewFor(20));}
 @Test void authoritativeOutFinishesAndSettles(){BzpGameProvider p=new BzpGameProvider();Map<String,Object>x=playingState(List.of(0x35),List.of(0x37));BzpSession s=(BzpSession)p.restoreAuthoritativeSession(x).orElseThrow();s.execute(out("out",1,List.of(0x35)));assertEquals("FINISHED",s.viewFor(10).get("phase"));assertEquals(5L,point(s,0));assertEquals(2L,s.settlement(1,"1.0.0").scoreDelta().get(10L));assertEquals(-2L,s.settlement(1,"1.0.0").scoreDelta().get(20L));}
 @Test void duplicateRequestReplayReconnectAndSettlementAreIdempotent(){BzpGameProvider p=new BzpGameProvider();BzpSession s=(BzpSession)p.restoreAuthoritativeSession(playingState(List.of(0x35),List.of(0x37))).orElseThrow();GameCommandRequest out=out("same-request",1,List.of(0x35));s.execute(out);long version=s.stateVersion();assertEquals(s.viewFor(10),s.execute(out).body().asMap());assertEquals(version,s.stateVersion());assertEquals(1,s.events().size());SettlementPayload first=s.settlement(1,"1.0.0");assertEquals(first,s.settlement(1,"1.0.0"));StatePayload replay=p.eventReplayProvider().orElseThrow().replay(StatePayload.copyOf(playingState(List.of(0x35),List.of(0x37))),s.events());BzpSession recovered=(BzpSession)p.restoreAuthoritativeSession(replay).orElseThrow();assertEquals(s.viewFor(20),p.reconnectViewProvider().orElseThrow().buildFor(20,new GameRoomHandle(46202,462,"1.0.0",recovered)));assertEquals(version,recovered.stateVersion());recovered.execute(out);assertEquals(version,recovered.stateVersion());assertEquals(first,recovered.settlement(1,"1.0.0"));}
 @Test void rejectsRequestIdConflictReplayGapAndInvalidHandAtomically(){BzpGameProvider p=new BzpGameProvider();BzpSession s=(BzpSession)p.restoreAuthoritativeSession(playingState(List.of(0x35,0x36),List.of(0x37))).orElseThrow();GameCommandRequest valid=out("request",1,List.of(0x35));s.execute(valid);assertThrows(IllegalArgumentException.class,()->s.execute(out("request",2,List.of(0x36))));BzpSession invalid=(BzpSession)p.restoreAuthoritativeSession(playingState(List.of(0x35,0x45),List.of(0x37))).orElseThrow();Map<String,Object>before=invalid.authoritativeState();assertThrows(IllegalArgumentException.class,()->invalid.execute(out("bad-hand",1,List.of(0x35,0x55))));assertEquals(before,invalid.authoritativeState());assertThrows(IllegalArgumentException.class,()->p.eventReplayProvider().orElseThrow().replay(StatePayload.copyOf(playingState(List.of(0x35),List.of(0x37))),List.of(Map.of("version",2L,"after",before))));}
 private static Map<String,Object>playingState(List<Integer>ownerHand,List<Integer>otherHand){Map<String,Object>x=new LinkedHashMap<>();x.put("schemaVersion",1);x.put("roomId",46202L);x.put("ownerId",10L);x.put("players",Map.of(0,10L,1,20L));x.put("ready",List.of(1));x.put("rules",Map.of());x.put("hands",Map.of(0,ownerHand,1,otherHand));x.put("points",Map.of(0,0L,1,0L));x.put("ranking",List.of());x.put("phase","PLAYING");x.put("current",0);x.put("leader",-1);x.put("passCount",0);x.put("challenge",-1);x.put("suBao",false);x.put("sequence",0L);x.put("stateVersion",0L);x.put("lead",Map.of());return x;}
 private static GameCommandRequest out(String requestId,long sequence,List<Integer>cards){return new GameCommandRequest("wordcard.bzp.dispatch",requestId,sequence,46202,0,"1.0.0","10",0,Map.of("action","operation","payload",Map.of("operation","OUT","type",cards.size()==1?"SINGLE":"PAIR","cards",cards)));}
 @SuppressWarnings("unchecked") private static long point(BzpSession s,int seat){return ((Number)((Map<String,Object>)((Map<Integer,Object>)s.viewFor(10).get("seats")).get(seat)).get("point")).longValue();}
 private static GameCommandRequest cmd(long n,int seat,long player,String action,Map<String,Object>payload){return new GameCommandRequest("wordcard.bzp.dispatch","bzp-"+n,n,46201,0,"1.0.0",String.valueOf(player),seat,Map.of("action",action,"payload",payload));}
}
