package com.aoo.bcg.roomsafety;
import javax.sql.DataSource;import java.sql.*;import java.time.*;import java.util.*;
public final class JdbcRoomSafetyService{
 private final DataSource db;private final Clock clock;
 public JdbcRoomSafetyService(DataSource db,Clock clock){this.db=Objects.requireNonNull(db);this.clock=Objects.requireNonNull(clock);}
 public Map<String,Object> report(long actor,Long room,Long target,String category,String detail,String key){
  if(category==null||!Set.of("CHEATING","ABUSE","COLLUSION","OTHER").contains(category)||detail==null||detail.isBlank()||detail.length()>1000)bad("invalid report");
  if(room!=null)participant(room,actor);if(target!=null&&target==actor)bad("cannot report yourself");
  String id=UUID.randomUUID().toString();
  try(Connection c=db.getConnection()){c.setAutoCommit(false);try{
   try(PreparedStatement q=c.prepareStatement("SELECT report_id, status FROM room_safety_report WHERE reporter_id=? AND idempotency_key=?")){q.setLong(1,actor);q.setString(2,key);try(ResultSet r=q.executeQuery()){if(r.next()){c.rollback();return Map.of("reportId",r.getString(1),"status",r.getString(2));}}}
   try(PreparedStatement p=c.prepareStatement("INSERT INTO room_safety_report(report_id,room_id,reporter_id,target_player_id,category,detail,status,idempotency_key,created_at) VALUES(?,?,?,?,?,?, 'SUBMITTED',?,?)")){p.setString(1,id);nullable(p,2,room);p.setLong(3,actor);nullable(p,4,target);p.setString(5,category);p.setString(6,detail.trim());p.setString(7,key);p.setTimestamp(8,Timestamp.from(clock.instant()));p.executeUpdate();}c.commit();return Map.of("reportId",id,"status","SUBMITTED");
  }catch(Exception x){c.rollback();throw x;}}catch(Exception x){throw db(x);}}
 public Map<String,Object> mute(long actor,long room,long target,int minutes,String reason,String key){
  Role role=participant(room,actor);participant(room,target);if(role!=Role.OWNER&&role!=Role.MODERATOR)throw new RoomSafetyException(403,"ROOM_SAFETY_FORBIDDEN","owner or moderator required");if(target==actor||minutes<1||minutes>1440)bad("invalid mute");
  Instant until=clock.instant().plus(Duration.ofMinutes(minutes));try(Connection c=db.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO room_safety_mute(room_id,player_id,muted_by,reason,muted_until,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE muted_until=GREATEST(muted_until,VALUES(muted_until)),reason=VALUES(reason),muted_by=VALUES(muted_by)")){p.setLong(1,room);p.setLong(2,target);p.setLong(3,actor);p.setString(4,reason==null?"":reason.substring(0,Math.min(reason.length(),256)));p.setTimestamp(5,Timestamp.from(until));p.setString(6,key);p.setTimestamp(7,Timestamp.from(clock.instant()));p.executeUpdate();return Map.of("roomId",room,"playerId",target,"mutedUntil",until.toString());}catch(Exception x){throw db(x);}}
 public Map<String,Object> location(long actor,long room,double latitude,double longitude,double accuracy){participant(room,actor);if(!Double.isFinite(latitude)||!Double.isFinite(longitude)||latitude< -90||latitude>90||longitude< -180||longitude>180||accuracy<0||accuracy>10000)bad("invalid location");try(Connection c=db.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO room_safety_location(room_id,player_id,latitude,longitude,accuracy_meters,observed_at) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE latitude=VALUES(latitude),longitude=VALUES(longitude),accuracy_meters=VALUES(accuracy_meters),observed_at=VALUES(observed_at)")){p.setLong(1,room);p.setLong(2,actor);p.setDouble(3,latitude);p.setDouble(4,longitude);p.setDouble(5,accuracy);p.setTimestamp(6,Timestamp.from(clock.instant()));p.executeUpdate();return distances(actor,room);}catch(Exception x){throw db(x);}}
 public Map<String,Object> distances(long actor,long room){
  participant(room,actor);record P(long id,double lat,double lon,double accuracy,Instant at){}List<P> points=new ArrayList<>();
  try(Connection c=db.getConnection();PreparedStatement p=c.prepareStatement("SELECT l.player_id,l.latitude,l.longitude,l.accuracy_meters,l.observed_at FROM room_safety_location l JOIN aoo_hall_room_member m ON m.room_id=l.room_id AND m.account_id=l.player_id JOIN aoo_hall_room r ON r.room_id=m.room_id WHERE l.room_id=? AND m.status='JOINED' AND r.state IN('OPEN','PLAYING')")){
   p.setLong(1,room);try(ResultSet r=p.executeQuery()){while(r.next())points.add(new P(r.getLong(1),r.getDouble(2),r.getDouble(3),r.getDouble(4),r.getTimestamp(5).toInstant()));}
  }catch(Exception x){throw db(x);}
  List<Map<String,Object>> pairs=new ArrayList<>();for(int i=0;i<points.size();i++)for(int j=i+1;j<points.size();j++){P a=points.get(i),b=points.get(j);pairs.add(Map.of("playerA",a.id,"playerB",b.id,"distanceMeters",Math.round(distance(a.lat,a.lon,b.lat,b.lon)),"authoritative",true));}return Map.of("roomId",room,"evaluatedAt",clock.instant().toString(),"pairs",pairs);
 }
 public Map<String,Object> muteStatus(long actor,long room){participant(room,actor);try(Connection c=db.getConnection();PreparedStatement p=c.prepareStatement("SELECT muted_until,reason FROM room_safety_mute WHERE room_id=? AND player_id=? AND muted_until>?")){p.setLong(1,room);p.setLong(2,actor);p.setTimestamp(3,Timestamp.from(clock.instant()));try(ResultSet r=p.executeQuery()){if(r.next())return Map.of("muted",true,"mutedUntil",r.getTimestamp(1).toInstant().toString(),"reason",r.getString(2));return Map.of("muted",false);}}catch(Exception x){throw db(x);}}
 private Role participant(long room,long player){try(Connection c=db.getConnection();PreparedStatement p=c.prepareStatement("SELECT CASE WHEN r.owner_account_id=m.account_id THEN 'OWNER' ELSE 'PLAYER' END FROM aoo_hall_room_member m JOIN aoo_hall_room r ON r.room_id=m.room_id WHERE m.room_id=? AND m.account_id=? AND m.status='JOINED' AND r.state IN('OPEN','PLAYING')")){p.setLong(1,room);p.setLong(2,player);try(ResultSet r=p.executeQuery()){if(!r.next())throw new RoomSafetyException(403,"ROOM_MEMBERSHIP_REQUIRED","active authoritative room membership required");return Role.valueOf(r.getString(1));}}catch(RoomSafetyException x){throw x;}catch(Exception x){throw db(x);}}
 private static double distance(double a,double b,double c,double d){double p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,z=Math.sin(x/2)*Math.sin(x/2)+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)*Math.sin(y/2);return 6371008.8*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z));}
 private static void nullable(PreparedStatement p,int i,Long v)throws SQLException{if(v==null)p.setNull(i,Types.BIGINT);else p.setLong(i,v);}private static void bad(String m){throw new RoomSafetyException(400,"INVALID_ARGUMENT",m);}private static RoomSafetyException db(Exception x){return new RoomSafetyException(503,"ROOM_SAFETY_UNAVAILABLE","room safety authority unavailable");}private enum Role{OWNER,MODERATOR,PLAYER}
}
