package com.aoo.bcg.roomsafety;
import com.fasterxml.jackson.databind.*;import com.sun.net.httpserver.*;import java.io.*;import java.util.*;
public final class RoomSafetyHttpRoutes{
 @FunctionalInterface public interface Authenticator{long authenticate(String authorization);}@FunctionalInterface private interface Action{Object run()throws Exception;}
 private final JdbcRoomSafetyService service;private final Authenticator auth;private final ObjectMapper json;
 public RoomSafetyHttpRoutes(JdbcRoomSafetyService s,Authenticator a,ObjectMapper j){service=s;auth=a;json=j.copy().enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);}
 public void mount(HttpServer server){server.createContext("/health/room-safety",e->reply(e,200,Map.of("status","UP","authority","jdbc")));server.createContext("/api/v2/room-safety/reports",this::reports);server.createContext("/api/v2/room-safety/rooms",this::rooms);}
 private void reports(HttpExchange e)throws IOException{handle(e,"POST",()->{Report d=read(e,Report.class);return service.report(actor(e),d.roomId,d.targetPlayerId,d.category,d.detail,key(e));});}
 private void rooms(HttpExchange e)throws IOException{handle(e,null,()->{String[] p=e.getRequestURI().getPath().substring("/api/v2/room-safety/rooms/".length()).split("/");if(p.length<2)throw new RoomSafetyException(404,"NOT_FOUND","route not found");long room=Long.parseLong(p[0]),actor=actor(e);return switch(p[1]){case "mutes"->{if("GET".equals(e.getRequestMethod()))yield service.muteStatus(actor,room);Mute d=read(e,Mute.class);yield service.mute(actor,room,d.playerId,d.minutes,d.reason,key(e));}case "location"->{Location d=read(e,Location.class);yield service.location(actor,room,d.latitude,d.longitude,d.accuracyMeters);}case "distances"->service.distances(actor,room);default->throw new RoomSafetyException(404,"NOT_FOUND","route not found");};});}
 private void handle(HttpExchange e,String method,Action a)throws IOException{try{version(e);if(method!=null&&!method.equals(e.getRequestMethod()))throw new RoomSafetyException(405,"METHOD_NOT_ALLOWED",method+" required");reply(e,200,Map.of("code","OK","data",a.run()));}catch(RoomSafetyException x){reply(e,x.status,Map.of("code",x.code,"message",x.getMessage()));}catch(SecurityException x){reply(e,401,Map.of("code","UNAUTHENTICATED","message","valid bearer token required"));}catch(Exception x){reply(e,400,Map.of("code","INVALID_ARGUMENT","message","invalid request"));}}
 private long actor(HttpExchange e){return auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));}private static void version(HttpExchange e){String v=e.getRequestHeaders().getFirst("X-Aoo-Api-Version");if(!"1".equals(v))throw new RoomSafetyException(426,"UNSUPPORTED_API_VERSION","X-Aoo-Api-Version: 1 required");}private static String key(HttpExchange e){String k=e.getRequestHeaders().getFirst("Idempotency-Key");if(k==null||k.isBlank())throw new RoomSafetyException(400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key required");return k;}
 private <T>T read(HttpExchange e,Class<T> t)throws IOException{if(!"application/json".equalsIgnoreCase(Optional.ofNullable(e.getRequestHeaders().getFirst("Content-Type")).orElse("").split(";")[0]))throw new RoomSafetyException(415,"UNSUPPORTED_MEDIA_TYPE","application/json required");byte[] b=e.getRequestBody().readNBytes(65537);if(b.length>65536)throw new RoomSafetyException(413,"PAYLOAD_TOO_LARGE","body too large");return json.readValue(b,t);}private void reply(HttpExchange e,int status,Object body)throws IOException{byte[] b=json.writeValueAsBytes(body);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}finally{e.close();}}
 private record Report(Long roomId,Long targetPlayerId,String category,String detail){}private record Mute(long playerId,int minutes,String reason){}private record Location(double latitude,double longitude,double accuracyMeters){}
}
