package com.aoo.bcg.club;

import com.fasterxml.jackson.databind.ObjectMapper;
import javax.sql.DataSource;
import java.sql.*;
import java.time.Clock;
import java.time.Instant;
import java.util.*;
import java.math.BigDecimal;

/** Authoritative Club service. Every command, snapshot and idempotency result commits atomically. */
public final class JdbcClubService {
    public record TemplateState(String id,String name,String game,String rules,int index) {}
    public record TableState(String id,String templateId,String displayName,String status,Instant createdAt) {}
    public record InviteState(String token,long playerId,Instant expiresAt,boolean accepted) {}
    public record MatchState(String roomId,Map<Long,Integer> scores,Instant finishedAt) {}
    public record LedgerState(String businessKey,long playerId,BigDecimal amount,String reason,Instant createdAt) {}
    public record State(long id,String name,String status,Map<Long,String> members,List<TemplateState> templates,List<TableState> tables,List<InviteState> invites,List<MatchState> records,List<LedgerState> ledger) {}
    private final DataSource source; private final ObjectMapper json; private final Clock clock;
    public JdbcClubService(DataSource source,ObjectMapper json,Clock clock){this.source=Objects.requireNonNull(source);this.json=Objects.requireNonNull(json);this.clock=Objects.requireNonNull(clock);}

    public State create(String key,long id,long owner,String name){return transaction(key,id,c->{if(c!=null)throw new IllegalStateException("club exists");if(id<=0||owner<=0||name==null||name.isBlank())throw new IllegalArgumentException("invalid club");return new State(id,name.strip(),"ACTIVE",Map.of(owner,"OWNER"),List.of(),List.of(),List.of(),List.of(),List.of());});}
    public State saveTemplate(String key,long id,long actor,String templateId,String name,String game,String rules){return transaction(key,id,c->{requireManager(c,actor);List<TemplateState> copy=new ArrayList<>(c.templates());int at=-1,index=copy.size()+1;for(int i=0;i<copy.size();i++)if(copy.get(i).id().equals(templateId)){at=i;index=copy.get(i).index();break;}TemplateState value=new TemplateState(required(templateId),Objects.requireNonNullElse(name,"").strip(),required(game),Objects.requireNonNullElse(rules,"{}"),index);if(at<0)copy.add(value);else copy.set(at,value);return copy(c,c.status(),c.members(),List.copyOf(copy),c.tables(),c.invites(),c.records(),c.ledger());});}
    public State createTable(String key,long id,long actor,String tableId,String templateId){return transaction(key,id,c->{requireManager(c,actor);TemplateState template=c.templates().stream().filter(t->t.id().equals(templateId)).findFirst().orElseThrow(()->new IllegalStateException("template missing"));if(c.tables().stream().anyMatch(t->t.id().equals(tableId)))throw new IllegalStateException("table exists");List<TableState> tables=new ArrayList<>(c.tables());tables.add(new TableState(required(tableId),templateId,template.index()+". "+template.name(),"OPEN",clock.instant()));return copy(c,c.status(),c.members(),c.templates(),List.copyOf(tables),c.invites(),c.records(),c.ledger());});}
    public State dissolve(String key,long id,long actor){return transaction(key,id,c->{requireOwner(c,actor);if(c.tables().stream().anyMatch(t->t.status().equals("PLAYING")))throw new IllegalStateException("active game");return copy(c,"DISSOLVED",c.members(),c.templates(),c.tables(),c.invites(),c.records(),c.ledger());});}
    public InviteState invite(String key,long id,long actor,long player,long ttl){State result=transaction(key,id,c->{requireManager(c,actor);if(c.members().containsKey(player)||ttl<1||ttl>604800)throw new IllegalArgumentException("invalid invite");InviteState value=new InviteState(UUID.randomUUID().toString(),player,clock.instant().plusSeconds(ttl),false);List<InviteState> invites=new ArrayList<>(c.invites());invites.add(value);return copy(c,c.status(),c.members(),c.templates(),c.tables(),List.copyOf(invites),c.records(),c.ledger());});return result.invites().stream().filter(i->i.playerId()==player).reduce((a,b)->b).orElseThrow();}
    public State acceptInvite(String key,long id,long player,String token){return transaction(key,id,c->{InviteState found=c.invites().stream().filter(i->i.token().equals(token)&&i.playerId()==player&&!i.accepted()&&i.expiresAt().isAfter(clock.instant())).findFirst().orElseThrow(()->new IllegalStateException("invalid invite"));Map<Long,String> members=new LinkedHashMap<>(c.members());members.put(player,"MEMBER");List<InviteState> invites=c.invites().stream().map(i->i==found?new InviteState(i.token(),i.playerId(),i.expiresAt(),true):i).toList();return copy(c,c.status(),Map.copyOf(members),c.templates(),c.tables(),invites,c.records(),c.ledger());});}
    public State setRole(String key,long id,long actor,long player,String role){return transaction(key,id,c->{requireOwner(c,actor);if(player==actor||"OWNER".equals(role)||(!"ADMIN".equals(role)&&!"MEMBER".equals(role))||!c.members().containsKey(player))throw new IllegalArgumentException("invalid role");Map<Long,String> m=new LinkedHashMap<>(c.members());m.put(player,role);return copy(c,c.status(),Map.copyOf(m),c.templates(),c.tables(),c.invites(),c.records(),c.ledger());});}
    public State kick(String key,long id,long actor,long player){return transaction(key,id,c->{requireManager(c,actor);String role=c.members().get(player);if("OWNER".equals(role)||("ADMIN".equals(role)&&!"OWNER".equals(c.members().get(actor))))throw new SecurityException("insufficient role");if(c.tables().stream().anyMatch(t->t.status().equals("PLAYING")))throw new IllegalStateException("active game");Map<Long,String> m=new LinkedHashMap<>(c.members());m.remove(player);return copy(c,c.status(),Map.copyOf(m),c.templates(),c.tables(),c.invites(),c.records(),c.ledger());});}
    public State kickAfterRoomAuthority(String key,long id,long actor,long player){return transaction(key,id,c->{requireManager(c,actor);String role=c.members().get(player);if(role==null) return c;if("OWNER".equals(role)||("ADMIN".equals(role)&&!"OWNER".equals(c.members().get(actor))))throw new SecurityException("insufficient role");Map<Long,String> m=new LinkedHashMap<>(c.members());m.remove(player);return copy(c,c.status(),Map.copyOf(m),c.templates(),c.tables(),c.invites(),c.records(),c.ledger());});}
    public State transition(String key,long id,long actor,String roomId,String next){return transaction(key,id,c->{requireManager(c,actor);List<TableState> tables=new ArrayList<>(c.tables());int at=-1;for(int i=0;i<tables.size();i++)if(tables.get(i).id().equals(roomId)){at=i;break;}if(at<0)throw new IllegalStateException("room missing");TableState old=tables.get(at);boolean valid=(old.status().equals("OPEN")&&(next.equals("PLAYING")||next.equals("DISSOLVED")))||(old.status().equals("PLAYING")&&(next.equals("FINISHED")||next.equals("DISSOLVED")));if(!valid)throw new IllegalStateException("invalid room transition");tables.set(at,new TableState(old.id(),old.templateId(),old.displayName(),next,old.createdAt()));return copy(c,c.status(),c.members(),c.templates(),List.copyOf(tables),c.invites(),c.records(),c.ledger());});}
    public State finishMatch(String key,long id,long actor,String roomId,Map<Long,Integer> scores){return transaction(key,id,c->{requireManager(c,actor);if(scores==null||scores.isEmpty()||!c.members().keySet().containsAll(scores.keySet())||scores.values().stream().mapToInt(Integer::intValue).sum()!=0)throw new IllegalArgumentException("scores must balance");List<TableState> tables=new ArrayList<>(c.tables());int at=-1;for(int i=0;i<tables.size();i++)if(tables.get(i).id().equals(roomId)){at=i;break;}if(at<0||!tables.get(at).status().equals("PLAYING"))throw new IllegalStateException("room not playing");TableState old=tables.get(at);tables.set(at,new TableState(old.id(),old.templateId(),old.displayName(),"FINISHED",old.createdAt()));List<MatchState> records=new ArrayList<>(c.records());records.add(new MatchState(roomId,Map.copyOf(scores),clock.instant()));return copy(c,c.status(),c.members(),c.templates(),List.copyOf(tables),c.invites(),List.copyOf(records),c.ledger());});}
    public State postLedger(String key,long id,long actor,long player,BigDecimal amount,String reason){return transaction(key,id,c->{requireManager(c,actor);if(!c.members().containsKey(player)||amount==null||amount.signum()==0)throw new IllegalArgumentException("invalid ledger");List<LedgerState> ledger=new ArrayList<>(c.ledger());ledger.add(new LedgerState(key,player,amount,required(reason),clock.instant()));return copy(c,c.status(),c.members(),c.templates(),c.tables(),c.invites(),c.records(),List.copyOf(ledger));});}
    public State get(long id){try(Connection c=source.getConnection()){State state=load(c,id,false);if(state==null)throw new IllegalStateException("club unavailable");return state;}catch(SQLException e){throw new IllegalStateException("club read failed",e);}}

    private State transaction(String key,long clubId,Mutation mutation){if(key==null||key.isBlank())throw new IllegalArgumentException("idempotency key required");try(Connection connection=source.getConnection()){connection.setAutoCommit(false);try{String cached=idempotency(connection,key,true);if(cached!=null){connection.commit();return json.readValue(cached,State.class);}State current=load(connection,clubId,true);State next=mutation.apply(current);String payload=json.writeValueAsString(next);save(connection,next,payload);try(PreparedStatement q=connection.prepareStatement("INSERT INTO aoo_club_write_idempotency(scope_key,response_json,created_at) VALUES(?,?,?)")){q.setString(1,key);q.setString(2,payload);q.setTimestamp(3,Timestamp.from(clock.instant()));q.executeUpdate();}connection.commit();return next;}catch(Exception e){connection.rollback();if(e instanceof RuntimeException r)throw r;throw new IllegalStateException("club transaction failed",e);}finally{connection.setAutoCommit(true);}}catch(SQLException e){throw new IllegalStateException("club transaction failed",e);}}
    private State load(Connection c,long id,boolean lock)throws SQLException{String sql="SELECT state_json FROM aoo_club_state WHERE club_id=?"+(lock?" FOR UPDATE":"");try(PreparedStatement q=c.prepareStatement(sql)){q.setLong(1,id);try(ResultSet rows=q.executeQuery()){if(!rows.next())return null;try{return json.readValue(rows.getString(1),State.class);}catch(Exception e){throw new SQLException("invalid club state",e);}}}}
    private String idempotency(Connection c,String key,boolean lock)throws SQLException{String sql="SELECT response_json FROM aoo_club_write_idempotency WHERE scope_key=?"+(lock?" FOR UPDATE":"");try(PreparedStatement q=c.prepareStatement(sql)){q.setString(1,key);try(ResultSet rows=q.executeQuery()){return rows.next()?rows.getString(1):null;}}}
    private void save(Connection c,State state,String payload)throws SQLException{try(PreparedStatement update=c.prepareStatement("UPDATE aoo_club_state SET state_json=?,row_version=row_version+1,updated_at=? WHERE club_id=?")){update.setString(1,payload);update.setTimestamp(2,Timestamp.from(clock.instant()));update.setLong(3,state.id());if(update.executeUpdate()==1)return;}try(PreparedStatement insert=c.prepareStatement("INSERT INTO aoo_club_state(club_id,state_json,row_version,updated_at) VALUES(?,?,1,?)")){insert.setLong(1,state.id());insert.setString(2,payload);insert.setTimestamp(3,Timestamp.from(clock.instant()));insert.executeUpdate();}}
    private static void requireManager(State c,long actor){active(c);String r=c.members().get(actor);if(!"OWNER".equals(r)&&!"ADMIN".equals(r))throw new SecurityException("manager required");}
    private static void requireOwner(State c,long actor){active(c);if(!"OWNER".equals(c.members().get(actor)))throw new SecurityException("owner required");}
    private static void active(State c){if(c==null||!"ACTIVE".equals(c.status()))throw new IllegalStateException("club unavailable");}
    private static String required(String value){if(value==null||value.isBlank())throw new IllegalArgumentException("required value");return value.strip();}
    private static State copy(State c,String status,Map<Long,String> members,List<TemplateState> templates,List<TableState> tables,List<InviteState> invites,List<MatchState> records,List<LedgerState> ledger){return new State(c.id(),c.name(),status,members,templates,tables,invites,records,ledger);}
    @FunctionalInterface private interface Mutation{State apply(State state)throws Exception;}
}
