package com.aoo.bcg.account.wechat;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.sql.*;import java.time.Instant;import java.util.*;import javax.sql.DataSource;
/** WeChat bindings use the canonical identity table shared by every login entry. */
public final class JdbcWeChatBindingRepository implements WeChatBindingService.Repository{
 private final DataSource source;public JdbcWeChatBindingRepository(DataSource s){source=Objects.requireNonNull(s);}
 public Optional<WeChatBindingService.Binding> findByAccountId(long id){try(Connection c=source.getConnection()){return byAccount(c,id);}catch(SQLException e){throw fail(e);}}
 public WeChatBindingService.Claim claim(WeChatBindingService.Binding v){try(Connection c=source.getConnection()){c.setAutoCommit(false);try{var current=byAccount(c,v.accountId());if(current.isPresent()){c.commit();var old=current.get();return new WeChatBindingService.Claim(old.appId().equals(v.appId())&&old.subject().equals(v.subject())?WeChatBindingService.ClaimStatus.IDEMPOTENT:WeChatBindingService.ClaimStatus.ACCOUNT_BOUND_TO_ANOTHER_IDENTITY,old);}var owner=byValue(c,v.appId(),v.subject(),v.unionId());if(owner.isPresent()){c.commit();return new WeChatBindingService.Claim(WeChatBindingService.ClaimStatus.IDENTITY_OWNED_BY_ANOTHER_ACCOUNT,owner.get());}insert(c,"WECHAT_OPEN",v.appId()+":"+v.subject(),v.accountId(),v.boundAt());if(v.unionId()!=null&&!v.unionId().isBlank())insert(c,"WECHAT_UNION",v.unionId(),v.accountId(),v.boundAt());c.commit();return new WeChatBindingService.Claim(WeChatBindingService.ClaimStatus.CREATED,v);}catch(Exception e){c.rollback();throw e;}}catch(SQLException e){throw fail(e);}}
 public boolean delete(long id,String subject,long version){if(version!=1)return false;try(Connection c=source.getConnection()){c.setAutoCommit(false);var current=byAccount(c,id);if(current.isEmpty()||!current.get().subject().equals(subject)){c.rollback();return false;}try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_identity SET status='DISABLED',updated_at=CURRENT_TIMESTAMP(3) WHERE account_id=? AND identity_type IN ('WECHAT_OPEN','WECHAT_UNION') AND status='ACTIVE'")){p.setLong(1,id);boolean changed=p.executeUpdate()>0;c.commit();return changed;}catch(Exception e){c.rollback();throw e;}}catch(SQLException e){throw fail(e);}}
 private static Optional<WeChatBindingService.Binding> byAccount(Connection c,long id)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT normalized_value,created_at FROM aoo_account_identity WHERE account_id=? AND identity_type='WECHAT_OPEN' AND status='ACTIVE'")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())return Optional.empty();String[] open=r.getString(1).split(":",2);String union=null;try(PreparedStatement u=c.prepareStatement("SELECT normalized_value FROM aoo_account_identity WHERE account_id=? AND identity_type='WECHAT_UNION' AND status='ACTIVE'")){u.setLong(1,id);try(ResultSet ur=u.executeQuery()){if(ur.next())union=ur.getString(1);}}return Optional.of(new WeChatBindingService.Binding(id,open[0],open[1],union,1,r.getTimestamp(2).toInstant()));}}}
 private static Optional<WeChatBindingService.Binding> byValue(Connection c,String app,String open,String union)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT account_id FROM aoo_account_identity WHERE status='ACTIVE' AND ((identity_type='WECHAT_OPEN' AND value_hash=?) OR (identity_type='WECHAT_UNION' AND value_hash=?)) LIMIT 1")){p.setString(1,hash(app+":"+open));p.setString(2,hash(union==null?"":union));try(ResultSet r=p.executeQuery()){return r.next()?byAccount(c,r.getLong(1)):Optional.empty();}}}
 private static void insert(Connection c,String type,String value,long id,Instant at)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account_identity(identity_type,normalized_value,value_hash,account_id,verified,status,created_at,updated_at) VALUES(?,?,?,?,TRUE,'ACTIVE',?,?)")){p.setString(1,type);p.setString(2,value);p.setString(3,hash(value));p.setLong(4,id);p.setTimestamp(5,Timestamp.from(at));p.setTimestamp(6,Timestamp.from(at));p.executeUpdate();}}
 private static String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static IllegalStateException fail(Exception e){return new IllegalStateException("cannot persist WeChat identity",e);}
}
