// Generated from Server/protocol/aoo-protocol-v2.json. Do not edit.
package com.aoo.bcg.gamespi.protocol;

import java.util.Map;
import java.util.Set;

public final class GeneratedProtocolIds {
    public record Shape(Set<String> required, Map<String, String> properties) {}
    public record Definition(String kind, String direction, String transport, String version, String stage, String auth, boolean write, String idempotency, Shape request, Shape response, Set<Integer> errors) {}
    private GeneratedProtocolIds() {}
    public static final String ACCOUNT_LOGIN = "account.login";
    public static final String ACCOUNT_LOGIN_COMPAT = "account.login_compat";
    public static final String ACCOUNT_SESSION_DISPATCH = "account.session_dispatch";
    public static final String ACCOUNT_SESSION_PUSH = "account.session_push";
    public static final String ACCOUNT_TOKEN_REFRESH = "account.token_refresh";
    public static final String ACCOUNT_WS_TICKET = "account.ws_ticket";
    public static final String CLUB_DISPATCH = "club.dispatch";
    public static final String CLUB_MEMBER_PAGE = "club.member_page";
    public static final String CLUB_STATE_PUSH = "club.state_push";
    public static final String COMMON_ROOM_COMPAT_STATE_PUSH = "common.room.compat_state_push";
    public static final String COMMON_ROOM_DISPATCH = "common.room.dispatch";
    public static final String COMMON_ROOM_STATE_PUSH = "common.room.state_push";
    public static final String GAME_ACTION = "game.action";
    public static final String GAME_DISPATCH = "game.dispatch";
    public static final String GAME_FINAL_SETTLEMENT = "game.final_settlement";
    public static final String GAME_ROUND_SETTLEMENT = "game.round_settlement";
    public static final String GAME_STATE_PUSH = "game.state_push";
    public static final String HALL_CATALOG = "hall.catalog";
    public static final String HALL_DISPATCH = "hall.dispatch";
    public static final String HALL_STATE_PUSH = "hall.state_push";
    public static final String LONGCARD_AYCP_DISPATCH = "longcard.aycp.dispatch";
    public static final String LONGCARD_AYDSS_DISPATCH = "longcard.aydss.dispatch";
    public static final String MAHJONG_XUEZHAN_DISPATCH = "mahjong.xuezhan.dispatch";
    public static final String MAHJONG_XUEZHAN_STATE_PUSH = "mahjong.xuezhan.state_push";
    public static final String POKER_CD201_DISPATCH = "poker.CD201.dispatch";
    public static final String POKER_CD201_STATE_PUSH = "poker.CD201.state_push";
    public static final String POKER_LS201_DISPATCH = "poker.LS201.dispatch";
    public static final String POKER_LS201_STATE_PUSH = "poker.LS201.state_push";
    public static final String POKER_NJ201_DISPATCH = "poker.NJ201.dispatch";
    public static final String POKER_NJ201_STATE_PUSH = "poker.NJ201.state_push";
    public static final String POKER_PDK_DISPATCH = "poker.pdk.dispatch";
    public static final String POKER_PDK_STATE_PUSH = "poker.pdk.state_push";
    public static final String REPLAY_PERSPECTIVE_PAGE = "replay.perspective_page";
    public static final String REPLAY_QUERY = "replay.query";
    public static final String ROOM_CREATE = "room.create";
    public static final String ROOM_DISSOLVE_APPLY = "room.dissolve_apply";
    public static final String ROOM_DISSOLVE_VOTE = "room.dissolve_vote";
    public static final String ROOM_JOIN = "room.join";
    public static final String ROOM_LEAVE = "room.leave";
    public static final String ROOM_RECONNECT = "room.reconnect";
    public static final String ROOM_SEAT = "room.seat";
    public static final String SYSTEM_HEARTBEAT = "system.heartbeat";
    public static final String SYSTEM_KICK_OUT = "system.kick_out";
    public static final Map<String, Definition> DEFINITIONS = Map.ofEntries(
        Map.entry(ACCOUNT_LOGIN, new Definition("req", "client_to_server", "HTTPS", "2.0", "M1", "anonymous", true, "required", new Shape(Set.of("loginType", "credential", "deviceId"), Map.ofEntries(Map.entry("loginType", "\"string\""), Map.entry("credential", "\"string\""), Map.entry("deviceId", "\"string\""), Map.entry("clientVersion", "\"string\""))), new Shape(Set.of("accessToken", "refreshToken", "userId", "wsTicket"), Map.ofEntries(Map.entry("accessToken", "\"string\""), Map.entry("refreshToken", "\"string\""), Map.entry("userId", "\"string\""), Map.entry("wsTicket", "\"string\""))), Set.of(1001, 1002, 2001, 2002))),
        Map.entry(ACCOUNT_LOGIN_COMPAT, new Definition("req", "client_to_server", "HTTPS", "2.0", "M1", "anonymous", true, "required", new Shape(Set.of("action", "payload", "deviceId"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("deviceId", "\"string\""), Map.entry("clientVersion", "\"string\""))), new Shape(Set.of("payload", "wsTicket"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("wsTicket", "\"string\""))), Set.of(1001, 1002, 2001, 2002))),
        Map.entry(ACCOUNT_SESSION_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M1", "ws_ticket", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload"), Map.ofEntries(Map.entry("payload", "\"object\""))), Set.of(1001, 1003, 2001, 2003))),
        Map.entry(ACCOUNT_SESSION_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M1", "session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), Set.of())),
        Map.entry(ACCOUNT_TOKEN_REFRESH, new Definition("req", "client_to_server", "HTTPS", "2.0", "M8", "refresh_token", true, "required", new Shape(Set.of("sessionId", "deviceId", "refreshToken"), Map.ofEntries(Map.entry("sessionId", "\"string\""), Map.entry("deviceId", "\"string\""), Map.entry("refreshToken", "\"string\""))), new Shape(Set.of("accessToken", "refreshToken", "expiresInSeconds"), Map.ofEntries(Map.entry("accessToken", "\"string\""), Map.entry("refreshToken", "\"string\""), Map.entry("expiresInSeconds", "\"integer\""))), Set.of(1001, 2003, 2004))),
        Map.entry(ACCOUNT_WS_TICKET, new Definition("req", "client_to_server", "HTTPS", "2.0", "M1", "access_token", true, "required", new Shape(Set.of("deviceId"), Map.ofEntries(Map.entry("deviceId", "\"string\""))), new Shape(Set.of("wsTicket", "expiresInSeconds"), Map.ofEntries(Map.entry("wsTicket", "\"string\""), Map.entry("expiresInSeconds", "\"integer\""))), Set.of(1001, 1003, 2003))),
        Map.entry(CLUB_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M3", "session", true, "required", new Shape(Set.of("action", "payload", "clubId"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("clubId", "\"string\""))), new Shape(Set.of("payload"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 1003, 6001, 6002))),
        Map.entry(CLUB_MEMBER_PAGE, new Definition("req", "client_to_server", "HTTPS", "2.0", "M8", "access_token", false, "optional", new Shape(Set.of("clubId", "limit"), Map.ofEntries(Map.entry("clubId", "\"string\""), Map.entry("cursor", "\"string\""), Map.entry("limit", "\"integer\""))), new Shape(Set.of("items", "hasMore"), Map.ofEntries(Map.entry("items", "\"array\""), Map.entry("nextCursor", "\"string\""), Map.entry("hasMore", "\"boolean\""))), Set.of(1001, 6001, 6002))),
        Map.entry(CLUB_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M3", "session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), Set.of())),
        Map.entry(COMMON_ROOM_COMPAT_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M4", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), Set.of())),
        Map.entry(COMMON_ROOM_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M4", "room_session", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("lastServerSeq", "\"integer\""), Map.entry("reconnectToken", "\"string\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""), Map.entry("serverSeq", "\"integer\""))), Set.of(1001, 1003, 3001, 3002, 3003))),
        Map.entry(COMMON_ROOM_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M4", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("payload", "stateVersion", "serverSeq"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""), Map.entry("serverSeq", "\"integer\""))), Set.of())),
        Map.entry(GAME_ACTION, new Definition("req", "client_to_server", "WSS", "2.0", "M8", "room_session", true, "required", new Shape(Set.of("action", "payload", "actionId", "playVersion", "expectedStateVersion", "intent"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("actionId", "\"string\""), Map.entry("playVersion", "\"string\""), Map.entry("expectedStateVersion", "\"integer\""), Map.entry("intent", "\"object\""))), new Shape(Set.of("accepted", "stateVersion", "serverSeq"), Map.ofEntries(Map.entry("accepted", "\"boolean\""), Map.entry("stateVersion", "\"integer\""), Map.entry("serverSeq", "\"integer\""))), Set.of(3001, 4001, 4002, 4003))),
        Map.entry(GAME_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M7", "room_session", true, "required", new Shape(Set.of("action", "payload", "gameId"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("gameId", "\"string\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(GAME_FINAL_SETTLEMENT, new Definition("push", "server_to_client", "WSS", "2.0", "M8", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("settlementBusinessId", "resultProfileId", "playerEntries"), Map.ofEntries(Map.entry("settlementBusinessId", "\"string\""), Map.entry("resultProfileId", "\"string\""), Map.entry("playerEntries", "\"array\""))), Set.of())),
        Map.entry(GAME_ROUND_SETTLEMENT, new Definition("push", "server_to_client", "WSS", "2.0", "M8", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("settlementBusinessId", "roundNo", "resultProfileId", "playerEntries"), Map.ofEntries(Map.entry("settlementBusinessId", "\"string\""), Map.entry("roundNo", "\"integer\""), Map.entry("resultProfileId", "\"string\""), Map.entry("playerEntries", "\"array\""))), Set.of())),
        Map.entry(GAME_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M7", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), Set.of())),
        Map.entry(HALL_CATALOG, new Definition("req", "client_to_server", "HTTPS", "2.0", "M8", "access_token", false, "optional", new Shape(Set.of("clientVersion"), Map.ofEntries(Map.entry("regionCode", "\"string\""), Map.entry("clientVersion", "\"string\""))), new Shape(Set.of("games"), Map.ofEntries(Map.entry("games", "\"array\""))), Set.of(1001, 1004))),
        Map.entry(HALL_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M2", "session", false, "optional", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 1003, 2003))),
        Map.entry(HALL_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M2", "session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), Set.of())),
        Map.entry(LONGCARD_AYCP_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M7", "room_session", true, "required", new Shape(Set.of("command", "action", "payload"), Map.ofEntries(Map.entry("command", "\"string\""), Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(LONGCARD_AYDSS_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M7", "room_session", true, "required", new Shape(Set.of("command", "action", "payload"), Map.ofEntries(Map.entry("command", "\"string\""), Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(MAHJONG_XUEZHAN_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M6", "room_session", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(MAHJONG_XUEZHAN_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M6", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), Set.of())),
        Map.entry(POKER_CD201_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M5", "room_session", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(POKER_CD201_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M5", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("payload", "stateVersion", "serverSeq"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""), Map.entry("serverSeq", "\"integer\""))), Set.of())),
        Map.entry(POKER_LS201_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M5", "room_session", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(POKER_LS201_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M5", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("payload", "stateVersion", "serverSeq"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""), Map.entry("serverSeq", "\"integer\""))), Set.of())),
        Map.entry(POKER_NJ201_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M5", "room_session", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(POKER_NJ201_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M5", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("payload", "stateVersion", "serverSeq"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""), Map.entry("serverSeq", "\"integer\""))), Set.of())),
        Map.entry(POKER_PDK_DISPATCH, new Definition("req", "client_to_server", "WSS", "2.0", "M5", "room_session", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("payload", "stateVersion"), Map.ofEntries(Map.entry("payload", "\"object\""), Map.entry("stateVersion", "\"integer\""))), Set.of(1001, 3001, 4001, 4002))),
        Map.entry(POKER_PDK_STATE_PUSH, new Definition("push", "server_to_client", "WSS", "2.0", "M5", "room_session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), Set.of())),
        Map.entry(REPLAY_PERSPECTIVE_PAGE, new Definition("req", "client_to_server", "WSS", "2.0", "M8", "session", false, "optional", new Shape(Set.of("action", "payload", "roomId", "setId"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("roomId", "\"string\""), Map.entry("setId", "\"integer\""), Map.entry("afterSequence", "\"integer\""), Map.entry("limit", "\"integer\""))), new Shape(Set.of("items", "nextSequence", "hasMore"), Map.ofEntries(Map.entry("items", "\"array\""), Map.entry("nextSequence", "\"integer\""), Map.entry("hasMore", "\"boolean\""))), Set.of(1001, 1003, 3001, 3003))),
        Map.entry(REPLAY_QUERY, new Definition("req", "client_to_server", "HTTPS", "2.0", "M8", "access_token", false, "optional", new Shape(Set.of("roomId"), Map.ofEntries(Map.entry("roomId", "\"string\""))), new Shape(Set.of("viewerReplay", "viewType"), Map.ofEntries(Map.entry("viewerReplay", "\"object\""), Map.entry("viewType", "\"string\""))), Set.of(1003, 3001, 6002))),
        Map.entry(ROOM_CREATE, new Definition("req", "client_to_server", "HTTPS", "2.0", "M8", "access_token", true, "required", new Shape(Set.of("gameId", "roomProfileVersion", "ruleSnapshotId", "paymentMode"), Map.ofEntries(Map.entry("gameId", "\"string\""), Map.entry("roomProfileVersion", "\"string\""), Map.entry("ruleSnapshotId", "\"string\""), Map.entry("paymentMode", "\"string\""), Map.entry("clubId", "\"string\""))), new Shape(Set.of("roomId", "roomSessionToken", "ruleSnapshotId"), Map.ofEntries(Map.entry("roomId", "\"string\""), Map.entry("roomSessionToken", "\"string\""), Map.entry("ruleSnapshotId", "\"string\""))), Set.of(1001, 3002, 5001, 6002))),
        Map.entry(ROOM_DISSOLVE_APPLY, new Definition("req", "client_to_server", "WSS", "2.0", "M8", "room_session", true, "required", new Shape(Set.of("action", "payload", "reasonCode"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("reasonCode", "\"string\""))), new Shape(Set.of("voteId", "expiresAt"), Map.ofEntries(Map.entry("voteId", "\"string\""), Map.entry("expiresAt", "\"integer\""))), Set.of(3001, 3003, 3004))),
        Map.entry(ROOM_DISSOLVE_VOTE, new Definition("req", "client_to_server", "WSS", "2.0", "M8", "room_session", true, "required", new Shape(Set.of("action", "payload", "voteId", "agree"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("voteId", "\"string\""), Map.entry("agree", "\"boolean\""))), new Shape(Set.of("accepted", "stateVersion"), Map.ofEntries(Map.entry("accepted", "\"boolean\""), Map.entry("stateVersion", "\"integer\""))), Set.of(3001, 3004))),
        Map.entry(ROOM_JOIN, new Definition("req", "client_to_server", "HTTPS", "2.0", "M8", "access_token", true, "required", new Shape(Set.of("roomId"), Map.ofEntries(Map.entry("roomId", "\"string\""))), new Shape(Set.of("roomSessionToken", "playVersion", "ruleSnapshotId"), Map.ofEntries(Map.entry("roomSessionToken", "\"string\""), Map.entry("playVersion", "\"string\""), Map.entry("ruleSnapshotId", "\"string\""))), Set.of(3001, 3002, 3003, 6002))),
        Map.entry(ROOM_LEAVE, new Definition("req", "client_to_server", "WSS", "2.0", "M8", "room_session", true, "required", new Shape(Set.of("action", "payload"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""))), new Shape(Set.of("left"), Map.ofEntries(Map.entry("left", "\"boolean\""))), Set.of(3001, 3003))),
        Map.entry(ROOM_RECONNECT, new Definition("req", "client_to_server", "WSS", "2.0", "M8", "room_session", false, "optional", new Shape(Set.of("action", "payload", "roomId", "lastServerSeq", "reconnectToken"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("roomId", "\"string\""), Map.entry("lastServerSeq", "\"integer\""), Map.entry("reconnectToken", "\"string\""))), new Shape(Set.of("viewerSnapshot", "events", "serverSeq", "hasMore"), Map.ofEntries(Map.entry("viewerSnapshot", "\"object\""), Map.entry("events", "\"array\""), Map.entry("serverSeq", "\"integer\""), Map.entry("hasMore", "\"boolean\""))), Set.of(3001, 3005))),
        Map.entry(ROOM_SEAT, new Definition("req", "client_to_server", "WSS", "2.0", "M8", "room_session", true, "required", new Shape(Set.of("action", "payload", "seatId"), Map.ofEntries(Map.entry("action", "\"string\""), Map.entry("payload", "\"object\""), Map.entry("seatId", "\"integer\""))), new Shape(Set.of("stateVersion", "serverSeq"), Map.ofEntries(Map.entry("stateVersion", "\"integer\""), Map.entry("serverSeq", "\"integer\""))), Set.of(3001, 3002, 3003))),
        Map.entry(SYSTEM_HEARTBEAT, new Definition("system", "bidirectional", "WSS", "2.0", "M7", "session", false, "none", new Shape(Set.of("clientTime"), Map.ofEntries(Map.entry("clientTime", "\"integer\""))), new Shape(Set.of("serverTime"), Map.ofEntries(Map.entry("serverTime", "\"integer\""))), Set.of())),
        Map.entry(SYSTEM_KICK_OUT, new Definition("system", "server_to_client", "WSS", "2.0", "M7", "session", false, "none", new Shape(Set.of(), Map.of()), new Shape(Set.of("reasonCode"), Map.ofEntries(Map.entry("reasonCode", "\"string\""), Map.entry("message", "\"string\""))), Set.of()))
    );
}
