package com.aoo.bcg.account;

import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.sql.*;
import java.time.*;
import java.util.*;

/** Durable authority for credentials, devices and rotating sessions. Raw bearer secrets are never stored. */
public final class JdbcAccountSessionService {
    private static final Duration ACCESS_TTL=Duration.ofMinutes(15), REFRESH_TTL=Duration.ofDays(30);
    private final DataSource source; private final Clock clock; private final PasswordHasher passwords; private final SecureRandom random; private final UnifiedIdentityService identities; private final SessionReplacementNotifier replacements;
    public JdbcAccountSessionService(DataSource source,Clock clock){this(source,clock,SessionReplacementNotifier.none());}
    public JdbcAccountSessionService(DataSource source,Clock clock,SessionReplacementNotifier replacements){this(source,clock,new PasswordHasher(),new SecureRandom(),replacements);}
    JdbcAccountSessionService(DataSource source,Clock clock,PasswordHasher passwords,SecureRandom random){this(source,clock,passwords,random,SessionReplacementNotifier.none());}
    JdbcAccountSessionService(DataSource source,Clock clock,PasswordHasher passwords,SecureRandom random,SessionReplacementNotifier replacements){this.source=Objects.requireNonNull(source);this.clock=Objects.requireNonNull(clock);this.passwords=Objects.requireNonNull(passwords);this.random=Objects.requireNonNull(random);this.replacements=Objects.requireNonNull(replacements);this.identities=new UnifiedIdentityService(source,clock,random);}

    public Registration register(String login,char[] password,String recovery,Client client){String name=login(login), pass=passwords.hash(password), recoveryHash=hash(required(recovery,"recovery"));return tx(c->{
        try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account(password_hash,recovery_credential_hash,guest,created_at,updated_at) VALUES(?,?,FALSE,?,?)",Statement.RETURN_GENERATED_KEYS)){Instant now=clock.instant();p.setString(1,pass);p.setString(2,recoveryHash);time(p,3,now);time(p,4,now);p.executeUpdate();long id=key(p);identities.insert(c,UnifiedIdentityService.Type.ALIAS,name,id,true);String displayId=identities.allocate(c,id,"registration-"+id);device(c,id,client);audit(c,id,"ACCOUNT_REGISTERED",name,client.ip());return new Registration(id,displayId,false);}
        catch(SQLIntegrityConstraintViolationException e){throw new Conflict("login or recovery credential already registered");}});}
    public boolean isRegisteredIdentity(String identity){try{identities.resolve(required(identity,"identity"));return true;}catch(UnifiedIdentityService.NotFound ignored){return false;}}
    public Registration registerGuest(String credential,Client client){String digest=hash(required(credential,"guest credential"));return tx(c->{
        try(PreparedStatement q=c.prepareStatement("SELECT account_id FROM aoo_account WHERE guest_credential_hash=?")){q.setString(1,digest);try(ResultSet r=q.executeQuery()){if(r.next()){long id=r.getLong(1);return new Registration(id,identities.currentDisplayId(c,id),true);}}}
        try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account(guest_credential_hash,recovery_credential_hash,guest,created_at,updated_at) VALUES(?,?,TRUE,?,?)",Statement.RETURN_GENERATED_KEYS)){Instant now=clock.instant();p.setString(1,digest);p.setString(2,digest);time(p,3,now);time(p,4,now);p.executeUpdate();long id=key(p);String displayId=identities.allocate(c,id,"guest-registration-"+id);device(c,id,client);audit(c,id,"GUEST_REGISTERED",client.deviceId(),client.ip());return new Registration(id,displayId,true);}});}
    public TokenPair login(String login,char[] password,Client client,boolean single){Issued issued=tx(c->{Account a=byId(c,resolveLoginIdentity(c,login),true);allowed(a);if(!passwords.verify(password,a.passwordHash))throw new Unauthorized("invalid credentials");return new Issued(a.id,issue(c,a,client,single,null));});return finishLogin(issued,client,single);}
    public TokenPair loginGuest(String credential,Client client,boolean single){Issued issued=tx(c->{Account a=byGuest(c,hash(required(credential,"guest credential")),true);allowed(a);if(!a.guest)throw new Unauthorized("guest credential upgraded");return new Issued(a.id,issue(c,a,client,single,null));});return finishLogin(issued,client,single);}
    public void upgrade(long accountId,String login,char[] password,String recovery,Client client){String name=login(login), pass=passwords.hash(password), recover=hash(required(recovery,"recovery"));tx(c->{Account a=byId(c,accountId,true);if(!a.guest)throw new Conflict("account is not a guest");try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET password_hash=?,recovery_credential_hash=?,guest=FALSE,guest_credential_hash=NULL,auth_generation=auth_generation+1,updated_at=? WHERE account_id=?")){p.setString(1,pass);p.setString(2,recover);time(p,3,clock.instant());p.setLong(4,accountId);p.executeUpdate();identities.insert(c,UnifiedIdentityService.Type.ALIAS,name,accountId,true);revokeAll(c,accountId,"GUEST_UPGRADED");audit(c,accountId,"GUEST_UPGRADED",name,client.ip());return null;}catch(SQLIntegrityConstraintViolationException e){throw new Conflict("login or recovery credential already registered");}});}
    public TokenPair refresh(String refresh,Client client){String digest=hash(required(refresh,"refresh token"));return tx(c->{Session s=session(c,"refresh_hash",digest,true);Account a=byId(c,s.accountId,true);allowed(a);if(!s.deviceId.equals(client.deviceId))throw new Unauthorized("device mismatch");revoke(c,s.sessionId,"REFRESH_ROTATED");return issue(c,a,client,false,s.family);});}
    public Principal authorize(String access,Client client){return tx(c->{Session s=session(c,"access_hash",hash(required(access,"access token")),false);Account a=byId(c,s.accountId,false);allowed(a);if(!s.deviceId.equals(client.deviceId)||s.generation!=a.generation)throw new Unauthorized("stale or mismatched session");return new Principal(a.id,identities.currentDisplayId(c,a.id),s.sessionId,s.accessExpiresAt);});}
    public TokenPair loginTrustedDevice(long accountId,Client client,boolean single){Issued issued=tx(c->{Account a=byId(c,accountId,true);allowed(a);return new Issued(a.id,issue(c,a,client,single,null));});return finishLogin(issued,client,single);}
    public void logout(String access,Client client){tx(c->{Session s=session(c,"access_hash",hash(required(access,"access token")),true);Account a=byId(c,s.accountId,true);if(!s.deviceId.equals(client.deviceId)||s.generation!=a.generation)throw new Unauthorized("stale or mismatched session");revokeFamily(c,s.family,"LOGOUT");audit(c,s.accountId,"LOGOUT",s.sessionId,client.ip());return null;});}
    public void changePassword(long id,char[] current,char[] replacement,Client client){String next=passwords.hash(replacement);tx(c->{Account a=byId(c,id,true);if(a.passwordHash==null||!passwords.verify(current,a.passwordHash))throw new Unauthorized("invalid credentials");try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET password_hash=?,auth_generation=auth_generation+1,updated_at=? WHERE account_id=?")){p.setString(1,next);time(p,2,clock.instant());p.setLong(3,id);p.executeUpdate();}revokeAll(c,id,"PASSWORD_CHANGED");audit(c,id,"PASSWORD_CHANGED",client.deviceId(),client.ip());return null;});}
    public void recover(String recovery,char[] replacement,Client client){String next=passwords.hash(replacement);tx(c->{Account a;try(PreparedStatement p=c.prepareStatement("SELECT account_id,password_hash,guest,auth_generation,banned_until FROM aoo_account WHERE recovery_credential_hash=? FOR UPDATE")){p.setString(1,hash(required(recovery,"recovery")));try(ResultSet r=p.executeQuery()){if(!r.next())throw new Unauthorized("invalid recovery credential");a=account(r);}}try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET password_hash=?,auth_generation=auth_generation+1,updated_at=? WHERE account_id=?")){p.setString(1,next);time(p,2,clock.instant());p.setLong(3,a.id);p.executeUpdate();}revokeAll(c,a.id,"ACCOUNT_RECOVERED");audit(c,a.id,"ACCOUNT_RECOVERED",client.deviceId(),client.ip());return null;});}
    public void ban(long id,Instant until,String reason,String operatorIp){tx(c->{byId(c,id,true);try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET banned_until=?,ban_reason=?,auth_generation=auth_generation+1,updated_at=? WHERE account_id=?")){time(p,1,until);p.setString(2,required(reason,"reason"));time(p,3,clock.instant());p.setLong(4,id);p.executeUpdate();}revokeAll(c,id,"ACCOUNT_BANNED");audit(c,id,"ACCOUNT_BANNED",reason,operatorIp);return null;});}
    public void revokeSessions(long id,String reason,String operatorIp){tx(c->{byId(c,id,true);try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET auth_generation=auth_generation+1,updated_at=? WHERE account_id=?")){time(p,1,clock.instant());p.setLong(2,id);p.executeUpdate();}revokeAll(c,id,"SESSIONS_REVOKED");audit(c,id,"SESSIONS_REVOKED",reason,operatorIp);return null;});}
    public List<Audit> audit(long id){return tx(c->{List<Audit> out=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT action_name,detail_value,source_ip,occurred_at FROM aoo_account_audit WHERE account_id=? ORDER BY audit_id")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new Audit(r.getString(1),r.getString(2),r.getString(3),r.getTimestamp(4).toInstant()));}}return List.copyOf(out);});}

    private TokenPair issue(Connection c,Account a,Client client,boolean single,String family)throws SQLException{if(single){try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET auth_generation=auth_generation+1,updated_at=? WHERE account_id=?")){time(p,1,clock.instant());p.setLong(2,a.id);p.executeUpdate();}revokeAll(c,a.id,"SINGLE_DEVICE_LOGIN");a=new Account(a.id,a.passwordHash,a.guest,a.generation+1,a.bannedUntil);}device(c,a.id,client);Instant now=clock.instant(),ae=now.plus(ACCESS_TTL),re=now.plus(REFRESH_TTL);String access=token(),refresh=token(),sid=UUID.randomUUID().toString(),fam=family==null?UUID.randomUUID().toString():family;try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account_session(session_id,account_id,device_id,token_family,access_hash,refresh_hash,access_expires_at,refresh_expires_at,auth_generation,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)")){p.setString(1,sid);p.setLong(2,a.id);p.setString(3,client.deviceId);p.setString(4,fam);p.setString(5,hash(access));p.setString(6,hash(refresh));time(p,7,ae);time(p,8,re);p.setLong(9,a.generation);time(p,10,now);p.executeUpdate();}audit(c,a.id,"SESSION_ISSUED",client.deviceId,client.ip);return new TokenPair(access,refresh,ae,re,sid,a.generation);}
    private TokenPair finishLogin(Issued issued,Client client,boolean single){if(single)replacements.replaced(issued.accountId,issued.tokens.sessionId,issued.tokens.authGeneration);return issued.tokens;}
    private long resolveLoginIdentity(Connection c,String login)throws SQLException{try{return identities.resolve(c,required(login,"identity"));}catch(UnifiedIdentityService.NotFound missing){throw new Unauthorized("invalid credentials");}}
    private void device(Connection c,long id,Client v)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account_device(account_id,device_id,channel_name,client_version,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE channel_name=VALUES(channel_name),client_version=VALUES(client_version),last_seen_at=VALUES(last_seen_at),revoked_at=NULL")){Instant now=clock.instant();p.setLong(1,id);p.setString(2,v.deviceId);p.setString(3,v.channel);p.setString(4,v.version);time(p,5,now);time(p,6,now);p.executeUpdate();}}
    private Account byGuest(Connection c,String value,boolean lock)throws SQLException{return one(c,"guest_credential_hash",value,lock);}
    private Account one(Connection c,String column,String value,boolean lock)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT account_id,password_hash,guest,auth_generation,banned_until FROM aoo_account WHERE "+column+"=?"+(lock?" FOR UPDATE":""))){p.setString(1,value);try(ResultSet r=p.executeQuery()){if(!r.next())throw new Unauthorized("invalid credentials");return account(r);}}}
    private Account byId(Connection c,long id,boolean lock)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT account_id,password_hash,guest,auth_generation,banned_until FROM aoo_account WHERE account_id=?"+(lock?" FOR UPDATE":""))){p.setLong(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())throw new Unauthorized("unknown account");return account(r);}}}
    private static Account account(ResultSet r)throws SQLException{Timestamp ban=r.getTimestamp(5);return new Account(r.getLong(1),r.getString(2),r.getBoolean(3),r.getLong(4),ban==null?null:ban.toInstant());}
    private Session session(Connection c,String column,String digest,boolean lock)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT session_id,account_id,device_id,token_family,access_expires_at,refresh_expires_at,auth_generation,revoked_at,revoke_reason FROM aoo_account_session WHERE "+column+"=?"+(lock?" FOR UPDATE":""))){p.setString(1,digest);try(ResultSet r=p.executeQuery()){if(!r.next())throw new Unauthorized("SESSION_INVALID","会话无效，请重新登录");if(r.getTimestamp(8)!=null)throw revoked(r.getString(9));Instant expiry=column.equals("access_hash")?r.getTimestamp(5).toInstant():r.getTimestamp(6).toInstant();if(!clock.instant().isBefore(expiry))throw new Unauthorized("SESSION_EXPIRED","登录已过期，请重新登录");return new Session(r.getString(1),r.getLong(2),r.getString(3),r.getString(4),r.getTimestamp(5).toInstant(),r.getLong(7));}}}
    private static Unauthorized revoked(String reason){return switch(String.valueOf(reason)){
        case "SINGLE_DEVICE_LOGIN","SESSION_REPLACED","WECHAT_SINGLE_DEVICE","REPLACED_BY_NEW_LOGIN"->new Unauthorized("SESSION_REPLACED","你的账号已在其他设备登录");
        case "LOGOUT"->new Unauthorized("SESSION_LOGGED_OUT","账号已退出，请重新登录");
        case "REFRESH_ROTATED"->new Unauthorized("REFRESH_TOKEN_REUSED","刷新令牌已失效，请重新登录");
        case "PASSWORD_CHANGED","ACCOUNT_RECOVERED","GUEST_UPGRADED"->new Unauthorized("SESSION_CREDENTIALS_CHANGED","账号凭据已变更，请重新登录");
        case "ACCOUNT_BANNED"->new Unauthorized("SESSION_ACCOUNT_BANNED","账号当前不可用");
        default->new Unauthorized("SESSION_REVOKED","会话已撤销，请重新登录");};}
    private void revoke(Connection c,String sid,String reason)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_session SET revoked_at=?,revoke_reason=? WHERE session_id=? AND revoked_at IS NULL")){time(p,1,clock.instant());p.setString(2,reason);p.setString(3,sid);p.executeUpdate();}}
    private void revokeFamily(Connection c,String family,String reason)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_session SET revoked_at=?,revoke_reason=? WHERE token_family=? AND revoked_at IS NULL")){time(p,1,clock.instant());p.setString(2,reason);p.setString(3,family);p.executeUpdate();}}
    private void revokeAll(Connection c,long id,String reason)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_session SET revoked_at=?,revoke_reason=? WHERE account_id=? AND revoked_at IS NULL")){time(p,1,clock.instant());p.setString(2,reason);p.setLong(3,id);p.executeUpdate();}}
    private void audit(Connection c,long id,String action,String detail,String ip)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account_audit(account_id,action_name,detail_value,source_ip,occurred_at) VALUES(?,?,?,?,?)")){p.setLong(1,id);p.setString(2,action);p.setString(3,detail);p.setString(4,ip);time(p,5,clock.instant());p.executeUpdate();}}
    private <T>T tx(SqlWork<T>w){try(Connection c=source.getConnection()){boolean auto=c.getAutoCommit();c.setAutoCommit(false);try{T out=w.run(c);c.commit();return out;}catch(Exception e){c.rollback();if(e instanceof RuntimeException r)throw r;throw new IllegalStateException("account persistence failed",e);}finally{c.setAutoCommit(auto);}}catch(SQLException e){throw new IllegalStateException("account persistence unavailable",e);}}
    private String token(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private static long key(PreparedStatement p)throws SQLException{try(ResultSet r=p.getGeneratedKeys()){if(!r.next())throw new SQLException("missing generated account id");return r.getLong(1);}}
    private static String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}} private static String login(String v){String n=required(v,"login").strip().toLowerCase(Locale.ROOT);if(n.length()<1||n.length()>64)throw new IllegalArgumentException("invalid login");return n;} private static String required(String v,String n){if(v==null||v.isBlank())throw new IllegalArgumentException("invalid "+n);return v;} private static void time(PreparedStatement p,int i,Instant v)throws SQLException{p.setTimestamp(i,Timestamp.from(v));} private void allowed(Account a){if(a.bannedUntil!=null&&clock.instant().isBefore(a.bannedUntil))throw new Forbidden("account banned");}
    @FunctionalInterface private interface SqlWork<T>{T run(Connection c)throws Exception;} private record Account(long id,String passwordHash,boolean guest,long generation,Instant bannedUntil){} private record Session(String sessionId,long accountId,String deviceId,String family,Instant accessExpiresAt,long generation){} private record Issued(long accountId,TokenPair tokens){}
    public record Client(String deviceId,String channel,String version,String ip){public Client{required(deviceId,"deviceId");required(channel,"channel");required(version,"version");required(ip,"ip");}} public record Registration(long accountId,String displayId,boolean guest){} public record TokenPair(String accessToken,String refreshToken,Instant accessExpiresAt,Instant refreshExpiresAt,String sessionId,long authGeneration){} public record Principal(long accountId,String displayId,String sessionId,Instant expiresAt){} public record Audit(String action,String detail,String sourceIp,Instant occurredAt){}
    public static final class Unauthorized extends SecurityException{private final String reasonCode;public Unauthorized(String m){this("SESSION_INVALID",m);}public Unauthorized(String reasonCode,String message){super(message);this.reasonCode=required(reasonCode,"reasonCode");}public String reasonCode(){return reasonCode;}} public static final class Forbidden extends SecurityException{public Forbidden(String m){super(m);}} public static final class Conflict extends IllegalStateException{public Conflict(String m){super(m);}}
}
