package com.aoo.bcg.account;

import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.sql.*;
import java.time.*;
import java.util.*;

/** A PIN is accepted only with a bound device key and a one-use signed challenge. */
public final class TrustedDevicePinService {
    private static final Duration CHALLENGE_TTL=Duration.ofMinutes(2); private static final int MAX_FAILURES=5;
    private final DataSource source;private final Clock clock;private final PasswordHasher pins;private final SecureRandom random=new SecureRandom();
    public TrustedDevicePinService(DataSource source,Clock clock){this.source=Objects.requireNonNull(source);this.clock=Objects.requireNonNull(clock);this.pins=new PasswordHasher();}
    public record Challenge(String challengeId,String challenge,Instant expiresAt,long sequence){}
    public void bind(long accountId,String deviceId,char pin,String publicKeyPem,boolean strongVerificationPassed){if(!strongVerificationPassed)throw new SecurityException("strong verification required");if(pin<'0'||pin>'9')throw new IllegalArgumentException("PIN must be one digit");String encoded=pins.hash(pinSecret(pin));tx(c->{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_device_pin(account_id,device_id,pin_hash,public_key_pem,failed_attempts,credential_version,created_at,updated_at) VALUES(?,?,?,?,0,1,?,?) ON DUPLICATE KEY UPDATE pin_hash=VALUES(pin_hash),public_key_pem=VALUES(public_key_pem),failed_attempts=0,frozen_at=NULL,credential_version=credential_version+1,updated_at=VALUES(updated_at)")){Instant now=clock.instant();p.setLong(1,accountId);p.setString(2,deviceId);p.setString(3,encoded);p.setString(4,publicKeyPem);p.setTimestamp(5,Timestamp.from(now));p.setTimestamp(6,Timestamp.from(now));p.executeUpdate();}return null;});}
    public Challenge challenge(long accountId,String deviceId,long sequence,String sourceIp){byte[] value=new byte[32];random.nextBytes(value);String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(value),id=UUID.randomUUID().toString();Instant expires=clock.instant().plus(CHALLENGE_TTL);tx(c->{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_device_challenge(challenge_id,account_id,device_id,challenge_hash,request_sequence,expires_at,source_ip) SELECT ?,?,?,?,?,?,? FROM aoo_device_pin WHERE account_id=? AND device_id=? AND frozen_at IS NULL")){p.setString(1,id);p.setLong(2,accountId);p.setString(3,deviceId);p.setString(4,sha(raw));p.setLong(5,sequence);p.setTimestamp(6,Timestamp.from(expires));p.setString(7,sourceIp);p.setLong(8,accountId);p.setString(9,deviceId);if(p.executeUpdate()!=1)throw new SecurityException("strong verification required");}return null;});return new Challenge(id,raw,expires,sequence);}
    public long verify(String challengeId,String challenge,long sequence,char pin,byte[] signature,String sourceIp){if(pin<'0'||pin>'9')throw new SecurityException("invalid credentials");return tx(c->{String sql="SELECT c.account_id,c.device_id,c.challenge_hash,c.expires_at,c.consumed_at,p.pin_hash,p.public_key_pem,p.failed_attempts,p.frozen_at FROM aoo_device_challenge c JOIN aoo_device_pin p ON p.account_id=c.account_id AND p.device_id=c.device_id WHERE c.challenge_id=? AND c.request_sequence=? FOR UPDATE";try(PreparedStatement q=c.prepareStatement(sql)){q.setString(1,challengeId);q.setLong(2,sequence);try(ResultSet r=q.executeQuery()){if(!r.next()||r.getTimestamp(5)!=null||r.getTimestamp(9)!=null||!clock.instant().isBefore(r.getTimestamp(4).toInstant())||!MessageDigest.isEqual(r.getString(3).getBytes(StandardCharsets.UTF_8),sha(challenge).getBytes(StandardCharsets.UTF_8)))throw new SecurityException("invalid credentials");long account=r.getLong(1);boolean valid=pins.verify(pinSecret(pin),r.getString(6))&&signature(r.getString(7),challengeId+":"+challenge+":"+sequence+":"+sourceIp,signature);consume(c,challengeId);if(!valid){failure(c,account,r.getString(2),r.getInt(8)+1);throw new SecurityException("invalid credentials");}try(PreparedStatement p=c.prepareStatement("UPDATE aoo_device_pin SET failed_attempts=0,updated_at=? WHERE account_id=? AND device_id=?")){p.setTimestamp(1,Timestamp.from(clock.instant()));p.setLong(2,account);p.setString(3,r.getString(2));p.executeUpdate();}return account;}}});}
    private void consume(Connection c,String id)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE aoo_device_challenge SET consumed_at=? WHERE challenge_id=? AND consumed_at IS NULL")){p.setTimestamp(1,Timestamp.from(clock.instant()));p.setString(2,id);if(p.executeUpdate()!=1)throw new SecurityException("challenge replayed");}}
    private void failure(Connection c,long account,String device,int count)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE aoo_device_pin SET failed_attempts=?,frozen_at=?,updated_at=? WHERE account_id=? AND device_id=?")){p.setInt(1,count);if(count>=MAX_FAILURES)p.setTimestamp(2,Timestamp.from(clock.instant()));else p.setNull(2,Types.TIMESTAMP);p.setTimestamp(3,Timestamp.from(clock.instant()));p.setLong(4,account);p.setString(5,device);p.executeUpdate();}}
    private static boolean signature(String encoded,String content,byte[] signature){try{String body=encoded.replace("-----BEGIN PUBLIC KEY-----","").replace("-----END PUBLIC KEY-----","").replaceAll("\\s","");PublicKey key=KeyFactory.getInstance("EC").generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(body)));Signature verifier=Signature.getInstance("SHA256withECDSA");verifier.initVerify(key);verifier.update(content.getBytes(StandardCharsets.UTF_8));return verifier.verify(signature);}catch(GeneralSecurityException e){return false;}}
    private static String sha(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static char[] pinSecret(char pin){return ("device-pin:"+pin).toCharArray();}
    private <T>T tx(Work<T> work){try(Connection c=source.getConnection()){c.setAutoCommit(false);try{T out=work.run(c);c.commit();return out;}catch(Exception e){c.rollback();if(e instanceof RuntimeException r)throw r;throw new IllegalStateException(e);}}catch(SQLException e){throw new IllegalStateException(e);}}
    @FunctionalInterface private interface Work<T>{T run(Connection c)throws Exception;}
}
