package com.aoo.bcg.account;

import javax.sql.DataSource;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.sql.*;
import java.time.*;
import java.util.*;

/** Transactional authority for public display IDs and all login identities. */
public final class UnifiedIdentityService {
    public enum Type { DISPLAY_ID, ALIAS, PHONE, WECHAT_UNION, WECHAT_OPEN, TRUSTED_DEVICE }
    public record Identity(Type type,String value,long accountId,boolean verified,String status){}
    public record DisplayOwner(String displayId,long accountId,Instant validFrom,Instant validUntil,boolean current){}
    public record AdminContext(long operatorId,String reason,String sourceIp,String traceId,String requestId,boolean secondFactorVerified,Set<String> permissions){
        public AdminContext { required(reason,"reason");required(sourceIp,"sourceIp");required(traceId,"traceId");required(requestId,"requestId");permissions=Set.copyOf(permissions); }
    }
    private static final int COLLISION_LIMIT=32;
    private final DataSource source; private final Clock clock; private final SecureRandom random;
    public UnifiedIdentityService(DataSource source,Clock clock){this(source,clock,new SecureRandom());}
    UnifiedIdentityService(DataSource source,Clock clock,SecureRandom random){this.source=Objects.requireNonNull(source);this.clock=Objects.requireNonNull(clock);this.random=Objects.requireNonNull(random);}

    public String allocate(long accountId,String traceId){return tx(c->allocate(c,accountId,traceId));}
    String currentDisplayId(Connection c,long accountId)throws SQLException{Identity value=active(c,Type.DISPLAY_ID,accountId);return value==null?null:value.value;}
    String allocate(Connection c,long accountId,String traceId)throws SQLException{
        lockAccount(c,accountId);Identity existing=active(c,Type.DISPLAY_ID,accountId);if(existing!=null)return existing.value();
        for(int expansion=0;expansion<16;expansion++){
            Segment segment=segment(c);
            for(int attempt=0;attempt<COLLISION_LIMIT;attempt++){
                String candidate=randomDecimal(segment.digits);
                try{insert(c,Type.DISPLAY_ID,candidate,accountId,true);increment(c,segment.digits);history(c,accountId,null,candidate,null,"SYSTEM_ALLOCATION","system",traceId,clock.instant());return candidate;}
                catch(SQLIntegrityConstraintViolationException collision){/* bounded retry */}
            }
            expand(c,segment.digits+1);
        }
        throw new IllegalStateException("display ID allocation unavailable");
    }

    public long resolve(String input){String value=required(input,"identity").strip();return tx(c->{
        return resolve(c,value);
    });}
    long resolve(Connection c,String input)throws SQLException{String value=required(input,"identity").strip();
        if(value.startsWith("wechat-open:"))return resolveHash(c,Type.WECHAT_OPEN,hash(normalize(Type.WECHAT_OPEN,value.substring(12))));
        if(value.startsWith("wechat-union:"))return resolveHash(c,Type.WECHAT_UNION,hash(normalize(Type.WECHAT_UNION,value.substring(13))));
        if(value.startsWith("+"))return resolveHash(c,Type.PHONE,hash(normalize(Type.PHONE,value)));
        String normalized=normalize(value.matches("[1-9][0-9]{5,}")?Type.DISPLAY_ID:Type.ALIAS,value);
        Type preferred=value.matches("[1-9][0-9]{5,}")?Type.DISPLAY_ID:Type.ALIAS;
        try{return resolveHash(c,preferred,hash(normalized));}catch(NotFound ignored){return resolveHash(c,Type.ALIAS,hash(normalize(Type.ALIAS,value)));}
    }

    public void bind(long accountId,Type type,String value,boolean verified,AdminContext admin){authorize(admin,"account.identity.mutate");if(type==Type.DISPLAY_ID)throw new IllegalArgumentException("use changeDisplayId");String normalized=normalize(type,value);tx(c->{dedupe(c,admin.requestId);lockAccount(c,accountId);try{insert(c,type,normalized,accountId,verified);}catch(SQLIntegrityConstraintViolationException e){Identity owner=byHash(c,type,hash(normalized));if(owner!=null&&owner.accountId()!=accountId)throw new Conflict("identity already belongs to another account; migration with two proofs is required");throw new Conflict("identity already active");}audit(c,accountId,"IDENTITY_BOUND",type.name(),admin);outbox(c,accountId,"account.identity.changed",admin.traceId,"{\"type\":\""+type+"\"}");complete(c,admin.requestId,"bound");return null;});}
    public void unbind(long accountId,Type type,String value,AdminContext admin){authorize(admin,"account.identity.mutate");if(type==Type.DISPLAY_ID)throw new IllegalArgumentException("display ID cannot be unbound");String normalized=normalize(type,value);tx(c->{dedupe(c,admin.requestId);lockAccount(c,accountId);try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_identity SET status='DISABLED',updated_at=? WHERE account_id=? AND identity_type=? AND value_hash=? AND status='ACTIVE'")){time(p,1,clock.instant());p.setLong(2,accountId);p.setString(3,type.name());p.setString(4,hash(normalized));if(p.executeUpdate()!=1)throw new NotFound("active identity not found");}revoke(c,accountId,"IDENTITY_UNBOUND");audit(c,accountId,"IDENTITY_UNBOUND",type.name(),admin);outbox(c,accountId,"account.identity.changed",admin.traceId,"{\"type\":\""+type+"\"}");complete(c,admin.requestId,"unbound");return null;});}
    public void changeDisplayId(long accountId,String next,AdminContext admin){authorize(admin,"account.identity.mutate");String wanted=normalize(Type.DISPLAY_ID,next);tx(c->{dedupe(c,admin.requestId);lockAccount(c,accountId);Identity old=active(c,Type.DISPLAY_ID,accountId);if(old==null)throw new NotFound("account has no display ID");if(old.value.equals(wanted))throw new Conflict("display ID unchanged");try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_identity SET status='DISABLED',updated_at=? WHERE identity_id=(SELECT identity_id FROM (SELECT identity_id FROM aoo_account_identity WHERE account_id=? AND identity_type='DISPLAY_ID' AND status='ACTIVE' FOR UPDATE) x)")){time(p,1,clock.instant());p.setLong(2,accountId);p.executeUpdate();}try{insert(c,Type.DISPLAY_ID,wanted,accountId,true);}catch(SQLIntegrityConstraintViolationException e){throw new Conflict("display ID occupied");}Instant now=clock.instant();try(PreparedStatement p=c.prepareStatement("UPDATE aoo_display_id_history SET valid_until=? WHERE account_id=? AND valid_until IS NULL")){time(p,1,now);p.setLong(2,accountId);p.executeUpdate();}history(c,accountId,old.value,wanted,admin.operatorId,admin.reason,admin.sourceIp,admin.traceId,now);revoke(c,accountId,"DISPLAY_ID_CHANGED");audit(c,accountId,"DISPLAY_ID_CHANGED",old.value+"->"+wanted,admin);outbox(c,accountId,"account.display-id.changed",admin.traceId,"{\"old\":\""+old.value+"\",\"new\":\""+wanted+"\"}");complete(c,admin.requestId,"changed");return null;});}
    public List<DisplayOwner> owners(String displayId){String id=normalize(Type.DISPLAY_ID,displayId);return tx(c->{List<DisplayOwner> out=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT account_id,new_display_id,valid_from,valid_until FROM aoo_display_id_history WHERE new_display_id=? ORDER BY valid_from DESC")){p.setString(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){Timestamp until=r.getTimestamp(4);out.add(new DisplayOwner(r.getString(2),r.getLong(1),r.getTimestamp(3).toInstant(),until==null?null:until.toInstant(),until==null));}}}return List.copyOf(out);});}

    public void migrateIdentity(long sourceAccount,long targetAccount,Type type,String value,String sourceProof,String targetProof,AdminContext admin){authorize(admin,"account.identity.migrate");if(sourceAccount==targetAccount)throw new IllegalArgumentException("accounts must differ");String normalized=normalize(type,value);if(required(sourceProof,"sourceProof").equals(targetProof))throw new IllegalArgumentException("independent proofs required");tx(c->{dedupe(c,admin.requestId);lockAccounts(c,sourceAccount,targetAccount);Identity owner=byHash(c,type,hash(normalized));if(owner==null||owner.accountId!=sourceAccount)throw new Conflict("source does not own identity");try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_identity SET account_id=?,updated_at=? WHERE identity_id=(SELECT identity_id FROM (SELECT identity_id FROM aoo_account_identity WHERE identity_type=? AND value_hash=? AND status='ACTIVE' FOR UPDATE) x)")){p.setLong(1,targetAccount);time(p,2,clock.instant());p.setString(3,type.name());p.setString(4,hash(normalized));p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_identity_migration(migration_id,source_account_id,target_account_id,identity_type,value_hash,source_proof_hash,target_proof_hash,operator_id,reason,trace_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)")){p.setString(1,UUID.randomUUID().toString());p.setLong(2,sourceAccount);p.setLong(3,targetAccount);p.setString(4,type.name());p.setString(5,hash(normalized));p.setString(6,hash(sourceProof));p.setString(7,hash(targetProof));p.setLong(8,admin.operatorId);p.setString(9,admin.reason);p.setString(10,admin.traceId);time(p,11,clock.instant());p.executeUpdate();}revoke(c,sourceAccount,"IDENTITY_MIGRATED");revoke(c,targetAccount,"IDENTITY_MIGRATED");audit(c,sourceAccount,"IDENTITY_MIGRATED_OUT",type.name(),admin);audit(c,targetAccount,"IDENTITY_MIGRATED_IN",type.name(),admin);outbox(c,targetAccount,"account.identity.migrated",admin.traceId,"{\"sourceAccountId\":\""+sourceAccount+"\"}");complete(c,admin.requestId,"migrated");return null;});}

    private Segment segment(Connection c)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT digit_length,occupied_count,capacity,allocation_threshold_bps FROM aoo_display_id_segment WHERE status='ACTIVE' ORDER BY digit_length DESC LIMIT 1 FOR UPDATE");ResultSet r=p.executeQuery()){if(!r.next()){expand(c,6);return new Segment(6,BigInteger.ZERO,BigInteger.valueOf(900000),8500);}Segment s=new Segment(r.getInt(1),new BigInteger(r.getString(2)),new BigInteger(r.getString(3)),r.getInt(4));if(s.occupied.multiply(BigInteger.valueOf(10000)).compareTo(s.capacity.multiply(BigInteger.valueOf(s.threshold)))>=0){expand(c,s.digits+1);return segment(c);}return s;}}
    private void expand(Connection c,int digits)throws SQLException{BigInteger start=BigInteger.TEN.pow(digits-1),end=BigInteger.TEN.pow(digits).subtract(BigInteger.ONE),capacity=end.subtract(start).add(BigInteger.ONE);try(PreparedStatement p=c.prepareStatement("INSERT IGNORE INTO aoo_display_id_segment(digit_length,range_start,range_end,capacity,occupied_count,allocation_threshold_bps,status,updated_at) VALUES(?,?,?,?,0,8500,'ACTIVE',?)")){p.setInt(1,digits);p.setString(2,start.toString());p.setString(3,end.toString());p.setString(4,capacity.toString());time(p,5,clock.instant());p.executeUpdate();}}
    private void increment(Connection c,int digits)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE aoo_display_id_segment SET occupied_count=occupied_count+1,updated_at=? WHERE digit_length=?")){time(p,1,clock.instant());p.setInt(2,digits);p.executeUpdate();}}
    private String randomDecimal(int digits){StringBuilder v=new StringBuilder(digits);v.append(1+random.nextInt(9));for(int i=1;i<digits;i++)v.append(random.nextInt(10));return v.toString();}
    void insert(Connection c,Type type,String value,long accountId,boolean verified)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account_identity(identity_type,normalized_value,value_hash,account_id,verified,status,created_at,updated_at) VALUES(?,?,?,?,?,'ACTIVE',?,?)")){Instant now=clock.instant();p.setString(1,type.name());p.setString(2,value);p.setString(3,hash(value));p.setLong(4,accountId);p.setBoolean(5,verified);time(p,6,now);time(p,7,now);p.executeUpdate();}}
    private Identity active(Connection c,Type type,long accountId)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT normalized_value,verified,status FROM aoo_account_identity WHERE account_id=? AND identity_type=? AND status='ACTIVE'")){p.setLong(1,accountId);p.setString(2,type.name());try(ResultSet r=p.executeQuery()){return r.next()?new Identity(type,r.getString(1),accountId,r.getBoolean(2),r.getString(3)):null;}}}
    private Identity byHash(Connection c,Type type,String digest)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT normalized_value,account_id,verified,status FROM aoo_account_identity WHERE identity_type=? AND value_hash=? AND status='ACTIVE'")){p.setString(1,type.name());p.setString(2,digest);try(ResultSet r=p.executeQuery()){return r.next()?new Identity(type,r.getString(1),r.getLong(2),r.getBoolean(3),r.getString(4)):null;}}}
    private long resolveHash(Connection c,Type type,String digest)throws SQLException{Identity identity=byHash(c,type,digest);if(identity==null||!identity.verified)throw new NotFound("invalid credentials");return identity.accountId;}
    private void lockAccount(Connection c,long id)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT account_id FROM aoo_account WHERE account_id=? FOR UPDATE")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())throw new NotFound("account not found");}}}
    private void lockAccounts(Connection c,long a,long b)throws SQLException{lockAccount(c,Math.min(a,b));lockAccount(c,Math.max(a,b));}
    private void revoke(Connection c,long accountId,String reason)throws SQLException{Instant now=clock.instant();try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET auth_generation=auth_generation+1,updated_at=? WHERE account_id=?")){time(p,1,now);p.setLong(2,accountId);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_session SET revoked_at=?,revoke_reason=? WHERE account_id=? AND revoked_at IS NULL")){time(p,1,now);p.setString(2,reason);p.setLong(3,accountId);p.executeUpdate();}}
    private void history(Connection c,long accountId,String oldId,String newId,Long operator,String reason,String ip,String trace,Instant now)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_display_id_history(account_id,old_display_id,new_display_id,valid_from,valid_until,operator_id,reason,source_ip,trace_id) VALUES(?,?,?,?,NULL,?,?,?,?)")){p.setLong(1,accountId);p.setString(2,oldId);p.setString(3,newId);time(p,4,now);if(operator==null)p.setNull(5,Types.BIGINT);else p.setLong(5,operator);p.setString(6,reason);p.setString(7,ip);p.setString(8,trace);p.executeUpdate();}}
    private void audit(Connection c,long accountId,String action,String detail,AdminContext a)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account_audit(account_id,action_name,detail_value,source_ip,occurred_at) VALUES(?,?,?,?,?)")){p.setLong(1,accountId);p.setString(2,action);p.setString(3,detail+";operator="+a.operatorId+";trace="+a.traceId+";reason="+a.reason);p.setString(4,a.sourceIp);time(p,5,clock.instant());p.executeUpdate();}}
    private void outbox(Connection c,long accountId,String type,String trace,String payload)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_outbox(event_id,aggregate_type,aggregate_id,event_type,payload,created_at) VALUES(?,?,?,?,?,?)")){p.setString(1,UUID.randomUUID().toString());p.setString(2,"account");p.setLong(3,accountId);p.setString(4,type);p.setString(5,payload.substring(0,payload.length()-1)+",\"traceId\":\""+trace+"\"}");time(p,6,clock.instant());p.executeUpdate();}}
    private void dedupe(Connection c,String request)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT result_json FROM aoo_identity_admin_request WHERE request_id=? FOR UPDATE")){p.setString(1,request);try(ResultSet r=p.executeQuery()){if(r.next())throw new DuplicateRequest(r.getString(1));}}}
    private void complete(Connection c,String request,String result)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_identity_admin_request(request_id,result_json,completed_at) VALUES(?,?,?)")){p.setString(1,request);p.setString(2,"{\"status\":\""+result+"\"}");time(p,3,clock.instant());p.executeUpdate();}}
    private static void authorize(AdminContext a,String permission){if(!a.secondFactorVerified||!a.permissions.contains(permission))throw new Forbidden("high-risk permission and second factor required");}
    private static String normalize(Type type,String raw){String v=required(raw,"identity").strip();return switch(type){case DISPLAY_ID->{if(!v.matches("[1-9][0-9]{5,}"))throw new IllegalArgumentException("display ID must be at least six digits without leading zero");yield v;}case ALIAS->{String n=v.toLowerCase(Locale.ROOT);if(!n.matches("[a-z0-9]{1,64}"))throw new IllegalArgumentException("alias must be 1-64 letters or digits");yield n;}case PHONE->{String n=v.replace(" ","").replace("-","");if(!n.matches("\\+[1-9][0-9]{7,14}"))throw new IllegalArgumentException("phone must be verified E.164");yield n;}case WECHAT_UNION->{if(v.length()>191)throw new IllegalArgumentException("invalid unionId");yield v;}case WECHAT_OPEN->{if(!v.matches("[^:]{1,64}:[^:]{1,191}"))throw new IllegalArgumentException("wechat open identity must be appId:openId");yield v;}case TRUSTED_DEVICE->{if(v.length()>128)throw new IllegalArgumentException("invalid device");yield v;}};}
    private static String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static String required(String value,String name){if(value==null||value.isBlank())throw new IllegalArgumentException(name+" required");return value;}
    private static void time(PreparedStatement p,int i,Instant value)throws SQLException{p.setTimestamp(i,Timestamp.from(value));}
    private <T>T tx(Work<T> work){try(Connection c=source.getConnection()){boolean auto=c.getAutoCommit();c.setAutoCommit(false);try{T value=work.run(c);c.commit();return value;}catch(Exception e){c.rollback();if(e instanceof RuntimeException r)throw r;throw new IllegalStateException("identity persistence failed",e);}finally{c.setAutoCommit(auto);}}catch(SQLException e){throw new IllegalStateException("identity persistence unavailable",e);}}
    private record Segment(int digits,BigInteger occupied,BigInteger capacity,int threshold){}
    @FunctionalInterface private interface Work<T>{T run(Connection c)throws Exception;}
    public static final class Conflict extends IllegalStateException{public Conflict(String m){super(m);}}
    public static final class NotFound extends SecurityException{public NotFound(String m){super(m);}}
    public static final class Forbidden extends SecurityException{public Forbidden(String m){super(m);}}
    public static final class DuplicateRequest extends IllegalStateException{public DuplicateRequest(String result){super(result);}}
}
