package com.aoo.bcg.common.resource;

import java.io.InputStream;import java.io.OutputStream;import java.nio.file.*;import java.util.ArrayList;import java.util.Comparator;import java.util.List;import java.util.concurrent.atomic.AtomicBoolean;import java.util.zip.ZipEntry;import java.util.zip.ZipInputStream;

/** Request-scoped uploads, archives and replay staging; recursive cleanup is mandatory on success and failure. */
public final class TemporaryFileScope implements AutoCloseable{
 private final Path root;private final AtomicBoolean closed=new AtomicBoolean();
 public TemporaryFileScope(Path parent,String prefix){try{root=Files.createTempDirectory(parent,prefix);}catch(Exception error){throw new IllegalStateException("cannot create temporary file scope",error);}}
 public Path copyUpload(InputStream input,String name,long maximumBytes){if(maximumBytes<=0)throw new IllegalArgumentException("invalid upload bounds");Path target=SafePathResolver.fileName(root,name);StorageCapacityGuard.system().require(target,maximumBytes,StorageCapacityGuard.Domain.UPLOAD);copyBounded(input,target,maximumBytes);return target;}
 public List<Path> extractZip(InputStream input,int maximumEntries,long maximumExpandedBytes){if(maximumEntries<1||maximumExpandedBytes<1)throw new IllegalArgumentException("invalid archive bounds");List<Path> files=new ArrayList<>();long total=0;try(var zip=new ZipInputStream(input)){ZipEntry entry;while((entry=zip.getNextEntry())!=null){if(files.size()>=maximumEntries)throw new IllegalArgumentException("archive entry limit exceeded");Path target=SafePathResolver.relative(root,entry.getName());if(entry.isDirectory()){Files.createDirectories(target);continue;}Files.createDirectories(target.getParent());long remaining=maximumExpandedBytes-total;long written=copyBounded(zip,target,remaining);total=Math.addExact(total,written);files.add(target);zip.closeEntry();}}catch(RuntimeException error){throw error;}catch(Exception error){throw new IllegalStateException("archive extraction failed",error);}return List.copyOf(files);}
 public void publishAtomically(Path staged,Path destination){if(!staged.normalize().startsWith(root))throw new SecurityException("staged file is outside scope");try{StorageCapacityGuard.system().require(destination,Files.size(staged),StorageCapacityGuard.Domain.REPLAY);}catch(java.io.IOException error){throw new IllegalStateException("cannot inspect replay staging",error);}AtomicFilePublisher.publish(staged,destination,AtomicFilePublisher.sha256(staged));}
 private static long copyBounded(InputStream input,Path target,long maximumBytes){long total=0;byte[]buffer=new byte[8192];try(OutputStream output=Files.newOutputStream(target,StandardOpenOption.CREATE_NEW)){int read;while((read=input.read(buffer))>=0){total=Math.addExact(total,read);if(total>maximumBytes)throw new IllegalArgumentException("file size limit exceeded");output.write(buffer,0,read);}return total;}catch(RuntimeException error){try{Files.deleteIfExists(target);}catch(Exception cleanup){error.addSuppressed(cleanup);}throw error;}catch(Exception error){try{Files.deleteIfExists(target);}catch(Exception cleanup){error.addSuppressed(cleanup);}throw new IllegalStateException("bounded file copy failed",error);}}
 @Override public void close(){if(!closed.compareAndSet(false,true))return;try{if(Files.exists(root))try(var paths=Files.walk(root)){for(Path path:paths.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(path);}}catch(Exception error){throw new IllegalStateException("temporary file cleanup failed",error);}}
 public Path root(){return root;}
}
