package com.aoo.bcg.telemetry;
import com.fasterxml.jackson.databind.ObjectMapper;import javax.sql.DataSource;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.sql.*;import java.time.*;import java.util.*;
/** Durable ingestion and server-side risk evaluation. Client assertions are evidence only. */
public final class JdbcTelemetryRiskService {
 public record Receipt(String eventId,String status,Long riskEventId){}
 private static final Set<String> ALLOWED=Set.of("fps","frameTimeMs","memoryMb","batteryPct","crashCode","stackFingerprint","rttMs","packetLossPct","networkType","os","appVersion","modelClass","emulator","rooted","vpn","mockLocation","accuracyM","operation","sequenceGap");
 private final DataSource source;private final ObjectMapper json;private final Clock clock;
 public JdbcTelemetryRiskService(DataSource source,ObjectMapper json,Clock clock){this.source=Objects.requireNonNull(source);this.json=Objects.requireNonNull(json);this.clock=Objects.requireNonNull(clock);}
 public Receipt ingest(long playerId,TelemetrySignal s){validate(s);Instant now=clock.instant();try(var c=source.getConnection()){c.setAutoCommit(false);try{
   if(exists(c,playerId,s.eventId())){c.rollback();return new Receipt(s.eventId(),"DUPLICATE",null);}
   if(count(c,"SELECT COUNT(*) FROM telemetry_signal WHERE player_id=? AND received_at>=?",playerId,Timestamp.from(now.minusSeconds(60)))>=120){c.rollback();return new Receipt(s.eventId(),"RATE_LIMITED",null);}
   if(!sample(s)){c.rollback();return new Receipt(s.eventId(),"SAMPLED_OUT",null);}
   Map<String,Object> attrs=clip(s.attributes());String deviceHash=hashNullable(s.deviceId()),networkPrefix=networkPrefix(s.ipAddress()),geoCell=geoCell(s.latitude(),s.longitude());
   long signalId;try(var q=c.prepareStatement("INSERT INTO telemetry_signal(event_id,player_id,signal_kind,occurred_at,received_at,session_id,room_id,device_hash,network_prefix,geo_cell,attributes_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){q.setString(1,s.eventId());q.setLong(2,playerId);q.setString(3,s.kind().name());q.setTimestamp(4,Timestamp.from(s.occurredAt()));q.setTimestamp(5,Timestamp.from(now));q.setString(6,trim(s.sessionId(),64));if(s.roomId()==null)q.setNull(7,Types.BIGINT);else q.setLong(7,s.roomId());q.setString(8,deviceHash);q.setString(9,networkPrefix);q.setString(10,geoCell);q.setString(11,json.writeValueAsString(attrs));q.executeUpdate();try(var keys=q.getGeneratedKeys()){if(!keys.next())throw new SQLException("signal id unavailable");signalId=keys.getLong(1);}}
   List<String> reasons=new ArrayList<>();int score=0;
   if(Boolean.TRUE.equals(attrs.get("emulator"))){score+=25;reasons.add("EMULATOR_ASSERTION");}if(Boolean.TRUE.equals(attrs.get("rooted"))){score+=25;reasons.add("ROOTED_DEVICE_ASSERTION");}if(Boolean.TRUE.equals(attrs.get("mockLocation"))){score+=35;reasons.add("MOCK_LOCATION_ASSERTION");}
   if(s.kind()==TelemetrySignal.Kind.OPERATION&&count(c,"SELECT COUNT(*) FROM telemetry_signal WHERE player_id=? AND signal_kind='OPERATION' AND received_at>=?",playerId,Timestamp.from(now.minusSeconds(60)))>60){score+=35;reasons.add("OPERATION_FREQUENCY");}
   if(s.roomId()!=null&&deviceHash!=null&&count(c,"SELECT COUNT(DISTINCT player_id) FROM telemetry_signal WHERE room_id=? AND device_hash=? AND received_at>=?",s.roomId(),deviceHash,Timestamp.from(now.minus(Duration.ofHours(24))))>1){score+=55;reasons.add("COSEAT_DEVICE_ASSOCIATION");}
   if(s.roomId()!=null&&geoCell!=null&&count(c,"SELECT COUNT(DISTINCT player_id) FROM telemetry_signal WHERE room_id=? AND geo_cell=? AND received_at>=?",s.roomId(),geoCell,Timestamp.from(now.minus(Duration.ofHours(24))))>2){score+=30;reasons.add("COSEAT_LOCATION_ASSOCIATION");}
   Long risk=null;if(score>=35){try(var q=c.prepareStatement("INSERT INTO risk_event(player_id,room_id,source_signal_id,risk_score,reasons_json,status,created_at) VALUES(?,?,?,?,?,'PENDING_REVIEW',?)",Statement.RETURN_GENERATED_KEYS)){q.setLong(1,playerId);if(s.roomId()==null)q.setNull(2,Types.BIGINT);else q.setLong(2,s.roomId());q.setLong(3,signalId);q.setInt(4,Math.min(score,100));q.setString(5,json.writeValueAsString(reasons));q.setTimestamp(6,Timestamp.from(now));q.executeUpdate();try(var keys=q.getGeneratedKeys()){keys.next();risk=keys.getLong(1);}}try(var q=c.prepareStatement("INSERT INTO risk_review_directive(risk_event_id,directive_type,status,created_at) VALUES(?,?,'OPEN',?)")){q.setLong(1,risk);q.setString(2,s.roomId()==null?"REVIEW_ACCOUNT":"REVIEW_TABLE");q.setTimestamp(3,Timestamp.from(now));q.executeUpdate();}}
   c.commit();return new Receipt(s.eventId(),"ACCEPTED",risk);
  }catch(Exception x){c.rollback();throw x;}}catch(Exception x){if(isDuplicate(x))return new Receipt(s.eventId(),"DUPLICATE",null);throw new IllegalStateException("telemetry persistence unavailable",x);}}
 public List<Map<String,Object>> review(long after,int limit){limit=Math.max(1,Math.min(100,limit));try(var c=source.getConnection();var q=c.prepareStatement("SELECT d.directive_id,d.risk_event_id,d.directive_type,d.status,r.player_id,r.room_id,r.risk_score,r.reasons_json,d.created_at FROM risk_review_directive d JOIN risk_event r ON r.risk_event_id=d.risk_event_id WHERE d.directive_id>? ORDER BY d.directive_id LIMIT ?")){q.setLong(1,after);q.setInt(2,limit);try(var rs=q.executeQuery()){List<Map<String,Object>> out=new ArrayList<>();while(rs.next()){Map<String,Object> v=new LinkedHashMap<>();v.put("directiveId",rs.getLong(1));v.put("riskEventId",rs.getLong(2));v.put("type",rs.getString(3));v.put("status",rs.getString(4));v.put("playerId",rs.getLong(5));v.put("roomId",rs.getObject(6));v.put("score",rs.getInt(7));v.put("reasons",json.readValue(rs.getString(8),List.class));v.put("createdAt",rs.getTimestamp(9).toInstant());out.add(v);}return List.copyOf(out);}}catch(Exception x){throw new IllegalStateException("risk review unavailable",x);}}
 private boolean exists(Connection c,long p,String e)throws SQLException{try(var q=c.prepareStatement("SELECT 1 FROM telemetry_signal WHERE player_id=? AND event_id=?")){q.setLong(1,p);q.setString(2,e);try(var r=q.executeQuery()){return r.next();}}}private static long count(Connection c,String sql,Object...p)throws SQLException{try(var q=c.prepareStatement(sql)){for(int i=0;i<p.length;i++)q.setObject(i+1,p[i]);try(var r=q.executeQuery()){r.next();return r.getLong(1);}}}
 private static void validate(TelemetrySignal s){if(s==null||s.eventId()==null||!s.eventId().matches("[A-Za-z0-9_-]{8,64}"))throw new IllegalArgumentException("eventId invalid");if(s.kind()==null||s.occurredAt()==null)throw new IllegalArgumentException("kind and occurredAt required");if(s.attributes()!=null&&s.attributes().size()>40)throw new IllegalArgumentException("too many attributes");}private static boolean sample(TelemetrySignal s){int rate=s.kind()==TelemetrySignal.Kind.PERFORMANCE?10:s.kind()==TelemetrySignal.Kind.NETWORK?25:100;return Math.floorMod(s.eventId().hashCode(),100)<rate;}private static Map<String,Object> clip(Map<String,Object> a){if(a==null)return Map.of();Map<String,Object> out=new TreeMap<>();a.forEach((k,v)->{if(ALLOWED.contains(k)&&(v instanceof Number||v instanceof Boolean||v instanceof String))out.put(k,v instanceof String?trim((String)v,128):v);});return Map.copyOf(out);}private static String trim(String s,int n){if(s==null)return null;String v=s.replaceAll("[\\p{Cntrl}]"," ").strip();return v.length()>n?v.substring(0,n):v;}private static String hashNullable(String s){if(s==null||s.isBlank())return null;try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception x){throw new IllegalStateException(x);}}private static String networkPrefix(String ip){if(ip==null)return null;String v=ip.strip();if(v.matches("\\d{1,3}(\\.\\d{1,3}){3}")){String[]p=v.split("\\.");return p[0]+"."+p[1]+"."+p[2]+".0/24";}return v.contains(":")?v.substring(0,Math.min(v.length(),19))+"::/64":null;}private static String geoCell(Double lat,Double lon){if(lat==null||lon==null||lat< -90||lat>90||lon< -180||lon>180)return null;return String.format(Locale.ROOT,"%.2f,%.2f",lat,lon);}private static boolean isDuplicate(Exception x){for(Throwable t=x;t!=null;t=t.getCause())if(t instanceof SQLException s&&("23505".equals(s.getSQLState())||"23000".equals(s.getSQLState())))return true;return false;}
}
