package com.aoo.bcg.bootstrap;
import com.aoo.bcg.billing.JdbcBillingService;import com.aoo.bcg.hall.room.RoomCreateSaga;import javax.sql.DataSource;import java.sql.*;import java.time.Clock;import java.util.*;import java.util.function.LongSupplier;
final class JdbcRoomSagaBillingPort implements RoomCreateSaga.BillingPort{
 private final DataSource source;private final JdbcBillingService billing;JdbcRoomSagaBillingPort(DataSource source,LongSupplier ids,Clock clock){this.source=Objects.requireNonNull(source);this.billing=new JdbcBillingService(source,ids,clock);}
 public void reserve(RoomCreateSaga.Command c){Policy p=policy(c);if(!"OWNER".equals(p.payer())&&p.amount()>0)throw new IllegalStateException("non-owner room charging requires participant billing");if(p.amount()>0)billing.debit("ROOM_CREATE_RESERVE:"+c.requestId(),c.accountId(),p.currency(),p.amount(),"ROOM_CREATE_RESERVE");try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("INSERT INTO aoo_room_billing_reservation(request_id,account_id,room_id,currency_code,amount,state,created_at,updated_at) VALUES(?,?,?,?,?,'RESERVED',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE request_id=request_id")){s.setString(1,c.requestId());s.setLong(2,c.accountId());s.setLong(3,c.roomId());s.setString(4,p.currency());s.setLong(5,p.amount());s.executeUpdate();}catch(Exception e){throw new IllegalStateException("room billing reservation persistence failed",e);}Reservation r=reservation(c.requestId());if(r==null||r.account()!=c.accountId()||r.room()!=c.roomId()||!r.currency().equals(p.currency())||r.amount()!=p.amount())throw new IllegalArgumentException("requestId reused with different billing");}
 public void confirm(RoomCreateSaga.Command c){try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_billing_reservation SET state='CONFIRMED',updated_at=CURRENT_TIMESTAMP(3) WHERE request_id=? AND state IN('RESERVED','CONFIRMED')")){s.setString(1,c.requestId());if(s.executeUpdate()!=1)throw new IllegalStateException("room billing reservation cannot be confirmed");}catch(Exception e){throw e instanceof RuntimeException r?r:new IllegalStateException(e);}}
 public void release(RoomCreateSaga.Command c){Reservation r=reservation(c.requestId());if(r==null||"RELEASED".equals(r.state()))return;if(r.amount()>0)billing.credit("ROOM_CREATE_RELEASE:"+c.requestId(),c.accountId(),r.currency(),r.amount(),"ROOM_CREATE_RELEASE");try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_billing_reservation SET state='RELEASED',updated_at=CURRENT_TIMESTAMP(3) WHERE request_id=? AND state<>'RELEASED'")){s.setString(1,c.requestId());s.executeUpdate();}catch(Exception e){throw new IllegalStateException("room billing release persistence failed",e);}}
 private Policy policy(RoomCreateSaga.Command c){int rounds=positiveInteger(c.rules(),"roundCount"),players=positiveInteger(c.rules(),"playerCount");String payer=requiredPayer(c.rules().get("payerMode"));String sql="SELECT payer_mode,currency_code,cost_minor FROM aoo_room_cost_policy WHERE game_id=? AND play_version=? AND status='ACTIVE' AND round_count=? AND player_count=? AND payer_mode=?";try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement(sql)){s.setInt(1,c.gameId());s.setString(2,c.playVersion());s.setInt(3,rounds);s.setInt(4,players);s.setString(5,payer);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("active room cost policy is missing");Policy p=new Policy(r.getString(1),r.getString(2),r.getLong(3));if(r.next())throw new IllegalStateException("room cost policy is duplicated");return p;}}catch(Exception e){throw e instanceof RuntimeException r?r:new IllegalStateException("room cost policy lookup failed",e);}}
 private Reservation reservation(String id){try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("SELECT account_id,room_id,currency_code,amount,state FROM aoo_room_billing_reservation WHERE request_id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){return r.next()?new Reservation(r.getLong(1),r.getLong(2),r.getString(3),r.getLong(4),r.getString(5)):null;}}catch(Exception e){throw new IllegalStateException("room billing lookup failed",e);}}
 private static int positiveInteger(Map<String,Object>rules,String key){Object value=rules.get(key);if(!(value instanceof Number number)||number.intValue()<=0)throw new IllegalArgumentException(key+" is required");return number.intValue();}
 private static String requiredPayer(Object value){
  // 付费方式是平台治理而非玩法 Excel 字段。个人房未显式配置时统一由房主支付；
  // 非空值仍严格匹配已发布费用策略，客户端无法借此伪造免费或跨支付模式。
  if(value==null)return "OWNER";
  if(!(value instanceof String payer)||payer.isBlank())throw new IllegalArgumentException("payerMode is invalid");
  return payer.toUpperCase(Locale.ROOT);
 }
 private record Policy(String payer,String currency,long amount){}private record Reservation(long account,long room,String currency,long amount,String state){}
}
