package com.aoo.bcg.bootstrap;
import com.aoo.bcg.billing.JdbcBillingService;import com.aoo.bcg.hall.room.RoomCreateSaga;import com.fasterxml.jackson.databind.ObjectMapper;import javax.sql.DataSource;import java.sql.*;import java.time.Clock;import java.util.*;import java.util.function.LongSupplier;
final class JdbcRoomSagaBillingPort implements RoomCreateSaga.BillingPort{
 private final DataSource source;private final JdbcBillingService billing;private final ObjectMapper json=new ObjectMapper().findAndRegisterModules();JdbcRoomSagaBillingPort(DataSource source,LongSupplier ids,Clock clock){this.source=Objects.requireNonNull(source);this.billing=new JdbcBillingService(source,ids,clock);}
 public void reserve(RoomCreateSaga.Command c){Policy p=policy(c);if(!"OWNER".equals(p.payer())&&p.amount()>0)throw new IllegalStateException("non-owner room charging requires participant billing");if(p.amount()>0)billing.debit("ROOM_CREATE_RESERVE:"+c.requestId(),c.accountId(),p.currency(),p.amount(),"ROOM_CREATE_RESERVE");try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("INSERT INTO aoo_room_billing_reservation(request_id,account_id,room_id,currency_code,amount,state,created_at,updated_at) VALUES(?,?,?,?,?,'RESERVED',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE request_id=request_id")){s.setString(1,c.requestId());s.setLong(2,c.accountId());s.setLong(3,c.roomId());s.setString(4,p.currency());s.setLong(5,p.amount());s.executeUpdate();}catch(Exception e){throw new IllegalStateException("room billing reservation persistence failed",e);}Reservation r=reservation(c.requestId());if(r==null||r.account()!=c.accountId()||r.room()!=c.roomId()||!r.currency().equals(p.currency())||r.amount()!=p.amount())throw new IllegalArgumentException("requestId reused with different billing");}
 public void confirm(RoomCreateSaga.Command c){try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_billing_reservation SET state='CONFIRMED',updated_at=CURRENT_TIMESTAMP(3) WHERE request_id=? AND state IN('RESERVED','CONFIRMED')")){s.setString(1,c.requestId());if(s.executeUpdate()!=1)throw new IllegalStateException("room billing reservation cannot be confirmed");}catch(Exception e){throw e instanceof RuntimeException r?r:new IllegalStateException(e);}}
 public void release(RoomCreateSaga.Command c){Reservation r=reservation(c.requestId());if(r==null||"RELEASED".equals(r.state()))return;if(r.amount()>0)billing.credit("ROOM_CREATE_RELEASE:"+c.requestId(),c.accountId(),r.currency(),r.amount(),"ROOM_CREATE_RELEASE");try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_billing_reservation SET state='RELEASED',updated_at=CURRENT_TIMESTAMP(3) WHERE request_id=? AND state<>'RELEASED'")){s.setString(1,c.requestId());s.executeUpdate();}catch(Exception e){throw new IllegalStateException("room billing release persistence failed",e);}}
 private Policy policy(RoomCreateSaga.Command c){BillingDimension dimension=billingDimension(c);int players=dimension.players();String payer=requiredPayer(valueOrDefault(c.rules(),dimension.defaults(),"payerMode"));String sql="SELECT payer_mode,currency_code,cost_minor FROM aoo_room_cost_policy WHERE game_id=? AND play_version=? AND region_code=? AND status='ACTIVE' AND measure_kind=? AND measure_value=? AND player_count=? AND payer_mode=?";try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement(sql)){s.setInt(1,c.gameId());s.setString(2,c.playVersion());s.setString(3,dimension.region());s.setString(4,dimension.kind().name());s.setInt(5,dimension.value());s.setInt(6,players);s.setString(7,payer);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("active room cost policy is missing for "+dimension.kind()+"="+dimension.value());Policy p=new Policy(r.getString(1),r.getString(2),r.getLong(3));if(r.next())throw new IllegalStateException("room cost policy is duplicated");return p;}}catch(Exception e){throw e instanceof RuntimeException r?r:new IllegalStateException("room cost policy lookup failed",e);}}
 private BillingDimension billingDimension(RoomCreateSaga.Command c){String sql="SELECT a.region_code,i.rule_validator FROM aoo_compiled_index_active a JOIN aoo_compiled_room_create_index i ON i.game_id=a.game_id AND i.region_code=a.region_code AND i.play_version=a.play_version AND i.index_generation=a.index_generation WHERE a.game_id=? AND a.play_version=? AND i.lifecycle_state='ACTIVE' ORDER BY CASE WHEN a.region_code='GLOBAL' THEN 0 ELSE 1 END LIMIT 1";try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement(sql)){s.setInt(1,c.gameId());s.setString(2,c.playVersion());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("active room rule schema is missing");Map<String,Object> schema=json.readValue(r.getString(2),Map.class),defaults=defaults(schema);Object publishedKind=schema.get("roomMeasureKind");MeasureKind kind=publishedKind==null?inferMeasureKind(defaults):MeasureKind.valueOf(Objects.toString(publishedKind));String key=kind==MeasureKind.DURATION_MINUTES?"roomDurationMinutes":"roundCount";if(kind==MeasureKind.DURATION_MINUTES&&containsAny(c.rules(),"roundCount","rounds","totalRounds"))throw new IllegalArgumentException("roundCount is not allowed for duration rooms");if(kind==MeasureKind.ROUND_COUNT&&c.rules().containsKey("roomDurationMinutes"))throw new IllegalArgumentException("roomDurationMinutes is not allowed for round-count rooms");int value=positiveInteger(c.rules(),defaults,key,kind==MeasureKind.ROUND_COUNT?new String[]{"rounds","totalRounds"}:new String[0]);int players=positiveInteger(c.rules(),defaults,"playerCount","maxPlayers","seatLimit");return new BillingDimension(r.getString(1),kind,value,players,defaults);}}catch(Exception e){throw e instanceof RuntimeException runtime?runtime:new IllegalStateException("room billing dimension lookup failed",e);}}
 private static MeasureKind inferMeasureKind(Map<String,Object> defaults){boolean duration=defaults.containsKey("roomDurationMinutes"),rounds=containsAny(defaults,"roundCount","rounds","totalRounds");if(duration==rounds)throw new IllegalStateException("published room schema must define exactly one billing measure");return duration?MeasureKind.DURATION_MINUTES:MeasureKind.ROUND_COUNT;}
 private static Map<String,Object> defaults(Map<String,Object> schema){Object value=schema.get("fields");if(!(value instanceof List<?> fields))throw new IllegalStateException("published room schema fields are missing");Map<String,Object> out=new HashMap<>();for(Object item:fields)if(item instanceof Map<?,?> field&&field.get("key") instanceof String key&&field.containsKey("defaultValue"))out.put(key,field.get("defaultValue"));return out;}
 private static Object valueOrDefault(Map<String,Object> rules,Map<String,Object> defaults,String key){return rules.containsKey(key)?rules.get(key):defaults.get(key);}
 private static boolean containsAny(Map<String,?> values,String...keys){for(String key:keys)if(values.containsKey(key))return true;return false;}
 private Reservation reservation(String id){try(Connection x=source.getConnection();PreparedStatement s=x.prepareStatement("SELECT account_id,room_id,currency_code,amount,state FROM aoo_room_billing_reservation WHERE request_id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){return r.next()?new Reservation(r.getLong(1),r.getLong(2),r.getString(3),r.getLong(4),r.getString(5)):null;}}catch(Exception e){throw new IllegalStateException("room billing lookup failed",e);}}
 private static int positiveInteger(Map<String,Object>rules,Map<String,Object>defaults,String canonical,String...aliases){Object value=valueOrDefault(rules,defaults,canonical);if(value==null)for(String alias:aliases)if((value=valueOrDefault(rules,defaults,alias))!=null)break;if(!(value instanceof Number number)||number.intValue()<=0)throw new IllegalArgumentException(canonical+" is required");return number.intValue();}
 private static String requiredPayer(Object value){
  // 付费方式是平台治理而非玩法 Excel 字段。个人房未显式配置时统一由房主支付；
  // 非空值仍严格匹配已发布费用策略，客户端无法借此伪造免费或跨支付模式。
  if(value==null)return "OWNER";
  if(!(value instanceof String payer)||payer.isBlank())throw new IllegalArgumentException("payerMode is invalid");
  return payer.toUpperCase(Locale.ROOT);
 }
 private enum MeasureKind{ROUND_COUNT,DURATION_MINUTES}private record BillingDimension(String region,MeasureKind kind,int value,int players,Map<String,Object>defaults){}private record Policy(String payer,String currency,long amount){}private record Reservation(long account,long room,String currency,long amount,String state){}
}
