package com.aoo.bcg.mahjong;

import com.aoo.bcg.gamespi.*;
import com.aoo.bcg.gamespi.time.*;
import java.util.*;
import java.util.stream.Collectors;

/** One catalog-routed state machine shared by the five Mahjong gameplay families. */
final class CatalogMahjongFamilySession implements AuthoritativeGameSession {
    private final MahjongRegionRuntimeProfile profile;private final String version;private final Map<String,Object> createRules;
    private final ProfiledMahjongRuleFamily family;private final MahjongAuthoritativeSession core;private final List<Object> events=new ArrayList<>();private final int[]rise;private final boolean[]ting;private String phase="LOBBY";private long wrapperVersion;
    CatalogMahjongFamilySession(long room,long owner,RulePayload rules,MahjongRegionRuntimeProfile profile,String version){this.profile=profile;this.version=version;this.createRules=validated(rules.asMap(),profile);this.family=new ProfiledMahjongRuleFamily(profile);int seats=number(createRules,"playerNum",4);long seed=longNumber(createRules,"shuffleSeed",room);this.core=new MahjongAuthoritativeSession(room,owner,seats,seed==0?room:seed,family,version);this.rise=new int[seats];this.ting=new boolean[seats];}
    private CatalogMahjongFamilySession(MahjongAuthoritativeSession core,Map<String,Object> rules,MahjongRegionRuntimeProfile profile,String version){this.core=core;this.createRules=rules;this.profile=profile;this.version=version;this.family=new ProfiledMahjongRuleFamily(profile);int seats=number(rules,"playerNum",4);this.rise=new int[seats];this.ting=new boolean[seats];}
    public synchronized GameCommandResult execute(GameCommandRequest request){String dispatch="mahjong."+profile.code()+".dispatch";if(!dispatch.equals(request.msgId()))throw new IllegalArgumentException("Mahjong catalog dispatch required");Map<String,Object>body=request.body().asMap(),payload=mapOrEmpty(body.get("payload"));String action=String.valueOf(body.getOrDefault("action","state"));if(isBozhou()&&(action.equals("zhangZhuang")||action.equals("CBZMJZhangZhuang"))){chooseDealer(request.seatId(),number(payload,"value",0));record(action);return response(request);}if(profile.code().equals("bzqzmj")&&action.equals("baoTing")){if(!phase.equals("PLAYING"))throw new IllegalStateException("bao-ting disabled");ting[request.seatId()]=true;record(action);return response(request);}String op=normalize(action);if(phase.equals("WAITING_EX")&&!op.equals("state"))throw new IllegalStateException("WaitingEx dealer choice required");Map<String,Object>authorityBody=new LinkedHashMap<>(payload);core.execute(new GameCommandRequest("mahjong."+profile.code()+"."+op+"_req",request.requestId(),request.sequence(),request.roomId(),request.roundNo(),request.playVersion(),request.authenticatedUserId(),request.seatId(),authorityBody));if(op.equals("start"))phase=isBozhou()&&dealerChoiceEnabled()?"WAITING_EX":"PLAYING";if(!op.equals("state"))record(op);return response(request);}
    private String normalize(String action){if(profile.code().equals("bzmj"))return switch(action){case"state","reconnect","CBZMJGetRoomInfo"->"state";case"join","CBZMJEnterRoom"->"join";case"ready","CBZMJReadyRoom"->"ready";case"start","CBZMJStartGame"->"start";case"discard","CBZMJOutCard"->"discard";case"draw","chi","peng","gang","hu","pass"->action;default->throw new IllegalArgumentException("unsupported bzmj action: "+action);};String op=action.equals("reconnect")?"state":action;if(!Set.of("state","join","ready","start","draw","discard","chi","peng","gang","hu","pass").contains(op))throw new IllegalArgumentException("unsupported "+profile.code()+" action: "+action);return op;}
    private boolean isBozhou(){return profile.code().equals("bzmj")||profile.code().equals("bzqzmj");}private boolean dealerChoiceEnabled(){Object z=createRules.get("zhangzhuang");if(z instanceof Number n&&n.intValue()>=0)return true;Object options=createRules.get("kexuanwanfa");return options instanceof Collection<?>c&&c.stream().anyMatch(v->Set.of("0","ZhangZhuang").contains(String.valueOf(v)));}private void chooseDealer(int seat,int value){if(!phase.equals("WAITING_EX")||seat!=0)throw new IllegalStateException("dealer-only zhang-zhuang choice");int fixed=number(createRules,"zhangzhuang",0),limit=fixed==0?rise[0]+1:fixed;if((value!=0&&value!=rise[0]+1)||value>limit)throw new IllegalArgumentException("invalid zhang-zhuang value");if(value>0)rise[0]=value;phase="PLAYING";}private void record(String op){wrapperVersion++;events.add(Map.of("version",stateVersion(),"op",op,"after",authoritativeState()));}private GameCommandResult response(GameCommandRequest request){return new GameCommandResult("mahjong."+profile.code()+".response",request.requestId(),viewFor(Long.parseLong(request.authenticatedUserId()))).withAuthorityMetadata(stateVersion(),stateVersion());}
    public synchronized Map<String,Object>viewFor(long viewer){Map<String,Object>out=new LinkedHashMap<>(core.viewFor(viewer));out.put("gameCode",profile.code());out.put("gameplayFamily",profile.family());out.put("runtimeArchetype",profile.archetype());out.put("regionConfig",profile.region());out.put("ruleComponents",profile.orderedRuleComponents());out.put("lifecycleComponents",profile.orderedLifecycleComponents());out.put("createRules",createRules);out.put("phase",phase);out.put("stateVersion",stateVersion());if(isBozhou()){out.put("zhangZhuang",Arrays.stream(rise).boxed().toList());out.put("wallReserve",14);out.put("wildcard",47);}if(profile.code().equals("bzqzmj")){List<Boolean>x=new ArrayList<>();for(boolean b:ting)x.add(b);out.put("baoTing",List.copyOf(x));}return Map.copyOf(out);}
    public synchronized Map<String,Object>authoritativeState(){Map<String,Object>out=new LinkedHashMap<>();out.put("schemaVersion",1);out.put("gameCode",profile.code());out.put("gameplayFamily",profile.family());out.put("runtimeArchetype",profile.archetype());out.put("regionConfig",profile.region());out.put("ruleComponents",profile.orderedRuleComponents());out.put("lifecycleComponents",profile.orderedLifecycleComponents());out.put("createRules",createRules);out.put("phase",phase);if(isBozhou()){out.put("zhangZhuang",Arrays.stream(rise).boxed().toList());List<Boolean>x=new ArrayList<>();for(boolean b:ting)x.add(b);out.put("baoTing",List.copyOf(x));}out.put("wrapperVersion",wrapperVersion);out.put("stateVersion",stateVersion());out.put("mahjongAuthority",core.authoritativeState());return Map.copyOf(out);}
    public long stateVersion(){return core.stateVersion()+wrapperVersion;}List<Object>recordedEvents(){return List.copyOf(events);}public OperationDeadline operationDeadline(){return core.operationDeadline();}public OperationDeadlineArbiter deadlineArbiter(){return core.deadlineArbiter();}public List<String>invariantViolations(){return core.invariantViolations();}public SettlementPayload settlement(int round,String requestedVersion){SettlementPayload base=core.settlement(round,requestedVersion);long unit=Math.min(MahjongRegionRulePolicies.baseUnit(createRules),MahjongRegionRulePolicies.scoreCap(createRules));Map<Long,Long>scaled=new LinkedHashMap<>();base.scoreDelta().forEach((player,delta)->scaled.put(player,Math.multiplyExact(delta,unit)));return new SettlementPayload(base.roomId(),base.roundNo(),base.playVersion(),scaled);}
    static StatePayload replay(StatePayload base,List<Object>ordered){Map<String,Object>current=new LinkedHashMap<>(base.asMap());long prior=((Number)current.get("stateVersion")).longValue();for(Object raw:ordered){Map<String,Object>after=map(map(raw).get("after"));long next=((Number)after.get("stateVersion")).longValue();if(next<=prior)throw new IllegalArgumentException("Mahjong family replay order/gap");current=new LinkedHashMap<>(after);prior=next;}return StatePayload.copyOf(current);}
    static CatalogMahjongFamilySession restore(Map<String,Object>state,MahjongRegionRuntimeProfile profile,String version){if(!profile.code().equals(String.valueOf(state.get("gameCode"))))throw new IllegalArgumentException("profile/state mismatch");Map<String,Object>rules=Map.copyOf(map(state.get("createRules")));ProfiledMahjongRuleFamily family=new ProfiledMahjongRuleFamily(profile);CatalogMahjongFamilySession out=new CatalogMahjongFamilySession(MahjongAuthoritativeSession.restore(restorable(map(state.get("mahjongAuthority"))),family),rules,profile,version);out.phase=String.valueOf(state.getOrDefault("phase","LOBBY"));if(state.get("zhangZhuang")instanceof List<?>r)for(int i=0;i<r.size();i++)out.rise[i]=((Number)r.get(i)).intValue();if(state.get("baoTing")instanceof List<?>t)for(int i=0;i<t.size();i++)out.ting[i]=Boolean.TRUE.equals(t.get(i));out.wrapperVersion=((Number)state.getOrDefault("wrapperVersion",0)).longValue();return out;}
    private static Map<String,Object>validated(Map<String,Object>raw,MahjongRegionRuntimeProfile profile){Map<String,Object>out=new LinkedHashMap<>(raw);int seats=number(out,"playerNum",4);if(seats<2||seats>4)throw new IllegalArgumentException("playerNum must be 2..4");out.putIfAbsent("playerNum",seats);out.putIfAbsent("shuffleSeed",0L);out.put("configSchemaHash",profile.configSchemaHash());return Map.copyOf(out);}
    private static int number(Map<String,Object>map,String key,int fallback){return map.get(key)instanceof Number n?n.intValue():fallback;}private static long longNumber(Map<String,Object>map,String key,long fallback){return map.get(key)instanceof Number n?n.longValue():fallback;}private static Map<String,Object>mapOrEmpty(Object value){return value instanceof Map<?,?>?map(value):Map.of();}private static Map<String,Object>map(Object value){if(!(value instanceof Map<?,?>source))throw new IllegalArgumentException("map required");Map<String,Object>out=new LinkedHashMap<>();source.forEach((k,v)->out.put(String.valueOf(k),v));return out;}
    private static Map<String,Object>restorable(Map<String,Object>saved){Map<String,Object>out=new LinkedHashMap<>(saved);if(saved.get("openingReplacements")instanceof List<?>items)out.put("openingReplacements",items.stream().map(item->item instanceof MahjongRegionalRules.ReplacementEvent event?Map.of("seat",event.seat(),"flowerTile",event.flowerTile(),"replacementTile",event.replacementTile()):item).toList());if(saved.get("state")instanceof MahjongState state){Map<String,Object>s=new LinkedHashMap<>();s.put("wall",state.wall());s.put("hands",state.hands());s.put("currentSeat",state.currentSeat());s.put("currentSeatHasDrawn",state.currentSeatHasDrawn());s.put("lastDiscard",state.lastDiscard());s.put("lastDiscardSeat",state.lastDiscardSeat());s.put("window",Map.of("candidates",state.window().candidates().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey,e->e.getValue().stream().map(Enum::name).toList()))));s.put("finished",state.finished());s.put("winnerSeat",state.winnerSeat());out.put("state",s);}return out;}
}
