package com.aoo.bcg.mahjong;

import com.aoo.bcg.gamespi.AuthoritativeGameSession;
import com.aoo.bcg.gamespi.GameCommandRequest;
import com.aoo.bcg.gamespi.GameCommandResult;
import com.aoo.bcg.gamespi.SettlementPayload;
import com.aoo.bcg.common.random.SeededGameRandomSource;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.time.Duration;
import com.aoo.bcg.gamespi.time.AuthoritativeTimeSource;
import com.aoo.bcg.gamespi.time.OperationDeadline;
import com.aoo.bcg.gamespi.time.OperationDeadlineArbiter;

/** Unified Gateway authority for Mahjong providers during legacy-runtime migration. */
public final class MahjongAuthoritativeSession implements AuthoritativeGameSession {
    private final long roomId, ownerId; private final int seatLimit; private final MahjongRuleFamily family; private final long seed; private final String playVersion; private final MahjongTileSet tileSet;
    private final Map<Integer,Long> players=new LinkedHashMap<>(); private final java.util.Set<Integer> readySeats=new java.util.LinkedHashSet<>(); private MahjongState state;
    private MahjongRegionalRules.SettlementDetail lastSettlementDetail;
    private List<Integer> openingFlowers=List.of();
    private List<MahjongRegionalRules.ReplacementEvent> openingReplacements=List.of();
    private long stateVersion;
    private final AuthoritativeTimeSource time=AuthoritativeTimeSource.systemUtc(); private final Duration operationTimeout=Duration.ofSeconds(20); private OperationDeadline operationDeadline=OperationDeadline.none(); private final OperationDeadlineArbiter deadlineArbiter=new OperationDeadlineArbiter();
    public MahjongAuthoritativeSession(long roomId,long ownerId,int seatLimit,long seed,MahjongRuleFamily family){this(roomId,ownerId,seatLimit,seed,family,"v1");}
    public MahjongAuthoritativeSession(long roomId,long ownerId,int seatLimit,long seed,MahjongRuleFamily family,String playVersion){if(roomId<=0||ownerId<=0||seatLimit<2||seatLimit>4||playVersion==null||playVersion.isBlank())throw new IllegalArgumentException("invalid mahjong session");this.roomId=roomId;this.ownerId=ownerId;this.seatLimit=seatLimit;this.seed=seed;this.family=java.util.Objects.requireNonNull(family);this.playVersion=playVersion;this.tileSet=family.tileSet(playVersion);}
    public static MahjongAuthoritativeSession restore(Map<String,Object> saved,MahjongRuleFamily family){long room=longValue(saved.get("roomId"));long owner=longValue(saved.get("ownerId"));long seed=longValue(saved.get("seed"));Map<Integer,Long> restoredPlayers=longMap(saved.get("players"));int limit=Math.max(2,number(saved,"seatLimit",Math.max(2,restoredPlayers.size())));String version=String.valueOf(saved.getOrDefault("playVersion","v1"));MahjongAuthoritativeSession session=new MahjongAuthoritativeSession(room,owner,limit,seed,family,version);session.players.putAll(restoredPlayers);session.readySeats.addAll(numbers(saved.get("readySeats")));Object raw=saved.get("state");if(raw instanceof Map<?,?> map)session.state=restoreState(map);session.stateVersion=saved.get("stateVersion")instanceof Number n?n.longValue():0;session.openingFlowers=numbers(saved.get("openingFlowers"));session.openingReplacements=restoreReplacements(saved.get("openingReplacements"));session.operationDeadline=OperationDeadline.from(saved.get("operationDeadline"));Object detail=saved.get("settlementDetail");if(detail instanceof Map<?,?>map)session.lastSettlementDetail=restoreSettlementDetail(map);return com.aoo.bcg.gamespi.fsm.RestoredAuthorityValidator.requireConsistent(session);}
    @Override public synchronized GameCommandResult execute(GameCommandRequest r){if(r.roomId()!=roomId||!playVersion.equals(r.playVersion()))throw new IllegalArgumentException("command roomId/playVersion mismatch");long player=player(r.authenticatedUserId());Map<String,Object> body;String op=leaf(r.msgId());switch(op){
        case "join"->{if(state!=null)throw new IllegalStateException("round started");if(r.seatId()>=seatLimit||players.containsKey(r.seatId())||players.containsValue(player))throw new IllegalStateException("seat/player occupied");players.put(r.seatId(),player);body=viewFor(player);}
        case "ready"->{requireSeat(player,r.seatId());if(state!=null)throw new IllegalStateException("round started");readySeats.add(r.seatId());body=viewFor(player);}
        case "start"->{if(player!=ownerId)throw new SecurityException("owner only");start();body=viewFor(player);}
        case "state"->body=viewFor(player);
        default->{requireSeat(player,r.seatId());if(state==null)throw new IllegalStateException("round not started");MahjongOperation operation=com.aoo.bcg.gamespi.StrictEnumDecoder.byName(MahjongOperation.class,op.toUpperCase(java.util.Locale.ROOT));int tile=number(r.body(),"tile",0);List<Integer> consumed=numbers(r.body().get("consumedTiles"));state=new MahjongCoreEngine().execute(state,new MahjongCommand(r.seatId(),operation,tile,consumed),family.ruleSet());body=viewFor(player);}
    }if(!op.equals("state")&&!op.equals("hint"))stateVersion=Math.addExact(stateVersion,1);if(state!=null&&!state.finished()&&!op.equals("state")&&!op.equals("hint"))operationDeadline=OperationDeadline.open(op,state.currentSeat(),operationTimeout,time);if(state!=null&&state.finished())operationDeadline=OperationDeadline.none();return new GameCommandResult(r.msgId().replace("_req","_resp"),r.requestId(),body);}
    @Override public synchronized long stateVersion(){return stateVersion;}
    private void start(){if(state!=null||players.size()<2)throw new IllegalStateException("cannot start");List<Integer> wall=new ArrayList<>(tileSet.createWall());new SeededGameRandomSource(seed).shuffle(wall);List<Integer>seats=players.keySet().stream().sorted().toList();MahjongRegionalRules.DealerPolicy dealerPolicy=new MahjongRegionalRules.DealerPolicy(true,true);int dealer=dealerPolicy.initialDealer(seats,0);MahjongRegionalRules.DealResult dealt=MahjongRegionalRules.deal(tileSet,wall,seats,dealer,13,!tileSet.flowerTiles().isEmpty());openingFlowers=dealt.flowers();openingReplacements=dealt.replacements();state=new MahjongState(dealt.wall(),dealt.hands(),dealer,true,-1,-1,MahjongOperationWindow.empty(),false,-1);}
    @Override public synchronized Map<String,Object> viewFor(long viewer){Integer own=seatOf(viewer);Map<Integer,Object> seats=new LinkedHashMap<>();for(var e:players.entrySet()){List<Integer> cards=state==null?List.of():state.hands().get(e.getKey());seats.put(e.getKey(),Map.of("playerId",e.getValue(),"cards",e.getKey().equals(own)||(state!=null&&state.finished())?cards:Collections.nCopies(cards.size(),0),"cardCount",cards.size()));}List<Map<String,Object>>replacementView=openingReplacements.stream().map(event->Map.<String,Object>of("seat",event.seat(),"flowerTile",event.flowerTile(),"replacementTile",event.seat()==(own==null?-1:own)||state!=null&&state.finished()?event.replacementTile():0)).toList();Map<String,Object> out=new LinkedHashMap<>();out.put("roomId",roomId);out.put("family",family.familyCode());out.put("started",state!=null);out.put("currentSeat",state==null?-1:state.currentSeat());out.put("finished",state!=null&&state.finished());out.put("winnerSeat",state==null?-1:state.winnerSeat());out.put("openingFlowers",openingFlowers);out.put("openingReplacements",replacementView);out.put("seats",Map.copyOf(seats));return Map.copyOf(out);}
    @Override public synchronized Map<String,Object> authoritativeState(){Map<String,Object>out=new LinkedHashMap<>();out.put("roomId",roomId);out.put("ownerId",ownerId);out.put("seatLimit",seatLimit);out.put("seed",seed);out.put("playVersion",playVersion);out.put("tileSetSize",tileSet.size());out.put("players",Map.copyOf(players));out.put("readySeats",List.copyOf(readySeats));out.put("state",state==null?"WAITING":state);out.put("openingFlowers",openingFlowers);out.put("openingReplacements",openingReplacements);out.put("operationDeadline",operationDeadline.toMap());out.put("stateVersion",stateVersion);if(lastSettlementDetail!=null)out.put("settlementDetail",lastSettlementDetail);return Map.copyOf(out);}
    @Override public synchronized OperationDeadline operationDeadline(){return operationDeadline;}
    @Override public OperationDeadlineArbiter deadlineArbiter(){return deadlineArbiter;}
    @Override public synchronized List<String> invariantViolations(){List<String>errors=new ArrayList<>();if(new java.util.HashSet<>(players.values()).size()!=players.size())errors.add("DUPLICATE_PLAYER");if(state!=null){if(!players.keySet().equals(state.hands().keySet()))errors.add("SEAT_HAND_MISMATCH");if(!state.hands().containsKey(state.currentSeat()))errors.add("CURRENT_SEAT_MISSING");List<Integer>allTiles=java.util.stream.Stream.concat(java.util.stream.Stream.concat(state.wall().stream(),state.hands().values().stream().flatMap(List::stream)),openingFlowers.stream()).toList();errors.addAll(tileSet.inventoryViolations(allTiles));if(state.hands().values().stream().flatMap(List::stream).anyMatch(tileSet::isFlower))errors.add("FLOWER_IN_HAND");}return List.copyOf(errors);}
    @Override public synchronized SettlementPayload settlement(int roundNo,String requestedPlayVersion){if(!playVersion.equals(requestedPlayVersion))throw new IllegalArgumentException("settlement playVersion mismatch");if(state==null||!state.finished())throw new IllegalStateException("round not finished");List<MahjongRegionalRules.SettlementLine>lines=new ArrayList<>();for(int seat:players.keySet())if(seat!=state.winnerSeat())lines.add(new MahjongRegionalRules.SettlementLine(seat,state.winnerSeat(),1,"WIN","AUTHORITATIVE_ROUND"));lastSettlementDetail=MahjongRegionalRules.settle(new ArrayList<>(players.keySet()),lines);Map<Long,Long>deltas=new LinkedHashMap<>();lastSettlementDetail.totals().forEach((seat,delta)->deltas.put(players.get(seat),delta));return new SettlementPayload(roomId,roundNo,playVersion,deltas);}
    private void requireSeat(long player,int seat){if(!Long.valueOf(player).equals(players.get(seat)))throw new SecurityException("seat not owned");}private Integer seatOf(long player){return players.entrySet().stream().filter(e->e.getValue()==player).map(Map.Entry::getKey).findFirst().orElse(null);}private static long player(String s){try{long v=Long.parseLong(s);if(v<=0)throw new NumberFormatException();return v;}catch(NumberFormatException e){throw new IllegalArgumentException("invalid player id");}}private static String leaf(String id){String value=id.substring(id.lastIndexOf('.')+1);return value.endsWith("_req")?value.substring(0,value.length()-4):value;}private static int number(Map<String,Object>b,String k,int fallback){Object v=b.get(k);return v instanceof Number n?n.intValue():fallback;}private static List<Integer> numbers(Object value){if(!(value instanceof List<?> list))return List.of();return list.stream().map(v->{if(!(v instanceof Number n))throw new IllegalArgumentException("numeric cards required");return n.intValue();}).toList();}
    private static MahjongState restoreState(Map<?,?> m){List<Integer>wall=numbers(m.get("wall"));Map<Integer,List<Integer>>hands=intListMap(m.get("hands"));int current=intValue(m.get("currentSeat"));Map<Integer,java.util.Set<MahjongOperation>>candidates=new LinkedHashMap<>();Object rawWindow=m.get("window");if(rawWindow instanceof Map<?,?>w){Object rawCandidates=w.get("candidates");if(rawCandidates instanceof Map<?,?>cm)cm.forEach((k,v)->{java.util.Set<MahjongOperation>ops=new java.util.LinkedHashSet<>();if(v instanceof List<?>l)l.forEach(x->ops.add(com.aoo.bcg.gamespi.StrictEnumDecoder.byName(MahjongOperation.class,String.valueOf(x))));candidates.put(intValue(k),ops);});}return new MahjongState(wall,hands,current,booleanValue(m.get("currentSeatHasDrawn")),intValue(m.get("lastDiscard")),intValue(m.get("lastDiscardSeat")),new MahjongOperationWindow(candidates),booleanValue(m.get("finished")),intValue(m.get("winnerSeat")));}
    private static Map<Integer,Long>longMap(Object value){Map<Integer,Long>out=new LinkedHashMap<>();if(value instanceof Map<?,?>m)m.forEach((k,v)->out.put(intValue(k),longValue(v)));return out;}private static Map<Integer,List<Integer>>intListMap(Object value){Map<Integer,List<Integer>>out=new LinkedHashMap<>();if(value instanceof Map<?,?>m)m.forEach((k,v)->out.put(intValue(k),numbers(v)));return out;}private static int intValue(Object v){return v instanceof Number n?n.intValue():Integer.parseInt(String.valueOf(v));}private static long longValue(Object v){return v instanceof Number n?n.longValue():Long.parseLong(String.valueOf(v));}private static boolean booleanValue(Object v){return v instanceof Boolean b?b:Boolean.parseBoolean(String.valueOf(v));}
    private static MahjongRegionalRules.SettlementDetail restoreSettlementDetail(Map<?,?>map){ArrayList<MahjongRegionalRules.SettlementLine>lines=new ArrayList<>();Object rawLines=map.get("lines");if(rawLines instanceof List<?>list)for(Object raw:list){if(!(raw instanceof Map<?,?>line))throw new IllegalArgumentException("invalid settlement detail");lines.add(new MahjongRegionalRules.SettlementLine(intValue(line.get("payer")),intValue(line.get("receiver")),longValue(line.get("points")),String.valueOf(line.get("category")),String.valueOf(line.get("source"))));}Map<Integer,Long>expected=longMap(map.get("totals"));MahjongRegionalRules.SettlementDetail detail=MahjongRegionalRules.settle(new ArrayList<>(expected.keySet()),lines);if(!detail.totals().equals(expected))throw new IllegalArgumentException("settlement totals mismatch");return detail;}
    private static List<MahjongRegionalRules.ReplacementEvent>restoreReplacements(Object raw){if(!(raw instanceof List<?>list))return List.of();return list.stream().map(value->{Map<?,?>m=(Map<?,?>)value;return new MahjongRegionalRules.ReplacementEvent(intValue(m.get("seat")),intValue(m.get("flowerTile")),intValue(m.get("replacementTile")));}).toList();}
}
