package com.aoo.bcg.version;
import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Clock;import java.util.*;import static com.aoo.bcg.version.VersionModels.*;
public final class VersionHttpRoutes {
 private final VersionRepository repo;private final VersionService service;private final ObjectMapper json;private final byte[] clientToken;private final byte[] operatorToken;
 public VersionHttpRoutes(VersionRepository r,ObjectMapper j,String client,String operator,Clock c){repo=Objects.requireNonNull(r);service=new VersionService(r,c);json=Objects.requireNonNull(j);clientToken=token(client,"version client token");operatorToken=token(operator,"version operator token");if(MessageDigest.isEqual(clientToken,operatorToken))throw new IllegalArgumentException("client and operator credentials must differ");}
 public void mount(HttpServer s){s.createContext("/health/version",e->reply(e,200,Map.of("status","UP","persistence","jdbc","signingKeyCustody","external")));s.createContext("/v1/version/check",this::check);s.createContext("/v1/version/rollback",this::rollback);}
 private void check(HttpExchange e)throws IOException{handle(e,clientToken,()->service.check(json.readValue(e.getRequestBody(),VersionModels.Request.class)));}
 @SuppressWarnings("unchecked") private void rollback(HttpExchange e)throws IOException{handle(e,operatorToken,()->{Map<String,Object> f=json.readValue(e.getRequestBody(),Map.class);return repo.rollback(req(f,"platform"),req(f,"channel"),req(f,"version")).orElseThrow(()->new IllegalArgumentException("rollback version not found"));});}
 private void handle(HttpExchange e,byte[] credential,Action a)throws IOException{try{if(!"POST".equals(e.getRequestMethod()))throw new Api(405,"METHOD_NOT_ALLOWED","POST required");if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw new Api(426,"API_VERSION_REQUIRED","X-API-Version: 1 required");authenticate(e,credential);reply(e,200,Map.of("code","OK","data",a.run()));}catch(Api x){reply(e,x.status,Map.of("code",x.code,"message",x.getMessage()));}catch(SecurityException x){reply(e,401,Map.of("code","UNAUTHORIZED","message",x.getMessage()));}catch(IllegalArgumentException x){reply(e,400,Map.of("code","INVALID_REQUEST","message",String.valueOf(x.getMessage())));}catch(IllegalStateException x){reply(e,503,Map.of("code","VERSION_SERVICE_UNAVAILABLE","message",String.valueOf(x.getMessage())));}}
 private void authenticate(HttpExchange e,byte[] expected){String h=e.getRequestHeaders().getFirst("Authorization");byte[] b=h!=null&&h.startsWith("Bearer ")?h.substring(7).getBytes(StandardCharsets.UTF_8):new byte[0];if(!MessageDigest.isEqual(expected,b))throw new SecurityException("invalid version service credential");}
 private static byte[] token(String value,String name){if(value==null||value.length()<32)throw new IllegalArgumentException(name+" must be at least 32 characters");return value.getBytes(StandardCharsets.UTF_8);}
 private static String req(Map<String,Object> f,String k){Object v=f.get(k);if(!(v instanceof String s)||s.isBlank())throw new IllegalArgumentException(k+" required");return s;}private void reply(HttpExchange e,int status,Object o)throws IOException{byte[] b=json.writeValueAsBytes(o);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,b.length);try(var out=e.getResponseBody()){out.write(b);}}private interface Action{Object run()throws IOException;}private static final class Api extends RuntimeException{final int status;final String code;Api(int s,String c,String m){super(m);status=s;code=c;}}
}
