package com.aoo.bcg.version;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Clock;import java.time.Instant;import java.util.*;import static com.aoo.bcg.version.VersionModels.*;
public final class VersionService {
 private final VersionRepository repo;private final Clock clock;public VersionService(VersionRepository r,Clock c){repo=Objects.requireNonNull(r);clock=Objects.requireNonNull(c);}
 public Decision check(Request q){valid(q);Instant now=clock.instant();int bucket=bucket(q.deviceId(),q.channel());var rel=repo.eligibleRelease(q.platform(),q.channel(),bucket,now);var maintenance=repo.maintenance(q.platform(),q.channel(),now).orElse(null);var flags=repo.featureFlags(q.platform(),q.channel(),bucket,now);var directory=repo.directory(q.platform(),q.channel(),bucket,q.preferredServerId(),now);if(rel.isEmpty())return new Decision(maintenance!=null&&maintenance.loginBlocked()?"MAINTENANCE":"CURRENT",false,null,null,null,repo.notices(q.platform(),q.channel(),now),maintenance,flags,directory);Release r=rel.get();var manifest=repo.manifest(r.id()).orElse(null);boolean below=compare(q.currentVersion(),r.minimumVersion())<0;boolean newer=compare(q.currentVersion(),r.version())<0;boolean resourcesOutdated=manifest!=null&&!q.resourceVersion().equals(manifest.version());String status=below||r.forceUpdate()&&newer?"FORCE_UPDATE":newer||resourcesOutdated?"UPDATE_AVAILABLE":"CURRENT";return new Decision(status,below||r.forceUpdate()&&newer,r.minimumVersion(),newer||resourcesOutdated?r:null,resourcesOutdated||newer?manifest:null,repo.notices(q.platform(),q.channel(),now),maintenance,flags,directory);}
 static int compare(String a,String b){if(b==null)return 0;String[] x=a.split("\\."),y=b.split("\\.");for(int i=0;i<Math.max(x.length,y.length);i++){int n=i<x.length?part(x[i]):0,m=i<y.length?part(y[i]):0;if(n!=m)return Integer.compare(n,m);}return 0;}private static int part(String s){if(!s.matches("[0-9]+"))throw new IllegalArgumentException("versions must be numeric dotted values");return Integer.parseInt(s);}
 static int bucket(String device,String channel){try{byte[] h=MessageDigest.getInstance("SHA-256").digest((channel+":"+device).getBytes(StandardCharsets.UTF_8));return Math.floorMod(((h[0]&255)<<8)|(h[1]&255),100);}catch(Exception e){throw new IllegalStateException(e);}}
 private static void valid(Request q){if(q==null||blank(q.platform())||blank(q.channel())||blank(q.currentVersion())||blank(q.resourceVersion())||blank(q.deviceId()))throw new IllegalArgumentException("platform, channel, currentVersion, resourceVersion and deviceId are required");compare(q.currentVersion(),q.currentVersion());}private static boolean blank(String s){return s==null||s.isBlank();}
}
