package com.aoo.bcg.hall.room;
import static org.junit.jupiter.api.Assertions.*;import java.time.Duration;import java.util.*;import org.junit.jupiter.api.Test;
final class RoomCreateSagaTest{
 @Test void completesOnceAndReturnsAuthorityLease(){Fixture f=new Fixture(0);Map<String,Object>a=f.saga.create(7,"request-00000001",request());Map<String,Object>b=f.saga.create(7,"request-00000001",request());assertEquals(a,b);assertEquals(1,f.billing.reserve);assertEquals(1,f.billing.confirm);assertEquals(1,f.rooms.register);assertEquals(1,f.authority.create);assertEquals("OPEN",a.get("state"));assertEquals(1L,a.get("fencingToken"));}
 @Test void compensatesEveryCompletedStepIdempotently(){for(int fail=1;fail<=4;fail++){final int currentFail=fail;Fixture f=new Fixture(currentFail);assertThrows(IllegalStateException.class,()->f.saga.create(7,"request-0000000"+currentFail,request()));assertEquals(currentFail>1?1:0,f.billing.release);assertEquals(currentFail>2?1:0,f.rooms.remove);assertEquals(currentFail>3?1:0,f.authority.remove);}}
 @Test void rejectsReplayDriftAuthorityFieldsAndCompensatedReplay(){Fixture f=new Fixture(0);f.saga.create(7,"request-00000001",request());Map<String,Object>drift=new HashMap<>(request());drift.put("playVersion","v2");assertThrows(RuntimeException.class,()->f.saga.create(7,"request-00000001",drift));Map<String,Object>forged=new HashMap<>(request());forged.put("winner",7);assertThrows(RuntimeException.class,()->f.saga.create(7,"request-00000002",forged));}
 @Test void clubScopeIsDurableAndPartOfIdempotencyHash(){Fixture f=new Fixture(0);Map<String,Object>club=new HashMap<>(request());club.put("scope",Map.of("type","CLUB","clubId",19L,"templateCode","default"));f.saga.create(7,"request-00000003",club);assertEquals(19L,f.store.command.scope().clubId());assertEquals("CLUB",f.store.command.scope().type());Map<String,Object>drift=new HashMap<>(club);drift.put("scope",Map.of("type","CLUB","clubId",20L,"templateCode","default"));assertThrows(RuntimeException.class,()->f.saga.create(7,"request-00000003",drift));}
 @Test void rejectsInvalidScopeAndRegionRouting(){Map<String,Object>personal=new HashMap<>(request());personal.put("scope",Map.of("type","PERSONAL","clubId",1));assertThrows(RuntimeException.class,()->RoomCreateSaga.Command.parse(7,"request-00000004",personal));Map<String,Object>region=new HashMap<>(request());region.put("regionCode","SC");assertThrows(RuntimeException.class,()->RoomCreateSaga.Command.parse(7,"request-00000005",region));}
 private static Map<String,Object>request(){return Map.of("roomId",99L,"gameId",8,"playVersion","v1","clientVersion","3.8.8","stateVersion",1L,"rules",Map.of("rounds",8));}
 private static final class Fixture{final Memory store=new Memory();final Port billing=new Port(),rooms=new Port(),authority=new Port();final RoomCreateSaga saga;Fixture(int fail){saga=new RoomCreateSaga(store,new RoomCreateSaga.BillingPort(){public void reserve(RoomCreateSaga.Command c){billing.reserve++;if(fail==1)throw new IllegalStateException("injected");}public void confirm(RoomCreateSaga.Command c){billing.confirm++;}public void release(RoomCreateSaga.Command c){billing.release++;}},new RoomCreateSaga.RoomPort(){public void register(RoomCreateSaga.Command c){rooms.register++;if(fail==2)throw new IllegalStateException("injected");}public Map<String,Object>confirm(RoomCreateSaga.Command c,long v){if(fail==4)throw new IllegalStateException("injected");return Map.of("roomId",c.roomId(),"state","OPEN","stateVersion",v,"playVersion",c.playVersion());}public void remove(RoomCreateSaga.Command c){rooms.remove++;}},new RoomCreateSaga.AuthorityPort(){public Map<String,Object>create(RoomCreateSaga.Command c){authority.create++;if(fail==3)throw new IllegalStateException("injected");return lease(c);}public Map<String,Object>recover(RoomCreateSaga.Command c){authority.recover++;return lease(c);}public void remove(RoomCreateSaga.Command c,long fence){authority.remove++;}private Map<String,Object>lease(RoomCreateSaga.Command c){return Map.of("roomId",c.roomId(),"gameId",c.gameId(),"playVersion",c.playVersion(),"fencingToken",1L,"route","ws://local","nodeId","test");}});}}
 private static final class Port{int reserve,confirm,release,register,remove,create,recover;}
 private static final class Memory implements RoomCreateSaga.Store{RoomCreateSaga.State state;RoomCreateSaga.Command command;public RoomCreateSaga.State begin(RoomCreateSaga.Command c){command=c;if(state==null)state=new RoomCreateSaga.State(c.requestId(),c.requestHash(),RoomCreateSaga.Step.STARTED,1,Map.of());return state;}public RoomCreateSaga.State find(String id){return state;}public RoomCreateSaga.State advance(String id,long v,RoomCreateSaga.Step step,Map<String,Object>out){return state=new RoomCreateSaga.State(id,state.requestHash(),step,v+1,out==null?state.response():out);}public void fail(String id,long v,RoomCreateSaga.Step step,RoomCreateSaga.Step origin,String reason){state=new RoomCreateSaga.State(id,state.requestHash(),step,v+1,state.response(),origin);}public boolean acquire(String id,String token,Duration lease){return true;}}
}
