package com.aoo.bcg.spectator;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.*;
import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;
import java.io.IOException;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Clock;import java.util.*;

public final class SpectatorHttpRoutes {
 private final SpectatorService service;private final ObjectMapper json;private final byte[] secret;private final Clock clock;
 public SpectatorHttpRoutes(SpectatorService service,ObjectMapper json,String secret,Clock clock){this.service=Objects.requireNonNull(service);this.json=Objects.requireNonNull(json);if(secret==null||secret.length()<32)throw new IllegalArgumentException("auth secret too short");this.secret=secret.getBytes(StandardCharsets.UTF_8);this.clock=Objects.requireNonNull(clock);}
 public void mount(HttpServer server){server.createContext("/health/spectator",e->reply(e,200,Map.of("status","UP","persistence","jdbc","roomPort","hall","replayPort","perspective-event")));server.createContext("/v1/spectator",this::spectator);server.createContext("/v1/game-shares",this::shares);}
 private void spectator(HttpExchange e)throws IOException{try{version(e);long actor=authenticate(e);String p=e.getRequestURI().getPath();var b=body(e);Object out;if(p.matches("/v1/spectator/rooms/\\d+/requests")&&"POST".equals(e.getRequestMethod()))out=service.request(id(p,4),actor);else if(p.matches("/v1/spectator/rooms/\\d+/requests")&&"GET".equals(e.getRequestMethod()))out=service.pending(id(p,4),actor);else if(p.matches("/v1/spectator/requests/\\d+")&&"GET".equals(e.getRequestMethod()))out=service.status(id(p,3),actor);else if(p.matches("/v1/spectator/requests/\\d+/authorization")&&"POST".equals(e.getRequestMethod())){if(!(b.get("approved") instanceof Boolean approved))throw new IllegalArgumentException("approved required");out=service.authorize(id(p,3),actor,approved);}else if(p.matches("/v1/spectator/rooms/\\d+/leave")&&"POST".equals(e.getRequestMethod()))out=service.leave(id(p,4),actor);else if(p.matches("/v1/spectator/rooms/\\d+/snapshot")&&"GET".equals(e.getRequestMethod()))out=service.snapshot(id(p,4),actor,queryInt(e,"limit",500));else if(p.matches("/v1/spectator/rooms/\\d+/events")&&"GET".equals(e.getRequestMethod()))out=service.stream(id(p,4),actor,positive(queryLong(e,"afterSequence",0)),bounded(queryInt(e,"limit",100),1,500));else if(p.matches("/v1/spectator/rooms/\\d+/reconnect")&&"GET".equals(e.getRequestMethod()))out=service.reconnect(id(p,4),actor,positive(queryLong(e,"afterSequence",0)),bounded(queryInt(e,"limit",100),1,500));else throw new NoSuchElementException();reply(e,200,Map.of("code","OK","data",out));}catch(SecurityException x){reply(e,401,error("SPECTATOR_UNAUTHORIZED"));}catch(NoSuchElementException x){reply(e,404,error("SPECTATOR_NOT_FOUND"));}catch(IllegalArgumentException x){reply(e,400,error("SPECTATOR_INVALID_REQUEST"));}catch(Exception x){reply(e,409,error("SPECTATOR_OPERATION_FAILED"));}}
 private void shares(HttpExchange e)throws IOException{try{String p=e.getRequestURI().getPath();Object out;if("/v1/game-shares".equals(p)&&"POST".equals(e.getRequestMethod())){long actor=authenticate(e);var b=body(e);out=service.share(((Number)b.get("roomId")).longValue(),actor,java.time.Duration.ofSeconds(Math.max(60,Math.min(86400,((Number)b.getOrDefault("ttlSeconds",3600)).longValue()))));}else if(p.matches("/v1/game-shares/[A-Za-z0-9_-]+")&&"GET".equals(e.getRequestMethod()))out=service.shared(p.substring(p.lastIndexOf('/')+1));else throw new NoSuchElementException();reply(e,200,out);}catch(SecurityException x){reply(e,403,error("GAME_SHARE_UNAVAILABLE"));}catch(NoSuchElementException x){reply(e,404,error("GAME_SHARE_NOT_FOUND"));}catch(Exception x){reply(e,400,error("GAME_SHARE_INVALID_REQUEST"));}}
 private long authenticate(HttpExchange e){try{String a=e.getRequestHeaders().getFirst("Authorization");if(a==null||!a.startsWith("Bearer "))throw new SecurityException();String[] p=a.substring(7).split("\\.");if(p.length!=3)throw new SecurityException();long id=Long.parseLong(p[0]),exp=Long.parseLong(p[1]);if(id<=0||exp<clock.instant().getEpochSecond()||exp>clock.instant().plusSeconds(300).getEpochSecond())throw new SecurityException();Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(secret,"HmacSHA256"));if(!MessageDigest.isEqual(m.doFinal((p[0]+"."+p[1]).getBytes(StandardCharsets.UTF_8)),HexFormat.of().parseHex(p[2])))throw new SecurityException();return id;}catch(SecurityException x){throw x;}catch(Exception x){throw new SecurityException();}}
 private Map<String,Object> body(HttpExchange e)throws IOException{byte[] b=e.getRequestBody().readNBytes(1048577);if(b.length>1048576)throw new IllegalArgumentException();return b.length==0?Map.of():json.readValue(b,new TypeReference<>(){});}private static long id(String p,int i){return Long.parseLong(p.split("/")[i]);}
 private static long queryLong(HttpExchange e,String k,long d){String v=query(e,k);return v==null?d:Long.parseLong(v);}private static int queryInt(HttpExchange e,String k,int d){String v=query(e,k);return v==null?d:Integer.parseInt(v);}private static String query(HttpExchange e,String k){String q=e.getRequestURI().getRawQuery();if(q==null)return null;for(String x:q.split("&")){String[] p=x.split("=",2);if(p[0].equals(k))return p.length==2?p[1]:"";}return null;}
 private static Map<String,Object> error(String code){return Map.of("error",Map.of("code",code));}private void reply(HttpExchange e,int status,Object value)throws IOException{byte[] b=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","private, no-store");e.sendResponseHeaders(status,b.length);try(var o=e.getResponseBody()){o.write(b);}}
 private static void version(HttpExchange e){if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw new IllegalArgumentException("X-API-Version: 1 required");}
 private static long positive(long value){if(value<0)throw new IllegalArgumentException("negative cursor");return value;}private static int bounded(int value,int min,int max){if(value<min||value>max)throw new IllegalArgumentException("limit out of range");return value;}
}
