package com.aoo.bcg.spectator;

import com.fasterxml.jackson.databind.ObjectMapper;
import javax.sql.DataSource;
import java.security.SecureRandom;
import java.time.*;
import java.util.*;

/** Durable spectator lifecycle. Every outbound event is public-only and recursively secret-key checked. */
public final class SpectatorService {
 public record Admission(long requestId,long roomId,long spectatorId,String status,Instant requestedAt,Instant authorizedAt,Instant leftAt){}
 private static final Set<String> FORBIDDEN=Set.of("hand","hands","cards","wall","deck","seed","randomSeed","rngState","internalState","drawPile","牌墙","暗牌","随机种子");
 private final DataSource source;private final SpectatorPorts.RoomPort rooms;private final SpectatorPorts.ReplayPort replay;private final ObjectMapper json;private final Clock clock;private final Duration delay;private final SecureRandom random=new SecureRandom();
 public SpectatorService(DataSource source,SpectatorPorts.RoomPort rooms,SpectatorPorts.ReplayPort replay,ObjectMapper json,Clock clock,Duration delay){this.source=Objects.requireNonNull(source);this.rooms=Objects.requireNonNull(rooms);this.replay=Objects.requireNonNull(replay);this.json=Objects.requireNonNull(json);this.clock=Objects.requireNonNull(clock);if(delay==null||delay.isNegative())throw new IllegalArgumentException("delay");this.delay=delay;}
 public Admission request(long roomId,long spectatorId){rooms.summary(roomId);try(var c=source.getConnection();var q=c.prepareStatement("INSERT INTO aoo_spectator_admission(room_id,spectator_id,status,requested_at,row_version) VALUES(?,?,'PENDING',?,1)",java.sql.Statement.RETURN_GENERATED_KEYS)){q.setLong(1,roomId);q.setLong(2,spectatorId);q.setTimestamp(3,java.sql.Timestamp.from(clock.instant()));q.executeUpdate();try(var k=q.getGeneratedKeys()){if(!k.next())throw new IllegalStateException("missing request id");return find(k.getLong(1),spectatorId,false);}}catch(Exception e){throw new IllegalStateException("spectator request failed",e);}}
 public Admission status(long requestId,long spectatorId){return find(requestId,spectatorId,false);}
 public List<Admission> pending(long roomId,long owner){if(!rooms.mayApprove(roomId,owner))throw new SecurityException("room owner required");try(var c=source.getConnection();var q=c.prepareStatement("SELECT request_id,room_id,spectator_id,status,requested_at,authorized_at,left_at FROM aoo_spectator_admission WHERE room_id=? AND status='PENDING' ORDER BY request_id")){q.setLong(1,roomId);try(var r=q.executeQuery()){var out=new ArrayList<Admission>();while(r.next())out.add(admission(r));return List.copyOf(out);}}catch(Exception e){throw new IllegalStateException("pending spectator lookup failed",e);}}
 public Admission authorize(long requestId,long approver,boolean approve){try(var c=source.getConnection()){c.setAutoCommit(false);try{long room;String status;try(var q=c.prepareStatement("SELECT room_id,status FROM aoo_spectator_admission WHERE request_id=? FOR UPDATE")){q.setLong(1,requestId);try(var r=q.executeQuery()){if(!r.next())throw new NoSuchElementException("request not found");room=r.getLong(1);status=r.getString(2);}}if(!rooms.mayApprove(room,approver))throw new SecurityException("room owner required");if(!"PENDING".equals(status))throw new IllegalStateException("request already decided");try(var u=c.prepareStatement("UPDATE aoo_spectator_admission SET status=?,authorized_by=?,authorized_at=?,row_version=row_version+1 WHERE request_id=?")){u.setString(1,approve?"AUTHORIZED":"REJECTED");u.setLong(2,approver);u.setTimestamp(3,java.sql.Timestamp.from(clock.instant()));u.setLong(4,requestId);u.executeUpdate();}c.commit();return find(requestId,approver,true);}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalStateException("authorization failed",e);}}
 public Admission leave(long roomId,long spectatorId){try(var c=source.getConnection();var q=c.prepareStatement("UPDATE aoo_spectator_admission SET status='LEFT',left_at=?,row_version=row_version+1 WHERE room_id=? AND spectator_id=? AND status='AUTHORIZED'")){q.setTimestamp(1,java.sql.Timestamp.from(clock.instant()));q.setLong(2,roomId);q.setLong(3,spectatorId);if(q.executeUpdate()!=1)throw new IllegalStateException("active spectator not found");return activeOrLatest(roomId,spectatorId);}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalStateException("spectator exit failed",e);}}
 public Map<String,Object> stream(long roomId,long spectatorId,long after,int limit){requireAuthorized(roomId,spectatorId);var events=replay.publicEvents(roomId,after,clock.instant().minus(delay),limit);var safe=new ArrayList<Map<String,Object>>();long cursor=after;for(var e:events){assertSafe(e.payload());cursor=e.sequence();safe.add(Map.of("sequence",e.sequence(),"type",e.type(),"payload",e.payload(),"occurredAt",e.occurredAt()));}return Map.of("roomId",roomId,"afterSequence",after,"nextSequence",cursor,"delayMillis",delay.toMillis(),"events",safe);}
 public Map<String,Object> snapshot(long roomId,long spectatorId,int limit){requireAuthorized(roomId,spectatorId);var summary=rooms.summary(roomId);var events=stream(roomId,spectatorId,0,limit);return Map.of("summary",publicSummary(summary,count(roomId)),"publicTimeline",events,"perspective","SPECTATOR_PUBLIC");}
 public Map<String,Object> reconnect(long roomId,long spectatorId,long after,int limit){return Map.of("snapshot",snapshot(roomId,spectatorId,limit),"incremental",stream(roomId,spectatorId,after,limit));}
 public Map<String,Object> share(long roomId,long playerId,Duration ttl){if(!rooms.mayApprove(roomId,playerId))throw new SecurityException("room owner required");byte[] b=new byte[24];random.nextBytes(b);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(b);String hash=sha256(token);Instant expires=clock.instant().plus(ttl);try(var c=source.getConnection();var q=c.prepareStatement("INSERT INTO aoo_game_share(share_hash,room_id,created_by,created_at,expires_at) VALUES(?,?,?,?,?)")){q.setString(1,hash);q.setLong(2,roomId);q.setLong(3,playerId);q.setTimestamp(4,java.sql.Timestamp.from(clock.instant()));q.setTimestamp(5,java.sql.Timestamp.from(expires));q.executeUpdate();return Map.of("token",token,"expiresAt",expires,"summary",publicSummary(rooms.summary(roomId),count(roomId)));}catch(Exception e){throw new IllegalStateException("share create failed",e);}}
 public Map<String,Object> shared(String token){try(var c=source.getConnection();var q=c.prepareStatement("SELECT room_id,expires_at,revoked_at FROM aoo_game_share WHERE share_hash=?")){q.setString(1,sha256(token));try(var r=q.executeQuery()){if(!r.next()||r.getTimestamp(3)!=null||!r.getTimestamp(2).toInstant().isAfter(clock.instant()))throw new SecurityException("share unavailable");long room=r.getLong(1);return publicSummary(rooms.summary(room),count(room));}}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalStateException("share lookup failed",e);}}
 private Admission find(long id,long actor,boolean approver){try(var c=source.getConnection();var q=c.prepareStatement("SELECT request_id,room_id,spectator_id,status,requested_at,authorized_at,left_at FROM aoo_spectator_admission WHERE request_id=?")){q.setLong(1,id);try(var r=q.executeQuery()){if(!r.next())throw new NoSuchElementException();if(!approver&&r.getLong(3)!=actor)throw new SecurityException();return admission(r);}}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalStateException(e);}}
 private Admission activeOrLatest(long room,long player){try(var c=source.getConnection();var q=c.prepareStatement("SELECT request_id,room_id,spectator_id,status,requested_at,authorized_at,left_at FROM aoo_spectator_admission WHERE room_id=? AND spectator_id=? ORDER BY request_id DESC LIMIT 1")){q.setLong(1,room);q.setLong(2,player);try(var r=q.executeQuery()){if(!r.next())throw new NoSuchElementException();return admission(r);}}catch(Exception e){throw new IllegalStateException(e);}}
 private Admission admission(java.sql.ResultSet r)throws Exception{return new Admission(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getTimestamp(5).toInstant(),r.getTimestamp(6)==null?null:r.getTimestamp(6).toInstant(),r.getTimestamp(7)==null?null:r.getTimestamp(7).toInstant());}
 private void requireAuthorized(long room,long player){try(var c=source.getConnection();var q=c.prepareStatement("SELECT 1 FROM aoo_spectator_admission WHERE room_id=? AND spectator_id=? AND status='AUTHORIZED'")){q.setLong(1,room);q.setLong(2,player);try(var r=q.executeQuery()){if(!r.next())throw new SecurityException("spectator authorization required");}}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalStateException(e);}}
 private int count(long room){try(var c=source.getConnection();var q=c.prepareStatement("SELECT COUNT(*) FROM aoo_spectator_admission WHERE room_id=? AND status='AUTHORIZED'")){q.setLong(1,room);try(var r=q.executeQuery()){r.next();return r.getInt(1);}}catch(Exception e){throw new IllegalStateException(e);}}
 private static Map<String,Object> publicSummary(SpectatorPorts.RoomSummary s,int viewers){return Map.of("roomId",s.roomId(),"gameId",s.gameId(),"classificationRegionCode",s.classificationRegionCode(),"playVersion",s.playVersion(),"state",s.state(),"playerCount",s.playerCount(),"spectatorCount",viewers);}
 private static void assertSafe(Object value){if(value instanceof Map<?,?> m)for(var e:m.entrySet()){String key=normalize(String.valueOf(e.getKey()));if(FORBIDDEN.stream().map(SpectatorService::normalize).anyMatch(key::contains))throw new SecurityException("unsafe event payload");assertSafe(e.getValue());}else if(value instanceof Collection<?> c)c.forEach(SpectatorService::assertSafe);}
 private static String normalize(String value){return value.replace("_","").replace("-","").toLowerCase(Locale.ROOT);}
 private static String sha256(String v){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(v.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
