package com.aoo.bcg.location;

import static com.aoo.bcg.location.LocationModels.*;
import static com.aoo.bcg.location.LocationPersistence.*;
import static org.junit.jupiter.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpServer;
import java.net.*;import java.net.http.*;import java.time.*;import java.util.*;
import org.junit.jupiter.api.*;

class LocationHttpRoutesTest {
    HttpServer server; HttpClient client=HttpClient.newHttpClient(); URI base; Store store=new Store();
    @BeforeEach void start()throws Exception{Instant now=Instant.parse("2026-08-24T00:00:00Z");Clock clock=Clock.fixed(now,ZoneOffset.UTC);var service=new LocationRiskService(store,store,store,store,new LocationRiskPolicy(100,75,Duration.ofMinutes(2),80,20,15,Duration.ofDays(7)),clock);var auth=new LocationRequestAuthenticator(Map.of("secret-token",new LocationRequestAuthenticator.Identity("tenant-a","gateway",Set.of("location.authorization.write","location.signal.write","location.risk.assess"))),"proxy-secret",clock);server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);new LocationHttpRoutes(service,auth,new ObjectMapper()).mount(server);server.start();base=URI.create("http://127.0.0.1:"+server.getAddress().getPort());}
    @AfterEach void stop(){server.stop(0);}
    @Test void acceptsStrictV1AuthorizationWithBearer()throws Exception{String body="{\"eventId\":\"evt-1\",\"playerId\":9,\"status\":\"GRANTED\",\"occurredAt\":\"2026-08-24T00:00:00Z\",\"platform\":\"ios\",\"platformDetail\":null}";var r=post("/api/v1/location/authorization",body,"Bearer secret-token","idem-1");assertEquals(200,r.statusCode());assertTrue(r.body().contains("evt-1"));assertEquals(1,store.authWrites);}
    @Test void acceptsTrustedProxyAndRejectsUnknownJsonField()throws Exception{String body="{\"eventId\":\"evt-2\",\"playerId\":9,\"status\":\"DENIED\",\"occurredAt\":\"2026-08-24T00:00:00Z\",\"platform\":\"ios\",\"unexpected\":true}";var request=HttpRequest.newBuilder(base.resolve("/api/v1/location/authorization")).header("Content-Type","application/json").header("Idempotency-Key","idem-2").header("X-Aoo-Proxy-Secret","proxy-secret").header("X-Aoo-Tenant-Id","tenant-a").header("X-Aoo-Subject","edge").header("X-Aoo-Scopes","location.authorization.write").POST(HttpRequest.BodyPublishers.ofString(body)).build();assertEquals(400,client.send(request,HttpResponse.BodyHandlers.ofString()).statusCode());}
    @Test void mapsAuthAndVersionErrors()throws Exception{String body="{\"eventId\":\"evt\",\"playerId\":9,\"status\":\"GRANTED\",\"occurredAt\":\"2026-08-24T00:00:00Z\",\"platform\":\"ios\"}";assertEquals(401,post("/api/v1/location/authorization",body,null,"i1").statusCode());var req=HttpRequest.newBuilder(base.resolve("/api/v1/location/authorization")).header("Content-Type","application/json").header("Authorization","Bearer secret-token").header("Idempotency-Key","i2").header("X-Api-Version","2").POST(HttpRequest.BodyPublishers.ofString(body)).build();assertEquals(426,client.send(req,HttpResponse.BodyHandlers.ofString()).statusCode());}
    private HttpResponse<String> post(String path,String body,String auth,String key)throws Exception{var b=HttpRequest.newBuilder(base.resolve(path)).header("Content-Type","application/json").header("Idempotency-Key",key);if(auth!=null)b.header("Authorization",auth);return client.send(b.POST(HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());}
    static final class Store implements AuthorizationRepository,RiskSignalRepository,AssessmentRepository,IdempotencyRepository{Map<String,String> fp=new HashMap<>(),ref=new HashMap<>();int authWrites;TableRiskAssessment assessment;public void append(String t,AuthorizationReport r,String a){authWrites++;}public void append(String t,NetworkRiskReport r,String a){}public void save(String t,TableRiskAssessment a,String x){assessment=a;}public Optional<TableRiskAssessment> findById(String t,String id){return Optional.ofNullable(assessment);}public Claim claim(String t,String o,String k,String f,Instant e){String x=t+o+k,old=fp.putIfAbsent(x,f);if(old!=null&&!old.equals(f))return new Claim(ClaimStatus.CONFLICT,Optional.empty());if(ref.containsKey(x))return new Claim(ClaimStatus.COMPLETED,Optional.of(ref.get(x)));return new Claim(ClaimStatus.CLAIMED,Optional.empty());}public void complete(String t,String o,String k,String r){ref.put(t+o+k,r);}public void abandon(String t,String o,String k){fp.remove(t+o+k);}}
}
