package com.aoo.bcg.referral;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;
import java.math.BigDecimal;
import java.sql.*;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class PromoterServiceTest {
    JdbcDataSource source;PromoterService service;List<String> credits;
    @BeforeEach void setup()throws Exception{source=new JdbcDataSource();source.setURL("jdbc:h2:mem:referral;MODE=MySQL;DB_CLOSE_DELAY=-1");try(Connection c=source.getConnection();Statement s=c.createStatement()){s.execute("DROP ALL OBJECTS");s.execute("CREATE TABLE dbClubmember(id BIGINT PRIMARY KEY,clubID BIGINT,playerID BIGINT,status INT,upLevelId BIGINT,level INT,promotion INT,updatetime BIGINT)");s.execute("CREATE TABLE PlayerRoomAlone(id BIGINT PRIMARY KEY,pid BIGINT,clubID BIGINT,dateTime INT,setCount INT,roomSportsConsume DECIMAL(20,2),sportsPoint DECIMAL(20,2))");s.execute("CREATE TABLE promoter_commission_instruction(command_id VARCHAR(128) PRIMARY KEY,club_id BIGINT,promoter_id BIGINT,from_date INT,to_date INT,base_amount DECIMAL(20,2),rate DECIMAL(9,6),commission_amount BIGINT,currency VARCHAR(32),status VARCHAR(20),billing_reference VARCHAR(160),created_at TIMESTAMP,updated_at TIMESTAMP)");s.execute("CREATE TABLE referral_invite_reward_policy(kind VARCHAR(8) PRIMARY KEY,currency VARCHAR(32),reward_amount DECIMAL(20,2),enabled INT)");s.execute("CREATE TABLE referral_invite_reward_instruction(idempotency_key VARCHAR(128) PRIMARY KEY,consumption_id BIGINT UNIQUE,invite_id BIGINT,issuer_account_id BIGINT,consumer_account_id BIGINT,kind VARCHAR(8),target_id BIGINT,currency VARCHAR(32),reward_amount DECIMAL(20,2),status VARCHAR(16),billing_reference VARCHAR(160),created_at TIMESTAMP,updated_at TIMESTAMP)");s.execute("INSERT INTO referral_invite_reward_policy VALUES('ROOM','GOLD',10,1)");s.execute("INSERT INTO dbClubmember VALUES(1,7,100,4,0,1,1,0),(2,7,200,4,0,0,0,0),(3,7,201,4,100,0,0,0)");s.execute("INSERT INTO PlayerRoomAlone VALUES(1,200,7,20260801,8,40,12),(2,201,7,20260802,4,60,-2)");}credits=new ArrayList<>();service=new PromoterService(new JdbcPromoterRepository(source,Clock.fixed(Instant.parse("2026-08-24T00:00:00Z"),ZoneOffset.UTC)),(key,player,scope,currency,amount,reason)->credits.add(key+":"+player+":"+amount));}
    @Test void bindsRealClubMembershipAndRejectsReparenting(){assertEquals(100L,service.bind(7,200,100).get("promoterId"));assertEquals(100L,service.relation(7,200).get("promoterId"));assertThrows(IllegalStateException.class,()->service.bind(7,201,200));}
    @Test void summarizesCalculatesIdempotentlyAndSettlesThroughBilling()throws Exception{service.bind(7,200,100);var summary=service.summary(7,100,20260801,20260831);assertEquals(2L,summary.get("players"));assertEquals(new BigDecimal("100.00"),summary.get("consumption"));var calculated=service.calculate("cmd-1",7,100,20260801,20260831,new BigDecimal("0.25"),"GOLD");assertEquals(new BigDecimal("25"),calculated.get("commissionAmount"));service.calculate("cmd-1",7,100,20260801,20260831,new BigDecimal("0.25"),"GOLD");assertEquals("SETTLED",service.settle("cmd-1").get("status"));assertEquals(List.of("promoter-commission:cmd-1:100:25"),credits);assertEquals("SETTLED",service.settle("cmd-1").get("status"));assertEquals(1,credits.size());}
    @Test void forbidsSelfBindingAndInvalidRate(){assertThrows(IllegalArgumentException.class,()->service.bind(7,100,100));assertThrows(IllegalArgumentException.class,()->service.calculate("bad",7,100,1,2,new BigDecimal("1.01"),"GOLD"));}
    @Test void inviteRewardIsDurableAndIdempotent()throws Exception{assertEquals("GRANTED",service.inviteReward("invite-consumption:9",9,8,42,77,"ROOM",7).get("status"));service.inviteReward("invite-consumption:9",9,8,42,77,"ROOM",7);assertEquals(List.of("invite-reward:9:77:10.00"),credits);}
}
