package com.aoo.bcg.mahjong;

import static com.aoo.bcg.mahjong.MahjongRegionalRules.*;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.Test;

class MahjongRegionalRulesTest {
 @Test void dealerRotationIsRegionalAndDeterministic(){DealerPolicy p=new DealerPolicy(true,false);assertEquals(1,p.nextDealer(1,DealerOutcome.WIN,List.of(0,1,2,3)));assertEquals(2,p.nextDealer(1,DealerOutcome.DRAW,List.of(0,1,2,3)));assertEquals(0,p.nextDealer(3,DealerOutcome.LOSS,List.of(0,1,2,3)));}
 @Test void initialDealerUsesSortedSeatsAndAuthoritativeOffset(){DealerPolicy p=new DealerPolicy(true,false);assertEquals(2,p.initialDealer(List.of(0,1,2,3),2));assertEquals(3,p.initialDealer(List.of(0,1,2,3),-1));assertThrows(IllegalArgumentException.class,()->p.initialDealer(List.of(1,0),0));assertThrows(IllegalArgumentException.class,()->p.initialDealer(List.of(0,0),0));}
 @Test void dealerAndDealRejectDuplicateSeatsAndNullOutcome(){DealerPolicy p=new DealerPolicy(true,false);assertThrows(IllegalArgumentException.class,()->p.nextDealer(0,null,List.of(0,1)));assertThrows(IllegalArgumentException.class,()->p.nextDealer(0,DealerOutcome.WIN,List.of(0,0)));assertThrows(IllegalArgumentException.class,()->deal(MahjongTileSet.sichuan("v"),MahjongTileSet.sichuan("v").createWall(),List.of(0,0),0,13,false));}
 @Test void dealMaintainsCountsAndReplacesFlowers(){MahjongTileSet ts=MahjongTileSet.standardWithFlowers("v");ArrayList<Integer>w=new ArrayList<>(ts.createWall());w.remove(Integer.valueOf(51));w.add(0,51);DealResult r=deal(ts,w,List.of(0,1,2,3),0,13,true);assertEquals(14,r.hands().get(0).size());assertEquals(13,r.hands().get(1).size());assertTrue(r.flowers().contains(51));assertTrue(r.flowers().stream().allMatch(ts::isFlower));assertEquals(r.flowers().size(),r.replacements().size());assertEquals(0,r.replacements().get(0).seat());assertEquals(51,r.replacements().get(0).flowerTile());assertEquals(144,r.wall().size()+r.flowers().size()+r.hands().values().stream().mapToInt(List::size).sum());}
 @Test void openingCoversSubmitTimeoutDirectionAndRestore(){Map<Integer,List<Integer>>hands=Map.of(0,List.of(11,12,13,21),1,List.of(21,22,23,31));OpeningSelections s=OpeningSelections.empty().submitExchange(0,hands.get(0),List.of(11,12,13)).timeoutExchange(1,hands.get(1)).submitMissingSuit(0,MahjongSuit.TONG).timeoutMissingSuit(1,hands.get(1));assertEquals(s,OpeningSelections.restore(s.snapshot()));Map<Integer,List<Integer>>changed=s.applyExchange(List.of(0,1),hands,1);assertTrue(changed.get(0).containsAll(List.of(21,22,23)));assertTrue(changed.get(1).containsAll(List.of(11,12,13)));}
 @Test void openingRejectsHonorsAndMismatchedSeatMaps(){assertThrows(IllegalArgumentException.class,()->OpeningSelections.empty().submitExchange(0,List.of(41,42,43),List.of(41,42,43)));OpeningSelections s=OpeningSelections.empty().submitExchange(0,List.of(11,12,13),List.of(11,12,13));assertThrows(IllegalStateException.class,()->s.applyExchange(List.of(0,0),Map.of(0,List.of(11,12,13)),1));}
 @Test void claimsSupportPriorityNearestAndMultipleWins(){List<ClaimRequest>r=List.of(new ClaimRequest(1,Claim.PONG),new ClaimRequest(2,Claim.WIN),new ClaimRequest(3,Claim.WIN));assertEquals(List.of(2,3),arbitrate(r,0,List.of(0,1,2,3),true).stream().map(ClaimRequest::seat).toList());assertEquals(2,arbitrate(r,0,List.of(0,1,2,3),false).get(0).seat());}
 @Test void claimValidationCoversPassDuplicatesAndRobKong(){assertTrue(arbitrate(List.of(new ClaimRequest(1,Claim.PASS)),0,List.of(0,1,2),false).get(0).claim()==Claim.PASS);assertTrue(arbitrate(List.of(),0,List.of(0,1,2),false).isEmpty());assertThrows(IllegalArgumentException.class,()->arbitrate(List.of(new ClaimRequest(1,Claim.PASS),new ClaimRequest(1,Claim.WIN)),0,List.of(0,1,2),true));assertEquals(2,arbitrate(List.of(new ClaimRequest(1,Claim.WIN),new ClaimRequest(2,Claim.WIN)),0,List.of(0,1,2),true,ClaimContext.ADDED_KONG).size());assertThrows(IllegalArgumentException.class,()->arbitrate(List.of(new ClaimRequest(1,Claim.PONG)),0,List.of(0,1,2),false,ClaimContext.ADDED_KONG));}
 @Test void kongDeclaresReplacementDirectionAndRobbingWindow(){KongCapability c=new KongCapability(Set.of(KongType.CONCEALED,KongType.ADDED),true,true);KongResult r=c.apply(KongType.ADDED,List.of(11,12,13));assertEquals(13,r.replacementTile());assertEquals(List.of(11,12),r.wall());assertTrue(r.robbingWindow());}
 @Test void winningMatrixCoversSpecialHandsAndMissingSuit(){WinPolicy seven=new WinPolicy(Set.of(WinningForm.SEVEN_PAIRS),null);assertTrue(seven.mayWin(List.of(11,11,12,12,21,21,22,22,31,31,32,32,41,41)));WinPolicy blocked=new WinPolicy(Set.of(WinningForm.SEVEN_PAIRS),MahjongSuit.WAN);assertFalse(blocked.mayWin(List.of(11,11,12,12,21,21,22,22,31,31,32,32,41,41)));WinPolicy orphan=new WinPolicy(Set.of(WinningForm.THIRTEEN_ORPHANS),null);assertTrue(orphan.mayWin(List.of(11,11,19,21,29,31,39,41,42,43,44,45,46,47)));}
 @Test void liabilityDistinguishesSelfDrawDiscardAndResponsibility(){assertEquals(3,liabilities(WinSource.SELF_DRAW,0,-1,List.of(0,1,2,3),2,null).size());assertEquals(6,liabilities(WinSource.DISCARD,0,2,List.of(0,1,2,3),2,null).get(0).amount());assertEquals("RESPONSIBILITY",liabilities(WinSource.DISCARD,0,2,List.of(0,1,2,3),2,3).get(0).reason());}
 @Test void liabilityRejectsIllegalActors(){assertThrows(IllegalArgumentException.class,()->liabilities(WinSource.DISCARD,0,4,List.of(0,1,2),1,null));assertThrows(IllegalArgumentException.class,()->liabilities(WinSource.DISCARD,0,1,List.of(0,1,2),1,0));}
 @Test void liabilityRejectsNullWinSource(){assertThrows(IllegalArgumentException.class,()->liabilities(null,0,1,List.of(0,1,2),1,null));}
 @Test void fanSchemaAppliesExclusionAndCap(){FanResult r=scoreFans(List.of(new FanRule("PURE",4,Set.of("HALF")),new FanRule("HALF",2,Set.of()),new FanRule("KONG",2,Set.of())),Set.of("PURE","HALF","KONG"),5);assertEquals(6,r.rawFan());assertEquals(5,r.cappedFan());assertEquals(Set.of("PURE","KONG"),r.applied());}
 @Test void fanSchemaRejectsInvalidReferencesAndMatches(){assertThrows(IllegalArgumentException.class,()->compileFanSchema(List.of(new FanRule("A",1,Set.of("MISSING")))));assertThrows(IllegalArgumentException.class,()->compileFanSchema(List.of(new FanRule("A",1,Set.of("A")))));assertThrows(IllegalArgumentException.class,()->scoreFans(List.of(new FanRule("A",1,Set.of())),Set.of("B"),1));assertThrows(IllegalArgumentException.class,()->scoreFans(List.of(new FanRule("A",1,Set.of())),Set.of("A"),-1));}
 @Test void wallTimingEnforcesPossibleStatesAndSourcePairs(){assertEquals(Set.of("HAI_DI_LAO","GANG_SHANG_HUA"),new WallTiming(108,0,true,false).winTags(true));assertEquals(Set.of("DI_HU"),new WallTiming(108,80,false,true).winTags(false));assertThrows(IllegalArgumentException.class,()->new WallTiming(108,0,false,true));assertThrows(IllegalArgumentException.class,()->new WallTiming(108,80,true,true));}
 @Test void wallTimingRejectsZeroInitialWall(){assertThrows(IllegalArgumentException.class,()->new WallTiming(0,0,false,false));}
 @Test void passRestrictionsRoundTripAndClearOnDraw(){PassRestrictions p=PassRestrictions.empty().pass(22,true,true);assertFalse(p.mayPong(22));assertFalse(p.mayWin(22));assertEquals(p,PassRestrictions.restore(p.snapshot()));assertTrue(p.onOwnDraw().mayWin(22));}
 @Test void drawAuditFindsFlowerPigAndConservesPenalty(){DrawAudit a=auditDraw(Map.of(0,List.of(11,21),1,List.of(22),2,List.of(31)),Map.of(0,MahjongSuit.WAN,1,MahjongSuit.WAN,2,MahjongSuit.WAN),5,0,new DealerPolicy(true,true));assertEquals(Set.of(0),a.flowerPigSeats());assertEquals(0,a.deltas().values().stream().mapToLong(Long::longValue).sum());assertEquals(0,a.nextDealer());}
 @Test void drawAuditHonorsRegionalFlowerPigThreshold(){DrawAudit a=auditDraw(Map.of(0,List.of(11,12),1,List.of(21),2,List.of(31)),Map.of(0,MahjongSuit.WAN,1,MahjongSuit.WAN,2,MahjongSuit.WAN),5,0,new DealerPolicy(true,true),3);assertTrue(a.flowerPigSeats().isEmpty());}
 @Test void drawAuditChargesNotReadySeatsAndStaysZeroSum(){DrawAudit a=auditDraw(Map.of(0,List.of(11),1,List.of(21),2,List.of(31)),Map.of(),0,0,new DealerPolicy(true,true),1,Set.of(0,2),3);assertEquals(Set.of(1),a.notReadySeats());assertEquals(2,a.callReadyLiabilities().size());assertEquals(-6,a.deltas().get(1));assertEquals(0,a.deltas().values().stream().mapToLong(Long::longValue).sum());}
 @Test void continuationLedgerRotatesSkipsFinishesAndRestores(){ContinuationLedger battle=new ContinuationLedger(false,List.of(0,1,2),0);battle.record(1,2,2);assertEquals(2,battle.currentSeat());ContinuationLedger restored=ContinuationLedger.restore(battle.snapshot());assertFalse(restored.mayOperate(1));restored.record(2,0,2);assertTrue(restored.finished());ContinuationLedger flow=new ContinuationLedger(true,List.of(0,1,2),0);flow.record(1,2,2);flow.record(1,0,4);assertTrue(flow.mayOperate(1));flow.finishWhenWallEmpty(0);assertTrue(flow.finished());assertEquals(List.of(1,2),flow.events().stream().map(WinEvent::sequence).toList());}
 @Test void continuationRestoreRejectsSelfPayBrokenSequenceAndForeignSeat(){assertThrows(IllegalArgumentException.class,()->new WinEvent(1,1,1,1));ContinuationLedger l=new ContinuationLedger(false,List.of(0,1,2),0);l.record(1,2,1);Map<String,Object>broken=new java.util.LinkedHashMap<>(l.snapshot());broken.put("events",List.of(Map.of("sequence",2,"winner",1,"payer",2,"amount",1)));assertThrows(IllegalArgumentException.class,()->ContinuationLedger.restore(broken));broken.put("events",List.of(Map.of("sequence",1,"winner",4,"payer",2,"amount",1)));assertThrows(IllegalArgumentException.class,()->ContinuationLedger.restore(broken));}
 @Test void continuationRequiresCompleteSeatTopology(){assertThrows(IllegalArgumentException.class,()->new ContinuationLedger(false,List.of(),-1));}
 @Test void settlementDetailsPreserveSourcesAndZeroSum(){SettlementDetail d=settle(List.of(0,1,2),List.of(new SettlementLine(1,0,4,"WIN","PURE"),new SettlementLine(2,0,2,"KONG","EXPOSED"),new SettlementLine(0,2,1,"PENALTY","FLOWER_PIG")));assertEquals(0,d.totals().values().stream().mapToLong(Long::longValue).sum());assertEquals(5,d.totals().get(0));assertEquals(List.of("WIN","KONG","PENALTY"),d.lines().stream().map(SettlementLine::category).toList());}
 @Test void settlementRejectsMalformedLinesAndSeats(){assertThrows(IllegalArgumentException.class,()->new SettlementLine(0,1,1,"","SRC"));assertThrows(IllegalArgumentException.class,()->settle(List.of(0,0),List.of()));}
}
