package com.aoo.bcg.luckdraw;

import com.fasterxml.jackson.databind.ObjectMapper;import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import java.security.SecureRandom;import java.sql.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;

final class LuckDrawServiceTest {
    private JdbcDataSource source;private FakeRewards rewards;private LuckDrawService service;
    @BeforeEach void setUp()throws Exception{source=new JdbcDataSource();source.setURL("jdbc:h2:mem:luck"+UUID.randomUUID()+";MODE=MySQL;DB_CLOSE_DELAY=-1");schema();rewards=new FakeRewards();service=new LuckDrawService(source,rewards,new ObjectMapper(),Clock.fixed(Instant.parse("2026-08-24T12:00:00Z"),ZoneOffset.UTC),new SecureRandom(new byte[]{7}));}
    @Test void queryDrawDeductAndReplayWithoutDoubleGrant(){assertEquals(2,service.query(9,"summer").remaining());var first=service.draw("request-1",9,"summer");assertEquals("DELIVERED",first.deliveryState());assertEquals(1,first.remaining());assertEquals(first,service.draw("request-1",9,"summer"));assertEquals(1,rewards.keys.size());assertEquals(1,service.query(9,"summer").remaining());}
    @Test void requestIdRejectsDifferentInputAndChancesAreAtomic(){service.draw("same",9,"summer");assertEquals(LuckDrawService.Code.IDEMPOTENCY_CONFLICT,assertThrows(LuckDrawService.Failure.class,()->service.draw("same",10,"summer")).code());service.draw("second",9,"summer");assertEquals(LuckDrawService.Code.NO_CHANCES,assertThrows(LuckDrawService.Failure.class,()->service.draw("third",9,"summer")).code());}
    @Test void committedOutboxRetriesSameAuthorityKey(){rewards.fail=true;assertEquals(LuckDrawService.Code.REWARD_PENDING,assertThrows(LuckDrawService.Failure.class,()->service.draw("retry",9,"summer")).code());rewards.fail=false;var retried=service.draw("retry",9,"summer");assertEquals("DELIVERED",retried.deliveryState());assertEquals(List.of("luckdraw:1","luckdraw:1"),rewards.attempts);assertEquals(1,service.query(9,"summer").remaining());}
    private void schema()throws Exception{try(var c=source.getConnection();var s=c.createStatement()){s.execute("CREATE TABLE aoo_luck_draw_campaign(id BIGINT AUTO_INCREMENT PRIMARY KEY,campaign_code VARCHAR(64) UNIQUE,campaign_name VARCHAR(128),starts_at TIMESTAMP,ends_at TIMESTAMP,enabled BOOLEAN,daily_free_count BIGINT)");s.execute("CREATE TABLE aoo_luck_draw_prize(id BIGINT AUTO_INCREMENT PRIMARY KEY,campaign_id BIGINT,prize_code VARCHAR(64),prize_name VARCHAR(128),reward_kind VARCHAR(16),reward_code VARCHAR(64),reward_amount BIGINT,weight BIGINT,enabled BOOLEAN)");s.execute("CREATE TABLE aoo_luck_draw_chance(player_id BIGINT,campaign_id BIGINT,business_date DATE,remaining_count BIGINT,version BIGINT,updated_at TIMESTAMP,PRIMARY KEY(player_id,campaign_id,business_date))");s.execute("CREATE TABLE aoo_luck_draw(id BIGINT AUTO_INCREMENT PRIMARY KEY,request_id VARCHAR(128) UNIQUE,request_fingerprint VARCHAR(160),player_id BIGINT,campaign_id BIGINT,campaign_code VARCHAR(64),prize_id BIGINT,prize_code VARCHAR(64),prize_name VARCHAR(128),reward_kind VARCHAR(16),reward_code VARCHAR(64),reward_amount BIGINT,remaining_count BIGINT,created_at TIMESTAMP)");s.execute("CREATE TABLE aoo_luck_draw_outbox(draw_id BIGINT PRIMARY KEY,event_key VARCHAR(160) UNIQUE,event_type VARCHAR(64),payload_json JSON,status VARCHAR(16),attempt_count INT,next_attempt_at TIMESTAMP,last_error VARCHAR(500),created_at TIMESTAMP,updated_at TIMESTAMP)");s.execute("INSERT INTO aoo_luck_draw_campaign(campaign_code,campaign_name,starts_at,ends_at,enabled,daily_free_count) VALUES('summer','Summer','2026-08-01','2026-09-01',TRUE,2)");s.execute("INSERT INTO aoo_luck_draw_prize(campaign_id,prize_code,prize_name,reward_kind,reward_code,reward_amount,weight,enabled) VALUES(1,'gold','Gold','CURRENCY','GOLD',100,1,TRUE)");}}
    private static final class FakeRewards implements LuckDrawPorts.RewardPort{boolean fail;final List<String>attempts=new ArrayList<>(),keys=new ArrayList<>();public void creditCurrency(String k,long p,String c,long a){attempts.add(k);if(fail)throw new IllegalStateException("down");keys.add(k);}public void grantItem(String k,long p,String i,long a){creditCurrency(k,p,i,a);}}
}
