CREATE TABLE aoo_room_id_sequence (
 room_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 created_at DATETIME(3) NOT NULL,
 PRIMARY KEY(room_id)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
