CREATE TABLE IF NOT EXISTS player_profile (
    player_id BIGINT NOT NULL,
    nickname VARCHAR(96) NOT NULL,
    avatar_asset_id BIGINT NULL,
    gender_code VARCHAR(16) NOT NULL DEFAULT 'UNSPECIFIED',
    region_code VARCHAR(16) NOT NULL DEFAULT '',
    language_code VARCHAR(35) NOT NULL DEFAULT 'en',
    sound_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    music_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    vibration_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    show_gender BOOLEAN NOT NULL DEFAULT FALSE,
    show_region BOOLEAN NOT NULL DEFAULT FALSE,
    nickname_changed_at TIMESTAMP(3) NULL,
    avatar_changed_at TIMESTAMP(3) NULL,
    profile_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (player_id),
    KEY idx_player_profile_nickname (nickname),
    KEY idx_player_profile_avatar (avatar_asset_id),
    CONSTRAINT fk_player_profile_account FOREIGN KEY (player_id) REFERENCES aoo_account(account_id),
    CONSTRAINT fk_player_profile_avatar FOREIGN KEY (avatar_asset_id) REFERENCES media_asset(id),
    CONSTRAINT ck_player_profile_version CHECK (profile_version >= 0),
    CONSTRAINT ck_player_profile_gender CHECK (gender_code IN ('UNSPECIFIED','FEMALE','MALE','NON_BINARY'))
);
