-- Publish CD299 room-create fields from the read-only workbook
-- Client/docs/开房规则表/扯旋/成都扯旋CD299.xlsx.
-- Source SHA-256: f0ab5905c39adf0ed0d9026684b74a7c238f47743ff31d5b8a3d36d7dabf81c7

SET @cd299_release_id = 6302026091906;
SET @cd299_generation = 2026091906;

SET @cd299_ui_fields = JSON_ARRAY(
  JSON_OBJECT('key','roomDurationMinutes','label','房间时长','order',10,'control','radio','visible',true,'disabled',false,'required',true,'defaultValue',30,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','30分钟','value',30,'order',10,'disabled',false),JSON_OBJECT('label','45分钟','value',45,'order',20,'disabled',false),JSON_OBJECT('label','60分钟','value',60,'order',30,'disabled',false))),
  JSON_OBJECT('key','startPlayers','label','开局人数','order',20,'control','radio','visible',true,'disabled',false,'required',true,'defaultValue',2,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','2人','value',2,'order',10,'disabled',false),JSON_OBJECT('label','4人','value',4,'order',20,'disabled',false),JSON_OBJECT('label','6人','value',6,'order',30,'disabled',false))),
  JSON_OBJECT('key','operationSeconds','label','操作时间','order',30,'control','radio','visible',true,'disabled',false,'required',true,'defaultValue',10,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','10秒','value',10,'order',10,'disabled',false),JSON_OBJECT('label','15秒','value',15,'order',20,'disabled',false),JSON_OBJECT('label','30秒','value',30,'order',30,'disabled',false))),
  JSON_OBJECT('key','standPolicy','label','站起规则','order',40,'control','radio','visible',true,'disabled',false,'required',true,'defaultValue','LOSER_ONLY','trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','输家可站起','value','LOSER_ONLY','order',10,'disabled',false),JSON_OBJECT('label','所有人可站起','value','EVERYONE','order',20,'disabled',false),JSON_OBJECT('label','所有人不可站起','value','NOBODY','order',30,'disabled',false))),
  JSON_OBJECT('key','mangoFlipMode','label','芒果翻法','order',50,'control','radio','visible',true,'disabled',false,'required',true,'defaultValue','LADDER','trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','梯翻','value','LADDER','order',10,'disabled',false),JSON_OBJECT('label','滚翻','value','ROLLING','order',20,'disabled',false))),
  JSON_OBJECT('key','mangoRaise','label','升芒','order',60,'control','radio','visible',true,'disabled',false,'required',true,'defaultValue',3,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(4),'options',JSON_ARRAY(JSON_OBJECT('label','不升','value',0,'order',10,'disabled',false),JSON_OBJECT('label','1芒','value',1,'order',20,'disabled',false),JSON_OBJECT('label','2芒','value',2,'order',30,'disabled',false),JSON_OBJECT('label','3芒','value',3,'order',40,'disabled',false),JSON_OBJECT('label','4芒','value',4,'order',50,'disabled',false),JSON_OBJECT('label','5芒','value',5,'order',60,'disabled',false))),
  JSON_OBJECT('key','mangoScore','label','芒果分数','order',70,'control','number','visible',true,'disabled',false,'required',true,'defaultValue',3,'trusteeCount',3,'min',0,'max',2147483647,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','openingBet','label','发招分数（发招分数不低于芒果分数）','order',80,'control','number','visible',true,'disabled',false,'required',true,'defaultValue',3,'trusteeCount',3,'min',0,'max',2147483647,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','restMango','label','休芒','order',90,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',true,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','休芒','value',true,'order',10,'disabled',false))),
  JSON_OBJECT('key','beatMango','label','揍芒','order',100,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',true,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','揍芒','value',true,'order',10,'disabled',false))),
  JSON_OBJECT('key','everyHandMango','label','手手芒','order',110,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',true,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','手手芒','value',true,'order',10,'disabled',false))),
  JSON_OBJECT('key','firstRoundCanRest','label','首轮可休','order',120,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',true,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','首轮可休','value',true,'order',10,'disabled',false))),
  JSON_OBJECT('key','eachPlayerMustFollow','label','挨家必挨','order',130,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',false,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(),'options',JSON_ARRAY(JSON_OBJECT('label','挨家必挨','value',true,'order',10,'disabled',false))),
  JSON_OBJECT('key','earthNineKing','label','地九王','order',140,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',true,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','地九王','value',true,'order',10,'disabled',false))),
  JSON_OBJECT('key','fireproofCard','label','防火牌','order',150,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',true,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(1),'options',JSON_ARRAY(JSON_OBJECT('label','防火牌','value',true,'order',10,'disabled',false))),
  JSON_OBJECT('key','bigHeadKeepsBase','label','头大不输底','order',160,'control','checkbox','visible',true,'disabled',false,'required',false,'defaultValue',false,'trusteeCount',3,'defaultCandidateIndexes',JSON_ARRAY(),'options',JSON_ARRAY(JSON_OBJECT('label','头大不输底','value',true,'order',10,'disabled',false)))
);

SET @cd299_validator_fields = JSON_MERGE_PRESERVE(JSON_EXTRACT(@cd299_ui_fields,'$'), JSON_ARRAY(
  JSON_OBJECT('key','maxPlayers','control','number','disabled',true,'required',true,'defaultValue',8,'min',8,'max',8,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','splitSeconds','control','number','disabled',true,'required',true,'defaultValue',30,'min',30,'max',30,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','splitExtensionSeconds','control','number','disabled',true,'required',true,'defaultValue',30,'min',30,'max',30,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','splitExtensionLimit','control','number','disabled',true,'required',true,'defaultValue',1,'min',1,'max',1,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','seatConfirmationSeconds','control','number','disabled',true,'required',true,'defaultValue',30,'min',30,'max',30,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','seatRetentionSeconds','control','number','disabled',true,'required',true,'defaultValue',120,'min',120,'max',120,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','autoOperateAfterTimeouts','control','number','disabled',true,'required',true,'defaultValue',3,'min',3,'max',3,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','spectatorEntry','control','checkbox','disabled',true,'required',true,'defaultValue',true,'options',JSON_ARRAY(true)),
  JSON_OBJECT('key','autoReady','control','checkbox','disabled',true,'required',true,'defaultValue',true,'options',JSON_ARRAY(true)),
  JSON_OBJECT('key','supplementNextRound','control','checkbox','disabled',true,'required',true,'defaultValue',true,'options',JSON_ARRAY(true)),
  JSON_OBJECT('key','mute','control','checkbox','disabled',true,'required',true,'defaultValue',true,'options',JSON_ARRAY(true)),
  JSON_OBJECT('key','interactionDisabled','control','checkbox','disabled',true,'required',true,'defaultValue',false,'options',JSON_ARRAY(true)),
  JSON_OBJECT('key','distanceTips','control','checkbox','disabled',true,'required',true,'defaultValue',true,'options',JSON_ARRAY(true)),
  JSON_OBJECT('key','hostingMissThreshold','control','number','disabled',true,'required',true,'defaultValue',3,'min',3,'max',3,'step',1,'options',JSON_ARRAY()),
  JSON_OBJECT('key','payerMode','control','radio','disabled',false,'required',true,'defaultValue','OWNER','options',JSON_ARRAY('OWNER'))
));

SET @cd299_validator = JSON_OBJECT('gameCode','CD299','playVersion','cd299-v1.0.0','roomMeasureKind','DURATION_MINUTES','source','成都扯旋CD299.xlsx','sourceHash','f0ab5905c39adf0ed0d9026684b74a7c238f47743ff31d5b8a3d36d7dabf81c7','fields',JSON_EXTRACT(@cd299_validator_fields,'$'));
SET @cd299_ui = JSON_OBJECT('bundle','poker-cx','scene','GameRoom2D','playFamily','poker:cd299','landscapePrefab','CD299/Prefab/Landscape/CD299RoomLandscape','portraitPrefab','CD299/Prefab/Portrait/CD299RoomPortrait','roomRuleSourceHash','f0ab5905c39adf0ed0d9026684b74a7c238f47743ff31d5b8a3d36d7dabf81c7','fields',JSON_EXTRACT(@cd299_ui_fields,'$'));

INSERT IGNORE INTO aoo_game_release(release_id,game_id,play_version,release_version,release_scope,catalog_snapshot,rule_snapshot,ui_snapshot,component_snapshot,catalog_hash,rule_hash,ui_hash,component_hash,bundle_hash,status,rollout_percent,created_by,reason,validated_at,activated_at)
VALUES(@cd299_release_id,630,'cd299-v1.0.0',4,'REGIONAL',JSON_OBJECT('gameId',630,'gameCode','CD299','family','poker:cd299'),@cd299_validator,@cd299_ui,JSON_OBJECT('factory','com.aoo.bcg.poker.cd299.Cd299ProviderFactory'),SHA2('CD299-catalog-v4',256),SHA2(CAST(@cd299_validator AS CHAR),256),SHA2(CAST(@cd299_ui AS CHAR),256),SHA2('CD299-components-v4',256),SHA2('CD299-runtime-poker-cx-v4',256),'ACTIVE',100,1,'Publish CD299 authoritative room-create schema',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3));
INSERT IGNORE INTO aoo_game_release_region(release_id,region_code,rollout_percent,status) VALUES(@cd299_release_id,'CN-51-01',100,'ACTIVE');
INSERT IGNORE INTO aoo_compiled_room_create_index(game_id,region_code,play_version,index_generation,release_id,component_chain,rule_validator,ui_schema,lookup_hash,bundle_hash,lifecycle_state,compiled_at,validated_at,activated_at)
VALUES(630,'CN-51-01','cd299-v1.0.0',@cd299_generation,@cd299_release_id,JSON_ARRAY('com.aoo.bcg.poker.cd299.Cd299ProviderFactory@cd299-v1.0.0'),@cd299_validator,@cd299_ui,SHA2(CONCAT('CD299|',@cd299_generation,'|',CAST(@cd299_validator AS CHAR)),256),SHA2('CD299-runtime-poker-cx-v4',256),'ACTIVE',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3));
UPDATE aoo_compiled_index_active SET index_generation=@cd299_generation,release_id=@cd299_release_id,cache_epoch=cache_epoch+1,activated_by=1,activation_reason='Activate CD299 authoritative room-create schema',activated_at=CURRENT_TIMESTAMP(3) WHERE game_id=630 AND region_code='CN-51-01' AND play_version='cd299-v1.0.0';
UPDATE aoo_compiled_room_create_index SET lifecycle_state='RETIRED',retired_at=CURRENT_TIMESTAMP(3) WHERE game_id=630 AND region_code='CN-51-01' AND play_version='cd299-v1.0.0' AND index_generation<>@cd299_generation AND lifecycle_state='ACTIVE';
UPDATE aoo_game_release SET status='RETIRED',retired_at=CURRENT_TIMESTAMP(3) WHERE game_id=630 AND play_version='cd299-v1.0.0' AND release_id<>@cd299_release_id AND status='ACTIVE';
