package com.aoo.bcg.identity;
import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.util.Map;
public final class IdentityVerificationHttpRoutes {
 public interface Authenticator{long authenticate(String bearer,String device,String channel,String version,String ip);}
 private final JdbcIdentityVerificationService service;private final Authenticator auth;private final ObjectMapper json;
 public IdentityVerificationHttpRoutes(JdbcIdentityVerificationService service,Authenticator auth,ObjectMapper json){this.service=service;this.auth=auth;this.json=json;}
 public void mount(HttpServer s){s.createContext("/health/identity-verification",e->reply(e,200,Map.of("code","OK","data",Map.of("status","UP","persistence","jdbc"))));s.createContext("/v1/identity-verification/status",e->handle(e,()->{method(e,"GET");return service.status(account(e));}));s.createContext("/v1/identity-verification/real-name/submissions",e->handle(e,()->{method(e,"POST");return service.submitRealName(account(e),key(e),json.readValue(e.getRequestBody(),JdbcIdentityVerificationService.RealNameRequest.class),ip(e));}));s.createContext("/v1/identity-verification/phone/challenges/verify",e->handle(e,()->{method(e,"POST");return service.verifyPhone(account(e),key(e),json.readValue(e.getRequestBody(),JdbcIdentityVerificationService.VerifyRequest.class),ip(e));}));s.createContext("/v1/identity-verification/phone/challenges",e->handle(e,()->{method(e,"POST");return service.sendPhone(account(e),key(e),json.readValue(e.getRequestBody(),JdbcIdentityVerificationService.PhoneRequest.class),ip(e));}));}
 private long account(HttpExchange e){return auth.authenticate(e.getRequestHeaders().getFirst("Authorization"),e.getRequestHeaders().getFirst("X-Device-Id"),e.getRequestHeaders().getFirst("X-Channel"),e.getRequestHeaders().getFirst("X-Client-Version"),ip(e));}private static String ip(HttpExchange e){return e.getRemoteAddress()==null?"":e.getRemoteAddress().getAddress().getHostAddress();}private static String key(HttpExchange e){return e.getRequestHeaders().getFirst("Idempotency-Key");}private static void method(HttpExchange e,String expected){if(!expected.equals(e.getRequestMethod()))throw new IdentityError(405,"IDENTITY_METHOD_NOT_ALLOWED",expected+" required");}
 private void handle(HttpExchange e,Action action)throws IOException{try{if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw new IdentityError(426,"IDENTITY_API_VERSION_REQUIRED","X-API-Version: 1 required");reply(e,200,Map.of("code","OK","data",action.run()));}catch(IdentityError x){reply(e,x.status,Map.of("code",x.code,"message",x.getMessage()));}catch(SecurityException x){reply(e,401,Map.of("code","IDENTITY_UNAUTHORIZED","message","valid account session required"));}catch(com.fasterxml.jackson.core.JacksonException x){reply(e,400,Map.of("code","IDENTITY_INVALID_JSON","message","valid JSON body required"));}catch(IllegalStateException x){reply(e,503,Map.of("code","IDENTITY_SERVICE_UNAVAILABLE","message","identity verification temporarily unavailable"));}}
 private void reply(HttpExchange e,int status,Object body)throws IOException{byte[] b=json.writeValueAsBytes(body);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.getResponseHeaders().set("Pragma","no-cache");e.getResponseHeaders().set("X-Content-Type-Options","nosniff");e.sendResponseHeaders(status,b.length);try(OutputStream out=e.getResponseBody()){out.write(b);}}@FunctionalInterface interface Action{Object run()throws IOException;}
}
