package com.aoo.bcg.identity;

import com.fasterxml.jackson.databind.ObjectMapper;
import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.sql.*;
import java.time.*;
import java.util.*;

/** Transactional authority for real-name and phone verification. Raw identifiers never leave encrypted columns. */
public final class JdbcIdentityVerificationService {
    private final DataSource db;private final IdentityCrypto crypto;private final PhoneCodeSender sender;private final ObjectMapper json;private final Clock clock;private final SecureRandom random;
    public JdbcIdentityVerificationService(DataSource db,IdentityCrypto crypto,PhoneCodeSender sender,ObjectMapper json,Clock clock,SecureRandom random){this.db=db;this.crypto=crypto;this.sender=sender;this.json=json;this.clock=clock;this.random=random;}
    public record Status(String realNameStatus,String maskedName,String maskedIdNumber,boolean phoneVerified,String maskedPhone,Instant updatedAt){}
    public record RealNameRequest(String legalName,String idNumber){}
    public record PhoneRequest(String phone){}
    public record VerifyRequest(String challengeId,String code){}
    public record Challenge(String challengeId,Instant expiresAt,long retryAfterSeconds){}
    public record Credential(String credential,Instant expiresAt,String maskedPhone){}

    public Status status(long accountId){try(Connection c=db.getConnection();PreparedStatement q=c.prepareStatement("SELECT real_name_status,masked_name,masked_id_number,phone_verified,masked_phone,updated_at FROM aoo_identity_verification WHERE account_id=?")){q.setLong(1,accountId);try(ResultSet r=q.executeQuery()){if(!r.next())return new Status("UNSUBMITTED","","",false,"",null);return new Status(r.getString(1),empty(r.getString(2)),empty(r.getString(3)),r.getBoolean(4),empty(r.getString(5)),instant(r.getTimestamp(6)));}}catch(SQLException e){throw database(e);}}
    public Status submitRealName(long accountId,String idempotencyKey,RealNameRequest request,String ip){
        String name=normalizeName(request==null?null:request.legalName()),id=normalizeId(request==null?null:request.idNumber());requireKey(idempotencyKey);String fingerprint=crypto.token("real-name-request",name+'\0'+id);
        try(Connection c=db.getConnection()){c.setAutoCommit(false);try{
            String cached=idempotency(c,accountId,"REAL_NAME",idempotencyKey,fingerprint);if(cached!=null){c.commit();return json.readValue(cached,Status.class);}
            String idToken=crypto.token("government-id",id);try(PreparedStatement q=c.prepareStatement("SELECT account_id FROM aoo_identity_verification WHERE id_token=? AND account_id<>?")){q.setString(1,idToken);q.setLong(2,accountId);try(ResultSet r=q.executeQuery()){if(r.next())throw new IdentityError(409,"IDENTITY_DOCUMENT_IN_USE","identity document is already bound");}}
            try(PreparedStatement u=c.prepareStatement("INSERT INTO aoo_identity_verification(account_id,real_name_status,legal_name_cipher,id_number_cipher,id_token,masked_name,masked_id_number,phone_verified,updated_at) VALUES(?,?,?,?,?,?,?,FALSE,?) ON DUPLICATE KEY UPDATE real_name_status=VALUES(real_name_status),legal_name_cipher=VALUES(legal_name_cipher),id_number_cipher=VALUES(id_number_cipher),id_token=VALUES(id_token),masked_name=VALUES(masked_name),masked_id_number=VALUES(masked_id_number),updated_at=VALUES(updated_at)")){u.setLong(1,accountId);u.setString(2,"PENDING");u.setString(3,crypto.encrypt(name));u.setString(4,crypto.encrypt(id));u.setString(5,idToken);u.setString(6,IdentityCrypto.maskName(name));u.setString(7,IdentityCrypto.maskId(id));u.setTimestamp(8,Timestamp.from(clock.instant()));u.executeUpdate();}
            audit(c,accountId,"REAL_NAME_SUBMITTED",ip,Map.of("idToken",idToken));Status out=status(c,accountId);saveIdempotency(c,accountId,"REAL_NAME",idempotencyKey,fingerprint,json.writeValueAsString(out));c.commit();return out;
        }catch(Exception e){rollback(c);throw map(e);}}catch(SQLException e){throw database(e);}}
    public Challenge sendPhone(long accountId,String idempotencyKey,PhoneRequest request,String ip){
        requireKey(idempotencyKey);String phone=normalizePhone(request==null?null:request.phone());String fingerprint=crypto.token("phone-request",phone);
        try(Connection c=db.getConnection()){c.setAutoCommit(false);try{
            String cached=idempotency(c,accountId,"PHONE_SEND",idempotencyKey,fingerprint);if(cached!=null){c.commit();return json.readValue(cached,Challenge.class);}Instant now=clock.instant();
            try(PreparedStatement q=c.prepareStatement("SELECT COUNT(*) FROM aoo_phone_challenge WHERE account_id=? AND created_at>?")){q.setLong(1,accountId);q.setTimestamp(2,Timestamp.from(now.minus(Duration.ofMinutes(10))));try(ResultSet r=q.executeQuery()){r.next();if(r.getInt(1)>=5)throw IdentityError.rate();}}
            String phoneToken=crypto.token("phone",phone);try(PreparedStatement q=c.prepareStatement("SELECT COUNT(*) FROM aoo_phone_challenge WHERE phone_token=? AND created_at>?")){q.setString(1,phoneToken);q.setTimestamp(2,Timestamp.from(now.minus(Duration.ofHours(1))));try(ResultSet r=q.executeQuery()){r.next();if(r.getInt(1)>=10)throw IdentityError.rate();}}
            String challenge=UUID.randomUUID().toString(),code=String.format("%06d",random.nextInt(1_000_000));Instant expires=now.plus(Duration.ofMinutes(5));
            try(PreparedStatement i=c.prepareStatement("INSERT INTO aoo_phone_challenge(challenge_id,account_id,phone_cipher,phone_token,masked_phone,code_hash,attempts,expires_at,created_at) VALUES(?,?,?,?,?,?,0,?,?)")){i.setString(1,challenge);i.setLong(2,accountId);i.setString(3,crypto.encrypt(phone));i.setString(4,phoneToken);i.setString(5,IdentityCrypto.maskPhone(phone));i.setString(6,crypto.codeHash(challenge,code));i.setTimestamp(7,Timestamp.from(expires));i.setTimestamp(8,Timestamp.from(now));i.executeUpdate();}
            sender.send(phone,code,challenge);Challenge out=new Challenge(challenge,expires,60);saveIdempotency(c,accountId,"PHONE_SEND",idempotencyKey,fingerprint,json.writeValueAsString(out));audit(c,accountId,"PHONE_CODE_SENT",ip,Map.of("challengeId",challenge,"phoneToken",phoneToken));c.commit();return out;
        }catch(Exception e){rollback(c);throw map(e);}}catch(SQLException e){throw database(e);}}
    public Credential verifyPhone(long accountId,String idempotencyKey,VerifyRequest request,String ip){
        requireKey(idempotencyKey);if(request==null||request.challengeId()==null||request.code()==null||!request.code().matches("[0-9]{6}"))throw IdentityError.invalid("challengeId and six digit code required");String fingerprint=crypto.token("phone-verify-request",request.challengeId()+'\0'+request.code());
        try(Connection c=db.getConnection()){c.setAutoCommit(false);try{String cached=idempotency(c,accountId,"PHONE_VERIFY",idempotencyKey,fingerprint);if(cached!=null){c.commit();return json.readValue(cached,Credential.class);}Instant now=clock.instant();String masked,expected;
            try(PreparedStatement q=c.prepareStatement("SELECT code_hash,masked_phone,attempts,expires_at,verified_at FROM aoo_phone_challenge WHERE challenge_id=? AND account_id=? FOR UPDATE")){q.setString(1,request.challengeId());q.setLong(2,accountId);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IdentityError(404,"IDENTITY_CHALLENGE_NOT_FOUND","phone challenge not found");expected=r.getString(1);masked=r.getString(2);if(r.getTimestamp(5)!=null)throw new IdentityError(409,"IDENTITY_CHALLENGE_USED","phone challenge already used");if(r.getInt(3)>=5)throw new IdentityError(429,"IDENTITY_ATTEMPTS_EXCEEDED","verification attempts exceeded");if(!r.getTimestamp(4).toInstant().isAfter(now))throw new IdentityError(410,"IDENTITY_CHALLENGE_EXPIRED","phone challenge expired");}}
            if(!IdentityCrypto.equal(expected,crypto.codeHash(request.challengeId(),request.code()))){try(PreparedStatement u=c.prepareStatement("UPDATE aoo_phone_challenge SET attempts=attempts+1 WHERE challenge_id=?")){u.setString(1,request.challengeId());u.executeUpdate();}audit(c,accountId,"PHONE_CODE_REJECTED",ip,Map.of("challengeId",request.challengeId()));c.commit();throw new IdentityError(400,"IDENTITY_CODE_INVALID","verification code invalid");}
            try(PreparedStatement u=c.prepareStatement("UPDATE aoo_phone_challenge SET verified_at=? WHERE challenge_id=?")){u.setTimestamp(1,Timestamp.from(now));u.setString(2,request.challengeId());u.executeUpdate();}
            try(PreparedStatement u=c.prepareStatement("INSERT INTO aoo_identity_verification(account_id,real_name_status,phone_verified,masked_phone,phone_token,updated_at) SELECT account_id,'UNSUBMITTED',TRUE,masked_phone,phone_token,? FROM aoo_phone_challenge WHERE challenge_id=? ON DUPLICATE KEY UPDATE phone_verified=TRUE,masked_phone=VALUES(masked_phone),phone_token=VALUES(phone_token),updated_at=VALUES(updated_at)")){u.setTimestamp(1,Timestamp.from(now));u.setString(2,request.challengeId());u.executeUpdate();}
            Instant expiry=now.plus(Duration.ofMinutes(10));String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(random.generateSeed(32));String token=crypto.token("short-credential",raw);try(PreparedStatement i=c.prepareStatement("INSERT INTO aoo_identity_credential(credential_token,account_id,purpose,expires_at,created_at) VALUES(?,?,'PHONE_VERIFIED',?,?)")){i.setString(1,token);i.setLong(2,accountId);i.setTimestamp(3,Timestamp.from(expiry));i.setTimestamp(4,Timestamp.from(now));i.executeUpdate();}
            Credential out=new Credential(raw,expiry,masked);saveIdempotency(c,accountId,"PHONE_VERIFY",idempotencyKey,fingerprint,json.writeValueAsString(out));audit(c,accountId,"PHONE_VERIFIED",ip,Map.of("challengeId",request.challengeId()));c.commit();return out;
        }catch(Exception e){rollback(c);throw map(e);}}catch(SQLException e){throw database(e);}}
    private Status status(Connection c,long id)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT real_name_status,masked_name,masked_id_number,phone_verified,masked_phone,updated_at FROM aoo_identity_verification WHERE account_id=?")){q.setLong(1,id);try(ResultSet r=q.executeQuery()){r.next();return new Status(r.getString(1),empty(r.getString(2)),empty(r.getString(3)),r.getBoolean(4),empty(r.getString(5)),instant(r.getTimestamp(6)));}}}
    private String idempotency(Connection c,long a,String scope,String key,String fingerprint)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT request_fingerprint,response_cipher FROM aoo_identity_idempotency WHERE account_id=? AND operation_scope=? AND idempotency_key=?")){q.setLong(1,a);q.setString(2,scope);q.setString(3,key);try(ResultSet r=q.executeQuery()){if(!r.next())return null;if(!IdentityCrypto.equal(r.getString(1),fingerprint))throw new IdentityError(409,"IDENTITY_IDEMPOTENCY_CONFLICT","idempotency key reused with different request");return crypto.decrypt(r.getString(2));}}}
    private void saveIdempotency(Connection c,long a,String s,String k,String f,String response)throws SQLException{try(PreparedStatement i=c.prepareStatement("INSERT INTO aoo_identity_idempotency(account_id,operation_scope,idempotency_key,request_fingerprint,response_cipher,created_at) VALUES(?,?,?,?,?,?)")){i.setLong(1,a);i.setString(2,s);i.setString(3,k);i.setString(4,f);i.setString(5,crypto.encrypt(response));i.setTimestamp(6,Timestamp.from(clock.instant()));i.executeUpdate();}}
    private void audit(Connection c,long a,String action,String ip,Object details)throws Exception{try(PreparedStatement i=c.prepareStatement("INSERT INTO aoo_identity_audit(account_id,action,ip_token,details_json,created_at) VALUES(?,?,?,?,?)")){i.setLong(1,a);i.setString(2,action);i.setString(3,crypto.token("ip",ip==null?"":ip));i.setString(4,json.writeValueAsString(details));i.setTimestamp(5,Timestamp.from(clock.instant()));i.executeUpdate();}}
    private static String normalizeName(String v){if(v==null||v.strip().length()<2||v.strip().length()>64)throw IdentityError.invalid("legalName length must be 2..64");return v.strip();}private static String normalizeId(String v){if(v==null||!v.strip().toUpperCase(Locale.ROOT).matches("[0-9]{17}[0-9X]"))throw IdentityError.invalid("idNumber must be a valid 18-character format");return v.strip().toUpperCase(Locale.ROOT);}private static String normalizePhone(String v){if(v==null||!v.strip().matches("\\+?[1-9][0-9]{7,14}"))throw IdentityError.invalid("phone must be E.164 compatible");return v.strip();}private static void requireKey(String v){if(v==null||!v.matches("[A-Za-z0-9._:-]{8,128}"))throw IdentityError.invalid("valid Idempotency-Key required");}
    private static RuntimeException database(SQLException e){return new IllegalStateException("identity persistence unavailable",e);}private static RuntimeException map(Exception e){if(e instanceof RuntimeException r)return r;return new IllegalStateException("identity operation failed",e);}private static void rollback(Connection c){try{c.rollback();}catch(SQLException ignored){}}private static String empty(String v){return v==null?"":v;}private static Instant instant(Timestamp v){return v==null?null:v.toInstant();}
}
