<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.aoo.bcg</groupId><artifactId>aoo-server-parent</artifactId><version>${revision}</version><relativePath>../../pom.xml</relativePath></parent>
    <artifactId>game-hall</artifactId>
    <name>Aoo Hall Application Boundary</name>
    <dependencies>
        <dependency><groupId>com.aoo.bcg</groupId><artifactId>game-common</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.aoo.bcg</groupId><artifactId>game-spi</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.aoo.bcg</groupId><artifactId>game-config-center</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.aoo.bcg</groupId><artifactId>account-domain</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId></dependency>
        <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
    </dependencies>
    <build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId></plugin><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-jar-plugin</artifactId></plugin></plugins></build>
</project>
