package com.aoo.bcg.poker;
import java.util.*;
/** Shared authoritative betting/folding/comparison state and private-card perspective. */
public final class ComparePokerEngine{
 public ComparePokerState bet(ComparePokerState state,int seat,long amount){requireTurn(state,seat);if(amount<=0)throw new IllegalArgumentException("bet must be positive");ComparePokerSeat old=active(state,seat);if(old.balance()<amount)throw new IllegalStateException("insufficient balance");Map<Integer,ComparePokerSeat> seats=new HashMap<>(state.seats());seats.put(seat,new ComparePokerSeat(old.playerId(),old.privateCards(),old.balance()-amount,Math.addExact(old.committed(),amount),false,false));return advance(state,seats,Math.addExact(state.pot(),amount));}
 public ComparePokerState fold(ComparePokerState state,int seat){requireTurn(state,seat);ComparePokerSeat old=active(state,seat);Map<Integer,ComparePokerSeat> seats=new HashMap<>(state.seats());seats.put(seat,new ComparePokerSeat(old.playerId(),old.privateCards(),old.balance(),old.committed(),true,false));return advance(state,seats,state.pot());}
 public ComparePokerState compare(ComparePokerState state,int challenger,int target,Comparator<List<Integer>> comparator){requireTurn(state,challenger);active(state,challenger);active(state,target);int loser=comparator.compare(state.seats().get(challenger).privateCards(),state.seats().get(target).privateCards())>=0?target:challenger;Map<Integer,ComparePokerSeat> seats=new HashMap<>(state.seats());ComparePokerSeat old=seats.get(loser);seats.put(loser,new ComparePokerSeat(old.playerId(),old.privateCards(),old.balance(),old.committed(),old.folded(),true));return advance(state,seats,state.pot());}
 public ComparePokerView viewFor(ComparePokerState state,long viewerPlayerId){Map<Integer,ComparePokerView.SeatView> views=new HashMap<>();state.seats().forEach((seat,value)->{boolean own=value.playerId()==viewerPlayerId;views.put(seat,new ComparePokerView.SeatView(value.playerId(),own?value.privateCards():List.of(),value.privateCards().size(),value.committed(),value.folded(),value.eliminated()));});return new ComparePokerView(state.currentSeat(),state.pot(),views,state.finished(),state.winnerSeat());}
 private static ComparePokerState advance(ComparePokerState state,Map<Integer,ComparePokerSeat> seats,long pot){List<Integer> active=seats.entrySet().stream().filter(e->!e.getValue().folded()&&!e.getValue().eliminated()).map(Map.Entry::getKey).sorted().toList();if(active.size()==1)return new ComparePokerState(seats,active.get(0),pot,true,active.get(0));List<Integer> all=seats.keySet().stream().sorted().toList();int next=state.currentSeat();do{next=all.get((all.indexOf(next)+1)%all.size());}while(!active.contains(next));return new ComparePokerState(seats,next,pot,false,null);}
 private static ComparePokerSeat active(ComparePokerState s,int seat){ComparePokerSeat value=s.seats().get(seat);if(value==null||value.folded()||value.eliminated())throw new IllegalStateException("seat is not active");return value;}private static void requireTurn(ComparePokerState s,int seat){if(s.finished()||s.currentSeat()!=seat)throw new IllegalStateException("not current seat");}
}
record ComparePokerSeat(long playerId,List<Integer>privateCards,long balance,long committed,boolean folded,boolean eliminated){ComparePokerSeat{if(playerId<=0||balance<0||committed<0)throw new IllegalArgumentException("invalid compare-poker seat");privateCards=List.copyOf(privateCards);}}
record ComparePokerState(Map<Integer,ComparePokerSeat>seats,int currentSeat,long pot,boolean finished,Integer winnerSeat){ComparePokerState{seats=Map.copyOf(seats);if(seats.size()<2||!seats.containsKey(currentSeat)||pot<0)throw new IllegalArgumentException("invalid compare-poker state");}}
record ComparePokerView(int currentSeat,long pot,Map<Integer,SeatView>seats,boolean finished,Integer winnerSeat){ComparePokerView{seats=Map.copyOf(seats);}record SeatView(long playerId,List<Integer>visibleCards,int cardCount,long committed,boolean folded,boolean eliminated){SeatView{visibleCards=List.copyOf(visibleCards);}}}
