package com.aoo.bcg.poker;
import java.util.*;
/** Configurable Paodekuai combinations shared by all regional variants. */
public final class PaoDeKuaiRuleSet implements PokerRuleSet<PaoDeKuaiContext>{
 private final PaoDeKuaiConfig config; private final PokerRuleProfile profile; private final StandardPokerRuleSet<PaoDeKuaiContext> basic=new StandardPokerRuleSet<>();
 public PaoDeKuaiRuleSet(PaoDeKuaiConfig config){this(config,PokerRuleProfile.fromConfig("pdk-v1",52,config));}public PaoDeKuaiRuleSet(PaoDeKuaiConfig config,PokerRuleProfile profile){this.config=Objects.requireNonNull(config);this.profile=Objects.requireNonNull(profile);}
 public PaoDeKuaiConfig config(){return config;}
 public CardCombination recognize(List<Integer> cards,PaoDeKuaiContext context){
  Map<Integer,Long> counts=new TreeMap<>();cards.forEach(card->counts.merge(StandardPokerRuleSet.rank(card),1L,Long::sum));int size=cards.size();Integer special=counts.entrySet().stream().filter(e->config.specialTripleBombRanks().contains(e.getKey())&&e.getValue()==3).map(Map.Entry::getKey).findFirst().orElse(null);if(special!=null){if(size==3)return new CardCombination("SPECIAL_TRIPLE_BOMB",special,cards);if(size==4&&config.allowSpecialTripleBombWithOne())return new CardCombination("SPECIAL_TRIPLE_BOMB_WITH_ONE",special,cards);}if(config.allowConsecutiveBomb()&&size>=8&&size%4==0&&counts.values().stream().allMatch(value->value==4)&&legalRun(counts.keySet(),2))return new CardCombination("CONSECUTIVE_BOMB",counts.keySet().stream().max(Integer::compareTo).orElseThrow(),cards);if(size==5&&config.allowFourBombWithOne()&&counts.containsValue(4L)){int rank=counts.entrySet().stream().filter(e->e.getValue()==4).findFirst().orElseThrow().getKey();return new CardCombination("FOUR_BOMB_WITH_ONE",rank,cards);}
  if(size>=config.minimumStraightLength()&&counts.size()==size&&legalRun(counts.keySet(),config.minimumStraightLength()))return new CardCombination("STRAIGHT",counts.keySet().stream().max(Integer::compareTo).orElseThrow(),cards);
  try{CardCombination basicCombination=basic.recognize(cards,context);if("SINGLE".equals(basicCombination.type())&&!config.allowSingle())throw new IllegalArgumentException("single is disabled");if("PAIR".equals(basicCombination.type())&&!config.allowPair())throw new IllegalArgumentException("pair is disabled");if("TRIPLE".equals(basicCombination.type())&&!timingAllows(config.tripleWithoutAttachmentTiming(),cards,context))throw new IllegalArgumentException("triple without attachment is disabled for this turn");if("STRAIGHT".equals(basicCombination.type()))profile.validateRun(basicCombination.cards().stream().map(StandardPokerRuleSet::rank).distinct().sorted().toList(),false);return basicCombination;}catch(IllegalArgumentException ignored){/* Basic parser rejection intentionally falls through to regional combinations. */}
  String type=null;int primary=counts.keySet().stream().max(Integer::compareTo).orElseThrow();
  if(size==4&&counts.containsValue(3L)&&allowsSingles(config.tripleAttachmentMode()))type="TRIPLE_WITH_ONE";
  else if(size==5&&frequency(counts,3)==1&&allowsPairs(config.tripleAttachmentMode())&&frequency(counts,2)==1)type="TRIPLE_WITH_PAIR";
  else if(size==5&&frequency(counts,3)==1&&allowsSingles(config.tripleAttachmentMode()))type="TRIPLE_WITH_TWO";
  else if(size>=4&&size%2==0&&counts.values().stream().allMatch(v->v==2)&&validProfileRun(counts.keySet(),true))type="CONSECUTIVE_PAIRS";
  else {List<Integer> triples=counts.entrySet().stream().filter(e->e.getValue()==3).map(Map.Entry::getKey).sorted().toList();if(!triples.isEmpty()&&triples.size()>=profile.minimumPlaneLength()&&validProfileRun(triples,true)){int n=triples.size();primary=triples.get(triples.size()-1);if(size==n*3&&timingAllows(config.airplaneWithoutAttachmentTiming(),cards,context))type="AIRPLANE";else if(size==n*4&&allowsSingles(config.airplaneAttachmentMode()))type="AIRPLANE_WITH_SINGLES";else if(size==n*5&&allowsPairs(config.airplaneAttachmentMode())&&counts.values().stream().filter(v->v!=3).allMatch(v->v==2))type="AIRPLANE_WITH_PAIRS";else if(size==n*5&&config.allowAirplaneWithTwo())type="AIRPLANE_WITH_TWO";}}
  if(type==null&&frequency(counts,4)==1){if(size==6&&allowsSingles(config.fourAttachmentMode()))type="FOUR_WITH_TWO";else if(size==8&&allowsPairs(config.fourAttachmentMode())&&counts.values().stream().filter(v->v!=4).allMatch(v->v==2))type="FOUR_WITH_TWO_PAIRS";else if(size==7&&config.allowFourWithThree())type="FOUR_WITH_THREE";}
  if(type==null)throw new IllegalArgumentException("unsupported paodekuai combination");return new CardCombination(type,primary,cards);
 }
 public boolean canBeat(CardCombination candidate,CardCombination previous,PaoDeKuaiContext context){if(previous==null)return true;if(isBomb(candidate)){if(!isBomb(previous))return true;int a=bombTier(candidate),b=bombTier(previous);return a>b||(a==b&&candidate.primaryRank()>previous.primaryRank());}if(config.allowTerminalAttachmentShortage()&&context!=null&&context.handBeforePlay().size()==candidate.cards().size()){if("TRIPLE".equals(candidate.type())&&previous.type().startsWith("TRIPLE_WITH"))return candidate.primaryRank()>previous.primaryRank();if("AIRPLANE".equals(candidate.type())&&previous.type().startsWith("AIRPLANE_WITH"))return tripleGroups(candidate)==tripleGroups(previous)&&candidate.primaryRank()>previous.primaryRank();}if(!candidate.type().equals(previous.type())||candidate.cards().size()!=previous.cards().size()||candidate.primaryRank()<=previous.primaryRank())return false;if(config.compareTripleAttachments()&&candidate.type().startsWith("TRIPLE_WITH"))return maximumAttachmentRank(candidate)>maximumAttachmentRank(previous);return true;}
 public boolean isBomb(CardCombination c){return "BOMB".equals(c.type())||c.type().contains("_BOMB");}private int bombTier(CardCombination c){return switch(c.type()){case"SPECIAL_TRIPLE_BOMB","SPECIAL_TRIPLE_BOMB_WITH_ONE"->config.specialBombTier();case"FOUR_BOMB_WITH_ONE"->config.fourBombWithOneTier();case"CONSECUTIVE_BOMB"->(int)(tripleGroups(c)*2-1);default->config.standardBombTier();};}private static long tripleGroups(CardCombination c){Map<Integer,Long>m=new HashMap<>();c.cards().forEach(card->m.merge(StandardPokerRuleSet.rank(card),1L,Long::sum));return m.values().stream().filter(n->n>=3).count();}
 public int cardsPerPlayer(int players){profile.validatePlayerCount(players,config.cardsPerPlayer());return config.cardsPerPlayer()==0?profile.deckSize()/players:config.cardsPerPlayer();}
 public List<CardCombination> hints(List<Integer> hand,CardCombination previous,PaoDeKuaiContext context){if(hand==null||hand.isEmpty())return List.of();if(hand.size()>profile.maximumHandSize())throw new IllegalStateException("hand exceeds complete-hint budget");List<Integer>sorted=hand.stream().sorted(Comparator.comparingInt((Integer card)->StandardPokerRuleSet.rank(card)).thenComparingInt(Integer::intValue)).toList();LinkedHashMap<String,CardCombination>result=new LinkedHashMap<>();long limit=1L<<sorted.size();for(long mask=1;mask<limit;mask++){List<Integer>candidate=new ArrayList<>();for(int i=0;i<sorted.size();i++)if((mask&(1L<<i))!=0)candidate.add(sorted.get(i));try{CardCombination c=recognize(candidate,context);validatePlay(candidate,context);if(canBeat(c,previous,context))result.putIfAbsent(c.type()+":"+c.primaryRank()+":"+c.cards(),c);}catch(IllegalArgumentException|IllegalStateException ignored){/* exhaustive candidate is illegal */}}return result.values().stream().sorted(Comparator.comparingInt((CardCombination c)->isBomb(c)?1:0).thenComparingInt(this::bombTier).thenComparingInt(CardCombination::primaryRank).thenComparingInt(c->c.cards().size()).thenComparing(c->c.cards().toString())).toList();}
 public void validatePlay(List<Integer> cards,PaoDeKuaiContext context){
  Integer required=context.authoritativeContext()?context.authoritativeRequiredFirstCard():config.requiredFirstCard();if(context.firstPlay()&&required!=null&&!cards.contains(required))throw new IllegalStateException("first play must contain required card");
  if(profile.forceHighestSingleAgainstReportedSingle()&&context.nextPlayerCardCount()==1&&cards.size()==1){int highest=context.handBeforePlay().stream().mapToInt(StandardPokerRuleSet::rank).max().orElseThrow();if(StandardPokerRuleSet.rank(cards.get(0))!=highest)throw new IllegalStateException("must play highest single against reported single");}
  if(config.forceHighestPairAgainstReportedPair()&&context.nextPlayerCardCount()==2&&cards.size()==2&&StandardPokerRuleSet.rank(cards.get(0))==StandardPokerRuleSet.rank(cards.get(1))){int highestPair=highestPairRank(context.handBeforePlay());if(highestPair>=0&&StandardPokerRuleSet.rank(cards.get(0))!=highestPair)throw new IllegalStateException("must play highest pair against reported pair");}
 }
 private boolean validProfileRun(Collection<Integer> ranks,boolean pairs){try{profile.validateRun(ranks.stream().sorted().toList(),pairs);return true;}catch(IllegalArgumentException e){return false;}}private static long frequency(Map<Integer,Long> counts,long value){return counts.values().stream().filter(v->v==value).count();}private static boolean timingAllows(PaoDeKuaiConfig.PlayTiming timing,List<Integer>cards,PaoDeKuaiContext context){return timing==PaoDeKuaiConfig.PlayTiming.ANYTIME||(timing==PaoDeKuaiConfig.PlayTiming.FINAL_ONLY&&context!=null&&context.handBeforePlay().size()==cards.size());}private static boolean allowsSingles(PaoDeKuaiConfig.AttachmentMode mode){return mode==PaoDeKuaiConfig.AttachmentMode.SINGLES||mode==PaoDeKuaiConfig.AttachmentMode.EITHER;}private static boolean allowsPairs(PaoDeKuaiConfig.AttachmentMode mode){return mode==PaoDeKuaiConfig.AttachmentMode.PAIRS||mode==PaoDeKuaiConfig.AttachmentMode.EITHER;}private static int highestPairRank(List<Integer>cards){Map<Integer,Long>counts=new HashMap<>();cards.forEach(card->counts.merge(StandardPokerRuleSet.rank(card),1L,Long::sum));return counts.entrySet().stream().filter(e->e.getValue()>=2).mapToInt(Map.Entry::getKey).max().orElse(-1);}private static int maximumAttachmentRank(CardCombination c){Map<Integer,Long>counts=new HashMap<>();c.cards().forEach(card->counts.merge(StandardPokerRuleSet.rank(card),1L,Long::sum));return counts.entrySet().stream().filter(e->e.getKey()!=c.primaryRank()).mapToInt(Map.Entry::getKey).max().orElse(-1);} private static boolean legalRun(Collection<Integer> ranks,int minimum){if(ranks.size()<minimum)return false;int previous=-1;for(int rank:ranks){if(rank>=15||(previous>=0&&rank!=previous+1))return false;previous=rank;}return true;}
}
