package com.aoo.bcg.poker;
import java.util.*;
/** Authoritative ownership, comparison, pass and turn engine shared by poker games. */
public final class PokerCoreEngine<T>{
 public PokerTurnState play(PokerTurnState state,int seat,List<Integer> cards,PokerRuleSet<T> rules,T context){requireTurn(state,seat);if(state.finished())throw new IllegalStateException("round finished");List<Integer> hand=new ArrayList<>(state.hands().get(seat));for(int card:cards)if(!hand.remove(Integer.valueOf(card)))throw new IllegalStateException("card not in hand");CardCombination combination=rules.recognize(cards,context);if(!rules.canBeat(combination,state.previous(),context))throw new IllegalStateException("combination cannot beat previous");Map<Integer,List<Integer>> hands=new LinkedHashMap<>(state.hands());hands.put(seat,hand);boolean finished=hand.isEmpty();return new PokerTurnState(hands,finished?seat:next(state,seat),combination,seat,Set.of(),finished,finished?seat:-1);}
 public PokerTurnState pass(PokerTurnState state,int seat){requireTurn(state,seat);if(state.finished())throw new IllegalStateException("round finished");if(state.previous()==null||state.previousSeat()==seat)throw new IllegalStateException("leader cannot pass");HashSet<Integer> passed=new HashSet<>(state.passed());passed.add(seat);int active=state.hands().size()-1;if(passed.size()>=active)return new PokerTurnState(state.hands(),state.previousSeat(),null,-1,Set.of(),false,-1);int next=next(state,seat);while(passed.contains(next))next=next(state,next);return new PokerTurnState(state.hands(),next,state.previous(),state.previousSeat(),passed,false,-1);}
 public List<CardCombination> hints(PokerTurnState state,int seat,PokerRuleSet<T> rules,T context){return rules.hints(state.hands().get(seat),state.previous(),context);}
 private static void requireTurn(PokerTurnState state,int seat){if(state.currentSeat()!=seat)throw new IllegalStateException("not current seat");} private static int next(PokerTurnState state,int seat){List<Integer> seats=state.hands().keySet().stream().sorted().toList();return seats.get((seats.indexOf(seat)+1)%seats.size());}
}

record CardCombination(String type,int primaryRank,List<Integer>cards){CardCombination{if(type==null||type.isBlank()||cards==null||cards.isEmpty())throw new IllegalArgumentException("invalid card combination");cards=List.copyOf(cards);}}
record PaoDeKuaiContext(boolean firstPlay,int nextPlayerCardCount,List<Integer>handBeforePlay,
        Integer authoritativeRequiredFirstCard,boolean authoritativeContext,
        boolean attachmentlessPlayPrivilege){
 PaoDeKuaiContext(boolean firstPlay,int nextPlayerCardCount,List<Integer>handBeforePlay){this(firstPlay,nextPlayerCardCount,handBeforePlay,null,false,false);}
 PaoDeKuaiContext(boolean firstPlay,int nextPlayerCardCount,List<Integer>handBeforePlay,
   Integer authoritativeRequiredFirstCard,boolean authoritativeContext){this(firstPlay,nextPlayerCardCount,handBeforePlay,authoritativeRequiredFirstCard,authoritativeContext,false);}
 PaoDeKuaiContext{handBeforePlay=List.copyOf(handBeforePlay==null?List.of():handBeforePlay);}
}
record PokerTurnState(Map<Integer,List<Integer>>hands,int currentSeat,CardCombination previous,int previousSeat,Set<Integer>passed,boolean finished,int winnerSeat){PokerTurnState{Map<Integer,List<Integer>>copy=new LinkedHashMap<>();hands.forEach((seat,cards)->copy.put(seat,List.copyOf(cards)));hands=Map.copyOf(copy);passed=Set.copyOf(passed==null?Set.of():passed);if(hands.size()<2||!hands.containsKey(currentSeat))throw new IllegalArgumentException("invalid poker state");}}

final class PokerCardCodec{
 private PokerCardCodec(){}
 static int encode(int suit,int rank){if(!((suit>=1&&suit<=4&&rank>=3&&rank<=15)||(suit==5&&rank>=16&&rank<=17)))throw new IllegalArgumentException("invalid suit/rank");return suit*100+rank;}
 static int suit(int card){validate(card);return card/100;}static int rank(int card){validate(card);return Math.floorMod(card,100);}
 static void validate(int card){int suit=card/100,rank=Math.floorMod(card,100);if(!((suit>=1&&suit<=4&&rank>=3&&rank<=15)||(suit==5&&rank>=16&&rank<=17)))throw new IllegalArgumentException("invalid card id: "+card);}
 static int fromLegacyNibble(int legacy){int suit=(legacy>>>4)&15,rank=legacy&15;if(suit>3||rank<3||rank>15)throw new IllegalArgumentException("invalid legacy card");return encode(suit+1,rank);}
 static int toLegacyNibble(int canonical){validate(canonical);int suit=suit(canonical),rank=rank(canonical);if(suit==5)throw new IllegalArgumentException("legacy format has no joker mapping");return((suit-1)<<4)|rank;}
 static List<Integer>deck(int size){if(size!=48&&size!=52&&size!=54)throw new IllegalArgumentException("deck size must be 48, 52 or 54");List<Integer>deck=new ArrayList<>(size);int lowest=size==48?4:3;for(int suit=1;suit<=4;suit++)for(int rank=lowest;rank<=15;rank++)deck.add(encode(suit,rank));if(size==54){deck.add(encode(5,16));deck.add(encode(5,17));}if(deck.size()!=size||new LinkedHashSet<>(deck).size()!=size)throw new IllegalStateException("invalid canonical deck");return List.copyOf(deck);}
}

final class PokerFirstLeadResolver{private PokerFirstLeadResolver(){}static int resolve(PokerRuleProfile p,Map<Integer,List<Integer>>hands,int owner,Integer previous,long seed){List<Integer>seats=hands.keySet().stream().sorted().toList();if(!seats.contains(owner))throw new IllegalArgumentException("owner seat unavailable");Comparator<Integer>order=Comparator.comparingInt((Integer c)->StandardPokerRuleSet.rank(c)).thenComparingInt(Integer::intValue);return switch(p.firstLead()){case ROOM_OWNER->owner;case PREVIOUS_WINNER->{if(previous==null||!hands.containsKey(previous))throw new IllegalStateException("previous winner seat unavailable");yield previous;}case RANDOM->seats.get(Math.floorMod(Long.hashCode(seed),seats.size()));case REQUIRED_CARD_HOLDER->hands.entrySet().stream().filter(e->e.getValue().contains(p.requiredFirstCard())).map(Map.Entry::getKey).findFirst().orElseThrow();case MINIMUM_CARD_HOLDER->hands.entrySet().stream().min(Comparator.comparing(e->e.getValue().stream().min(order).orElseThrow(),order)).map(Map.Entry::getKey).orElseThrow();};}}

final class PokerSettlementCalculator{
 record SeatInput(long playerId,int remainingCards,int plays,int bombs){SeatInput{if(playerId<=0||remainingCards<0||plays<0||bombs<0)throw new IllegalArgumentException("invalid seat input");}}
 record Line(long playerId,long base,long bomb,long special,long total,List<String>tags){Line{tags=List.copyOf(tags);if(base+bomb+special!=total)throw new IllegalArgumentException("line does not add up");}}
 record Detail(String ruleVersion,int winnerSeat,int multiplier,List<Line>lines,long checksum){Detail{lines=List.copyOf(lines);if(lines.stream().mapToLong(Line::total).sum()!=0)throw new IllegalArgumentException("settlement is not zero-sum");}}
 Detail calculate(String version,int winnerSeat,Map<Integer,SeatInput>seats,int bombUnit,int cap){return calculate(version,winnerSeat,winnerSeat,seats,bombUnit,cap);}
 Detail calculate(String version,int winnerSeat,int initialLeadSeat,Map<Integer,SeatInput>seats,int bombUnit,int cap){if(!seats.containsKey(winnerSeat)||seats.size()<2||bombUnit<0||cap<1)throw new IllegalArgumentException("invalid settlement input");boolean spring=seats.entrySet().stream().filter(e->e.getKey()!=winnerSeat).allMatch(e->e.getValue().plays()==0),reverse=seats.containsKey(initialLeadSeat)&&winnerSeat!=initialLeadSeat&&seats.get(initialLeadSeat).plays()<=1&&seats.entrySet().stream().filter(e->e.getKey()!=winnerSeat&&e.getKey()!=initialLeadSeat).allMatch(e->e.getValue().plays()==0);int multiplier=spring||reverse?Math.min(2,cap):1;Map<Integer,Long>base=new LinkedHashMap<>(),bomb=new LinkedHashMap<>();long winnerBase=0;for(var e:seats.entrySet().stream().sorted(Map.Entry.comparingByKey()).toList())if(e.getKey()!=winnerSeat){long loss=-(long)Math.max(1,e.getValue().remainingCards());base.put(e.getKey(),loss);winnerBase-=loss;}base.put(winnerSeat,winnerBase);seats.keySet().forEach(s->bomb.put(s,0L));List<Integer>ordered=seats.keySet().stream().sorted().toList();for(int i=0;i<ordered.size();i++)for(int j=i+1;j<ordered.size();j++){int a=ordered.get(i),b=ordered.get(j);long transfer=(long)(seats.get(a).bombs()-seats.get(b).bombs())*bombUnit;bomb.put(a,bomb.get(a)+transfer);bomb.put(b,bomb.get(b)-transfer);}List<Line>lines=new ArrayList<>();long checksum=17;checksum=checksum*31+version.hashCode();checksum=checksum*31+winnerSeat;checksum=checksum*31+multiplier;for(var e:seats.entrySet().stream().sorted(Map.Entry.comparingByKey()).toList()){List<String>tags=new ArrayList<>();if(e.getKey()==winnerSeat)tags.add("WINNER");if(spring)tags.add("SPRING");if(reverse)tags.add("REVERSE_SPRING");if(e.getValue().plays()==0&&e.getKey()!=winnerSeat)tags.add("SHUT_OUT");long b=base.get(e.getKey()),bo=bomb.get(e.getKey()),special=spring||reverse?b*(multiplier-1):0,total=b+bo+special;lines.add(new Line(e.getValue().playerId(),b,bo,special,total,tags));checksum=checksum*31+e.getKey();checksum=checksum*31+e.getValue().playerId();checksum=checksum*31+b;checksum=checksum*31+bo;checksum=checksum*31+special;checksum=checksum*31+total;checksum=checksum*31+tags.hashCode();}return new Detail(version,winnerSeat,multiplier,lines,checksum);}
}
