package com.aoo.bcg.poker;
import com.aoo.bcg.gamespi.*;import java.util.*;

/** Catalog bindings for the source-backed Poker engines; no code-specific SPI entries. */
public final class PokerCatalogRuntimeRegistry{
 private PokerCatalogRuntimeRegistry(){}
 public static Optional<GameProvider>providerFor(GameDescriptor d){if(d.category()!=GameCategory.POKER)return Optional.empty();GameProvider p=switch(d.code()){case"pdk"->new PdkGameProvider();case"aypdk"->new AypdkGameProvider();case"hbpdk"->new HbpdkGameProvider();case"cp"->new CpGameProvider();case"hndzp"->new HndzpGameProvider();case"lhzp"->new LhzpGameProvider();default->null;};return p==null?Optional.empty():Optional.of(new PokerFamilyCatalogProvider(d,p));}
}

final class PokerFamilyCatalogProvider implements GameProvider{
 private final GameDescriptor descriptor;private final GameProvider delegate;
 PokerFamilyCatalogProvider(GameDescriptor d,GameProvider p){descriptor=Objects.requireNonNull(d);delegate=Objects.requireNonNull(p);}
 public GameDescriptor descriptor(){return descriptor;}public GameRoomFactory roomFactory(){return delegate.roomFactory();}public Optional<GameCommandHandler>commandHandler(){return delegate.commandHandler();}public GameCommandCommitter commandCommitter(){return delegate.commandCommitter();}public Optional<ReconnectViewProvider<?>>reconnectViewProvider(){return delegate.reconnectViewProvider();}public Optional<SettlementProvider>settlementProvider(){return delegate.settlementProvider();}public Optional<EventReplayProvider>eventReplayProvider(){return delegate.eventReplayProvider();}public Optional<AuthoritativeGameSession>createAuthoritativeSession(RoomCreationContext c){return delegate.createAuthoritativeSession(c);}public Optional<AuthoritativeGameSession>restoreAuthoritativeSession(Map<String,Object>s){return delegate.restoreAuthoritativeSession(s);}public List<RuleComponent<GameCommandRequest>>ruleComponents(){return delegate.ruleComponents();}public GameCapabilityManifest capabilityManifest(){return delegate.capabilityManifest();}
 public Map<String,Object>defaultConfiguration(){var out=new LinkedHashMap<String,Object>(delegate.defaultConfiguration());out.put("provider","poker-family-runtime");out.put("regionCode",descriptor.code());return Map.copyOf(out);}
}

abstract class RegionalPokerProvider implements GameProvider{
 final String code;final int id;final String version;private final String family,province;
 RegionalPokerProvider(String c,int i,String v,String f,String p){code=c;id=i;version=v;family=f;province=p;}
 public GameDescriptor descriptor(){return new GameDescriptor(id,code,code.toUpperCase(),GameCategory.POKER,family,RegionScope.PROVINCE,province,"",version);}
 public GameRoomFactory roomFactory(){return c->new GameRoomHandle(c.roomId(),id,version,create(c));}abstract AuthoritativeGameSession create(RoomCreationContext c);abstract AuthoritativeGameSession restore(Map<String,Object>s);abstract StatePayload replay(StatePayload b,List<Object>e);
 public Optional<GameCommandHandler>commandHandler(){return Optional.of(this instanceof PokerGameProvider?new PokerDispatchCommandHandler():new AuthoritativeSessionCommandHandler());}public Optional<ReconnectViewProvider<?>>reconnectViewProvider(){return Optional.of((p,r)->r.requireAuthoritativeSession().viewFor(p));}public Optional<SettlementProvider>settlementProvider(){return Optional.of((r,n)->r.requireAuthoritativeSession().settlement(n,version));}public Optional<AuthoritativeGameSession>restoreAuthoritativeSession(Map<String,Object>s){return Optional.of(restore(s));}public Optional<EventReplayProvider>eventReplayProvider(){return Optional.of(this::replay);}
 public List<RuleComponent<GameCommandRequest>>ruleComponents(){return List.of(new RuleComponent<>(){public String ruleId(){return family+".provider-boundary";}public String componentVersion(){return version;}public RuleStage stage(){return RuleStage.PLAY;}public int priority(){return 100;}public RuleResult execute(GameCommandRequest request){return request.playVersion().equals(version)&&(request.msgId().startsWith("poker.")||request.msgId().startsWith("common.room."))?RuleResult.accept():RuleResult.reject("POKER_MESSAGE_REQUIRED","message does not belong to Poker runtime");}});}
}

final class PdkGameProvider extends RegionalPokerProvider implements PokerGameProvider{
 static final int GAME_ID=8;static final String VERSION="1.0.0";private static final Set<String>LEGACY_WAITING_KEYS=Set.of("4208ce24d1f9cc83de9eda6400b0bae2abc67af7a37df42493c37d681fa9ba5e");private static final PaoDeKuaiConfig BASE=new PaoDeKuaiConfig(5,true,true,false,null,true);private static final PaoDeKuaiFamily F=family(BASE,Map.of());PdkGameProvider(){super("pdk",GAME_ID,VERSION,PaoDeKuaiFamily.CODE,"");}public PokerRuleFamily pokerFamily(){return F;}AuthoritativeGameSession create(RoomCreationContext c){int seats=number(c.immutableRules(),"playerCount",3);int rounds=number(c.immutableRules(),"roundCount",8);long seed=c.immutableRules().get("shuffleSeed")instanceof Number n?n.longValue():c.roomId();PaoDeKuaiConfig config=PdkPublishedRuleOptions.apply(c.immutableRules(),BASE);return new PokerAuthoritativeSession(c.roomId(),c.ownerId(),seats,seed,family(config,c.immutableRules()),rounds);}AuthoritativeGameSession restore(Map<String,Object>s){Object raw=s.get("pdkRuleOptions");if(!(raw instanceof Map<?,?>map))throw new IllegalStateException("missing immutable PDK rule options");Map<String,Object>options=new LinkedHashMap<>();map.forEach((k,v)->options.put(String.valueOf(k),v));PaoDeKuaiFamily family=family(PdkPublishedRuleOptions.apply(options,BASE),options);return PokerAuthoritativeSession.restore(PdkPublishedRuleOptions.migrateWaitingSnapshotIdentity(s,family,LEGACY_WAITING_KEYS),family);}private static int number(Map<String,Object>rules,String key,int fallback){Object value=rules.get(key);return value instanceof Number n?n.intValue():fallback;}private static PaoDeKuaiFamily family(PaoDeKuaiConfig config,Map<String,Object>rules){PokerRuleProfile base=PdkRuleProfiles.flexibleTwoToFourPlayers(VERSION,config.requiredFirstCard());return new PaoDeKuaiFamily(config,PdkPublishedRuleOptions.profile(VERSION,rules,config,base));}StatePayload replay(StatePayload b,List<Object>e){return PokerAuthoritativeSession.replay(b,e);}public Map<String,Object>defaultConfiguration(){return Map.of("enabled",true,"playVersion",VERSION,"provider","native-pdk","deckSize",48,"minimumStraightLength",5,"allowFourWithTwo",true);}
}
final class AypdkGameProvider extends RegionalPokerProvider implements PokerGameProvider{
 static final int GAME_ID=78;static final String VERSION="aypdk-native-1";private static final PaoDeKuaiFamily F=AypdkRules.family();AypdkGameProvider(){super("aypdk",GAME_ID,VERSION,PaoDeKuaiFamily.CODE,"sichuan");}public PokerRuleFamily pokerFamily(){return F;}AuthoritativeGameSession create(RoomCreationContext c){int seats=c.immutableRules().get("seatLimit")instanceof Number n?n.intValue():3;if(seats!=3)throw new IllegalArgumentException("AYPDK requires three players");long seed=c.immutableRules().get("shuffleSeed")instanceof Number n?n.longValue():c.roomId();return new AypdkSession(c.roomId(),c.ownerId(),seed,AypdkOptions.from(c.immutableRules()));}AuthoritativeGameSession restore(Map<String,Object>s){return AypdkSession.restore(s);}StatePayload replay(StatePayload b,List<Object>e){return AypdkSession.replay(b,e);}public Map<String,Object>defaultConfiguration(){return Map.ofEntries(Map.entry("enabled",true),Map.entry("playVersion",VERSION),Map.entry("provider","native-aypdk"),Map.entry("seatLimit",3),Map.entry("deckSize",48),Map.entry("chupai",0),Map.entry("heitaosanbichu",0),Map.entry("zhadan",0),Map.entry("daxiaoguan",0),Map.entry("paixing",List.of(0)),Map.entry("teshu",List.of()),Map.entry("specialTripleBombRank",14));}
}
final class HbpdkGameProvider extends RegionalPokerProvider implements PokerGameProvider{
 static final int GAME_ID=89;static final String VERSION="hbpdk-native-1";private static final HbpdkOptions D=HbpdkOptions.from(Map.of());HbpdkGameProvider(){super("hbpdk",GAME_ID,VERSION,PaoDeKuaiFamily.CODE,"hubei");}public PokerRuleFamily pokerFamily(){return HbpdkRules.family(D);}AuthoritativeGameSession create(RoomCreationContext c){HbpdkOptions o=HbpdkOptions.from(c.immutableRules());long seed=c.immutableRules().get("shuffleSeed")instanceof Number n?n.longValue():c.roomId();return new HbpdkSession(c.roomId(),c.ownerId(),seed,o);}AuthoritativeGameSession restore(Map<String,Object>s){return HbpdkSession.restore(s);}StatePayload replay(StatePayload b,List<Object>e){return HbpdkSession.replay(b,e);}public Map<String,Object>defaultConfiguration(){return Map.of("enabled",true,"provider","native-hbpdk","playVersion",VERSION,"playerNum",3,"cardNum",2,"xianchu",1,"kexuanwanfa",List.of(4,11,13),"zhadansuanfa",1,"zhadanfenshu",0);}
}
final class CpGameProvider extends RegionalPokerProvider{static final int GAME_ID=392;static final String VERSION="1.0.0";CpGameProvider(){super("cp",GAME_ID,VERSION,"poker:compare-hand","chongqing");}AuthoritativeGameSession create(RoomCreationContext c){return new CpSession(c.roomId(),c.ownerId(),c.immutableRules());}AuthoritativeGameSession restore(Map<String,Object>s){return CpSession.restore(s);}StatePayload replay(StatePayload b,List<Object>e){return CpSession.replay(b,e);}public Map<String,Object>defaultConfiguration(){return Map.of("enabled",true,"playVersion",VERSION,"provider","native-cp","players",3,"deckSize",84,"moshi",0,"fanshushangxian",0,"difen",0);}}
final class HndzpGameProvider extends RegionalPokerProvider{static final int GAME_ID=267;static final String VERSION="1.0.0";HndzpGameProvider(){super("hndzp",GAME_ID,VERSION,"poker:landlord","hainan");}AuthoritativeGameSession create(RoomCreationContext c){return new HndzpSession(c.roomId(),c.ownerId(),c.immutableRules());}AuthoritativeGameSession restore(Map<String,Object>s){return HndzpSession.restore(s);}StatePayload replay(StatePayload b,List<Object>e){return HndzpSession.replay(b,e);}public Map<String,Object>defaultConfiguration(){return Map.of("enabled",true,"playVersion",VERSION,"provider","native-hndzp");}}
final class LhzpGameProvider extends RegionalPokerProvider{static final int GAME_ID=129;static final String VERSION="1.0.0";LhzpGameProvider(){super("lhzp",GAME_ID,VERSION,"poker:510k","jiangxi");}AuthoritativeGameSession create(RoomCreationContext c){return new LhzpSession(c.roomId(),c.ownerId(),c.immutableRules());}AuthoritativeGameSession restore(Map<String,Object>s){return LhzpSession.restore(s);}StatePayload replay(StatePayload b,List<Object>e){return LhzpSession.replay(b,e);}public Map<String,Object>defaultConfiguration(){return Map.of("enabled",true,"playVersion",VERSION,"provider","native-lhzp");}}
