package com.aoo.bcg.poker;
import java.util.*;
/** Four-player upgrade trick engine with trump, follow-category and defender scoring. */
public final class ShengJiEngine{
 public ShengJiState play(ShengJiState state,int seat,int card,ShengJiConfig config){if(state.finished()||state.currentSeat()!=seat)throw new IllegalStateException("not current seat");List<Integer> hand=new ArrayList<>(state.hands().get(seat));if(!hand.remove(Integer.valueOf(card)))throw new IllegalStateException("card not in hand");if(!state.trick().isEmpty()){int lead=category(state.trick().get(state.trickLeader()),config);boolean hasLead=state.hands().get(seat).stream().anyMatch(value->category(value,config)==lead);if(hasLead&&category(card,config)!=lead)throw new IllegalStateException("must follow lead category");}Map<Integer,List<Integer>> hands=new LinkedHashMap<>(state.hands());hands.put(seat,hand);Map<Integer,Integer> trick=new LinkedHashMap<>(state.trick());trick.put(seat,card);if(trick.size()<4)return new ShengJiState(hands,state.dealerSeat(),next(seat),state.trickLeader(),trick,state.defenderPoints(),false);int winner=winner(trick,state.trickLeader(),config);int points=trick.values().stream().mapToInt(ShengJiEngine::points).sum();boolean dealerTeam=winner==state.dealerSeat()||winner==(state.dealerSeat()+2)%4;int defenderPoints=state.defenderPoints()+(dealerTeam?0:points);boolean finished=hands.values().stream().allMatch(List::isEmpty);return new ShengJiState(hands,state.dealerSeat(),winner,winner,Map.of(),defenderPoints,finished);}
 public int nextLevelDelta(int defenderPoints){if(defenderPoints<40)return 3;if(defenderPoints<80)return 2;if(defenderPoints<120)return 1;return -Math.max(1,(defenderPoints-80)/40);}
 private static int winner(Map<Integer,Integer> trick,int leader,ShengJiConfig config){int lead=category(trick.get(leader),config);return trick.entrySet().stream().max(Comparator.comparingInt(e->strength(e.getValue(),lead,config))).orElseThrow().getKey();}
 private static int strength(int card,int lead,ShengJiConfig config){int category=category(card,config);int group=category==4?2:category==lead?1:0;int rank=rank(card)==config.levelRank()?100+rank(card):rank(card);return group*1000+rank;}
 private static int category(int card,ShengJiConfig config){return suit(card)==config.trumpSuit()||rank(card)==config.levelRank()?4:suit(card);}private static int suit(int card){return Math.floorDiv(card,100);}private static int rank(int card){return Math.floorMod(card,100);}private static int points(int card){return switch(rank(card)){case 5->5;case 10,13->10;default->0;};}private static int next(int seat){return (seat+1)%4;}
}
