package com.aoo.bcg.poker;
import com.aoo.bcg.gamespi.AlgorithmBudget;import java.time.Duration;import java.util.*;
/** Common single/pair/triple/straight/bomb recognition, comparison and hints. */
public final class StandardPokerRuleSet<T> implements PokerRuleSet<T>{
 public CardCombination recognize(List<Integer> cards,T state){if(cards==null||cards.isEmpty())throw new IllegalArgumentException("cards required");List<Integer> sorted=cards.stream().sorted(Comparator.comparingInt(StandardPokerRuleSet::rank)).toList();Map<Integer,Long> counts=new TreeMap<>();sorted.forEach(card->counts.merge(rank(card),1L,Long::sum));String type;if(sorted.size()==1)type="SINGLE";else if(counts.size()==1&&sorted.size()==2)type="PAIR";else if(counts.size()==1&&sorted.size()==3)type="TRIPLE";else if(counts.size()==1&&sorted.size()==4)type="BOMB";else if(sorted.size()>=5&&counts.size()==sorted.size()&&consecutive(counts.keySet()))type="STRAIGHT";else throw new IllegalArgumentException("unsupported card combination");return new CardCombination(type,counts.keySet().stream().max(Integer::compareTo).orElseThrow(),sorted);}
 public boolean canBeat(CardCombination candidate,CardCombination previous,T state){if(previous==null)return true;if(candidate.type().equals("BOMB")&&!previous.type().equals("BOMB"))return true;return candidate.type().equals(previous.type())&&candidate.cards().size()==previous.cards().size()&&candidate.primaryRank()>previous.primaryRank();}
 public List<CardCombination> hints(List<Integer> hand,CardCombination previous,T state){var budget=AlgorithmBudget.start(hand.size(),54,10_000,16,Duration.ofMillis(50));Map<Integer,List<Integer>> byRank=new TreeMap<>();hand.forEach(card->{budget.step();byRank.computeIfAbsent(rank(card),ignored->new ArrayList<>()).add(card);});ArrayList<CardCombination> result=new ArrayList<>();for(List<Integer> group:byRank.values()){budget.step();int need=previous==null?1:switch(previous.type()){case "PAIR"->2;case "TRIPLE"->3;case "BOMB"->4;default->1;};if(group.size()>=need)try{CardCombination c=recognize(group.subList(0,need),state);if(canBeat(c,previous,state))result.add(c);}catch(IllegalArgumentException ignored){/* Invalid hint candidate is intentionally omitted. */}if(group.size()>=4&&!"BOMB".equals(previous==null?"":previous.type()))result.add(recognize(group.subList(0,4),state));}return List.copyOf(result);}
 public static int rank(int card){return PokerCardCodec.rank(card);} private static boolean consecutive(Set<Integer> ranks){int previous=-1;for(int rank:ranks){if(previous>=0&&rank!=previous+1)return false;previous=rank;}return true;}
}
