package com.aoo.bcg.ranking;
import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import java.nio.file.*;import java.sql.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class RankingAchievementServiceTest{
 JdbcDataSource db;RankingAchievementService service;List<String> grants;
 @BeforeEach void setup()throws Exception{db=new JdbcDataSource();db.setURL("jdbc:h2:mem:r"+System.nanoTime()+";MODE=MySQL;DB_CLOSE_DELAY=-1");try(var c=db.getConnection();var s=c.createStatement()){s.execute(Files.readString(Path.of("src/main/resources/db/ranking-achievement-schema.sql")));s.execute("INSERT INTO aoo_rank_season VALUES('d','DAILY',CURRENT_TIMESTAMP,DATEADD('DAY',1,CURRENT_TIMESTAMP),'ACTIVE')");s.execute("INSERT INTO aoo_achievement_definition VALUES('WIN_3',3,'CURRENCY','GOLD',100,TRUE)");}grants=new ArrayList<>();service=new RankingAchievementService(db,new RankingAchievementService.RewardPort(){public void creditCurrency(String b,long p,String c,long a){grants.add(b);}public void grantItem(String b,long p,String i,long a){grants.add(b);}},Clock.systemUTC());}
 @Test void cursorStandingAndFreeze(){service.addScore("d",1,10);service.addScore("d",2,20);service.addScore("d",3,15);var first=service.leaderboard("d",null,2);assertEquals(List.of(2L,3L),first.entries().stream().map(RankingAchievementService.Entry::playerId).toList());assertEquals(1L,service.leaderboard("d",first.nextCursor(),2).entries().getFirst().playerId());assertEquals(2,service.standing("d",3).rank());service.transitionSeason("d","FROZEN");assertThrows(IllegalStateException.class,()->service.addScore("d",1,1));service.transitionSeason("d","CLOSED");}
 @Test void progressClaimIsIdempotent(){service.advance(7,"WIN_3",3);assertEquals(3,service.achievements(7).getFirst().progress());assertFalse(service.claim(7,"WIN_3").alreadyClaimed());assertTrue(service.claim(7,"WIN_3").alreadyClaimed());assertEquals(1,grants.size());}
 @Test void incompleteCannotClaim(){service.advance(7,"WIN_3",2);assertThrows(IllegalStateException.class,()->service.claim(7,"WIN_3"));}
}
