package com.aoo.bcg.luckdraw;

import com.fasterxml.jackson.databind.ObjectMapper;import javax.sql.DataSource;import java.security.SecureRandom;import java.sql.*;import java.time.*;import java.util.*;

/** JDBC authority for eligibility, chance consumption, random selection, durable idempotency and reward outbox. */
public final class LuckDrawService {
    public record State(String campaignCode,String campaignName,long remaining,Instant startsAt,Instant endsAt,boolean open){}
    public record Result(String requestId,long drawId,String campaignCode,String prizeCode,String prizeName,String rewardKind,String rewardCode,long rewardAmount,long remaining,String deliveryState){}
    public enum Code { CAMPAIGN_NOT_FOUND,CAMPAIGN_CLOSED,NO_CHANCES,IDEMPOTENCY_CONFLICT,REWARD_PENDING,PERSISTENCE_UNAVAILABLE }
    public static final class Failure extends RuntimeException {private final Code code;public Failure(Code code,String message){super(message);this.code=code;}public Code code(){return code;}}
    private final DataSource source;private final LuckDrawPorts.RewardPort rewards;private final ObjectMapper json;private final Clock clock;private final SecureRandom random;
    public LuckDrawService(DataSource source,LuckDrawPorts.RewardPort rewards,ObjectMapper json,Clock clock,SecureRandom random){this.source=Objects.requireNonNull(source);this.rewards=Objects.requireNonNull(rewards);this.json=Objects.requireNonNull(json);this.clock=Objects.requireNonNull(clock);this.random=Objects.requireNonNull(random);}
    public State query(long player,String campaign){positive(player);campaign=code(campaign);Instant now=clock.instant();try(var c=source.getConnection()){Campaign x=campaign(c,campaign,false);long remaining=remaining(c,player,x,now,false);return new State(x.code,x.name,remaining,x.start,x.end,!now.isBefore(x.start)&&now.isBefore(x.end)&&x.enabled);}catch(Failure e){throw e;}catch(Exception e){throw persistence(e);}}
    public Result draw(String requestId,long player,String campaignCode){requestId=request(requestId);positive(player);campaignCode=code(campaignCode);String fingerprint=player+":"+campaignCode;Result existing=find(requestId,fingerprint);if(existing!=null)return dispatch(existing);Instant now=clock.instant();Result created;
        try(var c=source.getConnection()){c.setAutoCommit(false);try{Campaign campaign=campaign(c,campaignCode,true);if(!campaign.enabled||now.isBefore(campaign.start)||!now.isBefore(campaign.end))throw new Failure(Code.CAMPAIGN_CLOSED,"luck draw campaign is closed");ensureBalance(c,player,campaign,now);long remaining=consume(c,player,campaign,now);Prize prize=select(c,campaign.id);long drawId=insertDraw(c,requestId,fingerprint,player,campaign,prize,remaining,now);insertOutbox(c,requestId,drawId,player,prize,now);c.commit();created=new Result(requestId,drawId,campaign.code,prize.code,prize.name,prize.kind,prize.rewardCode,prize.amount,remaining,"PENDING");}catch(Exception e){c.rollback();throw e;}}
        catch(Failure e){throw e;}catch(SQLIntegrityConstraintViolationException e){Result raced=find(requestId,fingerprint);if(raced!=null)return dispatch(raced);throw persistence(e);}catch(Exception e){throw persistence(e);}return dispatch(created);}
    private Result dispatch(Result result){if("DELIVERED".equals(result.deliveryState))return result;String key="luckdraw:"+result.drawId;try{if("CURRENCY".equals(result.rewardKind))rewards.creditCurrency(key,resultPlayer(result.drawId),result.rewardCode,result.rewardAmount);else if("ITEM".equals(result.rewardKind))rewards.grantItem(key,resultPlayer(result.drawId),result.rewardCode,result.rewardAmount);else throw new IllegalStateException("unsupported reward kind");markDelivered(result.drawId);return new Result(result.requestId,result.drawId,result.campaignCode,result.prizeCode,result.prizeName,result.rewardKind,result.rewardCode,result.rewardAmount,result.remaining,"DELIVERED");}catch(RuntimeException e){markAttempt(result.drawId,e.getMessage());throw new Failure(Code.REWARD_PENDING,"draw committed; reward delivery is pending retry");}}
    private Result find(String requestId,String fingerprint){try(var c=source.getConnection();var q=c.prepareStatement("SELECT d.id,d.request_fingerprint,d.campaign_code,d.prize_code,d.prize_name,d.reward_kind,d.reward_code,d.reward_amount,d.remaining_count,o.status FROM aoo_luck_draw d JOIN aoo_luck_draw_outbox o ON o.draw_id=d.id WHERE d.request_id=?")){q.setString(1,requestId);try(var r=q.executeQuery()){if(!r.next())return null;if(!fingerprint.equals(r.getString(2)))throw new Failure(Code.IDEMPOTENCY_CONFLICT,"requestId was already used with different input");return new Result(requestId,r.getLong(1),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getLong(8),r.getLong(9),r.getString(10));}}catch(Failure e){throw e;}catch(Exception e){throw persistence(e);}}
    private Campaign campaign(Connection c,String code,boolean lock)throws SQLException{try(var q=c.prepareStatement("SELECT id,campaign_code,campaign_name,starts_at,ends_at,enabled,daily_free_count FROM aoo_luck_draw_campaign WHERE campaign_code=?"+(lock?" FOR UPDATE":""))){q.setString(1,code);try(var r=q.executeQuery()){if(!r.next())throw new Failure(Code.CAMPAIGN_NOT_FOUND,"luck draw campaign not found");return new Campaign(r.getLong(1),r.getString(2),r.getString(3),r.getTimestamp(4).toInstant(),r.getTimestamp(5).toInstant(),r.getBoolean(6),r.getLong(7));}}}
    private void ensureBalance(Connection c,long player,Campaign campaign,Instant now)throws SQLException{try(var q=c.prepareStatement("INSERT INTO aoo_luck_draw_chance(player_id,campaign_id,business_date,remaining_count,version,updated_at) VALUES(?,?,?,?,0,?)")){q.setLong(1,player);q.setLong(2,campaign.id);q.setDate(3,java.sql.Date.valueOf(LocalDate.ofInstant(now,ZoneOffset.UTC)));q.setLong(4,campaign.daily);q.setTimestamp(5,Timestamp.from(now));q.executeUpdate();}catch(SQLIntegrityConstraintViolationException ignored){}}
    private long remaining(Connection c,long player,Campaign x,Instant now,boolean lock)throws SQLException{try(var q=c.prepareStatement("SELECT remaining_count FROM aoo_luck_draw_chance WHERE player_id=? AND campaign_id=? AND business_date=?"+(lock?" FOR UPDATE":""))){q.setLong(1,player);q.setLong(2,x.id);q.setDate(3,java.sql.Date.valueOf(LocalDate.ofInstant(now,ZoneOffset.UTC)));try(var r=q.executeQuery()){return r.next()?r.getLong(1):x.daily;}}}
    private long consume(Connection c,long player,Campaign x,Instant now)throws SQLException{long before=remaining(c,player,x,now,true);if(before<=0)throw new Failure(Code.NO_CHANCES,"no luck draw chances remaining");try(var q=c.prepareStatement("UPDATE aoo_luck_draw_chance SET remaining_count=remaining_count-1,version=version+1,updated_at=? WHERE player_id=? AND campaign_id=? AND business_date=? AND remaining_count>0")){q.setTimestamp(1,Timestamp.from(now));q.setLong(2,player);q.setLong(3,x.id);q.setDate(4,java.sql.Date.valueOf(LocalDate.ofInstant(now,ZoneOffset.UTC)));if(q.executeUpdate()!=1)throw new Failure(Code.NO_CHANCES,"no luck draw chances remaining");return before-1;}}
    private Prize select(Connection c,long campaign)throws SQLException{List<Prize> prizes=new ArrayList<>();long total=0;try(var q=c.prepareStatement("SELECT id,prize_code,prize_name,reward_kind,reward_code,reward_amount,weight FROM aoo_luck_draw_prize WHERE campaign_id=? AND enabled=TRUE ORDER BY id")){q.setLong(1,campaign);try(var r=q.executeQuery()){while(r.next()){Prize p=new Prize(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getLong(6),r.getLong(7));if(p.weight>0){prizes.add(p);total=Math.addExact(total,p.weight);}}}}if(total<=0)throw new Failure(Code.CAMPAIGN_CLOSED,"campaign has no enabled prizes");long ticket=random.nextLong(total)+1;for(Prize p:prizes)if((ticket-=p.weight)<=0)return p;throw new IllegalStateException("random selection failed");}
    private long insertDraw(Connection c,String request,String fingerprint,long player,Campaign campaign,Prize prize,long remaining,Instant now)throws SQLException{try(var q=c.prepareStatement("INSERT INTO aoo_luck_draw(request_id,request_fingerprint,player_id,campaign_id,campaign_code,prize_id,prize_code,prize_name,reward_kind,reward_code,reward_amount,remaining_count,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){int i=0;q.setString(++i,request);q.setString(++i,fingerprint);q.setLong(++i,player);q.setLong(++i,campaign.id);q.setString(++i,campaign.code);q.setLong(++i,prize.id);q.setString(++i,prize.code);q.setString(++i,prize.name);q.setString(++i,prize.kind);q.setString(++i,prize.rewardCode);q.setLong(++i,prize.amount);q.setLong(++i,remaining);q.setTimestamp(++i,Timestamp.from(now));q.executeUpdate();try(var r=q.getGeneratedKeys()){if(!r.next())throw new SQLException("draw id unavailable");return r.getLong(1);}}}
    private void insertOutbox(Connection c,String request,long draw,long player,Prize prize,Instant now)throws Exception{try(var q=c.prepareStatement("INSERT INTO aoo_luck_draw_outbox(draw_id,event_key,event_type,payload_json,status,attempt_count,next_attempt_at,created_at,updated_at) VALUES(?,?,?,?, 'PENDING',0,?,?,?)")){q.setLong(1,draw);q.setString(2,"luckdraw:"+draw);q.setString(3,"LUCK_DRAW_REWARD_REQUESTED");q.setString(4,json.writeValueAsString(Map.of("requestId",request,"playerId",player,"rewardKind",prize.kind,"rewardCode",prize.rewardCode,"amount",prize.amount)));q.setTimestamp(5,Timestamp.from(now));q.setTimestamp(6,Timestamp.from(now));q.setTimestamp(7,Timestamp.from(now));q.executeUpdate();}}
    private long resultPlayer(long draw){try(var c=source.getConnection();var q=c.prepareStatement("SELECT player_id FROM aoo_luck_draw WHERE id=?")){q.setLong(1,draw);try(var r=q.executeQuery()){if(!r.next())throw new IllegalStateException("draw missing");return r.getLong(1);}}catch(Exception e){throw persistence(e);}}
    private void markDelivered(long draw){updateOutbox(draw,"DELIVERED",null);}private void markAttempt(long draw,String error){updateOutbox(draw,"PENDING",error);}
    private void updateOutbox(long draw,String status,String error){try(var c=source.getConnection();var q=c.prepareStatement("UPDATE aoo_luck_draw_outbox SET status=?,attempt_count=attempt_count+1,last_error=?,updated_at=? WHERE draw_id=?")){q.setString(1,status);q.setString(2,error==null?null:error.substring(0,Math.min(500,error.length())));q.setTimestamp(3,Timestamp.from(clock.instant()));q.setLong(4,draw);q.executeUpdate();}catch(Exception e){throw persistence(e);}}
    private static long positive(long n){if(n<=0)throw new IllegalArgumentException("playerId must be positive");return n;}private static String request(String x){if(x==null||!x.matches("[A-Za-z0-9_.:-]{1,128}"))throw new IllegalArgumentException("valid requestId required");return x;}private static String code(String x){if(x==null||!x.matches("[A-Za-z0-9_.:-]{1,64}"))throw new IllegalArgumentException("valid campaignCode required");return x;}private static Failure persistence(Exception e){return new Failure(Code.PERSISTENCE_UNAVAILABLE,"luck draw persistence unavailable");}
    private record Campaign(long id,String code,String name,Instant start,Instant end,boolean enabled,long daily){}private record Prize(long id,String code,String name,String kind,String rewardCode,long amount,long weight){}
}
