package com.aoo.bcg.luckdraw;

import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

/** Authenticated production route. Legacy HTTP entry points are intentionally not mounted. */
public final class LuckDrawHttpRoutes {
    private final LuckDrawService service;private final LuckDrawPorts.PlayerAuthenticator auth;private final ObjectMapper json;
    public LuckDrawHttpRoutes(LuckDrawService service,LuckDrawPorts.PlayerAuthenticator auth,ObjectMapper json){this.service=Objects.requireNonNull(service);this.auth=Objects.requireNonNull(auth);this.json=Objects.requireNonNull(json);}
    public void mount(HttpServer server){server.createContext("/health/luck-draw",e->reply(e,200,Map.of("code","OK","data",Map.of("status","UP","persistence","jdbc","random","server-secure-random","delivery","transactional-outbox"))));server.createContext("/v1/luck-draw",this::handle);}
    private void handle(HttpExchange e)throws IOException{try{if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw new Api(426,"API_VERSION_REQUIRED","X-API-Version: 1 required");long player=auth.authenticate(e.getRequestHeaders().getFirst("Authorization"));String campaign=query(e,"campaignCode");Object data;if("GET".equals(e.getRequestMethod()))data=service.query(player,campaign);else if("POST".equals(e.getRequestMethod()))data=service.draw(requestId(e),player,campaign);else throw new Api(405,"METHOD_NOT_ALLOWED","GET or POST required");reply(e,200,Map.of("code","OK","requestId",requestIdOptional(e),"data",data));}catch(Api x){reply(e,x.status,error(x.code,x.getMessage()));}catch(SecurityException x){reply(e,401,error("UNAUTHORIZED","valid account bearer assertion required"));}catch(IllegalArgumentException x){reply(e,400,error("INVALID_REQUEST",x.getMessage()));}catch(LuckDrawService.Failure x){int status=switch(x.code()){case CAMPAIGN_NOT_FOUND->404;case CAMPAIGN_CLOSED,NO_CHANCES,IDEMPOTENCY_CONFLICT->409;case REWARD_PENDING->202;case PERSISTENCE_UNAVAILABLE->503;};reply(e,status,error(x.code().name(),x.getMessage()));}catch(Exception x){reply(e,500,error("INTERNAL_ERROR","luck draw request failed"));}}
    private static Map<String,Object> error(String code,String message){return Map.of("code",code,"message",message==null?code:message);}
    private static String query(HttpExchange e,String name){String raw=e.getRequestURI().getRawQuery();if(raw==null)throw new IllegalArgumentException(name+" required");for(String part:raw.split("&",-1)){String[] kv=part.split("=",2);if(kv.length==2&&name.equals(kv[0])&&!kv[1].isBlank())return java.net.URLDecoder.decode(kv[1],StandardCharsets.UTF_8);}throw new IllegalArgumentException(name+" required");}
    private static String requestId(HttpExchange e){String value=e.getRequestHeaders().getFirst("Idempotency-Key");if(value==null)value=e.getRequestHeaders().getFirst("X-Request-Id");return value;}private static String requestIdOptional(HttpExchange e){String x=e.getRequestHeaders().getFirst("Idempotency-Key");return x==null?"":x;}
    private void reply(HttpExchange e,int status,Object value)throws IOException{byte[] body=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,body.length);try(var out=e.getResponseBody()){out.write(body);}}
    private static final class Api extends RuntimeException{final int status;final String code;Api(int status,String code,String message){super(message);this.status=status;this.code=code;}}
}
