package com.aoo.bcg.location;

public enum LocationErrorCode {
    INVALID_ARGUMENT,
    UNAUTHENTICATED,
    FORBIDDEN,
    UNSUPPORTED_API_VERSION,
    IDEMPOTENCY_KEY_REUSED,
    REQUEST_IN_PROGRESS,
    STALE_EVENT,
    PARTICIPANT_NOT_FOUND,
    PERSISTENCE_FAILURE
}
