#!/usr/bin/env ruby
require 'json';require 'pathname';require 'time'
root=Pathname(__dir__).join('..').expand_path;marker=root.join('work/audit/unused38-clean-start.marker');abort('UNUSED38 marker missing')unless marker.exist?;started=marker.mtime
reactor_target=lambda{|path|module_dir=path.sub(%r{/target/.*},'');File.exist?(File.join(module_dir,'pom.xml'))}
jars=Dir[root.join('server/**/target/*.jar').to_s].select{|p|reactor_target.call(p)};classes=Dir[root.join('server/**/target/classes/**/*.class').to_s].select{|p|reactor_target.call(p)};reports=Dir[root.join('server/**/target/surefire-reports/TEST-*.xml').to_s].select{|p|reactor_target.call(p)}
historical=reports.find{|p|p.include?('HistoricalFormatCompatibilityTest')};historical_ok=historical&&File.read(historical).match?(/tests="[3-9]/)&&!File.read(historical).match?(/failures="[1-9]|errors="[1-9]/)
meta_count=Dir[root.join('../Client/assets/**/*.meta').expand_path.to_s].length;resource_gate=root.join('work/audit/unused21-resource-tooling.json')
checks={freshReactorJars:jars.length>=20&&jars.all?{|p|File.mtime(p)>=started},freshCompiledClasses:classes.length>=1000&&classes.all?{|p|File.mtime(p)>=started},historicalDataReadTest:!!historical_ok,creatorResourcesOpenable:meta_count>100&&resource_gate.exist?&&JSON.parse(resource_gate.read)['status']=='passed',fullChainEvidence:JSON.parse(root.join('work/audit/unused28-full-chain.json').read)['status']=='passed',isolatedLegacyArtifacts:JSON.parse(root.join('work/audit/unused36-isolated-retention.json').read)['status']=='passed'}
errors=checks.reject{|_,v|v}.keys;report={task:'UNUSED38',status:errors.empty? ? 'passed':'failed',cleanStartedAt:started.iso8601,checks:checks,freshJarCount:jars.length,freshClassCount:classes.length,testReportCount:reports.length,creatorMetaCount:meta_count,errors:errors};root.join('work/audit/unused38-clean-recovery.json').write(JSON.pretty_generate(report)+"\n");abort("UNUSED38 failed: #{errors.join(', ')}")unless errors.empty?;puts "UNUSED38 passed: clean reactor rebuilt #{jars.length} jars/#{classes.length} classes with historical/resource/full-chain evidence"
