#!/usr/bin/env ruby
require 'json';require 'find';require 'digest';require 'fileutils'
root=File.expand_path('..',__dir__);client=File.expand_path('../Client',root);assets=File.join(client,'assets');out=File.join(root,'docs/generated');FileUtils.mkdir_p(out)
legacy=Dir.glob(File.join(assets,'**/*Legacy*'))+Dir.glob(File.join(assets,'**/Legacy/**/*'));legacy=legacy.uniq.select{|p|File.file?(p)}
inventory=legacy.map{|p|{path:p.delete_prefix(client+'/'),bytes:File.size(p),sha256:Digest::SHA256.file(p).hexdigest,extension:File.extname(p).downcase}}
roomcost=Dir.glob(File.join(assets,'**/roomcost.json')).sort.map{|p|{path:p.delete_prefix(client+'/'),bytes:File.size(p),sha256:Digest::SHA256.file(p).hexdigest}}
loads=[];Dir.glob(File.join(assets,'**/*.ts')).each{|p|File.foreach(p).with_index(1){|l,i|loads<<{path:p.delete_prefix(client+'/'),line:i+1} if l.match?(/Legacy|resources\.load|loadBundle|roomcost|gameCreate/)}}
emit=lambda{|id,data|File.write(File.join(out,"#{id}.json"),JSON.pretty_generate({schemaVersion:1}.merge(data))+"\n")}
emit.call('cleg01-legacy-inventory',{files:inventory,sourceReplacementComplete:false,passed:false});emit.call('cleg02-roomcost-consistency',{files:roomcost,uniqueHashes:roomcost.map{|r|r[:sha256]}.uniq.length,databaseBillingClosure:false,passed:false});emit.call('cleg03-client-billing-authority',{tamperTestPresent:false,serverSnapshotIndependenceProven:false,passed:false});emit.call('cleg04-dynamic-load',{hits:loads,passed:loads.empty?});emit.call('cleg05-migration',{legacyFiles:inventory.length,newSchemaCoverage:false,activeUsage:true,passed:false});emit.call('cleg06-build-isolation',{legacyFilesByExtension:inventory.group_by{|r|r[:extension]}.transform_values(&:length),insideAssets:true,passed:false});emit.call('cleg07-room-cost-regression',{requiredSurfaces:%w[lobbyCreate clubTemplate roomRules ledger errorMessage],endToEndCoverage:false,passed:false});emit.call('cleg08-tamper-test',{attack:'modify client roomcost and verify server charge/assets unchanged',implemented:false,passed:false});puts "CLEG01-CLEG08 audited: legacy=#{inventory.length}, roomcost=#{roomcost.length}, loadHits=#{loads.length}"
