require 'json';require 'fileutils';require 'set'
root=File.expand_path('..',__dir__);client=File.expand_path('../Client',root);assets=File.join(client,'assets');uuid_report=JSON.parse(File.read(File.join(root,'work/audit/cocos-uuid-reference-audit.json')));dynamic=JSON.parse(File.read(File.join(root,'work/audit/client-dynamic-load-graph.json')))
referenced=Set.new;Dir.glob(File.join(assets,'**/*.{prefab,scene,json}')).each{|path|File.binread(path).force_encoding('UTF-8').scrub.scan(/"__uuid__"\s*:\s*"([0-9a-fA-F-]{20,40})"/){|uuid|referenced<<uuid[0]}}
script_corpus=Dir.glob(File.join(assets,'**/*.{ts,js}')).map{|path|File.binread(path).force_encoding('UTF-8').scrub}.join("\n");bundle_roots=dynamic['bundleRoots'].to_set;extensions=%w[.prefab .scene .png .jpg .jpeg .webp .plist .atlas .ttf .otf .mp3 .ogg .wav .json];rows=[]
Dir.glob(File.join(assets,'**/*')).select{|path|File.file?(path)&&extensions.include?(File.extname(path).downcase)}.each do |path|
 meta=path+'.meta';uuid=nil;if File.file?(meta);begin;uuid=JSON.parse(File.read(meta))['uuid'];rescue JSON::ParserError;end;end
 relative=path.sub(client+'/','');base=File.basename(path,File.extname(path));in_bundle=bundle_roots.any?{|bundle|relative.start_with?(bundle+'/')};literal=script_corpus.match?(/(?<![A-Za-z0-9_])#{Regexp.escape(base)}(?![A-Za-z0-9_])/);direct=uuid&&referenced.include?(uuid);status=(direct||literal||in_bundle)?'reachable':'review-unused'
 rows<<{path:relative,type:File.extname(path).downcase,uuid:uuid,directReference:!!direct,pathLiteral:literal,dynamicBundleRoot:in_bundle,status:status}
end
review=rows.select{|row|row[:status]=='review-unused'};out=File.join(root,'work/audit/dead12-client-resource-reachability.json');FileUtils.mkdir_p(File.dirname(out));File.write(out,JSON.pretty_generate({task:'DEAD12',status:'passed-with-review',resourceCount:rows.size,reachableCount:rows.size-review.size,reviewUnusedCount:review.size,unresolvedDynamicExpressions:dynamic.dig('summary','unresolvedDynamicExpressions'),uuidIntegrity:uuid_report['summary'],resources:rows,limitations:['Computed runtime paths and Editor-only dependency resolution require final instrumented load capture before deletion.']})+"\n")
File.write(File.join(root,'docs/前端资源删除复核登记.md'),"# 前端资源删除复核登记\n\n静态无引用不等于可删除。必须补齐 Creator AssetDB、运行时动态加载、热更新清单、原生平台和失败路径证据。\n\n| 资源 | 类型 | Creator/运行证据 | 结论 |\n|---|---|---|---|\n"+review.map{|row|"| `#{row[:path]}` | #{row[:type]} | 待补 | 待人工核验 |"}.join("\n")+"\n")
