#!/usr/bin/env ruby
# frozen_string_literal: true
require 'json'; require 'time'
ROOT=File.expand_path('..',__dir__); OUTPUT=File.join(ROOT,'docs/generated/proto02-tool-responsibility.json'); TASKS=File.join(ROOT,'docs/Aoo-前后端全框架功能通信审计任务清单.md'); MANIFEST=File.join(ROOT,'docs/generated/generated-artifact-manifest.json')
java_target=File.join(ROOT,'server/GameSPI/src/main/java/com/aoo/bcg/gamespi/protocol/GeneratedProtocolIds.java'); ts_target=File.expand_path('../Client/assets/Common/Code/Runtime/network/GeneratedProtocolIds.ts',ROOT)
generators=(Dir[File.join(ROOT,'tools/**/generate*protocol*')]+Dir[File.join(ROOT,'tools/protocol/generate.*')]).select{|path|File.file?(path)}.uniq.sort; java=File.exist?(java_target)?File.read(java_target,encoding:'UTF-8'):''; ts=File.exist?(ts_target)?File.read(ts_target,encoding:'UTF-8'):''
ids=JSON.parse(File.read(File.join(ROOT,'protocol/aoo-protocol-v2.json'),encoding:'UTF-8')).fetch('messages').map{|message|message.fetch('msgId')}
checks={oneGenerator:generators.map{|path|path.delete_prefix(ROOT+'/')}==['tools/protocol/generate.mjs'],javaGeneratedInActiveSpi:java.include?('package com.aoo.bcg.gamespi.protocol;')&&java.include?('Do not edit.'),clientGeneratedInNetworkLayer:ts.include?('Do not edit.')&&ts_target.include?('/Runtime/network/'),everyMessageGeneratedInBothLanguages:ids.all?{|id|java.include?(%Q{"#{id}"})&&ts.include?(%Q{'#{id}'})},noLegacyGeneratedDefinition:!File.exist?(File.join(ROOT,'server/LegacyCommon/src/com/ddm/server/protocol/v2/GeneratedProtocolIds.java')),compatibilityCodeConsumesActiveDefinition:%w[ProtocolRegistry.java ProtocolV2Bridge.java].all?{|name|File.read(File.join(ROOT,'server/LegacyCommon/src/com/ddm/server/protocol/v2',name),encoding:'UTF-8').include?('import com.aoo.bcg.gamespi.protocol.GeneratedProtocolIds;')}}
report={schemaVersion:1,generatedAt:Time.now.utc.iso8601,task:'PROTO02',generator:generators.map{|path|path.delete_prefix(ROOT+'/')},outputs:[java_target.delete_prefix(ROOT+'/'),ts_target.delete_prefix(File.expand_path('..',ROOT)+'/')],messageCount:ids.size,responsibilities:{protocol:'machine source only',toolsProtocol:'validation and deterministic generation only',generatedJava:'active server constants and immutable metadata only',generatedTypeScript:'client constants and immutable metadata only',legacyCommdef:'isolated compatibility adapter input; never an authority source'},checks:checks,passed:checks.values.all?};File.write(OUTPUT,JSON.pretty_generate(report)+"\n",mode:'w:UTF-8')
tasks=File.read(TASKS,encoding:'UTF-8');status=report[:passed]?'已完成':'失败跳过';result=report[:passed]?'通过':'未完成';detail=report[:passed]?"协议职责已收敛：protocol 仅存机器源，tools/protocol 仅有校验/模型/唯一生成器；#{ids.size} 个消息同步生成到 active GameSPI Java 与客户端统一网络层，遗留 commdef/桥接仅消费生成定义，不再生成或维护第二份 V2 常量。":"协议工具职责门禁未通过：#{checks.reject{|_,passed|passed}.keys.join('、')}，已记录后跳过。";tasks.sub!(/^\| PROTO02 \|.*$/,"| PROTO02 | #{status} | `tools/protocol` 职责 | #{result} | #{detail} 证据：docs/generated/proto02-tool-responsibility.json |")or abort'PROTO02 row not found';File.write(TASKS,tasks,mode:'w:UTF-8')
manifest=JSON.parse(File.read(MANIFEST,encoding:'UTF-8'));manifest.fetch('artifacts').reject!{|artifact|artifact['path']=='server/LegacyCommon/src/com/ddm/server/protocol/v2/GeneratedProtocolIds.java'};[['server/GameSPI/src/main/java/com/aoo/bcg/gamespi/protocol/GeneratedProtocolIds.java','generated-java'],['../Client/assets/Common/Code/Runtime/network/GeneratedProtocolIds.ts','generated-typescript'],['docs/generated/proto02-tool-responsibility.json','generated-protocol-evidence']].each{|path,kind|next if manifest.fetch('artifacts').any?{|artifact|artifact['path']==path};manifest.fetch('artifacts')<<{'path'=>path,'kind'=>kind,'authoritativeInputs'=>['protocol/aoo-protocol-v2.json','tools/protocol/protocol-model.mjs'],'generator'=>path.start_with?('docs/')?'scripts/audit-proto02-tool-responsibility.rb':'tools/protocol/generate.mjs','rebuild'=>path.start_with?('docs/')?'ruby scripts/audit-proto02-tool-responsibility.rb':'node tools/protocol/generate.mjs','owner'=>'protocol-governance','editPolicy'=>'generated-do-not-edit'}};File.write(MANIFEST,JSON.pretty_generate(manifest)+"\n",mode:'w:UTF-8');puts JSON.generate(report.slice(:task,:generator,:messageCount,:checks,:passed));exit 1 unless report[:passed]
