package com.aoo.bcg.media;

import javax.sql.DataSource;
import java.sql.*;
import java.time.Instant;
import java.util.*;

public final class JdbcMediaRepository implements MediaRepository {
    private final DataSource source;
    public JdbcMediaRepository(DataSource source){this.source=Objects.requireNonNull(source);}
    @Override public Optional<Asset> findReadyByHash(String hash,long size,String mime){return assetQuery("SELECT id,object_key,kind,mime_type,byte_size,duration_ms,sha256 FROM media_asset WHERE sha256=? AND byte_size=? AND mime_type=? AND state='READY' ORDER BY id LIMIT 1",hash,size,mime);}
    @Override public Optional<Asset> asset(long id){return assetQuery("SELECT id,object_key,kind,mime_type,byte_size,duration_ms,sha256 FROM media_asset WHERE id=? AND state='READY'",id);}
    private Optional<Asset> assetQuery(String sql,Object... values){try(var c=source.getConnection();var p=c.prepareStatement(sql)){bind(p,values);try(var r=p.executeQuery()){return r.next()?Optional.of(new Asset(r.getLong(1),r.getString(2),MediaPolicy.Kind.valueOf(r.getString(3)),r.getString(4),r.getLong(5),r.getLong(6),r.getString(7))):Optional.empty();}}catch(SQLException e){throw db(e);}}
    @Override public boolean canRead(long assetId,long ownerId){try(var c=source.getConnection();var p=c.prepareStatement("SELECT 1 FROM media_asset_access WHERE asset_id=? AND owner_id=?")){p.setLong(1,assetId);p.setLong(2,ownerId);try(var r=p.executeQuery()){return r.next();}}catch(SQLException e){throw db(e);}}
    @Override public void grant(long assetId,long ownerId){try(var c=source.getConnection();var p=c.prepareStatement("INSERT INTO media_asset_access(asset_id,owner_id,granted_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE granted_at=granted_at")){p.setLong(1,assetId);p.setLong(2,ownerId);p.setTimestamp(3,Timestamp.from(Instant.now()));p.executeUpdate();}catch(SQLException e){throw db(e);}}
    @Override public Asset authorizeVoice(long assetId,long senderId,List<Long> memberIds){try(var c=source.getConnection()){c.setAutoCommit(false);try{Asset asset;try(var q=c.prepareStatement("SELECT a.id,a.object_key,a.kind,a.mime_type,a.byte_size,a.duration_ms,a.sha256 FROM media_asset a JOIN media_asset_access x ON x.asset_id=a.id WHERE a.id=? AND x.owner_id=? AND a.state='READY' AND a.kind='VOICE' FOR UPDATE")){q.setLong(1,assetId);q.setLong(2,senderId);try(var r=q.executeQuery()){if(!r.next())throw new SecurityException("sender does not own READY voice asset");asset=new Asset(r.getLong(1),r.getString(2),MediaPolicy.Kind.valueOf(r.getString(3)),r.getString(4),r.getLong(5),r.getLong(6),r.getString(7));}}try(var p=c.prepareStatement("INSERT INTO media_asset_access(asset_id,owner_id,granted_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE granted_at=granted_at")){for(long member:new LinkedHashSet<>(memberIds)){if(member<=0)throw new IllegalArgumentException("room member id invalid");p.setLong(1,assetId);p.setLong(2,member);p.setTimestamp(3,Timestamp.from(Instant.now()));p.addBatch();}p.executeBatch();}c.commit();return asset;}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}catch(Exception e){if(e instanceof RuntimeException r)throw r;throw db((SQLException)e);}}
    @Override public void create(Ticket t){try(var c=source.getConnection();var p=c.prepareStatement("INSERT INTO media_upload_ticket(id,owner_id,object_key,storage_upload_id,kind,mime_type,byte_size,duration_ms,sha256,chunk_bytes,expected_parts,expires_at,state,asset_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){int i=1;p.setString(i++,t.id());p.setLong(i++,t.ownerId());p.setString(i++,t.objectKey());p.setString(i++,t.storageUploadId());p.setString(i++,t.kind().name());p.setString(i++,t.mime());p.setLong(i++,t.size());p.setLong(i++,t.durationMillis());p.setString(i++,t.sha256());p.setInt(i++,t.chunkBytes());p.setInt(i++,t.expectedParts());p.setTimestamp(i++,Timestamp.from(t.expiresAt()));p.setString(i++,t.state().name());p.setNull(i++,Types.BIGINT);Timestamp now=Timestamp.from(Instant.now());p.setTimestamp(i++,now);p.setTimestamp(i,now);p.executeUpdate();}catch(SQLException e){throw db(e);}}
    @Override public Optional<Ticket> ticket(String id){try(var c=source.getConnection();var p=c.prepareStatement("SELECT id,owner_id,object_key,storage_upload_id,kind,mime_type,byte_size,duration_ms,sha256,chunk_bytes,expected_parts,expires_at,state,asset_id FROM media_upload_ticket WHERE id=?")){p.setString(1,id);try(var r=p.executeQuery()){if(!r.next())return Optional.empty();long aid=r.getLong(14);return Optional.of(new Ticket(r.getString(1),r.getLong(2),r.getString(3),r.getString(4),MediaPolicy.Kind.valueOf(r.getString(5)),r.getString(6),r.getLong(7),r.getLong(8),r.getString(9),r.getInt(10),r.getInt(11),r.getTimestamp(12).toInstant(),TicketState.valueOf(r.getString(13)),r.wasNull()?null:aid));}}catch(SQLException e){throw db(e);}}
    @Override public void addPart(String ticketId,Part part){try(var c=source.getConnection();var p=c.prepareStatement("INSERT INTO media_upload_part(ticket_id,part_number,byte_size,etag,sha256,created_at) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE byte_size=VALUES(byte_size),etag=VALUES(etag),sha256=VALUES(sha256)")){p.setString(1,ticketId);p.setInt(2,part.number());p.setLong(3,part.size());p.setString(4,part.etag());p.setString(5,part.sha256());p.setTimestamp(6,Timestamp.from(Instant.now()));p.executeUpdate();}catch(SQLException e){throw db(e);}}
    @Override public List<Part> parts(String id){try(var c=source.getConnection();var p=c.prepareStatement("SELECT part_number,byte_size,etag,sha256 FROM media_upload_part WHERE ticket_id=? ORDER BY part_number")){p.setString(1,id);try(var r=p.executeQuery()){var out=new ArrayList<Part>();while(r.next())out.add(new Part(r.getInt(1),r.getLong(2),r.getString(3),r.getString(4)));return List.copyOf(out);}}catch(SQLException e){throw db(e);}}
    @Override public boolean transition(String id,TicketState expected,TicketState next){try(var c=source.getConnection();var p=c.prepareStatement("UPDATE media_upload_ticket SET state=?,updated_at=? WHERE id=? AND state=?")){p.setString(1,next.name());p.setTimestamp(2,Timestamp.from(Instant.now()));p.setString(3,id);p.setString(4,expected.name());return p.executeUpdate()==1;}catch(SQLException e){throw db(e);}}
    @Override public long finish(String ticketId,String key,MediaPolicy.Kind kind,String mime,long size,long duration,String hash,long owner){try(var c=source.getConnection()){c.setAutoCommit(false);try{Long existing=null;try(var q=c.prepareStatement("SELECT id FROM media_asset WHERE sha256=? AND byte_size=? AND mime_type=? AND state='READY' ORDER BY id LIMIT 1 FOR UPDATE")){q.setString(1,hash);q.setLong(2,size);q.setString(3,mime);try(var r=q.executeQuery()){if(r.next())existing=r.getLong(1);}}long id;if(existing!=null)id=existing;else try(var p=c.prepareStatement("INSERT INTO media_asset(object_key,kind,mime_type,byte_size,duration_ms,sha256,state,created_at) VALUES(?,?,?,?,?,?,'READY',?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,key);p.setString(2,kind.name());p.setString(3,mime);p.setLong(4,size);p.setLong(5,duration);p.setString(6,hash);p.setTimestamp(7,Timestamp.from(Instant.now()));p.executeUpdate();try(var r=p.getGeneratedKeys()){if(!r.next())throw new SQLException("asset id missing");id=r.getLong(1);}}try(var p=c.prepareStatement("INSERT INTO media_asset_access(asset_id,owner_id,granted_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE granted_at=granted_at")){p.setLong(1,id);p.setLong(2,owner);p.setTimestamp(3,Timestamp.from(Instant.now()));p.executeUpdate();}try(var p=c.prepareStatement("UPDATE media_upload_ticket SET state='READY',asset_id=?,updated_at=? WHERE id=? AND state='COMPLETING'")){p.setLong(1,id);p.setTimestamp(2,Timestamp.from(Instant.now()));p.setString(3,ticketId);if(p.executeUpdate()!=1)throw new SQLException("ticket state changed");}c.commit();return id;}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}catch(Exception e){throw e instanceof SQLException s?db(s):new IllegalStateException(e);}}
    @Override public void fail(String id,TicketState state,String reason){try(var c=source.getConnection();var p=c.prepareStatement("UPDATE media_upload_ticket SET state=?,failure_reason=?,updated_at=? WHERE id=? AND state NOT IN ('READY','EXPIRED')")){p.setString(1,state.name());p.setString(2,reason==null?"unspecified":reason.substring(0,Math.min(255,reason.length())));p.setTimestamp(3,Timestamp.from(Instant.now()));p.setString(4,id);p.executeUpdate();}catch(SQLException e){throw db(e);}}
    @Override public List<Ticket> expired(Instant now,int limit){try(var c=source.getConnection();var p=c.prepareStatement("SELECT id FROM media_upload_ticket WHERE state='OPEN' AND expires_at<=? ORDER BY expires_at LIMIT ?")){p.setTimestamp(1,Timestamp.from(now));p.setInt(2,Math.max(1,Math.min(limit,1000)));var out=new ArrayList<Ticket>();try(var r=p.executeQuery()){while(r.next())ticket(r.getString(1)).ifPresent(out::add);}return out;}catch(SQLException e){throw db(e);}}
    private static void bind(PreparedStatement p,Object... values)throws SQLException{for(int i=0;i<values.length;i++)p.setObject(i+1,values[i]);}
    private static IllegalStateException db(SQLException e){return new IllegalStateException("media repository failure",e);}
}
