package com.aoo.bcg.media;

import java.io.*;
import java.security.*;
import java.time.*;
import java.util.*;

public final class MediaUploadService {
    public record Initiated(String ticketId,Long assetId,int chunkBytes,int expectedParts,Instant expiresAt,boolean deduplicated) {}
    public record Completed(long assetId,boolean deduplicated) {}
    private final MediaRepository repository;private final ObjectStorage storage;private final MediaPolicy policy;private final Clock clock;private final Duration ttl;
    public MediaUploadService(MediaRepository repository,ObjectStorage storage,MediaPolicy policy,Clock clock,Duration ttl){this.repository=Objects.requireNonNull(repository);this.storage=Objects.requireNonNull(storage);this.policy=Objects.requireNonNull(policy);this.clock=Objects.requireNonNull(clock);if(ttl==null||ttl.isNegative()||ttl.isZero()||ttl.compareTo(Duration.ofHours(24))>0)throw new IllegalArgumentException("ticket TTL must be in (0,24h]");this.ttl=ttl;}
    public Initiated initiate(long owner,MediaPolicy.Kind kind,String mime,long size,long duration,String sha256){requireOwner(owner);var rule=policy.validate(kind,mime,size,duration,sha256);var existing=repository.findReadyByHash(sha256,size,mime);if(existing.isPresent()){repository.grant(existing.get().id(),owner);return new Initiated(null,existing.get().id(),0,0,null,true);}String id=UUID.randomUUID().toString(),key="media/"+sha256.substring(0,2)+"/"+sha256,uploadId=storage.begin(key,mime);int parts=(int)((size+rule.chunkBytes()-1)/rule.chunkBytes());Instant expires=clock.instant().plus(ttl);try{repository.create(new MediaRepository.Ticket(id,owner,key,uploadId,kind,mime,size,duration,sha256,rule.chunkBytes(),parts,expires,MediaRepository.TicketState.OPEN,null));}catch(RuntimeException e){compensateAbort(key,uploadId,e);throw e;}return new Initiated(id,null,rule.chunkBytes(),parts,expires,false);}
    public void upload(long owner,String ticketId,int number,byte[] content){var t=requireOpen(owner,ticketId);if(number<1||number>t.expectedParts())throw new IllegalArgumentException("part number outside ticket range");long expected=number<t.expectedParts()?t.chunkBytes():t.size()-(long)t.chunkBytes()*(t.expectedParts()-1);if(content==null||content.length!=expected)throw new IllegalArgumentException("part byte size mismatch");String hash=sha256(new ByteArrayInputStream(content));String etag=storage.uploadPart(t.objectKey(),t.storageUploadId(),number,content);try{repository.addPart(t.id(),new MediaRepository.Part(number,content.length,etag,hash));}catch(RuntimeException e){repository.fail(t.id(),MediaRepository.TicketState.FAILED,"part metadata persistence failed");compensateAbort(t.objectKey(),t.storageUploadId(),e);throw e;}}
    public Completed complete(long owner,String ticketId){var t=requireOpen(owner,ticketId);List<MediaRepository.Part> parts=repository.parts(t.id());validateParts(t,parts);if(!repository.transition(t.id(),MediaRepository.TicketState.OPEN,MediaRepository.TicketState.COMPLETING))throw new IllegalStateException("ticket is no longer open");boolean composed=false;try{storage.complete(t.objectKey(),t.storageUploadId(),parts.stream().map(p->new ObjectStorage.UploadedPart(p.number(),p.etag())).toList());composed=true;String actual;long bytes;try(InputStream in=storage.open(t.objectKey())){var digest=MessageDigest.getInstance("SHA-256");byte[] buffer=new byte[64*1024];long count=0;for(int n;(n=in.read(buffer))>=0;){digest.update(buffer,0,n);count+=n;}actual=HexFormat.of().formatHex(digest.digest());bytes=count;}if(bytes!=t.size()||!MessageDigest.isEqual(actual.getBytes(),t.sha256().getBytes()))throw new IllegalArgumentException("completed object hash or size mismatch");long id=repository.finish(t.id(),t.objectKey(),t.kind(),t.mime(),t.size(),t.durationMillis(),t.sha256(),owner);return new Completed(id,false);}catch(NoSuchAlgorithmException impossible){throw new IllegalStateException(impossible);}catch(RuntimeException|IOException e){try{if(composed)storage.delete(t.objectKey());else storage.abort(t.objectKey(),t.storageUploadId());}catch(RuntimeException cleanup){e.addSuppressed(cleanup);}repository.fail(t.id(),MediaRepository.TicketState.FAILED,e.getClass().getSimpleName());throw e instanceof RuntimeException r?r:new IllegalStateException("object verification failed",e);}}
    public MediaRepository.Asset authorizeRead(long owner,long assetId){requireOwner(owner);if(!repository.canRead(assetId,owner))throw new SecurityException("media access denied");return repository.asset(assetId).orElseThrow(()->new IllegalArgumentException("media asset not found"));}
    public MediaRepository.Asset authorizeVoice(long sender,long assetId,List<Long> roomMembers){requireOwner(sender);if(assetId<=0)throw new IllegalArgumentException("assetId required");if(roomMembers==null||roomMembers.isEmpty()||roomMembers.size()>100)throw new IllegalArgumentException("roomMembers required");if(!roomMembers.contains(sender))throw new SecurityException("sender is not a room member");return repository.authorizeVoice(assetId,sender,List.copyOf(roomMembers));}
    public InputStream open(MediaRepository.Asset asset){return storage.open(asset.objectKey());}
    public int cleanupExpired(int limit){int cleaned=0;for(var t:repository.expired(clock.instant(),limit)){try{storage.abort(t.objectKey(),t.storageUploadId());repository.fail(t.id(),MediaRepository.TicketState.EXPIRED,"ticket expired");cleaned++;}catch(RuntimeException ignored){repository.fail(t.id(),MediaRepository.TicketState.FAILED,"expiry abort failed");}}return cleaned;}
    private MediaRepository.Ticket requireOpen(long owner,String id){requireOwner(owner);var t=repository.ticket(id).orElseThrow(()->new IllegalArgumentException("upload ticket not found"));if(t.ownerId()!=owner)throw new SecurityException("upload ticket owner mismatch");if(t.state()!=MediaRepository.TicketState.OPEN)throw new IllegalStateException("upload ticket is not open");if(!clock.instant().isBefore(t.expiresAt())){try{storage.abort(t.objectKey(),t.storageUploadId());}finally{repository.fail(t.id(),MediaRepository.TicketState.EXPIRED,"ticket expired");}throw new IllegalStateException("upload ticket expired");}return t;}
    private static void validateParts(MediaRepository.Ticket t,List<MediaRepository.Part> parts){if(parts.size()!=t.expectedParts())throw new IllegalArgumentException("upload parts incomplete");long size=0;for(int i=0;i<parts.size();i++){var p=parts.get(i);if(p.number()!=i+1)throw new IllegalArgumentException("upload parts are not contiguous");size+=p.size();}if(size!=t.size())throw new IllegalArgumentException("upload part total mismatch");}
    private void compensateAbort(String key,String uploadId,RuntimeException original){try{storage.abort(key,uploadId);}catch(RuntimeException cleanup){original.addSuppressed(cleanup);}}
    private static void requireOwner(long owner){if(owner<=0)throw new SecurityException("authenticated owner required");}
    private static String sha256(InputStream in){try{var digest=MessageDigest.getInstance("SHA-256");byte[] b=new byte[8192];for(int n;(n=in.read(b))>=0;)digest.update(b,0,n);return HexFormat.of().formatHex(digest.digest());}catch(IOException|NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
