package com.aoo.bcg.media;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

public final class MediaHttpRoutes {
    private static final int MAX_JSON=32*1024,MAX_PART=5*1024*1024;
    private final MediaUploadService service;private final MediaAuthenticator auth;private final ObjectMapper json;private final byte[] cleanupToken,roomToken;
    public MediaHttpRoutes(MediaUploadService service,MediaAuthenticator auth,ObjectMapper json,String cleanupToken,String roomToken){this.service=Objects.requireNonNull(service);this.auth=Objects.requireNonNull(auth);this.json=Objects.requireNonNull(json);if(cleanupToken==null||cleanupToken.length()<32)throw new IllegalArgumentException("cleanup token must be at least 32 characters");if(roomToken==null||roomToken.length()<32)throw new IllegalArgumentException("room token must be at least 32 characters");this.cleanupToken=cleanupToken.getBytes(StandardCharsets.UTF_8);this.roomToken=roomToken.getBytes(StandardCharsets.UTF_8);}
    public void mount(HttpServer server){server.createContext("/health/media",e->reply(e,200,Map.of("status","UP","persistence","jdbc","objectStorage","s3","apiVersion","1")));server.createContext("/v1/media/uploads",this::uploads);server.createContext("/v1/media/assets",this::assets);server.createContext("/internal/media/cleanup",this::cleanup);server.createContext("/internal/media/voice/authorize",this::authorizeVoice);}
    private void authorizeVoice(HttpExchange ex)throws IOException{try{requireMethod(ex,"POST");requireBearer(ex,roomToken);byte[] body=read(ex,MAX_JSON);@SuppressWarnings("unchecked") Map<String,Object> f=json.readValue(body,Map.class);@SuppressWarnings("unchecked") List<Object> raw=f.get("memberIds") instanceof List<?> l?(List<Object>)l:throwInvalid("memberIds required");List<Long> members=raw.stream().map(v->{if(!(v instanceof Number n))throw new IllegalArgumentException("memberIds must be numeric");return n.longValue();}).toList();var a=service.authorizeVoice(number(f,"senderId"),number(f,"assetId"),members);reply(ex,200,Map.of("code","OK","data",Map.of("assetId",a.id(),"durationMillis",a.durationMillis(),"mimeType",a.mime(),"state","READY")));}catch(Exception e){error(ex,e);}}
    private void uploads(HttpExchange ex)throws IOException{try{requireVersion(ex);String path=ex.getRequestURI().getPath();String tail=path.substring("/v1/media/uploads".length());if(tail.isEmpty()||tail.equals("/")){requireMethod(ex,"POST");byte[] body=read(ex,MAX_JSON);long owner=auth.authenticate(ex,body);@SuppressWarnings("unchecked") Map<String,Object> f=json.readValue(body,Map.class);var result=service.initiate(owner,MediaPolicy.Kind.valueOf(text(f,"kind").toUpperCase(Locale.ROOT)),text(f,"mimeType"),number(f,"byteSize"),numberOr(f,"durationMillis",0),text(f,"sha256"));reply(ex,result.deduplicated()?200:201,Map.of("code","OK","data",result));return;}String[] p=tail.substring(1).split("/");if(p.length==2&&p[1].equals("complete")){requireMethod(ex,"POST");byte[] body=read(ex,0);long owner=auth.authenticate(ex,body);reply(ex,200,Map.of("code","OK","data",service.complete(owner,p[0])));return;}if(p.length==3&&p[1].equals("parts")){requireMethod(ex,"PUT");byte[] body=read(ex,MAX_PART);long owner=auth.authenticate(ex,body);service.upload(owner,p[0],Integer.parseInt(p[2]),body);reply(ex,200,Map.of("code","OK","data",Map.of("partNumber",Integer.parseInt(p[2]))));return;}throw new Api(404,"NOT_FOUND","media route not found");}catch(Exception e){error(ex,e);}}
    private void assets(HttpExchange ex)throws IOException{try{requireVersion(ex);requireMethod(ex,"GET");byte[] body=new byte[0];long owner=auth.authenticate(ex,body);String tail=ex.getRequestURI().getPath().substring("/v1/media/assets".length());String[] p=tail.startsWith("/")?tail.substring(1).split("/"):new String[0];if(p.length<1||p.length>2)throw new Api(404,"NOT_FOUND","media route not found");var asset=service.authorizeRead(owner,Long.parseLong(p[0]));if(p.length==1){reply(ex,200,Map.of("code","OK","data",Map.of("assetId",asset.id(),"durationMillis",asset.durationMillis(),"mimeType",asset.mime(),"state","READY")));return;}if(!p[1].equals("content"))throw new Api(404,"NOT_FOUND","media route not found");ex.getResponseHeaders().set("Content-Type",asset.mime());ex.getResponseHeaders().set("Content-Length",String.valueOf(asset.size()));ex.getResponseHeaders().set("Cache-Control","private, no-store");ex.sendResponseHeaders(200,asset.size());try(var in=service.open(asset);var out=ex.getResponseBody()){in.transferTo(out);}}catch(Exception e){error(ex,e);}}
    private void cleanup(HttpExchange ex)throws IOException{try{requireMethod(ex,"POST");String h=ex.getRequestHeaders().getFirst("Authorization");byte[] got=h!=null&&h.startsWith("Bearer ")?h.substring(7).getBytes(StandardCharsets.UTF_8):new byte[0];if(!MessageDigest.isEqual(cleanupToken,got))throw new SecurityException("invalid cleanup credential");reply(ex,200,Map.of("code","OK","data",Map.of("cleaned",service.cleanupExpired(500))));}catch(Exception e){error(ex,e);}}
    private static void requireBearer(HttpExchange ex,byte[] expected){String h=ex.getRequestHeaders().getFirst("Authorization");byte[] got=h!=null&&h.startsWith("Bearer ")?h.substring(7).getBytes(StandardCharsets.UTF_8):new byte[0];if(!MessageDigest.isEqual(expected,got))throw new SecurityException("invalid room media credential");}
    private void error(HttpExchange ex,Exception e)throws IOException{if(ex.getResponseCode()!=-1)return;int status;String code;if(e instanceof Api a){status=a.status;code=a.code;}else if(e instanceof SecurityException){status=401;code="UNAUTHORIZED";}else if(e instanceof IllegalArgumentException){status=400;code="INVALID_REQUEST";}else if(e instanceof IllegalStateException){status=409;code="UPLOAD_STATE_CONFLICT";}else{status=503;code="MEDIA_UNAVAILABLE";}reply(ex,status,Map.of("code",code,"message",String.valueOf(e.getMessage())));}
    private static byte[] read(HttpExchange ex,int max)throws IOException{long declared=numberHeader(ex,"Content-Length",-1);if(declared>max)throw new Api(413,"PAYLOAD_TOO_LARGE","request body too large");try(var in=ex.getRequestBody();var out=new ByteArrayOutputStream()){byte[] b=new byte[8192];for(int n;(n=in.read(b))>=0;){if(out.size()+n>max)throw new Api(413,"PAYLOAD_TOO_LARGE","request body too large");out.write(b,0,n);}return out.toByteArray();}}
    private static long numberHeader(HttpExchange e,String k,long d){String v=e.getRequestHeaders().getFirst(k);return v==null?d:Long.parseLong(v);}private static void requireMethod(HttpExchange e,String method){if(!method.equals(e.getRequestMethod()))throw new Api(405,"METHOD_NOT_ALLOWED",method+" required");}private static void requireVersion(HttpExchange e){if(!"1".equals(e.getRequestHeaders().getFirst("X-API-Version")))throw new Api(426,"API_VERSION_REQUIRED","X-API-Version: 1 required");}
    private static String text(Map<String,Object> f,String k){Object v=f.get(k);if(!(v instanceof String s)||s.isBlank())throw new IllegalArgumentException(k+" required");return s;}private static long number(Map<String,Object> f,String k){Object v=f.get(k);if(v instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+" required");}private static long numberOr(Map<String,Object> f,String k,long d){return f.containsKey(k)?number(f,k):d;}
    private static <T> T throwInvalid(String message){throw new IllegalArgumentException(message);}
    private void reply(HttpExchange ex,int status,Object value)throws IOException{byte[] b=json.writeValueAsBytes(value);ex.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");ex.getResponseHeaders().set("Cache-Control","no-store");ex.sendResponseHeaders(status,b.length);try(var out=ex.getResponseBody()){out.write(b);}}
    private static final class Api extends RuntimeException{final int status;final String code;Api(int status,String code,String message){super(message);this.status=status;this.code=code;}}
}
