package com.aoo.bcg.media;

import java.io.*;
import java.net.*;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

/** S3-compatible multipart adapter using short-lived server-side credentials only. */
public final class S3ObjectStorage implements ObjectStorage {
    private static final String EMPTY=sha256(new byte[0]);
    private final HttpClient client;private final URI endpoint;private final String bucket,region,accessKey,secretKey;private final Clock clock;
    public S3ObjectStorage(URI endpoint,String bucket,String region,String accessKey,String secretKey){this(endpoint,bucket,region,accessKey,secretKey,HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build(),Clock.systemUTC());}
    S3ObjectStorage(URI endpoint,String bucket,String region,String accessKey,String secretKey,HttpClient client,Clock clock){this.endpoint=require(endpoint);this.bucket=text(bucket);this.region=text(region);this.accessKey=text(accessKey);this.secretKey=text(secretKey);this.client=Objects.requireNonNull(client);this.clock=Objects.requireNonNull(clock);}
    @Override public String begin(String key,String contentType){var response=send("POST",key,Map.of("uploads",""),new byte[0],contentType);String xml=utf8(response.body());int a=xml.indexOf("<UploadId>"),b=xml.indexOf("</UploadId>");if(a<0||b<a)throw new IllegalStateException("S3 multipart response has no upload id");return unescape(xml.substring(a+10,b));}
    @Override public String uploadPart(String key,String uploadId,int partNumber,byte[] content){if(partNumber<1||partNumber>10_000)throw new IllegalArgumentException("invalid part number");var response=send("PUT",key,Map.of("partNumber",String.valueOf(partNumber),"uploadId",uploadId),Objects.requireNonNull(content),"application/octet-stream");String etag=response.headers().firstValue("etag").orElseThrow(()->new IllegalStateException("S3 part ETag missing"));return etag.replace("\"","");}
    @Override public void complete(String key,String uploadId,List<UploadedPart> parts){if(parts==null||parts.isEmpty())throw new IllegalArgumentException("parts required");StringBuilder xml=new StringBuilder("<CompleteMultipartUpload>");for(var p:parts)xml.append("<Part><PartNumber>").append(p.number()).append("</PartNumber><ETag>&quot;").append(p.etag()).append("&quot;</ETag></Part>");xml.append("</CompleteMultipartUpload>");send("POST",key,Map.of("uploadId",uploadId),xml.toString().getBytes(StandardCharsets.UTF_8),"application/xml");}
    @Override public void abort(String key,String uploadId){send("DELETE",key,Map.of("uploadId",uploadId),new byte[0],null);}
    @Override public InputStream open(String key){return new ByteArrayInputStream(send("GET",key,Map.of(),new byte[0],null).body());}
    @Override public void delete(String key){send("DELETE",key,Map.of(),new byte[0],null);}
    private HttpResponse<byte[]> send(String method,String key,Map<String,String> query,byte[] body,String contentType){try{Instant now=clock.instant();String date=DateTimeFormatter.ofPattern("yyyyMMdd").withZone(ZoneOffset.UTC).format(now),stamp=DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss'Z'").withZone(ZoneOffset.UTC).format(now),payload=sha256(body);String path="/"+encode(bucket)+"/"+Arrays.stream(text(key).split("/",-1)).map(S3ObjectStorage::encode).reduce((a,b)->a+"/"+b).orElseThrow();String canonicalQuery=query.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->encode(e.getKey())+"="+encode(e.getValue())).reduce((a,b)->a+"&"+b).orElse("");String host=endpoint.getHost()+(endpoint.getPort()>0?":"+endpoint.getPort():"");String headers="host:"+host+"\nx-amz-content-sha256:"+payload+"\nx-amz-date:"+stamp+"\n";String request=method+"\n"+path+"\n"+canonicalQuery+"\n"+headers+"\nhost;x-amz-content-sha256;x-amz-date\n"+payload;String scope=date+"/"+region+"/s3/aws4_request";String toSign="AWS4-HMAC-SHA256\n"+stamp+"\n"+scope+"\n"+sha256(request.getBytes(StandardCharsets.UTF_8));byte[] signing=hmac(hmac(hmac(hmac(("AWS4"+secretKey).getBytes(StandardCharsets.UTF_8),date),region),"s3"),"aws4_request");String signature=HexFormat.of().formatHex(hmac(signing,toSign));URI uri=endpoint.resolve(path+(canonicalQuery.isEmpty()?"":"?"+canonicalQuery));var builder=HttpRequest.newBuilder(uri).timeout(Duration.ofMinutes(2)).header("x-amz-date",stamp).header("x-amz-content-sha256",payload).header("Authorization","AWS4-HMAC-SHA256 Credential="+accessKey+"/"+scope+", SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature="+signature).method(method,HttpRequest.BodyPublishers.ofByteArray(body));if(contentType!=null)builder.header("Content-Type",contentType);var response=client.send(builder.build(),HttpResponse.BodyHandlers.ofByteArray());if(response.statusCode()<200||response.statusCode()>=300){String detail=utf8(response.body());throw new IllegalStateException("S3 "+method+" failed: HTTP "+response.statusCode()+" "+detail.substring(0,Math.min(512,detail.length())));}return response;}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("S3 request interrupted",e);}catch(IOException e){throw new IllegalStateException("S3 request failed",e);}}
    private static byte[] hmac(byte[] key,String value){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(key,"HmacSHA256"));return mac.doFinal(value.getBytes(StandardCharsets.UTF_8));}catch(GeneralSecurityException e){throw new IllegalStateException(e);}}
    private static String sha256(byte[] value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
    private static String encode(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8).replace("+","%20").replace("%7E","~");}
    private static String unescape(String s){return s.replace("&amp;","&").replace("&lt;","<").replace("&gt;",">");}private static String utf8(byte[] b){return new String(b,StandardCharsets.UTF_8);}private static String text(String s){if(s==null||s.isBlank())throw new IllegalArgumentException("S3 configuration value required");return s;}private static URI require(URI uri){Objects.requireNonNull(uri);if(!Set.of("http","https").contains(uri.getScheme())||uri.getHost()==null||!(uri.getPath().isEmpty()||uri.getPath().equals("/")))throw new IllegalArgumentException("S3 endpoint must be an HTTP origin");return uri;}
}
