package com.aoo.bcg.poker.cd299;

import com.aoo.bcg.gamespi.*;
import com.aoo.bcg.gamespi.time.OperationDeadline;
import com.aoo.bcg.gamespi.time.OperationDeadlineArbiter;
import java.util.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Server-owned真人状态机；不包含机器人、聊天、定位或支付逻辑。 */
public final class Cd299Session implements AuthoritativeGameSession {
    private static final Logger LOG=LoggerFactory.getLogger(Cd299Session.class);
    private static final List<Integer> CD299_DECK=List.of(202,402,203,104,204,304,404,105,305,106,206,306,406,107,207,307,407,108,208,308,408,109,309,110,210,310,410,111,311,212,412,506);
    public enum Phase { WAITING, BASE_AND_MANGO, DEALING, BETTING, ADD_CARD, SPLITTING, REVEAL, ROUND_SETTLEMENT, FINISHED }
    public enum BetAction { DROP, FOLLOW, REST, RAISE, ALL_IN }
    private final long roomId, ownerId, seed; private final Cd299Rules rules;
    private final Cd299HandEvaluator evaluator=new Cd299HandEvaluator();
    private final Map<Integer,Long> players=new LinkedHashMap<>(); private final Set<Integer> ready=new LinkedHashSet<>();
    private final Map<Integer,List<Integer>> hands=new LinkedHashMap<>(); private final Map<Integer,Long> scores=new LinkedHashMap<>();
    private final Map<Integer,Integer> committed=new LinkedHashMap<>(); private final Set<Integer> dropped=new LinkedHashSet<>(), split=new LinkedHashSet<>(),threeFlowerSeats=new LinkedHashSet<>();
    private final Map<Integer,Integer> bases=new LinkedHashMap<>(),mangos=new LinkedHashMap<>(),bets=new LinkedHashMap<>();
    private final Set<String> operations=new LinkedHashSet<>(); private final Set<Integer> phaseActedSeats=new LinkedHashSet<>(); private final List<Object> events=new ArrayList<>(),replayEvents=new ArrayList<>();
    private final OperationDeadlineArbiter arbiter=new OperationDeadlineArbiter(); private Phase phase=Phase.WAITING;
    private final List<Integer> deck=new ArrayList<>(); private int deckCursor;
    private int round,currentSeat=-1; private long stateVersion; private Map<Long,Long> lastDelta=Map.of();
    public Cd299Session(long roomId,long ownerId,long seed,Cd299Rules rules){this.roomId=roomId;this.ownerId=ownerId;this.seed=seed;this.rules=Objects.requireNonNull(rules);}
    /** Atomically changes one authenticated spectator into a seated, auto-ready player. */
    public synchronized void sit(int seat,long playerId,String op){
        mutating(op);
        if(seat<0||seat>=rules.maxPlayers())throw sitRejected("CD299_INVALID_SEAT",seat,playerId,op,true);
        if(players.containsValue(playerId))throw sitRejected("CD299_ALREADY_SEATED",seat,playerId,op,false);
        if(players.containsKey(seat))throw sitRejected("CD299_SEAT_OCCUPIED",seat,playerId,op,false);
        if(phase!=Phase.WAITING||round!=0||players.size()>=rules.maxPlayers())throw sitRejected("CD299_SIT_UNAVAILABLE",seat,playerId,op,false);
        players.put(seat,playerId);scores.put(seat,0L);ready.add(seat);changed(op,"sit",seat);
        LOG.info("[CD299] sit accepted roomId={} playerId={} seatId={} operationId={} stateVersion={}",roomId,playerId,seat,op,stateVersion);
        if(players.size()>=rules.startPlayers())startRound();
    }
    private RuntimeException sitRejected(String code,int seat,long playerId,String op,boolean invalid){LOG.warn("[CD299] sit rejected code={} roomId={} playerId={} seatId={} operationId={} stateVersion={}",code,roomId,playerId,seat,op,stateVersion);String message="[CD299] "+code+" roomId="+roomId+" playerId="+playerId+" seatId="+seat;return invalid?new IllegalArgumentException(message):new IllegalStateException(message);}
    /** Single legacy-read bridge. New clients must send sit_req instead of ready_req. */
    private void legacyReady(int seat,long playerId,String op){sit(seat,playerId,op);}
    public synchronized void preset(int seat,int base,int mango,String op){mutating(op);requireTurn(seat,Phase.BASE_AND_MANGO);if(base<1||mango<0)throw new IllegalArgumentException("invalid base/mango");bases.put(seat,base);mangos.put(seat,mango);committed.put(seat,base+mango);changed(op,"preset",seat);advanceOr(seat,Phase.DEALING);if(phase==Phase.DEALING){events.add(Map.of("type","deal","stateVersion",stateVersion));phase=Phase.BETTING;phaseActedSeats.clear();currentSeat=activeSeats().get(0);stateVersion++;}}
    public synchronized void bet(int seat,BetAction action,int amount,String op){mutating(op);requireTurn(seat,Phase.BETTING);if(action==BetAction.RAISE||action==BetAction.ALL_IN){if(amount<rules.openingBet())throw new IllegalArgumentException("invalid raise");}else if(amount<0)throw new IllegalArgumentException("invalid bet");if(action==BetAction.DROP)dropped.add(seat);else{int value=Math.max(amount,rules.mangoScore());bets.merge(seat,value,Integer::sum);committed.merge(seat,value,Integer::sum);}changed(op,"bet:"+action,seat);if(activeSeats().size()<=1){phase=Phase.REVEAL;settle();return;}advanceOr(seat,Phase.ADD_CARD);}
    public synchronized void addCard(int seat,String op){mutating(op);requireTurn(seat,Phase.ADD_CARD);List<Integer> hand=new ArrayList<>(hands.get(seat));hand.add(drawCard());hands.put(seat,List.copyOf(hand));if(hand.size()==3&&evaluator.isThreeFlower(hand))threeFlowerSeats.add(seat);changed(op,"addCard",seat);if(activeSeats().size()<=1){phase=Phase.REVEAL;settle();return;}advanceOr(seat,hand.size()>=4?Phase.SPLITTING:Phase.BETTING);}
    public synchronized void split(int seat,List<Integer> ordered,String op){mutating(op);requireSeat(seat);if(phase!=Phase.SPLITTING||dropped.contains(seat)||!sameCards(hands.get(seat),ordered))throw new IllegalArgumentException("invalid CD299 split");hands.put(seat,List.copyOf(ordered));split.add(seat);changed(op,"split",seat);if(split.containsAll(activeSeats())){phase=Phase.REVEAL;settle();}}
    public synchronized void timeout(int seat,String op){switch(phase){case BASE_AND_MANGO->preset(seat,1,rules.mangoScore(),op);case BETTING->bet(seat,BetAction.DROP,0,op);case ADD_CARD->addCard(seat,op);case SPLITTING->split(seat,hands.get(seat),op);default->throw new IllegalStateException("no CD299 timeout action");}}
    private void startRound(){round++;hands.clear();committed.clear();bases.clear();mangos.clear();bets.clear();dropped.clear();split.clear();threeFlowerSeats.clear();phaseActedSeats.clear();deck.clear();deck.addAll(CD299_DECK);Collections.shuffle(deck,new Random(seed+round));deckCursor=0;for(int seat:players.keySet())hands.put(seat,List.of(drawCard(),drawCard()));currentSeat=players.keySet().stream().min(Integer::compareTo).orElseThrow();phase=Phase.BASE_AND_MANGO;stateVersion++;}
    private void settle(){List<Cd299SettlementEngine.Player>input=new ArrayList<>();for(var e:players.entrySet()){int seat=e.getKey();boolean drop=dropped.contains(seat),flower=threeFlowerSeats.contains(seat)||evaluator.isThreeFlower(hands.get(seat));Cd299HandEvaluator.SplitRank rank=drop||flower||hands.get(seat).size()!=4?null:evaluator.split(hands.get(seat),rules.earthNineKing());input.add(new Cd299SettlementEngine.Player(seat,e.getValue(),bases.getOrDefault(seat,1),mangos.getOrDefault(seat,rules.mangoScore()),bets.getOrDefault(seat,0),drop,flower,rank));}Map<Long,Long>d=new Cd299SettlementEngine().settle(input,rules.headBigKeepsBase()).scoreDelta();d.forEach((p,v)->{int seat=players.entrySet().stream().filter(e->e.getValue().equals(p)).findFirst().orElseThrow().getKey();scores.put(seat,scores.get(seat)+v);});lastDelta=Map.copyOf(d);phase=round>=rules.rounds()?Phase.FINISHED:Phase.ROUND_SETTLEMENT;stateVersion++;}
    private int drawCard(){if(deckCursor>=deck.size())throw new IllegalStateException("CD299 deck exhausted");return deck.get(deckCursor++);}
    /**
     * Advances within one operation phase without inferring wraparound from the
     * current active-seat list. DROP and three-flower can remove the acting seat,
     * so comparing the next seat with the first active seat would end the phase early.
     */
    private void advanceOr(int actedSeat,Phase next){
        phaseActedSeats.add(actedSeat);
        List<Integer> active=activeSeats();
        List<Integer> remaining=active.stream().filter(s->!phaseActedSeats.contains(s)).toList();
        if(remaining.isEmpty()){
            phase=next;
            phaseActedSeats.clear();
            currentSeat=active.isEmpty()?-1:active.get(0);
            return;
        }
        currentSeat=remaining.stream().filter(s->s>actedSeat).findFirst().orElse(remaining.get(0));
    }
    private List<Integer>activeSeats(){return players.keySet().stream().filter(s->!dropped.contains(s)&&!threeFlowerSeats.contains(s)).sorted().toList();}
    private void requireTurn(int seat,Phase expected){requireSeat(seat);if(phase!=expected||currentSeat!=seat)throw new IllegalStateException("not CD299 turn");}
    private void requireSeat(int seat){if(!players.containsKey(seat))throw new IllegalArgumentException("unknown CD299 seat");}
    private void mutating(String op){if(op==null||op.isBlank()||operations.contains(op)||phase==Phase.FINISHED)throw new IllegalStateException("invalid/duplicate CD299 operation");}
    private void changed(String op,String type,int seat){operations.add(op);events.add(Map.of("operationId",op,"type",type,"seat",seat,"stateVersion",stateVersion+1));stateVersion++;}
    private static boolean sameCards(List<Integer>a,List<Integer>b){return a!=null&&b!=null&&a.size()==b.size()&&new HashSet<>(a).equals(new HashSet<>(b));} private static long longValue(Integer v){return v==null?0:v.longValue();}
    public synchronized GameCommandResult execute(GameCommandRequest r){if(r.roomId()!=roomId||!r.playVersion().equals(Cd299Rules.VERSION))throw new IllegalArgumentException("CD299 identity mismatch");Map<String,Object>b=r.body().asMap();long playerId=Long.parseLong(r.authenticatedUserId());switch(r.msgId()){case"poker.cd299.state_req"->{return new GameCommandResult("poker.cd299.state_rsp",r.requestId(),viewFor(playerId)).withAuthorityMetadata(stateVersion,Math.max(1,stateVersion));}case"poker.cd299.sit_req"->sit(number(b,"seatId",-1),playerId,r.requestId());case"poker.cd299.ready_req"->legacyReady(number(b,"seatId",r.seatId()),playerId,r.requestId());case"poker.cd299.continue_req"->{requireSeat(r.seatId());if(phase!=Phase.ROUND_SETTLEMENT)throw new IllegalStateException("[CD299] continue rejected");startRound();}case"poker.cd299.preset_req"->preset(r.seatId(),number(b,"base",1),number(b,"mango",rules.mangoScore()),r.requestId());case"poker.cd299.bet_req"->bet(r.seatId(),BetAction.valueOf(String.valueOf(b.get("action"))),number(b,"amount",0),r.requestId());case"poker.cd299.add_card_req"->addCard(r.seatId(),r.requestId());case"poker.cd299.split_req"->split(r.seatId(),intList(b.get("cards")),r.requestId());case"poker.cd299.timeout_req"->timeout(r.seatId(),r.requestId());default->throw new IllegalArgumentException("unsupported CD299 command");}replayEvents.add(Map.of("version",stateVersion,"after",authoritativeState()));return new GameCommandResult(r.msgId().replace("_req","_rsp"),r.requestId(),viewFor(playerId)).withAuthorityMetadata(stateVersion,stateVersion);}
    public synchronized Map<String,Object>viewFor(long viewer){Map<Integer,List<Integer>>visible=new LinkedHashMap<>();hands.forEach((s,c)->visible.put(s,players.get(s)==viewer||phase==Phase.REVEAL||phase==Phase.ROUND_SETTLEMENT||phase==Phase.FINISHED?c:Collections.nCopies(c.size(),0)));Map<String,Object>m=new LinkedHashMap<>(authoritativeState());int viewerSeat=players.entrySet().stream().filter(e->e.getValue()==viewer).map(Map.Entry::getKey).findFirst().orElse(-1);m.put("viewerRole",viewerSeat>=0?"SEATED":"SPECTATOR");m.put("viewerSeat",viewerSeat);m.put("hands",visible);return Map.copyOf(m);}
    public synchronized Map<String,Object>authoritativeState(){Map<String,Object>m=new LinkedHashMap<>();m.put("schemaVersion",1);m.put("gameCode",Cd299Rules.GAME_CODE);m.put("playVersion",Cd299Rules.VERSION);m.put("roomId",roomId);m.put("ownerId",ownerId);m.put("seed",seed);m.put("rules",rules.toMap());m.put("phase",phase.name());m.put("round",round);m.put("stateVersion",stateVersion);m.put("players",Map.copyOf(players));m.put("readySeats",List.copyOf(ready));m.put("hands",Map.copyOf(hands));m.put("committed",Map.copyOf(committed));m.put("droppedSeats",List.copyOf(dropped));m.put("threeFlowerSeats",List.copyOf(threeFlowerSeats));m.put("splitSeats",List.copyOf(split));m.put("scores",Map.copyOf(scores));m.put("bases",Map.copyOf(bases));m.put("mangos",Map.copyOf(mangos));m.put("bets",Map.copyOf(bets));m.put("operations",List.copyOf(operations));m.put("phaseActedSeats",List.copyOf(phaseActedSeats));m.put("deck",List.copyOf(deck));m.put("deckCursor",deckCursor);m.put("currentSeat",currentSeat);m.put("lastDelta",Map.copyOf(lastDelta));return Map.copyOf(m);}
    public long stateVersion(){return stateVersion;}public OperationDeadline operationDeadline(){return OperationDeadline.none();}public OperationDeadlineArbiter deadlineArbiter(){return arbiter;}public List<String>invariantViolations(){List<String>v=new ArrayList<>();if(players.size()>rules.maxPlayers())v.add("too many players");if(scores.size()!=players.size())v.add("score/player mismatch");if(!ready.equals(players.keySet()))v.add("seated/ready mismatch");if(deckCursor<0||deckCursor>deck.size())v.add("invalid deck cursor");return List.copyOf(v);}public SettlementPayload settlement(int roundNo,String version){if(roundNo!=round||!version.equals(Cd299Rules.VERSION)||lastDelta.isEmpty())throw new IllegalStateException("CD299 settlement unavailable");return new SettlementPayload(roomId,roundNo,version,lastDelta);}public List<Object>recordedEvents(){return List.copyOf(replayEvents);}
    public static Cd299Session restore(Map<String,Object>s){if(!Cd299Rules.GAME_CODE.equals(String.valueOf(s.get("gameCode")))||!Cd299Rules.VERSION.equals(String.valueOf(s.get("playVersion"))))throw new IllegalArgumentException("[CD299] restore identity mismatch");Cd299Session x=new Cd299Session(lng(s.get("roomId")),lng(s.get("ownerId")),lng(s.get("seed")),Cd299Rules.from(map(s.get("rules"))));x.players.clear();copyLongMap(s.get("players"),x.players);x.scores.clear();copyLongMap(s.get("scores"),x.scores);copyIntMap(s.get("committed"),x.committed);copyIntMap(s.get("bases"),x.bases);copyIntMap(s.get("mangos"),x.mangos);copyIntMap(s.get("bets"),x.bets);copyHands(s.get("hands"),x.hands);x.ready.addAll(intList(s.get("readySeats")));x.dropped.addAll(intList(s.get("droppedSeats")));x.threeFlowerSeats.addAll(intList(s.get("threeFlowerSeats")));x.split.addAll(intList(s.get("splitSeats")));x.phaseActedSeats.addAll(intList(s.get("phaseActedSeats")));for(Object o:list(s.get("operations")))x.operations.add(String.valueOf(o));x.deck.addAll(intList(s.get("deck")));x.deckCursor=number(s,"deckCursor",0);x.currentSeat=number(s,"currentSeat",-1);x.round=number(s,"round",0);x.stateVersion=lng(s.get("stateVersion"));x.phase=Phase.valueOf(String.valueOf(s.get("phase")));copyPlayerDelta(s.get("lastDelta"),x.lastDelta=new LinkedHashMap<>());return x;}
    public static StatePayload replay(StatePayload base,List<Object>ordered){Map<String,Object>state=new LinkedHashMap<>(base.asMap());long version=lng(state.get("stateVersion"));for(Object raw:ordered){Map<String,Object>event=map(raw);long next=lng(event.get("version"));if(next<=version)throw new IllegalArgumentException("[CD299] replay version must increase");state=new LinkedHashMap<>(map(event.get("after")));if(lng(state.get("stateVersion"))!=next)throw new IllegalArgumentException("[CD299] replay event/state mismatch");version=next;}return StatePayload.copyOf(state);}
    private static int number(Map<String,Object>m,String k,int d){Object v=m.get(k);return v instanceof Number n?n.intValue():d;}private static long lng(Object v){return v instanceof Number n?n.longValue():Long.parseLong(String.valueOf(v));}private static List<?>list(Object v){return v instanceof Collection<?>c?List.copyOf(c):List.of();}private static List<Integer>intList(Object v){return list(v).stream().map(x->((Number)x).intValue()).toList();}@SuppressWarnings("unchecked")private static Map<String,Object>map(Object v){Map<String,Object>m=new LinkedHashMap<>();if(v instanceof Map<?,?>raw)raw.forEach((k,n)->m.put(String.valueOf(k),n));return m;}private static void copyLongMap(Object raw,Map<Integer,Long>out){map(raw).forEach((k,v)->out.put(Integer.parseInt(k),lng(v)));}private static void copyIntMap(Object raw,Map<Integer,Integer>out){map(raw).forEach((k,v)->out.put(Integer.parseInt(k),((Number)v).intValue()));}private static void copyHands(Object raw,Map<Integer,List<Integer>>out){map(raw).forEach((k,v)->out.put(Integer.parseInt(k),List.copyOf(intList(v))));}private static void copyPlayerDelta(Object raw,Map<Long,Long>out){map(raw).forEach((k,v)->out.put(Long.parseLong(k),lng(v)));}
}
