package com.aoo.bcg.privacy;

import com.fasterxml.jackson.databind.ObjectMapper;
import javax.sql.DataSource;
import java.sql.*;import java.time.*;import java.util.*;

/** Durable privacy workflow. Export projection is deliberately allow-listed and never reads gameplay/hand tables. */
public final class JdbcPrivacyService {
 private final DataSource db;private final Clock clock;private final ObjectMapper json;
 public JdbcPrivacyService(DataSource db,Clock clock,ObjectMapper json){this.db=Objects.requireNonNull(db);this.clock=Objects.requireNonNull(clock);this.json=Objects.requireNonNull(json);}
 public Request requestExport(long account){return create(account,"EXPORT",null);}
 public Request requestDeletion(long account){return create(account,"DELETE",clock.instant().plus(Duration.ofDays(7)));}
 public List<Request> list(long account){try(Connection c=db.getConnection();PreparedStatement p=c.prepareStatement("SELECT request_id,request_type,status,requested_at,cooling_off_until,cancelled_at,completed_at,result_manifest,version FROM aoo_data_rights_request WHERE account_id=? ORDER BY requested_at DESC")){p.setLong(1,account);try(ResultSet r=p.executeQuery()){List<Request> out=new ArrayList<>();while(r.next())out.add(read(r));return List.copyOf(out);}}catch(SQLException e){throw failure(e);}}
 public Request cancel(long account,String id,long expectedVersion){return tx(c->{Request r=lock(c,account,id);if(r.version()!=expectedVersion)throw new Conflict("request version conflict");if(!Set.of("PENDING","COOLING_OFF","ON_HOLD").contains(r.status()))throw new Conflict("request can no longer be cancelled");update(c,id,"CANCELLED",null,"cancelled_at",expectedVersion);audit(c,id,account,"REQUEST_CANCELLED","PLAYER",String.valueOf(account),Map.of("expectedVersion",expectedVersion));return lock(c,account,id);});}
 public int processDue(){try(Connection c=db.getConnection();PreparedStatement p=c.prepareStatement("SELECT request_id,account_id FROM aoo_data_rights_request WHERE status IN ('PENDING','COOLING_OFF','ON_HOLD') AND (cooling_off_until IS NULL OR cooling_off_until<=?) ORDER BY requested_at LIMIT 100")){p.setTimestamp(1,Timestamp.from(clock.instant()));List<Map.Entry<String,Long>> jobs=new ArrayList<>();try(ResultSet r=p.executeQuery()){while(r.next())jobs.add(Map.entry(r.getString(1),r.getLong(2)));}int done=0;for(var j:jobs){process(j.getValue(),j.getKey());done++;}return done;}catch(SQLException e){throw failure(e);}}
 public String placeHold(long account,String authority,String reason,String actor){return tx(c->{ensureAccount(c,account);String id=UUID.randomUUID().toString();try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_account_legal_hold(hold_id,account_id,authority_reference,reason,placed_by,placed_at) VALUES(?,?,?,?,?,?)")){p.setString(1,id);p.setLong(2,account);p.setString(3,required(authority));p.setString(4,required(reason));p.setString(5,required(actor));p.setTimestamp(6,Timestamp.from(clock.instant()));p.executeUpdate();}audit(c,null,account,"LEGAL_HOLD_PLACED","OPERATOR",actor,Map.of("holdId",id,"authority",authority));return id;});}
 public void releaseHold(String hold,String actor){tx(c->{long account;try(PreparedStatement q=c.prepareStatement("SELECT account_id FROM aoo_account_legal_hold WHERE hold_id=? AND released_at IS NULL FOR UPDATE")){q.setString(1,hold);try(ResultSet r=q.executeQuery()){if(!r.next())throw new NotFound("active hold not found");account=r.getLong(1);}}try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_legal_hold SET released_by=?,released_at=? WHERE hold_id=?")){p.setString(1,required(actor));p.setTimestamp(2,Timestamp.from(clock.instant()));p.setString(3,hold);p.executeUpdate();}audit(c,null,account,"LEGAL_HOLD_RELEASED","OPERATOR",actor,Map.of("holdId",hold));return null;});}
 private Request create(long account,String type,Instant cooling){return tx(c->{ensureAccount(c,account);try(PreparedStatement q=c.prepareStatement("SELECT request_id FROM aoo_data_rights_request WHERE account_id=? AND request_type=? AND status IN ('PENDING','COOLING_OFF','ON_HOLD','RUNNING')")){q.setLong(1,account);q.setString(2,type);try(ResultSet r=q.executeQuery()){if(r.next())throw new Conflict("active request already exists");}}String id=UUID.randomUUID().toString(),status=cooling==null?"PENDING":"COOLING_OFF";try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_data_rights_request(request_id,account_id,request_type,status,requested_at,cooling_off_until) VALUES(?,?,?,?,?,?)")){p.setString(1,id);p.setLong(2,account);p.setString(3,type);p.setString(4,status);p.setTimestamp(5,Timestamp.from(clock.instant()));p.setTimestamp(6,cooling==null?null:Timestamp.from(cooling));p.executeUpdate();}audit(c,id,account,"REQUEST_CREATED","PLAYER",String.valueOf(account),Map.of("type",type));return lock(c,account,id);});}
 private void process(long account,String id){tx(c->{Request r=lock(c,account,id);if(hasHold(c,account)){update(c,id,"ON_HOLD",null,null);audit(c,id,account,"REQUEST_HELD","SYSTEM","orchestrator",Map.of());return null;}update(c,id,"RUNNING",null,null);if("EXPORT".equals(r.type())){Map<String,Object> manifest=export(c,account);update(c,id,"COMPLETED",json.writeValueAsString(manifest),"completed_at");}else{anonymize(c,account);Map<String,Object> manifest=Map.of("accountIdToken","anon-"+sha(String.valueOf(account)).substring(0,20),"onlineData","ANONYMIZED","sessions","REVOKED","backupPurgeDueAt",clock.instant().plus(Duration.ofDays(30)).toString());update(c,id,"COMPLETED",json.writeValueAsString(manifest),"completed_at");}audit(c,id,account,"REQUEST_COMPLETED","SYSTEM","orchestrator",Map.of("type",r.type()));return null;});}
 private Map<String,Object> export(Connection c,long a)throws Exception{Map<String,Object> account=new LinkedHashMap<>();try(PreparedStatement p=c.prepareStatement("SELECT account_id,login_name,guest,banned_until,created_at,updated_at FROM aoo_account WHERE account_id=?")){p.setLong(1,a);try(ResultSet r=p.executeQuery()){if(r.next()){account.put("accountId",r.getLong(1));account.put("loginName",r.getString(2));account.put("guest",r.getBoolean(3));account.put("bannedUntil",instant(r,4));account.put("createdAt",instant(r,5));account.put("updatedAt",instant(r,6));}}}List<Map<String,Object>> devices=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT channel_name,client_version,first_seen_at,last_seen_at,revoked_at FROM aoo_account_device WHERE account_id=?")){p.setLong(1,a);try(ResultSet r=p.executeQuery()){while(r.next())devices.add(Map.of("channel",r.getString(1),"clientVersion",r.getString(2),"firstSeenAt",instant(r,3),"lastSeenAt",instant(r,4),"revoked",r.getTimestamp(5)!=null));}}List<Map<String,Object>> audits=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT action_name,occurred_at FROM aoo_account_audit WHERE account_id=? ORDER BY occurred_at")){p.setLong(1,a);try(ResultSet r=p.executeQuery()){while(r.next())audits.add(Map.of("action",r.getString(1),"occurredAt",instant(r,2)));}}return Map.of("schemaVersion",1,"scope","SUBJECT_ONLY_NO_GAMEPLAY_OR_HIDDEN_CARDS","account",account,"devices",devices,"accountEvents",audits,"generatedAt",clock.instant().toString());}
 private void anonymize(Connection c,long a)throws Exception{String token="deleted-"+sha(String.valueOf(a)).substring(0,20);try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account SET login_name=NULL,password_hash=NULL,guest_credential_hash=NULL,recovery_credential_hash=NULL,guest=TRUE,auth_generation=auth_generation+1,banned_until=NULL,ban_reason=NULL,updated_at=? WHERE account_id=?")){p.setTimestamp(1,Timestamp.from(clock.instant()));p.setLong(2,a);p.executeUpdate();}List<String[]> sessions=new ArrayList<>();try(PreparedStatement q=c.prepareStatement("SELECT session_id,access_hash,refresh_hash FROM aoo_account_session WHERE account_id=? FOR UPDATE")){q.setLong(1,a);try(ResultSet r=q.executeQuery()){while(r.next())sessions.add(new String[]{r.getString(1),r.getString(2),r.getString(3)});}}try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_session SET revoked_at=COALESCE(revoked_at,?),revoke_reason='ACCOUNT_DELETED',access_hash=?,refresh_hash=?,device_id=? WHERE session_id=?")){for(String[] s:sessions){p.setTimestamp(1,Timestamp.from(clock.instant()));p.setString(2,sha(s[1]+token));p.setString(3,sha(s[2]+token));p.setString(4,token);p.setString(5,s[0]);p.addBatch();}p.executeBatch();}try(PreparedStatement p=c.prepareStatement("DELETE FROM aoo_account_device WHERE account_id=?")){p.setLong(1,a);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE aoo_account_audit SET detail_value=?,source_ip='anonymized' WHERE account_id=?")){p.setString(1,token);p.setLong(2,a);p.executeUpdate();}}
 private boolean hasHold(Connection c,long a)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT 1 FROM aoo_account_legal_hold WHERE account_id=? AND released_at IS NULL LIMIT 1")){p.setLong(1,a);try(ResultSet r=p.executeQuery()){return r.next();}}}
 private Request lock(Connection c,long a,String id)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT request_id,request_type,status,requested_at,cooling_off_until,cancelled_at,completed_at,result_manifest,version FROM aoo_data_rights_request WHERE request_id=? AND account_id=? FOR UPDATE")){p.setString(1,id);p.setLong(2,a);try(ResultSet r=p.executeQuery()){if(!r.next())throw new NotFound("request not found");return read(r);}}}
 private Request read(ResultSet r)throws SQLException{return new Request(r.getString(1),r.getString(2),r.getString(3),instant(r,4),instant(r,5),instant(r,6),instant(r,7),r.getString(8),r.getLong(9));}
 private void update(Connection c,String id,String status,String manifest,String timestamp){update(c,id,status,manifest,timestamp,null);}
 private void update(Connection c,String id,String status,String manifest,String timestamp,Long expectedVersion){String sql="UPDATE aoo_data_rights_request SET status=?,result_manifest=COALESCE(?,result_manifest),version=version+1"+(timestamp==null?"":","+timestamp+"=?")+" WHERE request_id=?"+(expectedVersion==null?"":" AND version=?");try(PreparedStatement p=c.prepareStatement(sql)){p.setString(1,status);p.setString(2,manifest);int n=3;if(timestamp!=null)p.setTimestamp(n++,Timestamp.from(clock.instant()));p.setString(n++,id);if(expectedVersion!=null)p.setLong(n,expectedVersion);if(p.executeUpdate()!=1)throw new Conflict("request version conflict");}catch(SQLException e){throw failure(e);}}
 private void audit(Connection c,String id,long a,String action,String type,String actor,Map<String,?> detail)throws Exception{try(PreparedStatement p=c.prepareStatement("INSERT INTO aoo_data_rights_audit(request_id,account_id,action_name,actor_type,actor_ref,detail_json,occurred_at) VALUES(?,?,?,?,?,?,?)")){p.setString(1,id);p.setLong(2,a);p.setString(3,action);p.setString(4,type);p.setString(5,actor);p.setString(6,json.writeValueAsString(detail));p.setTimestamp(7,Timestamp.from(clock.instant()));p.executeUpdate();}}
 private void ensureAccount(Connection c,long a)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT 1 FROM aoo_account WHERE account_id=?")){p.setLong(1,a);try(ResultSet r=p.executeQuery()){if(!r.next())throw new NotFound("account not found");}}}
 private <T>T tx(Sql<T> work){try(Connection c=db.getConnection()){boolean ac=c.getAutoCommit();c.setAutoCommit(false);try{T value=work.run(c);c.commit();return value;}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(ac);}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure(e);}}
 private static String instant(ResultSet r,int n)throws SQLException{Timestamp t=r.getTimestamp(n);return t==null?null:t.toInstant().toString();}private static String required(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("value required");return v;}private static String sha(String v){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(v.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static IllegalStateException failure(Exception e){return new IllegalStateException("privacy persistence failed",e);}
 @FunctionalInterface private interface Sql<T>{T run(Connection c)throws Exception;}
 public record Request(String id,String type,String status,String requestedAt,String coolingOffUntil,String cancelledAt,String completedAt,String resultManifest,long version){}
 public static final class Conflict extends RuntimeException{public Conflict(String m){super(m);}}public static final class NotFound extends RuntimeException{public NotFound(String m){super(m);}}
}
