package com.aoo.bcg.privacy;
import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.net.URLDecoder;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;

public final class PrivacyHttpRoutes {
 private final JdbcPrivacyService service;private final AccountIdentityPort identities;private final ObjectMapper json;private final String operator;
 public PrivacyHttpRoutes(JdbcPrivacyService s,AccountIdentityPort i,ObjectMapper j,String o){service=Objects.requireNonNull(s);identities=Objects.requireNonNull(i);json=Objects.requireNonNull(j);operator=Objects.requireNonNull(o);}
 public void mount(HttpServer server){server.createContext("/health/privacy",e->reply(e,200,Map.of("status","UP","persistence","jdbc")));server.createContext("/v1/privacy",this::handle);}
 private void handle(HttpExchange e)throws IOException{try{Map<String,String> f=form(e);String path=e.getRequestURI().getPath().substring("/v1/privacy".length());Object out;if(path.startsWith("/operator/")){checkOperator(e);out=operator(path,f);}else{long account=authenticate(e);out=player(path,e.getRequestMethod(),account,f);}reply(e,200,out);}catch(JdbcPrivacyService.NotFound x){reply(e,404,Map.of("error",x.getMessage()));}catch(JdbcPrivacyService.Conflict x){reply(e,409,Map.of("error",x.getMessage()));}catch(IllegalArgumentException x){reply(e,400,Map.of("error",x.getMessage()));}catch(SecurityException x){reply(e,401,Map.of("error",x.getMessage()));}catch(IllegalStateException x){reply(e,503,Map.of("error","privacy service unavailable"));}}
 private Object player(String p,String method,long a,Map<String,String> f){return switch(p){case "/exports"->{require(method,"POST");yield present(service.requestExport(a));}case "/deletions"->{require(method,"POST");yield present(service.requestDeletion(a));}case "/requests"->{require(method,"GET");yield service.list(a).stream().map(this::present).toList();}case "/requests/cancel"->{require(method,"POST");yield present(service.cancel(a,required(f,"requestId"),number(f,"expectedVersion")));}default->throw new JdbcPrivacyService.NotFound("route not found");};}
 private Map<String,Object> present(JdbcPrivacyService.Request r){boolean canCancel=Set.of("PENDING","COOLING_OFF","ON_HOLD").contains(r.status());Map<String,Object> out=new LinkedHashMap<>();out.put("id",r.id());out.put("type",r.type());out.put("status",r.status());out.put("requestedAt",r.requestedAt());out.put("coolingOffUntil",r.coolingOffUntil());out.put("cancelledAt",r.cancelledAt());out.put("completedAt",r.completedAt());out.put("resultManifest",r.resultManifest());out.put("version",r.version());out.put("allowedActions",canCancel?List.of("CANCEL"):List.of());return out;}
 private Object operator(String p,Map<String,String> f){return switch(p){case "/operator/process"->Map.of("processed",service.processDue());case "/operator/holds/place"->Map.of("holdId",service.placeHold(number(f,"accountId"),required(f,"authorityReference"),required(f,"reason"),required(f,"actor")));case "/operator/holds/release"->{service.releaseHold(required(f,"holdId"),required(f,"actor"));yield Map.of("status","released");}default->throw new JdbcPrivacyService.NotFound("route not found");};}
 private long authenticate(HttpExchange e){String h=e.getRequestHeaders().getFirst("Authorization");if(h==null||!h.startsWith("Bearer "))throw new SecurityException("bearer token required");String ip=e.getRemoteAddress()==null?"unknown":e.getRemoteAddress().getAddress().getHostAddress();return identities.authenticate(h.substring(7),header(e,"X-Device-Id"),header(e,"X-Client-Channel"),header(e,"X-Client-Version"),ip);}
 private void checkOperator(HttpExchange e){String got=e.getRequestHeaders().getFirst("X-Account-Operator-Token");if(got==null||!MessageDigest.isEqual(got.getBytes(StandardCharsets.UTF_8),operator.getBytes(StandardCharsets.UTF_8)))throw new SecurityException("operator authentication failed");}
 private void reply(HttpExchange e,int code,Object value)throws IOException{byte[] b=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(code,b.length);e.getResponseBody().write(b);e.close();}
 private Map<String,String> form(HttpExchange e)throws IOException{Map<String,String> out=new HashMap<>();if("GET".equals(e.getRequestMethod()))return out;String body=new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);String content=String.valueOf(e.getRequestHeaders().getFirst("Content-Type"));if(content.toLowerCase(Locale.ROOT).contains("application/json")){if(body.isBlank())return out;Map<?,?> decoded=json.readValue(body,Map.class);for(var entry:decoded.entrySet())if(entry.getKey()!=null&&entry.getValue()!=null)out.put(String.valueOf(entry.getKey()),String.valueOf(entry.getValue()));return out;}for(String pair:body.split("&")){int i=pair.indexOf('=');if(i>0)out.put(URLDecoder.decode(pair.substring(0,i),StandardCharsets.UTF_8),URLDecoder.decode(pair.substring(i+1),StandardCharsets.UTF_8));}return out;}private static String header(HttpExchange e,String n){String v=e.getRequestHeaders().getFirst(n);if(v==null||v.isBlank())throw new IllegalArgumentException(n+" required");return v;}private static String required(Map<String,String> f,String n){String v=f.get(n);if(v==null||v.isBlank())throw new IllegalArgumentException(n+" required");return v;}private static long number(Map<String,String> f,String n){return Long.parseLong(required(f,n));}private static void require(String actual,String wanted){if(!wanted.equals(actual))throw new IllegalArgumentException("method not allowed");}
}
