package com.aoo.bcg.inventory;

import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;

/** Authenticated v1 player and internal inventory routes mounted on the shared Bootstrap server. */
public final class InventoryHttpRoutes {
 private final InventoryStoreService service;private final ObjectMapper json;private final byte[] token;private final Clock clock;
 public InventoryHttpRoutes(InventoryStoreService service,ObjectMapper json,String token,Clock clock){this.service=Objects.requireNonNull(service);this.json=Objects.requireNonNull(json);this.clock=Objects.requireNonNull(clock);if(token==null||token.length()<32)throw new IllegalArgumentException("inventory token must be at least 32 characters");this.token=token.getBytes(StandardCharsets.UTF_8);}
 public void mount(HttpServer server){server.createContext("/health/inventory",e->reply(e,200,Map.of("status","UP","persistence","jdbc","billing","http-port")));server.createContext("/v1/items",this::items);server.createContext("/v1/inventory",this::inventory);server.createContext("/v1/store",this::store);server.createContext("/v1/redemptions",this::redemption);server.createContext("/internal/v1/inventory",this::internal);}
 private void items(HttpExchange e)throws IOException{handle(e,()->{must(e,"GET");return service.catalog(clock.instant());});}
 private void inventory(HttpExchange e)throws IOException{handle(e,()->{long player=player(e);if("GET".equals(e.getRequestMethod()))return service.inventory(player,clock.instant());Map<String,Object>b=body(e);return service.use(key(e),player,text(b,"itemCode"),number(b,"quantity"));});}
 private void store(HttpExchange e)throws IOException{handle(e,()->{if("GET".equals(e.getRequestMethod()))return service.offers(clock.instant());must(e,"POST");Map<String,Object>b=body(e);return service.purchase(key(e),player(e),text(b,"offerCode"));});}
 private void redemption(HttpExchange e)throws IOException{handle(e,()->{must(e,"POST");Map<String,Object>b=body(e);return service.redeem(key(e),player(e),text(b,"code"));});}
 private void internal(HttpExchange e)throws IOException{handle(e,()->{must(e,"POST");Map<String,Object>b=body(e);String action=text(b,"action");return switch(action){case "grant"->service.grant(key(e),number(b,"playerId"),text(b,"itemCode"),number(b,"quantity"),instant(b.get("expiresAt")),text(b,"source"));case "revoke"->service.revoke(key(e),text(b,"originalCommandId"),text(b,"reason"));case "expire"->Map.of("expired",service.expire(clock.instant(),(int)numberOr(b,"limit",100)));default->throw new IllegalArgumentException("unknown inventory action");};});}
 private void handle(HttpExchange e,Action a)throws IOException{try{authenticate(e);String version=e.getRequestHeaders().getFirst("X-API-Version");if(!"1".equals(version))throw new Api(426,"API_VERSION_REQUIRED","X-API-Version: 1 required");reply(e,200,Map.of("code","OK","data",a.run()));}catch(Api x){reply(e,x.status,Map.of("code",x.code,"message",x.getMessage()));}catch(SecurityException x){reply(e,401,Map.of("code","UNAUTHORIZED","message",x.getMessage()));}catch(IllegalArgumentException x){reply(e,400,Map.of("code","INVALID_REQUEST","message",String.valueOf(x.getMessage())));}catch(IllegalStateException x){reply(e,409,Map.of("code","CONFLICT","message",String.valueOf(x.getMessage())));}catch(Exception x){reply(e,500,Map.of("code","INTERNAL_ERROR","message","inventory request failed"));}}
 private void authenticate(HttpExchange e){String h=e.getRequestHeaders().getFirst("Authorization");byte[] got=h!=null&&h.startsWith("Bearer ")?h.substring(7).getBytes(StandardCharsets.UTF_8):new byte[0];if(!MessageDigest.isEqual(token,got))throw new SecurityException("invalid inventory credential");}
 @SuppressWarnings("unchecked")private Map<String,Object> body(HttpExchange e)throws IOException{return json.readValue(e.getRequestBody(),Map.class);}private static long player(HttpExchange e){String v=e.getRequestHeaders().getFirst("X-Player-Id");try{long n=Long.parseLong(v);if(n<=0)throw new Exception();return n;}catch(Exception x){throw new IllegalArgumentException("valid X-Player-Id required");}}private static String key(HttpExchange e){String k=e.getRequestHeaders().getFirst("Idempotency-Key");if(k==null)throw new IllegalArgumentException("Idempotency-Key required");return k;}private static void must(HttpExchange e,String m){if(!m.equals(e.getRequestMethod()))throw new Api(405,"METHOD_NOT_ALLOWED",m+" required");}private static String text(Map<String,Object>b,String k){Object v=b.get(k);if(!(v instanceof String s)||s.isBlank())throw new IllegalArgumentException(k+" required");return s;}private static long number(Map<String,Object>b,String k){Object v=b.get(k);if(v instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+" required");}private static long numberOr(Map<String,Object>b,String k,long d){return b.get(k)==null?d:number(b,k);}private static Instant instant(Object v){return v==null?null:Instant.parse(String.valueOf(v));}private void reply(HttpExchange e,int status,Object value)throws IOException{byte[] b=json.writeValueAsBytes(value);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(status,b.length);try(var o=e.getResponseBody()){o.write(b);}}@FunctionalInterface private interface Action{Object run()throws Exception;}private static final class Api extends RuntimeException{final int status;final String code;Api(int s,String c,String m){super(m);status=s;code=c;}}
}
