package com.aoo.bcg.inventory;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import javax.sql.DataSource;import java.sql.*;import java.time.*;import java.util.*;

/** JDBC authority for catalog, stock, commands, redemption and immutable movements. */
public final class JdbcInventoryStoreService implements InventoryStoreService {
 private final DataSource source;private final BillingPort billing;private final ObjectMapper json;private final Clock clock;
 public JdbcInventoryStoreService(DataSource source,BillingPort billing,ObjectMapper json,Clock clock){this.source=Objects.requireNonNull(source);this.billing=Objects.requireNonNull(billing);this.json=Objects.requireNonNull(json);this.clock=Objects.requireNonNull(clock);}
 public List<Item> catalog(Instant at){try(var c=source.getConnection();var q=c.prepareStatement("SELECT item_code,item_name,item_type,consumable,active_from,active_until,attributes_json FROM aoo_item_catalog WHERE active_from<=? AND (active_until IS NULL OR active_until>?) ORDER BY item_code")){q.setTimestamp(1,Timestamp.from(at));q.setTimestamp(2,Timestamp.from(at));try(var r=q.executeQuery()){List<Item>x=new ArrayList<>();while(r.next())x.add(new Item(r.getString(1),r.getString(2),r.getString(3),r.getBoolean(4),r.getTimestamp(5).toInstant(),instant(r.getTimestamp(6)),map(r.getString(7))));return List.copyOf(x);}}catch(Exception e){throw fail(e);}}
 public List<Stock> inventory(long player,Instant at){try(var c=source.getConnection();var q=c.prepareStatement("SELECT item_code,SUM(quantity),expires_at,MAX(row_version) FROM aoo_inventory_lot WHERE player_id=? AND quantity>0 AND (expires_at IS NULL OR expires_at>?) GROUP BY item_code,expires_at ORDER BY item_code,expires_at")){q.setLong(1,positive(player,"playerId"));q.setTimestamp(2,Timestamp.from(at));try(var r=q.executeQuery()){List<Stock>x=new ArrayList<>();while(r.next())x.add(new Stock(r.getString(1),r.getLong(2),instant(r.getTimestamp(3)),r.getLong(4)));return List.copyOf(x);}}catch(Exception e){throw fail(e);}}
 public List<Offer> offers(Instant at){try(var c=source.getConnection();var q=c.prepareStatement("SELECT offer_code,item_code,item_quantity,currency_code,price_minor,active_from,active_until FROM aoo_store_offer WHERE active_from<=? AND (active_until IS NULL OR active_until>?) ORDER BY offer_code")){q.setTimestamp(1,Timestamp.from(at));q.setTimestamp(2,Timestamp.from(at));try(var r=q.executeQuery()){List<Offer>x=new ArrayList<>();while(r.next())x.add(new Offer(r.getString(1),r.getString(2),r.getLong(3),r.getString(4),r.getLong(5),r.getTimestamp(6).toInstant(),instant(r.getTimestamp(7))));return List.copyOf(x);}}catch(Exception e){throw fail(e);}}
 public Command grant(String key,long player,String item,long quantity,Instant expires,String sourceCode){validateKey(key);positive(player,"playerId");positive(quantity,"quantity");return mutate(key,"GRANT",player,item,c->{requireItem(c,item);addLot(c,player,item,quantity,expires);movement(c,key,player,item,quantity,"GRANT",sourceCode);return "SUCCEEDED";});}
 public Command use(String key,long player,String item,long quantity){validateKey(key);positive(quantity,"quantity");return mutate(key,"USE",player,item,c->{requireItem(c,item);consume(c,player,item,quantity,clock.instant());movement(c,key,player,item,-quantity,"USE","PLAYER");return "SUCCEEDED";});}
 public Command purchase(String key,long player,String offerCode){validateKey(key);Command old=find(key);if(old!=null)return old;Offer offer=offer(offerCode,clock.instant());insertPending(key,"PURCHASE",player,offerCode);try{billing.debit("store:"+key,player,offer.currency(),offer.price(),"STORE_PURCHASE");try{return mutateExisting(key,c->{addLot(c,player,offer.itemCode(),offer.quantity(),null);movement(c,key,player,offer.itemCode(),offer.quantity(),"PURCHASE",offerCode);return "SUCCEEDED";});}catch(RuntimeException grantFailure){try{billing.refund("store-refund:"+key,player,offer.currency(),offer.price(),"STORE_COMPENSATION");state(key,"COMPENSATED",grantFailure.getMessage());}catch(RuntimeException refundFailure){state(key,"COMPENSATION_PENDING",grantFailure.getMessage());grantFailure.addSuppressed(refundFailure);}throw grantFailure;}}catch(RuntimeException billingFailure){Command current=find(key);if(current!=null&&"PENDING".equals(current.state()))state(key,"FAILED",billingFailure.getMessage());throw billingFailure;}}
 public Command redeem(String key,long player,String code){validateKey(key);return mutate(key,"REDEEM",player,code,c->{long campaign;String item;long quantity;Instant expires;try(var q=c.prepareStatement("SELECT c.id,c.item_code,c.item_quantity,c.grant_expires_at FROM aoo_redemption_code r JOIN aoo_redemption_campaign c ON c.id=r.campaign_id WHERE r.code_hash=? AND r.status='ACTIVE' AND c.active_from<=? AND c.active_until>? FOR UPDATE")){q.setString(1,hash(code));q.setTimestamp(2,Timestamp.from(clock.instant()));q.setTimestamp(3,Timestamp.from(clock.instant()));try(var r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("redemption code invalid or expired");campaign=r.getLong(1);item=r.getString(2);quantity=r.getLong(3);expires=instant(r.getTimestamp(4));}}try(var q=c.prepareStatement("INSERT INTO aoo_redemption_claim(campaign_id,code_hash,player_id,command_id,claimed_at) VALUES(?,?,?,?,?)")){q.setLong(1,campaign);q.setString(2,hash(code));q.setLong(3,player);q.setString(4,key);q.setTimestamp(5,Timestamp.from(clock.instant()));q.executeUpdate();}addLot(c,player,item,quantity,expires);movement(c,key,player,item,quantity,"REDEEM",String.valueOf(campaign));return "SUCCEEDED";});}
 public Command revoke(String key,String original,String reason){validateKey(key);Command prior=find(original);if(prior==null||!"SUCCEEDED".equals(prior.state()))throw new IllegalArgumentException("original command is not reversible");return mutate(key,"REVOKE",prior.playerId(),original,c->{List<Object[]> rows=new ArrayList<>();try(var q=c.prepareStatement("SELECT item_code,quantity_delta FROM aoo_inventory_movement WHERE command_id=? AND quantity_delta>0")){q.setString(1,original);try(var r=q.executeQuery()){while(r.next())rows.add(new Object[]{r.getString(1),r.getLong(2)});}}if(rows.isEmpty())throw new IllegalArgumentException("original command has no grant");for(Object[] row:rows){String item=(String)row[0];long qty=(long)row[1];consume(c,prior.playerId(),item,qty,clock.instant());movement(c,key,prior.playerId(),item,-qty,"REVOKE",reason);}return "SUCCEEDED";});}
 public int expire(Instant at,int limit){limit=Math.max(1,Math.min(limit,1000));try(var c=source.getConnection()){c.setAutoCommit(false);try(var q=c.prepareStatement("SELECT id,player_id,item_code,quantity FROM aoo_inventory_lot WHERE quantity>0 AND expires_at<=? ORDER BY expires_at,id LIMIT ? FOR UPDATE")){q.setTimestamp(1,Timestamp.from(at));q.setInt(2,limit);int n=0;try(var r=q.executeQuery()){while(r.next()){long id=r.getLong(1),player=r.getLong(2),qty=r.getLong(4);String item=r.getString(3),key="expire:"+id;try(var u=c.prepareStatement("UPDATE aoo_inventory_lot SET quantity=0,row_version=row_version+1 WHERE id=?")){u.setLong(1,id);u.executeUpdate();}movement(c,key,player,item,-qty,"EXPIRE",String.valueOf(id));n++;}}c.commit();return n;}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw fail(e);}}
 private Command mutate(String key,String kind,long player,String ref,Tx tx){Command old=find(key);if(old!=null)return old;insertPending(key,kind,player,ref);return mutateExisting(key,tx);}
 private Command mutateExisting(String key,Tx tx){try(var c=source.getConnection()){c.setAutoCommit(false);try{String next=tx.run(c);try(var q=c.prepareStatement("UPDATE aoo_inventory_command SET command_state=?,updated_at=? WHERE command_id=? AND command_state='PENDING'")){q.setString(1,next);q.setTimestamp(2,Timestamp.from(clock.instant()));q.setString(3,key);if(q.executeUpdate()!=1)throw new IllegalStateException("command state conflict");}c.commit();return find(key);}catch(Exception e){c.rollback();throw e;}}catch(Exception e){state(key,"FAILED",e.getMessage());throw fail(e);}}
 private void insertPending(String key,String kind,long player,String ref){try(var c=source.getConnection();var q=c.prepareStatement("INSERT INTO aoo_inventory_command(command_id,command_kind,command_state,player_id,reference_code,error_message,created_at,updated_at) VALUES(?,?,'PENDING',?,?,NULL,?,?)")){q.setString(1,key);q.setString(2,kind);q.setLong(3,player);q.setString(4,ref);Timestamp now=Timestamp.from(clock.instant());q.setTimestamp(5,now);q.setTimestamp(6,now);q.executeUpdate();}catch(SQLIntegrityConstraintViolationException e){}catch(Exception e){if(find(key)==null)throw fail(e);}}
 private Command find(String key){try(var c=source.getConnection();var q=c.prepareStatement("SELECT command_id,command_kind,command_state,player_id,reference_code,created_at FROM aoo_inventory_command WHERE command_id=?")){q.setString(1,key);try(var r=q.executeQuery()){return r.next()?new Command(r.getString(1),r.getString(2),r.getString(3),r.getLong(4),r.getString(5),r.getTimestamp(6).toInstant()):null;}}catch(Exception e){throw fail(e);}}
 private void state(String key,String state,String error){try(var c=source.getConnection();var q=c.prepareStatement("UPDATE aoo_inventory_command SET command_state=?,error_message=?,updated_at=? WHERE command_id=?")){q.setString(1,state);q.setString(2,error==null?null:error.substring(0,Math.min(500,error.length())));q.setTimestamp(3,Timestamp.from(clock.instant()));q.setString(4,key);q.executeUpdate();}catch(Exception e){throw fail(e);}}
 private Offer offer(String code,Instant at){return offers(at).stream().filter(x->x.code().equals(code)).findFirst().orElseThrow(()->new IllegalArgumentException("offer inactive or missing"));}
 private void requireItem(Connection c,String item)throws SQLException{try(var q=c.prepareStatement("SELECT 1 FROM aoo_item_catalog WHERE item_code=? AND active_from<=? AND (active_until IS NULL OR active_until>?)")){q.setString(1,item);q.setTimestamp(2,Timestamp.from(clock.instant()));q.setTimestamp(3,Timestamp.from(clock.instant()));try(var r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("item inactive or missing");}}}
 private void addLot(Connection c,long player,String item,long qty,Instant expires)throws SQLException{try(var q=c.prepareStatement("INSERT INTO aoo_inventory_lot(player_id,item_code,quantity,expires_at,row_version,created_at) VALUES(?,?,?,?,1,?)")){q.setLong(1,player);q.setString(2,item);q.setLong(3,qty);if(expires==null)q.setNull(4,Types.TIMESTAMP);else q.setTimestamp(4,Timestamp.from(expires));q.setTimestamp(5,Timestamp.from(clock.instant()));q.executeUpdate();}}
 private void consume(Connection c,long player,String item,long needed,Instant at)throws SQLException{try(var q=c.prepareStatement("SELECT id,quantity FROM aoo_inventory_lot WHERE player_id=? AND item_code=? AND quantity>0 AND (expires_at IS NULL OR expires_at>?) ORDER BY CASE WHEN expires_at IS NULL THEN 1 ELSE 0 END,expires_at,id FOR UPDATE")){q.setLong(1,player);q.setString(2,item);q.setTimestamp(3,Timestamp.from(at));try(var r=q.executeQuery()){List<long[]> lots=new ArrayList<>();long total=0;while(r.next()){lots.add(new long[]{r.getLong(1),r.getLong(2)});total+=r.getLong(2);}if(total<needed)throw new IllegalStateException("insufficient item quantity");long left=needed;for(long[] lot:lots){if(left==0)break;long take=Math.min(left,lot[1]);try(var u=c.prepareStatement("UPDATE aoo_inventory_lot SET quantity=quantity-?,row_version=row_version+1 WHERE id=? AND quantity>=?")){u.setLong(1,take);u.setLong(2,lot[0]);u.setLong(3,take);if(u.executeUpdate()!=1)throw new IllegalStateException("inventory write conflict");}left-=take;}}}}
 private void movement(Connection c,String command,long player,String item,long delta,String type,String sourceCode)throws SQLException{try(var q=c.prepareStatement("INSERT INTO aoo_inventory_movement(command_id,player_id,item_code,quantity_delta,movement_type,source_reference,created_at) VALUES(?,?,?,?,?,?,?)")){q.setString(1,command);q.setLong(2,player);q.setString(3,item);q.setLong(4,delta);q.setString(5,type);q.setString(6,sourceCode);q.setTimestamp(7,Timestamp.from(clock.instant()));q.executeUpdate();}}
 private Map<String,Object> map(String s)throws Exception{return s==null||s.isBlank()?Map.of():json.readValue(s,new TypeReference<>(){});}private static Instant instant(Timestamp t){return t==null?null:t.toInstant();}private static long positive(long n,String name){if(n<=0)throw new IllegalArgumentException(name+" must be positive");return n;}private static void validateKey(String k){if(k==null||!k.matches("[A-Za-z0-9_.:-]{1,128}"))throw new IllegalArgumentException("valid idempotency key required");}private static String hash(String code){if(code==null||!code.matches("[A-Za-z0-9-]{6,64}"))throw new IllegalArgumentException("invalid redemption code");try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(code.toUpperCase(Locale.ROOT).getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static RuntimeException fail(Exception e){return e instanceof RuntimeException r?r:new IllegalStateException("inventory persistence unavailable",e);}@FunctionalInterface private interface Tx{String run(Connection c)throws Exception;}
}
