#!/usr/bin/env ruby
require 'json';require 'digest';require 'find';require 'time';require 'fileutils'
root=File.expand_path('..',__dir__);input=File.expand_path(ARGV.fetch(0),root);output=File.expand_path(ARGV.fetch(1),root);abort "log directory missing: #{input}"unless Dir.exist?(input)
patterns={startup:/\b(?:startup|starting|failed to start|LOADED=|APPS=)\b/i,thread:/\b(?:thread|deadlock|mutex|executor|rejectedexecution)\b/i,database:/\b(?:sql|jdbc|database|mysql|redis|connection pool)\b/i,protocol:/\b(?:protocol|websocket|handshake|msgId|requestId)\b/i,network:/\b(?:connect|timeout|connection refused|broken pipe)\b/i}
severity=lambda{|line|case line;when /\b(?:fatal|panic)\b/i then'fatal';when /\b(?:error|exception|failed|severe|严重)\b/i then'error';when /\b(?:warn|warning|警告)\b/i then'warning';else'info';end}
normalize=lambda{|line|line.gsub(/[0-9a-f]{8}-[0-9a-f-]{27,}/i,'<uuid>').gsub(/\b\d{1,3}(?:\.\d{1,3}){3}(?::\d+)?\b/,'<ip>').gsub(/\b\d{4}-\d{2}-\d{2}[T ][0-9:.+Z-]+/,'<time>').gsub(/\b\d+\b/,'<n>').gsub(/\s+/,' ').strip}
rows=[];files=Dir.glob(File.join(input,'**/*')).select{|p|File.file?(p)}.sort;files.each{|file|File.foreach(file,encoding:'UTF-8',invalid: :replace,undef: :replace){|line|level=severity.call(line);next if level=='info'&&!line.match?(/LOADED=|APPS=/);signature=normalize.call(line);category=patterns.find{|_,regex|line.match?(regex)}&.first||:uncategorized;rows<<{file:file.delete_prefix(root+'/'),severity:level,category:category.to_s,signature:signature,fingerprint:Digest::SHA256.hexdigest(signature)[0,16]}}}
groups=rows.group_by{|r|[r[:severity],r[:category],r[:fingerprint]]}.map{|(level,category,fingerprint),items|{severity:level,category:category,fingerprint:fingerprint,count:items.length,signature:items.first[:signature],files:items.map{|i|i[:file]}.uniq.sort}}.sort_by{|x|[-x[:count],x[:fingerprint]]}
report={schemaVersion:1,generatedAt:Time.now.utc.iso8601,input:input.delete_prefix(root+'/'),files:files.map{|p|p.delete_prefix(root+'/')},summary:{files:files.length,classifiedLines:rows.length,errorSignatures:groups.count{|g|%w[fatal error].include?(g[:severity])}},signatures:groups,policy:'Historical logs are diagnostic clues only; each finding requires reproduction in current code/test before closure.'};FileUtils.mkdir_p(File.dirname(output));File.write(output,JSON.pretty_generate(report)+"\n")
