import java.nio.file.*;import java.sql.*;import java.util.*;import java.util.concurrent.*;
public final class ClubMemberScaleBenchmark{
 public static void main(String[]a)throws Exception{if(a.length!=5)throw new IllegalArgumentException("jdbc user password samples output");int samples=Integer.parseInt(a[3]);List<Long>t=new ArrayList<>(samples);try(Connection c=DriverManager.getConnection(a[0],a[1],a[2])){
  long rows=count(c,"SELECT COUNT(*) FROM aoo_club_member WHERE club_id=1");if(rows<1_000_000)throw new IllegalStateException("member capacity failed");
  String pageKey=key(c,"EXPLAIN SELECT player_id FROM aoo_club_member WHERE club_id=1 AND member_status='ACTIVE' AND player_id>500000 ORDER BY player_id LIMIT 201");if(!Set.of("PRIMARY","idx_club_member_page").contains(pageKey))throw new IllegalStateException("page plan "+pageKey);
  String managerKey=key(c,"EXPLAIN SELECT player_id FROM aoo_club_member WHERE club_id=1 AND member_role='MANAGER' AND online=1 AND player_id>0 ORDER BY player_id LIMIT 1000");if(!"idx_club_manager_online".equals(managerKey))throw new IllegalStateException("permission plan "+managerKey);
  c.setAutoCommit(false);try(PreparedStatement d=c.prepareStatement("UPDATE aoo_club_member SET member_status='LEFT',online=0,row_version=row_version+1 WHERE club_id=1 AND player_id=500000")){d.executeUpdate();}if(count(c,"SELECT COUNT(*) FROM aoo_club_member WHERE club_id=1 AND member_status='ACTIVE' AND player_id=500000")!=0)throw new IllegalStateException("soft delete failed");c.rollback();c.setAutoCommit(true);
  SplittableRandom random=new SplittableRandom(20260823);try(PreparedStatement q=c.prepareStatement("SELECT player_id FROM aoo_club_member WHERE club_id=1 AND member_status='ACTIVE' AND player_id>? ORDER BY player_id LIMIT 201")){for(int i=0;i<100;i++)query(q,random.nextLong(1,999800));for(int i=0;i<samples;i++){long n=System.nanoTime();query(q,random.nextLong(1,999800));t.add(System.nanoTime()-n);}}
  Collections.sort(t);double p95=ms(t.get((int)Math.ceil(samples*.95)-1)),p99=ms(t.get((int)Math.ceil(samples*.99)-1));if(p95>25||p99>60)throw new IllegalStateException("latency failed");int winners=hotspot(a);if(winners!=1)throw new IllegalStateException("hotspot lost update: "+winners);
  String j=String.format(Locale.ROOT,"{\n  \"members\": %d,\n  \"pageIndex\": \"%s\",\n  \"permissionIndex\": \"%s\",\n  \"softDeleteExcluded\": true,\n  \"hotspotWinners\": %d,\n  \"sustainedSamples\": %d,\n  \"p95Ms\": %.3f,\n  \"p99Ms\": %.3f,\n  \"p95BudgetMs\": 25,\n  \"p99BudgetMs\": 60,\n  \"status\": \"passed\"\n}\n",rows,pageKey,managerKey,winners,samples,p95,p99);Files.writeString(Path.of(a[4]),j);System.out.print(j);
 }}
 static int hotspot(String[]a)throws Exception{long version;try(Connection c=DriverManager.getConnection(a[0],a[1],a[2]);Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT row_version FROM aoo_club_member WHERE club_id=1 AND player_id=1")){r.next();version=r.getLong(1);}ExecutorService p=Executors.newFixedThreadPool(16);CountDownLatch go=new CountDownLatch(1);List<Future<Integer>>fs=new ArrayList<>();for(int i=0;i<16;i++)fs.add(p.submit(()->{go.await();try(Connection c=DriverManager.getConnection(a[0],a[1],a[2]);PreparedStatement q=c.prepareStatement("UPDATE aoo_club_member SET updated_at=CURRENT_TIMESTAMP(3),row_version=row_version+1 WHERE club_id=1 AND player_id=1 AND row_version=?")){q.setLong(1,version);return q.executeUpdate();}}));go.countDown();int n=0;for(Future<Integer>f:fs)n+=f.get();p.shutdown();return n;}
 static long count(Connection c,String sql)throws Exception{try(Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){r.next();return r.getLong(1);}}
 static String key(Connection c,String sql)throws Exception{try(Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){r.next();return r.getString("key");}}
 static void query(PreparedStatement q,long after)throws Exception{q.setLong(1,after);try(ResultSet r=q.executeQuery()){int n=0;while(r.next())n++;if(n==0)throw new SQLException("empty page");}}
 static double ms(long n){return n/1_000_000d;}
}
