import java.nio.file.*;import java.util.*;import java.util.regex.*;import java.io.*;
/** Rejects historical implementations and temporarily disabled logic preserved as comments. */
public final class CommentedCodeCheck{
 private static final Pattern CODE=Pattern.compile("^\\s*//\\s*(?:if|for|while|switch|return|throw|public|private|protected|class|interface|record|const|let|var|this\\.|[A-Za-z_$][A-Za-z0-9_$<>., ?]*\\s+[A-Za-z_$][A-Za-z0-9_$]*\\s*[=(]).*");
 private static final Pattern DISABLED=Pattern.compile("(?i)(temporar(?:y|ily)\\s+disabled|commented[ -]?out|old code|legacy code|临时关闭|注释掉|旧代码)");
 public static void main(String[]args)throws Exception{Path root=Path.of(args[0]),client=Path.of(args[1]);List<String>failures=new ArrayList<>();scan(root.resolve("server"),failures);scan(client.resolve("assets"),failures);Path out=root.resolve("work/audit/dead08-commented-code.txt");Files.createDirectories(out.getParent());Files.writeString(out,failures.isEmpty()?"DEAD08 passed: canonical production source contains no commented implementation block or temporary-disable marker. Historical code belongs in version control and isolated reference roots.\n":String.join("\n",failures)+"\n");if(!failures.isEmpty())throw new IllegalStateException("commented production code gate failed: "+failures.size());System.out.println("Commented code check passed.");}
 private static void scan(Path base,List<String>failures)throws IOException{if(!Files.isDirectory(base))return;try(var paths=Files.walk(base)){for(Path path:paths.filter(Files::isRegularFile).filter(CommentedCodeCheck::canonical).toList()){List<String>lines=Files.readAllLines(path);int run=0;for(int index=0;index<lines.size();index++){String line=lines.get(index);run=CODE.matcher(line).matches()?run+1:0;if(run==3)failures.add(path+":"+(index-1)+" commented implementation block");if(DISABLED.matcher(line).find())failures.add(path+":"+(index+1)+" disable/history marker");}}}}
 private static boolean canonical(Path value){String path=value.toString().replace('\\','/'),lower=path.toLowerCase(Locale.ROOT);if(lower.contains("/target/")||lower.contains("/build/")||lower.contains("/test/")||lower.contains("/legacy")||lower.contains("/compatibilityapp/"))return false;if(path.endsWith(".ts"))return true;return path.endsWith(".java")&&path.contains("/src/main/java/com/aoo/");}
}
