import java.nio.file.*;import java.sql.*;import java.util.*;
public final class PlayerScaleBenchmark{
 public static void main(String[]a)throws Exception{int samples=Integer.parseInt(a[3]);List<Long>times=new ArrayList<>(samples);try(Connection c=DriverManager.getConnection(a[0],a[1],a[2])){
  long rows=value(c,"SELECT COUNT(*) FROM db_player");if(rows<10_000_000)throw new IllegalStateException("capacity failed");long createdTime=value(c,"SELECT MIN(createTime) FROM db_player"),loginTime=value(c,"SELECT MIN(lastLogin) FROM db_player");
  String created=key(c,"EXPLAIN SELECT id FROM db_player WHERE (createTime>"+createdTime+" OR (createTime="+createdTime+" AND id>5000000)) ORDER BY createTime,id LIMIT 500"),login=key(c,"EXPLAIN SELECT id FROM db_player WHERE (lastLogin>"+loginTime+" OR (lastLogin="+loginTime+" AND id>5000000)) ORDER BY lastLogin,id LIMIT 500");if(!"idx_db_player_created_cursor".equals(created)||!"idx_db_player_last_login_cursor".equals(login))throw new IllegalStateException("cursor plan failed "+created+"/"+login);
  SplittableRandom random=new SplittableRandom(7);try(PreparedStatement q=c.prepareStatement("SELECT id FROM db_player WHERE (lastLogin>? OR (lastLogin=? AND id>?)) ORDER BY lastLogin,id LIMIT 500")){for(int i=0;i<100;i++)query(q,loginTime,random.nextLong(1,rows-500));for(int i=0;i<samples;i++){long n=System.nanoTime();query(q,loginTime,random.nextLong(1,rows-500));times.add(System.nanoTime()-n);}}
  Collections.sort(times);double p95=ms(times.get((int)Math.ceil(samples*.95)-1)),p99=ms(times.get((int)Math.ceil(samples*.99)-1));if(p95>30||p99>75)throw new IllegalStateException("cursor latency failed");long secondary=value(c,"SELECT COUNT(DISTINCT index_name) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='db_player' AND index_name<>'PRIMARY'");if(secondary>5)throw new IllegalStateException("write amplification index budget failed");
  long base=20_000_000,start=System.nanoTime();c.setAutoCommit(false);try(PreparedStatement q=c.prepareStatement("INSERT INTO db_player(id,account_id,phone,createTime,lastLogin) VALUES(?,?,?,?,?)")){for(int i=1;i<=10000;i++){q.setLong(1,base+i);q.setLong(2,base+i);q.setString(3,"bench-"+i);q.setLong(4,i);q.setLong(5,i);q.addBatch();if(i%1000==0)q.executeBatch();}c.rollback();}finally{c.setAutoCommit(true);}double writeMs=ms(System.nanoTime()-start),writesPerSecond=10_000/(writeMs/1000);if(writesPerSecond<1000)throw new IllegalStateException("write throughput failed");
  String j=String.format(Locale.ROOT,"{\n  \"rows\": %d,\n  \"createdCursorIndex\": \"%s\",\n  \"lastLoginCursorIndex\": \"%s\",\n  \"secondaryIndexes\": %d,\n  \"estimatedBtreeMutationsPerWrite\": %d,\n  \"querySamples\": %d,\n  \"p95Ms\": %.3f,\n  \"p99Ms\": %.3f,\n  \"writeSamples\": 10000,\n  \"writesPerSecond\": %.1f,\n  \"mysqlVersion\": \"%s\",\n  \"availableProcessors\": %d,\n  \"status\": \"passed\"\n}\n",rows,created,login,secondary,secondary+1,samples,p95,p99,writesPerSecond,text(c,"SELECT VERSION()"),Runtime.getRuntime().availableProcessors());Files.writeString(Path.of(a[4]),j);System.out.print(j);
 }}
 static void query(PreparedStatement q,long time,long id)throws Exception{q.setLong(1,time);q.setLong(2,time);q.setLong(3,id);try(ResultSet r=q.executeQuery()){int n=0;while(r.next())n++;if(n==0)throw new SQLException("empty cursor page");}}static long value(Connection c,String s)throws Exception{try(Statement q=c.createStatement();ResultSet r=q.executeQuery(s)){r.next();return r.getLong(1);}}static String text(Connection c,String s)throws Exception{try(Statement q=c.createStatement();ResultSet r=q.executeQuery(s)){r.next();return r.getString(1);}}static String key(Connection c,String s)throws Exception{try(Statement q=c.createStatement();ResultSet r=q.executeQuery(s)){r.next();return r.getString("key");}}static double ms(long n){return n/1_000_000d;}
}
