import java.nio.file.*;import java.sql.*;
public final class ViewerIdentityChainSmoke{
 public static void main(String[]a)throws Exception{try(Connection c=DriverManager.getConnection(a[0],a[1],a[2])){long room=830003,player=830031,other=830032;int seat=2,set=1;c.setAutoCommit(false);
  try(PreparedStatement q=c.prepareStatement("INSERT INTO aoo_connection_generation(user_id,room_id,seat_id,generation,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP(3))")){q.setString(1,""+player);q.setLong(2,room);q.setInt(3,seat);q.setLong(4,2);q.executeUpdate();}
  try(PreparedStatement q=c.prepareStatement("INSERT INTO replay_participant(room_id,set_id,player_id,seat_id,granted_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP(3))")){q.setLong(1,room);q.setInt(2,set);q.setLong(3,player);q.setInt(4,seat);q.executeUpdate();}
  String ins="INSERT INTO aoo_room_event(room_id,round_no,event_sequence,business_event_id,event_type,schema_version,event_payload,created_at,visibility,owner_player_id) VALUES(?,1,?,?,?,1,'{}',CURRENT_TIMESTAMP(3),?,?)";try(PreparedStatement q=c.prepareStatement(ins)){event(q,room,1,"public","PUBLIC",0);event(q,room,2,"mine","PLAYER_PRIVATE",player);event(q,room,3,"other","PLAYER_PRIVATE",other);}
  boolean exact=exists(c,"SELECT 1 FROM replay_participant WHERE room_id="+room+" AND set_id=1 AND player_id="+player+" AND seat_id=2"),wrong=exists(c,"SELECT 1 FROM replay_participant WHERE room_id="+room+" AND set_id=1 AND player_id="+player+" AND seat_id=1");long visible=count(c,"SELECT COUNT(*) FROM aoo_room_event WHERE room_id="+room+" AND ((visibility='PUBLIC' AND owner_player_id=0) OR (visibility='PLAYER_PRIVATE' AND owner_player_id="+player+"))");long generation=count(c,"SELECT generation FROM aoo_connection_generation WHERE user_id='"+player+"' AND room_id="+room+" AND seat_id=2");c.rollback();if(!exact||wrong||visible!=2||generation!=2)throw new IllegalStateException("identity chain failed");String j="{\n  \"connectionGeneration\": 2,\n  \"seatAuthorized\": true,\n  \"wrongSeatDenied\": true,\n  \"visibleEvents\": 2,\n  \"otherPrivateEventsLeaked\": 0,\n  \"status\": \"passed\"\n}\n";Files.writeString(Path.of(a[3]),j);System.out.print(j);}}
 static void event(PreparedStatement q,long room,long seq,String type,String visibility,long owner)throws Exception{q.setLong(1,room);q.setLong(2,seq);q.setString(3,"smoke:"+seq+":"+visibility+":"+owner);q.setString(4,type);q.setString(5,visibility);q.setLong(6,owner);q.executeUpdate();}
 static boolean exists(Connection c,String s)throws Exception{return count(c,"SELECT COUNT(*) FROM ("+s+")x")>0;}static long count(Connection c,String s)throws Exception{try(Statement q=c.createStatement();ResultSet r=q.executeQuery(s)){r.next();return r.getLong(1);}}
}
