package com.aoo.bcg.wordcard;
import com.aoo.bcg.gamespi.*;import com.aoo.bcg.gamespi.time.*;import java.util.*;
final class ByzpSession implements AuthoritativeGameSession{
 private final long room,owner;private final RulePayload rawRules;private final ByzpRules.Config config;private final Map<Integer,Long>players=new LinkedHashMap<>();private final Set<Integer>ready=new LinkedHashSet<>();private final List<Object>events=new ArrayList<>();private final OperationDeadlineArbiter arbiter=new OperationDeadlineArbiter();private WordCardState game;private long sequence,version;
 ByzpSession(long room,long owner,RulePayload rules){if(room<=0||owner<=0)throw new IllegalArgumentException("invalid BYZP room");this.room=room;this.owner=owner;rawRules=rules==null?RulePayload.empty():rules;config=parse(rawRules.asMap());players.put(0,owner);}
 public synchronized GameCommandResult execute(GameCommandRequest r){if(r.roomId()!=room||r.sequence()<=sequence)throw new IllegalArgumentException("invalid BYZP command order");long p=id(r.authenticatedUserId());String a=String.valueOf(r.body().asMap().getOrDefault("action","state"));boolean change=true;switch(a){case"state","CBYZPGetRoomInfo"-> {participant(p);change=false;}case"join","CBYZPEnterRoom"->join(r.seatId(),p);case"ready","CBYZPReadyRoom"->{own(r.seatId(),p);waiting();ready.add(r.seatId());}case"unready","CBYZPUnReadyRoom"->{own(r.seatId(),p);waiting();ready.remove(r.seatId());}case"start","CBYZPStartGame"->start(p);case"operation","CBYZPOpCard"->operate(r,p);default->throw new IllegalArgumentException("unsupported BYZP action");}sequence=r.sequence();if(change){version++;events.add(Map.of("version",version,"after",snapshot()));}return new GameCommandResult("wordcard.byzp.response",r.requestId(),viewFor(p));}
 private void join(int seat,long p){waiting();if(seat<0||seat>=4||players.putIfAbsent(seat,p)!=null)throw new IllegalStateException("invalid or occupied BYZP seat");}
 private void start(long p){if(p!=owner)throw new SecurityException("owner only");waiting();if(players.size()<2||!ready.containsAll(players.keySet().stream().filter(x->x!=0).toList()))throw new IllegalStateException("players not ready");List<Integer>d=new ArrayList<>(ByzpRules.deck());Collections.shuffle(d,new Random(room));Map<Integer,List<Integer>>h=new LinkedHashMap<>();Map<Integer,Integer>x=new LinkedHashMap<>();for(int seat:players.keySet()){List<Integer>hand=new ArrayList<>();for(int i=0;i<20;i++)hand.add(d.removeFirst());h.put(seat,hand);x.put(seat,0);}game=new WordCardState(h,d,List.of(),x,0,WordCardPhase.PLAYING,null,null);}
 private void operate(GameCommandRequest r,long p){own(r.seatId(),p);if(game==null)throw new IllegalStateException("round not started");Map<String,Object>b=map(r.body().asMap().getOrDefault("payload",Map.of()));WordCardOperation op=WordCardOperation.valueOf(String.valueOf(b.getOrDefault("operation","PASS")));List<Integer>cards=b.get("cards")instanceof Collection<?>c?c.stream().map(ByzpSession::num).toList():List.of();int xi=num(b.getOrDefault("huXi",game.huXi().get(r.seatId()))),ghosts=config.ghostCard()?num(b.getOrDefault("ghosts",0)):0;boolean can=huCandidate(r.seatId(),xi,ghosts);var context=new ByzpRuleSet.Context(config,xi,ghosts,can);game=new WordCardCoreEngine<>(new ByzpRuleSet()).apply(game,new WordCardCommand(op,r.seatId(),cards),context);}
 private boolean huCandidate(int seat,int xi,int ghosts){List<Integer>h=new ArrayList<>(game.hands().get(seat));if(game.exposedCard()!=null)h.add(game.exposedCard());return xi>=15&&ByzpRules.canHu(h,ghosts);}
 public synchronized Map<String,Object>viewFor(long viewer){Integer mine=seat(viewer);Map<Integer,Object>s=new LinkedHashMap<>();players.forEach((pos,p)->{List<Integer>h=game==null?List.of():game.hands().get(pos);s.put(pos,Map.of("playerId",p,"ready",ready.contains(pos),"cards",Objects.equals(pos,mine)||game!=null&&game.phase()==WordCardPhase.FINISHED?h:Collections.nCopies(h.size(),0),"cardCount",h.size(),"huXi",game==null?0:game.huXi().get(pos)));});return Map.of("roomId",room,"roomID",room,"gameCode","byzp","started",game!=null,"phase",game==null?"WAITING":game.phase().name(),"currentSeat",game==null?-1:game.currentSeat(),"winnerSeat",game==null||game.winnerSeat()==null?-1:game.winnerSeat(),"seats",Map.copyOf(s),"stateVersion",version);}
 public synchronized Map<String,Object>authoritativeState(){return snapshot();}public synchronized long stateVersion(){return version;}synchronized List<Object>events(){return List.copyOf(events);}private Map<String,Object>snapshot(){return Map.of("schemaVersion",1,"roomId",room,"ownerId",owner,"players",Map.copyOf(players),"ready",List.copyOf(ready),"rules",rawRules.asMap(),"sequence",sequence,"stateVersion",version,"game",game==null?"WAITING":encode(game));}
 static ByzpSession restore(Map<String,Object>s){if(num(s.get("schemaVersion"))!=1)throw new IllegalArgumentException("bad BYZP schema");ByzpSession x=new ByzpSession(longNum(s.get("roomId")),longNum(s.get("ownerId")),RulePayload.copyOf(map(s.get("rules"))));x.players.clear();map(s.get("players")).forEach((k,v)->x.players.put(Integer.parseInt(k),longNum(v)));for(Object v:(Collection<?>)s.get("ready"))x.ready.add(num(v));if(s.get("game")instanceof Map<?,?>)x.game=decode(map(s.get("game")));x.sequence=longNum(s.get("sequence"));x.version=longNum(s.get("stateVersion"));return x;}
 static StatePayload replay(StatePayload base,List<Object>events){Map<String,Object>s=new LinkedHashMap<>(base.asMap());long v=longNum(s.get("stateVersion"));for(Object raw:events){Map<String,Object>e=map(raw);if(longNum(e.get("version"))!=++v)throw new IllegalArgumentException("BYZP replay gap");s=new LinkedHashMap<>(map(e.get("after")));}return StatePayload.copyOf(s);}
 private static Map<String,Object>encode(WordCardState s){return Map.of("hands",s.hands(),"deck",s.deck(),"discards",s.discards(),"huXi",s.huXi(),"currentSeat",s.currentSeat(),"phase",s.phase().name(),"exposed",s.exposedCard()==null?-1:s.exposedCard(),"winner",s.winnerSeat()==null?-1:s.winnerSeat());}
 private static WordCardState decode(Map<String,Object>m){Map<Integer,List<Integer>>h=new LinkedHashMap<>();map(m.get("hands")).forEach((k,v)->h.put(Integer.parseInt(k),((Collection<?>)v).stream().map(ByzpSession::num).toList()));Map<Integer,Integer>x=new LinkedHashMap<>();map(m.get("huXi")).forEach((k,v)->x.put(Integer.parseInt(k),num(v)));int e=num(m.get("exposed")),w=num(m.get("winner"));return new WordCardState(h,ints(m.get("deck")),ints(m.get("discards")),x,num(m.get("currentSeat")),WordCardPhase.valueOf(String.valueOf(m.get("phase"))),e<0?null:e,w<0?null:w);}
 private static ByzpRules.Config parse(Map<String,Object>r){return new ByzpRules.Config(ByzpRules.WakeMode.valueOf(String.valueOf(r.getOrDefault("wakeMode","UPPER"))),bool(r,"oilContest"),bool(r,"mandatoryHu"),bool(r,"doubleShot"),bool(r,"ghostCard"),bool(r,"autoReady"),bool(r,"dissolveOnTrusteeship"),num(r.getOrDefault("oilsPerPoint",5)),num(r.getOrDefault("multiplier",1)));}
 public OperationDeadline operationDeadline(){return OperationDeadline.none();}public OperationDeadlineArbiter deadlineArbiter(){return arbiter;}public synchronized List<String>invariantViolations(){List<String>v=new ArrayList<>();if(!players.containsValue(owner))v.add("OWNER_NOT_SEATED");if(game!=null&&!game.hands().keySet().equals(players.keySet()))v.add("HAND_SEAT_MISMATCH");return v;}public synchronized SettlementPayload settlement(int round,String pv){if(game==null||game.phase()!=WordCardPhase.FINISHED)throw new IllegalStateException("round not finished");if(!ByzpGameProvider.VERSION.equals(pv))throw new IllegalArgumentException("play version mismatch");Map<Long,Long>d=new LinkedHashMap<>();for(var e:players.entrySet())d.put(e.getValue(),e.getKey().equals(game.winnerSeat())?players.size()-1L:-1L);return new SettlementPayload(room,round,pv,d);}
 private void waiting(){if(game!=null)throw new IllegalStateException("round started");}private void own(int s,long p){if(!Long.valueOf(p).equals(players.get(s)))throw new SecurityException("seat not owned");}private void participant(long p){if(!players.containsValue(p))throw new SecurityException("not participant");}private Integer seat(long p){return players.entrySet().stream().filter(e->e.getValue()==p).map(Map.Entry::getKey).findFirst().orElse(null);}private static boolean bool(Map<String,Object>m,String k){return Boolean.TRUE.equals(m.get(k));}private static int num(Object v){return v instanceof Number n?n.intValue():Integer.parseInt(String.valueOf(v));}private static long longNum(Object v){return v instanceof Number n?n.longValue():Long.parseLong(String.valueOf(v));}private static long id(String v){long x=Long.parseLong(v);if(x<=0)throw new IllegalArgumentException("bad player");return x;}private static List<Integer>ints(Object v){return((Collection<?>)v).stream().map(ByzpSession::num).toList();}@SuppressWarnings("unchecked")private static Map<String,Object>map(Object v){Map<String,Object>o=new LinkedHashMap<>();((Map<?,?>)v).forEach((k,x)->o.put(String.valueOf(k),x));return o;}
}
