package com.aoo.bcg.wordcard;import java.util.*;
/** Yongzhou che-hu-zi authority ported from YZCHZHuXiEnum and hutype implementations. */
final class YzchzRules{
 record Config(int playerCount,int wangCount,int piaoCap,int scoreCap,boolean genXing){Config{if(playerCount<2||playerCount>4||wangCount<0||wangCount>4||piaoCap<0||scoreCap<0)throw new IllegalArgumentException("invalid YZCHZ config");}}
 enum Meld{TI_DA(12),TI_XIAO(9),PAO_DA(9),PAO_XIAO(6),WEI_DA(6),WEI_XIAO(3),DA_2710(6),XIAO_2710(3),SHUN_DA(6),SHUN_XIAO(3),KAN_DA(6),KAN_XIAO(3),PENG_DA(3),PENG_XIAO(1),DUI(0),DA_XIAO_SAN_DA(0),SHUN(0),NOT(0);final int huXi;Meld(int x){huXi=x;}}
 enum MingTang{DIAN_HU,HONG_HU,WU_HU,SHI_BA_DA,SHI_LIU_XIAO,PENG_PENG_HU}
 private YzchzRules(){}static int type(int c){return c>1000?c/100:c;}static boolean big(int c){return type(c)>=20;}static boolean red(int c){int r=type(c)%10;return r==1||r==6||r==9;}
 static List<Integer>deck(int wang){List<Integer>d=new ArrayList<>();for(int copy=1;copy<=4;copy++){for(int t=1;t<=10;t++)d.add(t*100+copy);for(int t=20;t<=29;t++)d.add(t*100+copy);}for(int i=1;i<=wang;i++)d.add(4100+i);return List.copyOf(d);}
 static boolean legalChi(List<Integer>hand,Integer card,Set<Integer>passed){if(card==null||passed.contains(type(card)))return false;int t=type(card);Set<Integer>types=new HashSet<>();hand.forEach(c->types.add(type(c)));return types.contains(t-2)&&types.contains(t-1)||types.contains(t-1)&&types.contains(t+1)||types.contains(t+1)&&types.contains(t+2)||types.contains(t%10==2?(big(t)?27:7):-99)&&types.contains(t%10==2?(big(t)?30:10):-99);}
 static boolean canHu(int huXi,int lockedHuXi){return huXi+lockedHuXi>=15;}
 static Meld concealed(List<Integer>raw,boolean peng){List<Integer>c=raw.stream().map(YzchzRules::type).sorted().toList();if(c.size()==2)return Meld.DUI;if(c.size()==4)return big(c.getFirst())?Meld.TI_DA:Meld.TI_XIAO;if(c.size()!=3)return Meld.NOT;int a=c.get(0),b=c.get(1),d=c.get(2);if(a==b&&b==d){if(peng)return big(a)?Meld.PENG_DA:Meld.PENG_XIAO;return big(a)?Meld.KAN_DA:Meld.KAN_XIAO;}if(b-a==1&&d-b==1){if(d%10==2)return big(a)?Meld.SHUN_DA:Meld.SHUN_XIAO;return Meld.SHUN;}if(b%10==a%10)return Meld.DA_XIAO_SAN_DA;return big(a)?Meld.DA_2710:Meld.XIAO_2710;}
 static Set<MingTang>mingTang(Collection<Integer>all,boolean pengPeng){List<Integer>t=all.stream().map(YzchzRules::type).toList();long red=t.stream().filter(YzchzRules::red).count(),big=t.stream().filter(x->x>=20).count(),small=t.size()-big;Set<MingTang>m=new LinkedHashSet<>();if(red==1)m.add(MingTang.DIAN_HU);if(red>=10)m.add(MingTang.HONG_HU);if(red==0)m.add(MingTang.WU_HU);if(big>=18)m.add(MingTang.SHI_BA_DA);if(small>=16)m.add(MingTang.SHI_LIU_XIAO);if(pengPeng)m.add(MingTang.PENG_PENG_HU);return Set.copyOf(m);}
 static long settlement(int huXi,int xing,int tun,int piao,int cap,int wangPenalty){if(huXi<15)throw new IllegalArgumentException("YZCHZ requires 15 hu-xi");long value=(huXi/3L)+xing+tun+piao-wangPenalty*5L;return cap>0?Math.min(value,cap):value;}
}
