package com.aoo.bcg.poker.cd299;

import static org.junit.jupiter.api.Assertions.*;
import com.aoo.bcg.gamespi.*;
import com.aoo.bcg.poker.PokerFamilyProviderFactory;
import java.util.Map;
import java.util.ServiceLoader;
import java.util.Set;
import org.junit.jupiter.api.Test;

class Cd299ProviderFactoryTest {
 @Test void businessCodeAndPlayVersionHaveDistinctCanonicalCase(){assertEquals("CD299",Cd299Rules.GAME_CODE);assertEquals("cd299-v1.0.0",Cd299Rules.VERSION);assertTrue(Cd299Rules.VERSION.matches("^[a-z][a-z0-9._-]*$"));assertFalse(Cd299Rules.GAME_CODE.matches("^[a-z][a-z0-9._-]*$"));}
 @Test void providerPublishesStrictNonEmptyCommandBoundary(){var provider=new Cd299GameProvider(descriptor(74021,"CD299",Cd299Rules.FAMILY));var rules=provider.ruleComponents();assertEquals(1,rules.size());var rule=rules.getFirst();assertEquals("cd299.command-boundary",rule.ruleId());assertEquals(Cd299Rules.VERSION,rule.componentVersion());var commands=Set.of("poker.cd299.state_req","poker.cd299.sit_req","poker.cd299.ready_req","poker.cd299.preset_req","poker.cd299.bet_req","poker.cd299.add_card_req","poker.cd299.split_req","poker.cd299.delay_split_req","poker.cd299.continue_req","poker.cd299.timeout_req");for(String command:commands)assertTrue(rule.execute(command(command,Cd299Rules.VERSION)).accepted(),command);assertTrue(rule.execute(new GameCommandRequest("poker.CD299.dispatch","dispatch-1",1,9001,0,Cd299Rules.VERSION,"101",-1,Map.of("action","poker.cd299.state_req","payload",Map.of()))).accepted());var badCommand=rule.execute(command("poker.cd299.join_req",Cd299Rules.VERSION));assertEquals("CD299_COMMAND_NOT_ALLOWED",badCommand.code());assertTrue(badCommand.message().startsWith("[CD299]"));var badVersion=rule.execute(command("poker.cd299.state_req","CD299-v1.0.0"));assertEquals("CD299_PLAY_VERSION_MISMATCH",badVersion.code());assertTrue(badVersion.message().startsWith("[CD299]"));}
 @Test void outerDispatchIsStrictlyUnwrappedBeforeAuthoritativeExecution(){var provider=new Cd299GameProvider(descriptor(74021,"CD299",Cd299Rules.FAMILY));var room=provider.roomFactory().create(new RoomCreationContext(9001,101,Map.of()));var response=provider.commandHandler().orElseThrow().handle(room,new GameCommandRequest("poker.CD299.dispatch","dispatch-state",1,9001,0,Cd299Rules.VERSION,"101",-1,Map.of("action","poker.cd299.state_req","payload",Map.of())));assertEquals("poker.cd299.state_rsp",response.msgId());assertEquals("CD299",response.body().asMap().get("gameCode"));assertThrows(IllegalArgumentException.class,()->provider.commandHandler().orElseThrow().handle(room,new GameCommandRequest("poker.CD299.dispatch","dispatch-bad",2,9001,0,Cd299Rules.VERSION,"101",-1,Map.of("action","poker.cd299.unknown_req","payload",Map.of()))));}
 @Test void ruleRejectsProviderDescriptorIdentityInsteadOfAcceptingPlaceholder(){var wrongCode=new Cd299GameProvider(descriptor(74021,"CD201",Cd299Rules.FAMILY)).ruleComponents().getFirst().execute(command("poker.cd299.state_req",Cd299Rules.VERSION));assertEquals("CD299_IDENTITY_MISMATCH",wrongCode.code());var wrongFamily=new Cd299GameProvider(descriptor(74021,"CD299","poker:pdk")).ruleComponents().getFirst().execute(command("poker.cd299.state_req",Cd299Rules.VERSION));assertEquals("CD299_IDENTITY_MISMATCH",wrongFamily.code());var wrongProviderVersion=new Cd299GameProvider(new GameDescriptor(74021,"CD299","成都扯旋",GameCategory.POKER,Cd299Rules.FAMILY,RegionScope.CITY,"SC","CD","other-v1")).ruleComponents().getFirst().execute(command("poker.cd299.state_req",Cd299Rules.VERSION));assertEquals("CD299_PLAY_VERSION_MISMATCH",wrongProviderVersion.code());}
 @Test void restoreAndInternalReplayPreserveAuthorityForContinuedRealPlay(){var provider=new Cd299GameProvider(descriptor(74021,"CD299",Cd299Rules.FAMILY));var original=new Cd299Session(9001,101,77,Cd299Rules.from(Map.of()));original.sit(0,101,"sit-1");original.sit(1,102,"sit-2");StatePayload replayBase=StatePayload.copyOf(original.authoritativeState());original.execute(new GameCommandRequest("poker.cd299.bet_req","b0",1,9001,1,Cd299Rules.VERSION,"101",0,Map.of("action","FOLLOW","amount",3)));var takeover=provider.restoreAuthoritativeSession(original.authoritativeState()).orElseThrow();assertEquals(original.authoritativeState(),takeover.authoritativeState());var continuation=new GameCommandRequest("poker.cd299.bet_req","b1",2,9001,1,Cd299Rules.VERSION,"102",1,Map.of("action","FOLLOW","amount",3));original.execute(continuation);takeover.execute(continuation);assertEquivalentIgnoringWallClockDeadline(original.authoritativeState(),takeover.authoritativeState());assertEquivalentIgnoringWallClockDeadline(original.viewFor(101),takeover.viewFor(101));assertEquals(original.authoritativeState(),provider.eventReplayProvider().orElseThrow().replay(replayBase,original.recordedEvents()).asMap());assertTrue(original.invariantViolations().isEmpty());}
 @Test void factoryUsesCatalogProxyIdButOwnsOnlyCd299Identity(){var f=new Cd299ProviderFactory();var first=descriptor(74021,"CD299",Cd299Rules.FAMILY);var second=descriptor(981337,"CD299",Cd299Rules.FAMILY);assertEquals(74021,f.create(first).orElseThrow().descriptor().gameId());assertEquals(981337,f.create(second).orElseThrow().descriptor().gameId());assertTrue(f.create(descriptor(74021,"CD201",Cd299Rules.FAMILY)).isEmpty());assertTrue(f.create(descriptor(74021,"CD299","poker:pdk")).isEmpty());}
 @Test void createContractPublishesAndConsumesEveryWorkbookDefault(){var provider=new Cd299GameProvider(descriptor(74021,"CD299",Cd299Rules.FAMILY));var defaults=provider.defaultConfiguration();assertEquals("CD299",defaults.get("gameCode"));assertEquals(Cd299Rules.FAMILY,defaults.get("family"));assertEquals(Cd299Rules.VERSION,defaults.get("playVersion"));assertEquals(Cd299Rules.from(Map.of()).toMap().entrySet(),defaults.entrySet().stream().filter(e->Cd299Rules.from(Map.of()).toMap().containsKey(e.getKey())).collect(java.util.stream.Collectors.toSet()));var custom=new java.util.HashMap<String,Object>(Cd299Rules.from(Map.of()).toMap());custom.put("roomDurationMinutes",60);custom.put("startPlayers",6);custom.put("operationSeconds",30);custom.put("standPolicy","NOBODY");custom.put("mangoFlipMode","ROLLING");custom.put("mangoRaise",5);custom.put("mangoScore",7);custom.put("openingBet",9);custom.put("restMango",false);custom.put("beatMango",false);custom.put("everyHandMango",false);custom.put("firstRoundCanRest",false);custom.put("eachPlayerMustFollow",true);custom.put("earthNineKing",false);custom.put("fireproofCard",false);custom.put("bigHeadKeepsBase",true);var session=provider.createAuthoritativeSession(new RoomCreationContext(9901,101,custom)).orElseThrow();assertEquals(Map.copyOf(custom),session.authoritativeState().get("rules"));}
 @Test void createContractRejectsMalformedTypedValues(){assertThrows(IllegalArgumentException.class,()->Cd299Rules.from(Map.of("restMango","true")));assertThrows(IllegalArgumentException.class,()->Cd299Rules.from(Map.of("mangoRaise",3.5)));assertThrows(IllegalArgumentException.class,()->Cd299Rules.from(Map.of("standPolicy","loser_only")));}
 @Test void serviceLoaderPublishesFactoryOnly(){assertTrue(ServiceLoader.load(PokerFamilyProviderFactory.class).stream().anyMatch(p->p.type()==Cd299ProviderFactory.class));assertTrue(ServiceLoader.load(GameProvider.class).stream().noneMatch(p->p.type()==Cd299GameProvider.class));}
 @Test void spectatorSitIsAtomicAutoReadyAndReconnectStable(){var s=new Cd299Session(9001,101,7,Cd299Rules.from(Map.of()));assertEquals("SPECTATOR",s.viewFor(101).get("viewerRole"));assertTrue(((Map<?,?>)s.authoritativeState().get("players")).isEmpty());s.sit(0,101,"sit-1");assertEquals("SEATED",s.viewFor(101).get("viewerRole"));assertEquals(0,s.viewFor(101).get("viewerSeat"));assertEquals(java.util.List.of(0),s.authoritativeState().get("readySeats"));assertEquals("SPECTATOR",s.viewFor(999).get("viewerRole"));assertThrows(IllegalStateException.class,()->s.sit(0,103,"occupied"));assertThrows(IllegalStateException.class,()->s.sit(1,101,"duplicate-player"));assertThrows(IllegalArgumentException.class,()->s.sit(8,103,"illegal-seat"));s.sit(1,102,"sit-2");assertEquals(Cd299Session.Phase.BETTING,Cd299Session.Phase.valueOf((String)s.authoritativeState().get("phase")));assertTrue(s.operationDeadline().open());assertEquals(0,s.operationDeadline().seatId());assertThrows(IllegalStateException.class,()->s.timeout(0,"early-timeout"));assertThrows(IllegalArgumentException.class,()->s.presetBet(7,1,"spectator-action"));var restored=Cd299Session.restore(s.authoritativeState());assertEquals("SEATED",restored.viewFor(101).get("viewerRole"));assertEquals("SPECTATOR",restored.viewFor(999).get("viewerRole"));assertEquals(s.authoritativeState(),restored.authoritativeState());}
 @Test void canonicalSitRequiresAndPersistsCarryScore(){var s=new Cd299Session(9011,101,11,Cd299Rules.from(Map.of("startPlayers",4)));var accepted=s.execute(new GameCommandRequest("poker.cd299.sit_req","sit-carry",1,9011,0,Cd299Rules.VERSION,"101",-1,Map.of("seatId",0,"carryScore",1200)));assertEquals(1200L,((Map<?,?>)accepted.body().asMap().get("carryScores")).get(0));assertEquals(1200L,((Map<?,?>)accepted.body().asMap().get("scores")).get(0));assertEquals(s.authoritativeState(),Cd299Session.restore(s.authoritativeState()).authoritativeState());assertThrows(IllegalArgumentException.class,()->new Cd299Session(9012,101,12,Cd299Rules.from(Map.of())).execute(new GameCommandRequest("poker.cd299.sit_req","missing-carry",1,9012,0,Cd299Rules.VERSION,"101",-1,Map.of("seatId",0))));assertThrows(IllegalArgumentException.class,()->new Cd299Session(9013,101,13,Cd299Rules.from(Map.of())).execute(new GameCommandRequest("poker.cd299.sit_req","negative-carry",1,9013,0,Cd299Rules.VERSION,"101",-1,Map.of("seatId",0,"carryScore",-1))));}
 @Test void concurrentSpectatorsCannotWinTheSameSeatTwice()throws Exception{var s=new Cd299Session(9010,101,9,Cd299Rules.from(Map.of()));var gate=new java.util.concurrent.CountDownLatch(1);var pool=java.util.concurrent.Executors.newFixedThreadPool(2);try{var attempts=java.util.List.of(java.util.concurrent.CompletableFuture.supplyAsync(()->sitAttempt(s,2,201,"race-a",gate),pool),java.util.concurrent.CompletableFuture.supplyAsync(()->sitAttempt(s,2,202,"race-b",gate),pool));gate.countDown();var results=attempts.stream().map(java.util.concurrent.CompletableFuture::join).toList();assertEquals(1,results.stream().filter("OK"::equals).count());assertEquals(1,results.stream().filter(v->v.contains("CD299_SEAT_OCCUPIED")).count());assertEquals(1,((Map<?,?>)s.authoritativeState().get("players")).size());}finally{pool.shutdownNow();}}
 @Test void realPlayerLifecycleAndPrivateReconnect(){var s=new Cd299Session(9001,101,7,Cd299Rules.from(Map.of()));s.sit(0,101,"sit-1");s.sit(1,102,"sit-2");assertEquals(Cd299Session.Phase.BETTING,Cd299Session.Phase.valueOf((String)s.authoritativeState().get("phase")));assertEquals(2,((java.util.List<?>)((Map<?,?>)s.viewFor(101).get("hands")).get(1)).size());assertEquals(0,((java.util.List<?>)((Map<?,?>)s.viewFor(101).get("hands")).get(1)).get(0));assertTrue(s.invariantViolations().isEmpty());}
 private static GameDescriptor descriptor(int gameId,String code,String family){return new GameDescriptor(gameId,code,"成都扯旋",GameCategory.POKER,family,RegionScope.CITY,"SC","CD",Cd299Rules.VERSION);}
 private static GameCommandRequest command(String msgId,String version){return new GameCommandRequest(msgId,"rule-test",1,9001,0,version,"101",0,Map.of());}
 private static String sitAttempt(Cd299Session s,int seat,long player,String op,java.util.concurrent.CountDownLatch gate){try{gate.await();s.sit(seat,player,op);return"OK";}catch(InterruptedException e){Thread.currentThread().interrupt();return"INTERRUPTED";}catch(IllegalStateException e){return e.getMessage();}}
 private static void assertEquivalentIgnoringWallClockDeadline(Map<String,Object>left,Map<String,Object>right){var a=new java.util.LinkedHashMap<>(left);var b=new java.util.LinkedHashMap<>(right);a.remove("operationDeadline");b.remove("operationDeadline");assertEquals(a,b);assertEquals(((Map<?,?>)left.get("operationDeadline")).get("operationId"),((Map<?,?>)right.get("operationDeadline")).get("operationId"));}
}
