package com.aoo.bcg.share;
import javax.sql.DataSource;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.sql.*;import java.time.*;import java.util.*;
/** JDBC authority for signed invite links and authenticated idempotent consumption. */
public final class JdbcInviteLinkRepository{
 private final DataSource source;private final Clock clock;public JdbcInviteLinkRepository(DataSource s,Clock c){source=Objects.requireNonNull(s);clock=Objects.requireNonNull(c);}
 public Map<String,Object>create(long issuer,String kind,long target,Duration ttl,int max,String token,String channel){if(issuer<=0||target<=0||!Set.of("ROOM","CLUB").contains(kind))throw bad("invalid invite target");if(ttl.isZero()||ttl.isNegative()||ttl.compareTo(Duration.ofDays(30))>0||max<1||max>10000)throw bad("invalid invite limits");try(Connection c=source.getConnection()){c.setAutoCommit(false);try{authority(c,issuer,kind,target);Timestamp expires=Timestamp.from(clock.instant().plus(ttl));try(PreparedStatement q=c.prepareStatement("INSERT INTO aoo_invite_link(token_hash,kind,target_id,issuer_account_id,max_uses,use_count,expires_at,status,created_at) VALUES(?,?,?,?,?,0,?,'ACTIVE',CURRENT_TIMESTAMP(3))",Statement.RETURN_GENERATED_KEYS)){q.setBytes(1,hash(code(token)));q.setString(2,kind);q.setLong(3,target);q.setLong(4,issuer);q.setInt(5,max);q.setTimestamp(6,expires);q.executeUpdate();try(ResultSet r=q.getGeneratedKeys()){r.next();long id=r.getLong(1);audit(c,id,"CREATED",issuer,channel,"SUCCESS");c.commit();return Map.of("inviteId",id,"token",token,"kind",kind,"targetId",target,"expiresAt",expires.toInstant().toString(),"maxUses",max);}}}catch(Exception e){c.rollback();throw e;}}catch(InviteLinkError e){throw e;}catch(Exception e){throw storage();}}
 /** Preview does not spend a use; only an authenticated consume can do that. */
 public Map<String,Object>preview(String code,String channel,String address,String referrer){try(Connection c=source.getConnection()){Link l=link(c,code,false);available(l);Map<String,Object> out=target(c,l);audit(c,l.id,"PREVIEWED",null,channel,"SUCCESS");return out;}catch(InviteLinkError e){throw e;}catch(Exception e){throw storage();}}
 public Consumption consume(String code,long consumer,String key,String channel){if(consumer<=0)throw unauthorized();if(key==null||!key.matches("[A-Za-z0-9_.:-]{8,128}"))throw bad("valid Idempotency-Key required");try(Connection c=source.getConnection()){c.setAutoCommit(false);try{Link l=link(c,code,true);Consumption old=byKey(c,key);if(old!=null){if(old.inviteId!=l.id||old.consumerId!=consumer)throw new InviteLinkError(409,"INVITE_IDEMPOTENCY_CONFLICT","idempotency key conflict");c.commit();return old;}old=byConsumer(c,l.id,consumer);if(old!=null){c.commit();return old;}available(l);if(l.issuer==consumer)throw new InviteLinkError(409,"INVITE_SELF_CONSUME","issuer cannot consume own invite");Map<String,Object> t=target(c,l);try(PreparedStatement q=c.prepareStatement("INSERT INTO aoo_invite_consumption(idempotency_key,invite_id,consumer_account_id,reward_state,created_at,updated_at) VALUES(?,?,?,'PENDING',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3))",Statement.RETURN_GENERATED_KEYS)){q.setString(1,key);q.setLong(2,l.id);q.setLong(3,consumer);q.executeUpdate();try(ResultSet r=q.getGeneratedKeys()){r.next();long id=r.getLong(1);try(PreparedStatement u=c.prepareStatement("UPDATE aoo_invite_link SET use_count=use_count+1,status=CASE WHEN use_count+1>=max_uses THEN 'EXHAUSTED' ELSE status END,last_used_at=CURRENT_TIMESTAMP(3) WHERE invite_id=?")){u.setLong(1,l.id);u.executeUpdate();}audit(c,l.id,"CONSUMED",consumer,channel,"SUCCESS");c.commit();return new Consumption(id,l.id,l.issuer,consumer,l.kind,l.target,key,"PENDING",t);}}}catch(Exception e){c.rollback();throw e;}}catch(InviteLinkError e){throw e;}catch(Exception e){throw storage();}}
 public Consumption rewarded(long id,String reference){try(Connection c=source.getConnection()){try(PreparedStatement q=c.prepareStatement("UPDATE aoo_invite_consumption SET reward_state='GRANTED',reward_reference=?,updated_at=CURRENT_TIMESTAMP(3) WHERE consumption_id=? AND reward_state='PENDING'")){q.setString(1,reference);q.setLong(2,id);q.executeUpdate();}return consumption(c,id);}catch(Exception e){throw storage();}}
 public void revoke(long issuer,long id,String channel){try(Connection c=source.getConnection()){c.setAutoCommit(false);try(PreparedStatement q=c.prepareStatement("UPDATE aoo_invite_link SET status='REVOKED',revoked_at=CURRENT_TIMESTAMP(3) WHERE invite_id=? AND issuer_account_id=? AND status IN ('ACTIVE','EXHAUSTED')")){q.setLong(1,id);q.setLong(2,issuer);if(q.executeUpdate()!=1)throw unavailable();audit(c,id,"REVOKED",issuer,channel,"SUCCESS");c.commit();}}catch(InviteLinkError e){throw e;}catch(Exception e){throw storage();}}
 private Link link(Connection c,String code,boolean lock)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT invite_id,kind,target_id,issuer_account_id,max_uses,use_count,expires_at,status FROM aoo_invite_link WHERE token_hash=?"+(lock?" FOR UPDATE":""))){q.setBytes(1,hash(code));try(ResultSet r=q.executeQuery()){if(!r.next())throw unavailable();return new Link(r.getLong(1),r.getString(2),r.getLong(3),r.getLong(4),r.getInt(5),r.getInt(6),r.getTimestamp(7),r.getString(8));}}}
 private Consumption byKey(Connection c,String key)throws SQLException{return lookup(c,"x.idempotency_key=?",key);}private Consumption byConsumer(Connection c,long invite,long consumer)throws SQLException{return lookup(c,"x.invite_id=? AND x.consumer_account_id=?",null,invite,consumer);}
 private Consumption lookup(Connection c,String where,String text,long...nums)throws SQLException{String sql="SELECT x.consumption_id,x.invite_id,l.issuer_account_id,x.consumer_account_id,l.kind,l.target_id,x.idempotency_key,x.reward_state FROM aoo_invite_consumption x JOIN aoo_invite_link l ON l.invite_id=x.invite_id WHERE "+where;try(PreparedStatement q=c.prepareStatement(sql)){int i=1;if(text!=null)q.setString(i++,text);for(long n:nums)q.setLong(i++,n);try(ResultSet r=q.executeQuery()){return r.next()?row(c,r):null;}}}private Consumption consumption(Connection c,long id)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT x.consumption_id,x.invite_id,l.issuer_account_id,x.consumer_account_id,l.kind,l.target_id,x.idempotency_key,x.reward_state FROM aoo_invite_consumption x JOIN aoo_invite_link l ON l.invite_id=x.invite_id WHERE x.consumption_id=?")){q.setLong(1,id);try(ResultSet r=q.executeQuery()){if(!r.next())throw unavailable();return row(c,r);}}}private Consumption row(Connection c,ResultSet r)throws SQLException{Link l=new Link(r.getLong(2),r.getString(5),r.getLong(6),r.getLong(3),0,0,new Timestamp(0),"");return new Consumption(r.getLong(1),r.getLong(2),r.getLong(3),r.getLong(4),r.getString(5),r.getLong(6),r.getString(7),r.getString(8),target(c,l));}
 private void available(Link l){if(!"ACTIVE".equals(l.status)||!l.expires.toInstant().isAfter(clock.instant())||l.uses>=l.max)throw unavailable();}private void authority(Connection c,long issuer,String kind,long target)throws SQLException{String s="ROOM".equals(kind)?"SELECT 1 FROM aoo_hall_room WHERE room_id=? AND owner_account_id=? AND state='OPEN'":"SELECT 1 FROM aoo_club_state WHERE club_id=?";try(PreparedStatement q=c.prepareStatement(s)){q.setLong(1,target);if("ROOM".equals(kind))q.setLong(2,issuer);try(ResultSet r=q.executeQuery()){if(!r.next())throw new InviteLinkError(404,"INVITE_TARGET_NOT_FOUND","invite target unavailable");}}}
 private Map<String,Object>target(Connection c,Link l)throws SQLException{if("ROOM".equals(l.kind)){try(PreparedStatement q=c.prepareStatement("SELECT game_id,play_version,state FROM aoo_hall_room WHERE room_id=?")){q.setLong(1,l.target);try(ResultSet r=q.executeQuery()){if(!r.next()||!"OPEN".equals(r.getString(3)))throw unavailable();return Map.of("kind","ROOM","targetId",l.target,"gameId",r.getLong(1),"playVersion",r.getString(2),"state","OPEN");}}}try(PreparedStatement q=c.prepareStatement("SELECT 1 FROM aoo_club_state WHERE club_id=?")){q.setLong(1,l.target);try(ResultSet r=q.executeQuery()){if(!r.next())throw unavailable();return Map.of("kind","CLUB","targetId",l.target);}}}
 private void audit(Connection c,long id,String type,Long actor,String channel,String outcome)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT INTO aoo_invite_link_audit(invite_id,event_type,actor_account_id,source_channel,outcome,occurred_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP(3))")){q.setLong(1,id);q.setString(2,type);if(actor==null)q.setNull(3,Types.BIGINT);else q.setLong(3,actor);q.setString(4,channel==null?"direct":channel.substring(0,Math.min(64,channel.length())));q.setString(5,outcome);q.executeUpdate();}}
 private static String code(String t){return t.substring(0,t.indexOf('.'));}private static byte[]hash(String s){try{return MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.US_ASCII));}catch(Exception e){throw new IllegalStateException(e);}}private static InviteLinkError bad(String m){return new InviteLinkError(400,"INVITE_INVALID_REQUEST",m);}private static InviteLinkError unavailable(){return new InviteLinkError(404,"INVITE_NOT_FOUND","invite link is unavailable");}private static InviteLinkError unauthorized(){return new InviteLinkError(401,"INVITE_UNAUTHORIZED","valid account bearer assertion required");}private static InviteLinkError storage(){return new InviteLinkError(503,"INVITE_STORAGE_UNAVAILABLE","invite storage is unavailable");}
 private record Link(long id,String kind,long target,long issuer,int max,int uses,Timestamp expires,String status){}public record Consumption(long consumptionId,long inviteId,long issuerId,long consumerId,String kind,long targetId,String idempotencyKey,String rewardState,Map<String,Object>target){}
}
