package com.aoo.bcg.hall.room;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import java.net.URI;import java.net.http.*;import java.time.Duration;import java.util.*;
public final class HttpRoomAuthorityPort implements RoomCreateSaga.AuthorityPort,RoomMembershipAuthorityPort{
 private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(3)).build();private final URI base;private final String token;private final ObjectMapper json;
 public HttpRoomAuthorityPort(URI base,String token,ObjectMapper json){this.base=base;this.token=token;this.json=json;}
 public Map<String,Object>create(RoomCreateSaga.Command c){return call("create",body(c,c.stateVersion()));}public Map<String,Object>recover(RoomCreateSaga.Command c){return call("recover",body(c,c.stateVersion()));}public void remove(RoomCreateSaga.Command c,long fence){call("remove",body(c,fence));}
 @Override public Map<String,Object>join(long roomId,long accountId,int seatNo,String playVersion,String requestId,String traceId,Map<String,Object>admission){Map<String,Object>b=new LinkedHashMap<>();b.put("roomId",roomId);b.put("accountId",accountId);b.put("seatNo",seatNo);b.put("playVersion",playVersion);b.put("requestId",requestId);b.put("traceId",traceId);b.put("admission",Map.copyOf(admission));return call("join",b);}
 private static Map<String,Object>body(RoomCreateSaga.Command c,long fence){Map<String,Object>b=new LinkedHashMap<>();b.put("roomId",c.roomId());b.put("requestId",c.requestId());b.put("traceId",c.traceId());b.put("ownerId",c.accountId());b.put("gameId",c.gameId());b.put("playVersion",c.playVersion());b.put("fencingToken",fence);b.put("rules",c.rules());b.put("scope",c.scope().asMap());b.put("admission",c.admission());return b;}
 private Map<String,Object>call(String action,Map<String,Object>b){RuntimeException last=null;for(int attempt=0;attempt<3;attempt++){try{var q=HttpRequest.newBuilder(base.resolve("/internal/v1/room-authority/"+action)).timeout(Duration.ofSeconds(8)).header("Content-Type","application/json").header("X-Aoo-Internal-Token",token).header("X-Trace-Id",String.valueOf(b.getOrDefault("traceId","authority"))).POST(HttpRequest.BodyPublishers.ofByteArray(json.writeValueAsBytes(b))).build();var r=http.send(q,HttpResponse.BodyHandlers.ofByteArray());if(r.statusCode()/100==2){Map<String,Object>envelope=json.readValue(r.body(),new TypeReference<>(){});Object data=envelope.get("data");if(data instanceof Map<?,?>map){@SuppressWarnings("unchecked")Map<String,Object>result=(Map<String,Object>)map;return Map.copyOf(result);}return Map.of();}if(r.statusCode()<500)throw new IllegalStateException("room authority rejected request: "+r.statusCode());last=new IllegalStateException("room authority temporarily unavailable: "+r.statusCode());}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("room authority call interrupted",e);}catch(Exception e){last=e instanceof RuntimeException r?r:new IllegalStateException("room authority unavailable",e);}if(attempt<2)try{Thread.sleep(100L<<attempt);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}}throw last==null?new IllegalStateException("room authority unavailable"):last;}
}
