package com.aoo.bcg.hall.room;

import com.aoo.bcg.hall.http.HallError;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import javax.sql.DataSource;
import java.security.SecureRandom;
import java.sql.*;
import java.time.Clock;
import java.util.*;

/** Transactional production repository for the Hall catalog and room lifecycle. */
public final class JdbcHallRepository {
    static final String FILTER_ACTIVE_INDEX_JOIN="JOIN aoo_compiled_index_active ai ON ai.game_id=gr.game_id";
    static final String CATALOG_ACTIVE_INDEX_JOIN="JOIN aoo_compiled_index_active a ON a.game_id=g.game_id";
    private final DataSource dataSource;private final ObjectMapper json;private final Clock clock;private final RoomMembershipAuthorityPort membershipAuthority;private final SecureRandom random=new SecureRandom();
    public JdbcHallRepository(DataSource dataSource,ObjectMapper json,Clock clock,RoomMembershipAuthorityPort membershipAuthority){this.dataSource=Objects.requireNonNull(dataSource);this.json=Objects.requireNonNull(json);this.clock=Objects.requireNonNull(clock);this.membershipAuthority=Objects.requireNonNull(membershipAuthority);}

    public List<Map<String,Object>> playFilters(String clientVersion){
        require(clientVersion,"clientVersion");
        String sql="SELECT DISTINCT r.region_code,r.parent_region_code,r.region_type,r.display_name,r.path,r.depth FROM aoo_region r WHERE r.status='ACTIVE' AND (EXISTS(SELECT 1 FROM aoo_game_region gr JOIN aoo_game_catalog g ON g.game_id=gr.game_id "+FILTER_ACTIVE_INDEX_JOIN+" JOIN aoo_play_version p ON p.game_id=ai.game_id AND p.play_version=ai.play_version WHERE gr.region_code=r.region_code AND gr.availability='AVAILABLE' AND g.status='ACTIVE' AND p.status='ACTIVE' AND EXISTS(SELECT 1 FROM aoo_game_service_route sr WHERE sr.game_id=g.game_id AND sr.play_version=p.play_version AND sr.status='ACTIVE')) OR EXISTS(SELECT 1 FROM aoo_region child JOIN aoo_game_region gr ON gr.region_code=child.region_code JOIN aoo_game_catalog g ON g.game_id=gr.game_id "+FILTER_ACTIVE_INDEX_JOIN+" JOIN aoo_play_version p ON p.game_id=ai.game_id AND p.play_version=ai.play_version WHERE child.path LIKE CONCAT(r.path,'/%') AND gr.availability='AVAILABLE' AND g.status='ACTIVE' AND p.status='ACTIVE' AND EXISTS(SELECT 1 FROM aoo_game_service_route sr WHERE sr.game_id=g.game_id AND sr.play_version=p.play_version AND sr.status='ACTIVE'))) ORDER BY r.depth,r.path";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<Map<String,Object>> out=new ArrayList<>();out.add(Map.of("regionCode","ALL","regionType","ALL","displayName","全部玩法","depth",0));while(r.next())out.add(row(r,"region_code","parent_region_code","region_type","display_name","path","depth"));return out;}catch(SQLException e){throw storage(e);}
    }
    public List<Map<String,Object>> catalog(String region,String clientVersion){
        require(region,"regionCode");require(clientVersion,"clientVersion");
        String sql="SELECT DISTINCT g.game_id,g.game_code,g.display_name,g.category_code,g.family_code,a.play_version,p.compatibility_floor,a.release_id,a.index_generation,a.cache_epoch,gr.region_code classification_region_code,r.display_name classification_name,r.region_type,r.parent_region_code,parent.display_name parent_region_name FROM aoo_game_catalog g JOIN aoo_game_region gr ON gr.game_id=g.game_id JOIN aoo_region r ON r.region_code=gr.region_code LEFT JOIN aoo_region parent ON parent.region_code=r.parent_region_code "+CATALOG_ACTIVE_INDEX_JOIN+" JOIN aoo_play_version p ON p.game_id=a.game_id AND p.play_version=a.play_version WHERE (?='ALL' OR gr.region_code='GLOBAL' OR gr.region_code=? OR EXISTS(SELECT 1 FROM aoo_region filter_region WHERE filter_region.region_code=? AND (r.path=filter_region.path OR r.path LIKE CONCAT(filter_region.path,'/%')))) AND g.status='ACTIVE' AND gr.availability='AVAILABLE' AND p.status='ACTIVE' AND EXISTS(SELECT 1 FROM aoo_game_service_route sr WHERE sr.game_id=g.game_id AND sr.play_version=a.play_version AND sr.status='ACTIVE') ORDER BY CASE WHEN gr.region_code='GLOBAL' THEN 0 ELSE 1 END,r.depth DESC,gr.priority,g.game_id";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setString(1,region);s.setString(2,region);s.setString(3,region);try(ResultSet r=s.executeQuery()){Map<Long,Map<String,Object>> unique=new LinkedHashMap<>();while(r.next()){String floor=r.getString("compatibility_floor");if(compatible(clientVersion,floor))unique.putIfAbsent(r.getLong("game_id"),row(r,"game_id","game_code","display_name","category_code","family_code","play_version","release_id","index_generation","cache_epoch","classification_region_code","classification_name","region_type","parent_region_code","parent_region_name"));}return List.copyOf(unique.values());}}catch(SQLException e){throw storage(e);}
    }
    public Map<String,Object> configuration(long gameId,String playVersion,String clientVersion){
        require(playVersion,"playVersion");require(clientVersion,"clientVersion");String region=activeRegion(gameId,playVersion);
        String sql="SELECT i.release_id,i.index_generation,i.component_chain,i.rule_validator,i.ui_schema,i.bundle_hash,a.cache_epoch,p.compatibility_floor,g.family_code FROM aoo_compiled_index_active a JOIN aoo_compiled_room_create_index i ON i.game_id=a.game_id AND i.region_code=a.region_code AND i.play_version=a.play_version AND i.index_generation=a.index_generation JOIN aoo_play_version p ON p.game_id=i.game_id AND p.play_version=i.play_version JOIN aoo_game_catalog g ON g.game_id=i.game_id WHERE a.game_id=? AND a.region_code=? AND a.play_version=? AND i.lifecycle_state='ACTIVE'";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,gameId);s.setString(2,region);s.setString(3,playVersion);try(ResultSet r=s.executeQuery()){if(!r.next())throw HallError.notFound("active game configuration not found");requireCompatible(clientVersion,r.getString("compatibility_floor"));Map<String,Object> out=row(r,"release_id","index_generation","bundle_hash","cache_epoch");out.put("gameId",gameId);out.put("classificationRegionCode",region);out.put("playVersion",playVersion);out.put("components",document(r.getString("component_chain")));out.put("rules",document(r.getString("rule_validator")));out.put("ui",settlementUi(r.getString("family_code"),document(r.getString("ui_schema"))));return out;}}catch(SQLException e){throw storage(e);}
    }
public Map<String,Object> activeRoom(long account){
    String sql="SELECT r.room_id,r.game_id,r.classification_region_code,r.play_version,r.state,r.route_endpoint,r.scope_type,r.club_id,a.lifecycle_state,s.state_payload FROM aoo_hall_room r JOIN aoo_hall_room_member m ON m.room_id=r.room_id JOIN aoo_room_authority_route a ON a.room_id=r.room_id LEFT JOIN aoo_room_snapshot s ON s.room_id=r.room_id WHERE m.account_id=? AND m.status='JOINED' AND r.state IN('OPEN','PLAYING') ORDER BY r.updated_at DESC,r.room_id DESC";
    try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,account);try(ResultSet r=s.executeQuery()){while(r.next()){Map<String,Object> snapshot=r.getString("state_payload")==null?Map.of():json.readValue(r.getString("state_payload"),new TypeReference<>(){});if(!ActiveRoomRecoveryPolicy.isRecoverable(r.getString("state"),r.getString("lifecycle_state"),snapshot))continue;long room=r.getLong("room_id");Map<String,Object> out=new LinkedHashMap<>();out.put("active",true);out.put("roomId",room);out.put("gameId",r.getLong("game_id"));out.put("classificationRegionCode",r.getString("classification_region_code"));out.put("playVersion",r.getString("play_version"));out.put("state",r.getString("state"));out.put("route",r.getString("route_endpoint"));out.put("scopeType",r.getString("scope_type"));out.put("rules",roomRules(c,room));long club=r.getLong("club_id");if(club>0)out.put("clubId",club);out.putAll(resourceRoute(c,room));return Map.copyOf(out);}return Map.of("active",false);}}catch(SQLException e){throw storage(e);}catch(RuntimeException e){throw e;}catch(Exception e){throw storage(e);}
}
public void registerRoom(RoomCreateSaga.Command command){
    transaction(c->{enforceUniqueRoomMembership(c,command.accountId(),command.roomId());return Boolean.TRUE;});
    transaction(c->{long game=command.gameId(),room=command.roomId();String play=command.playVersion(),region=activeRegion(game,play);authorizeCreateScope(c,command);Index index=lockIndex(c,game,region,play);requireCompatible(command.clientVersion(),index.compatibilityFloor());Map<String,Object> validatedRules=validateRules(c,game,region,play,command.rules());String route=route(c,game,play);try(PreparedStatement s=c.prepareStatement("INSERT INTO aoo_hall_room(room_id,game_id,classification_region_code,play_version,release_id,index_generation,owner_account_id,scope_type,club_id,club_template_code,state,route_endpoint,rules_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'CREATING',?,?,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3))")){int i=1;s.setLong(i++,room);s.setLong(i++,game);s.setString(i++,region);s.setString(i++,play);s.setLong(i++,index.releaseId());s.setLong(i++,index.generation());s.setLong(i++,command.accountId());s.setString(i++,command.scope().type());if(command.scope().club())s.setLong(i++,command.scope().clubId());else s.setNull(i++,Types.BIGINT);if(command.scope().club())s.setString(i++,command.scope().templateCode());else s.setNull(i++,Types.VARCHAR);s.setString(i++,route);s.setString(i,json.writeValueAsString(validatedRules));s.executeUpdate();}try(PreparedStatement s=c.prepareStatement("INSERT INTO aoo_hall_room_member(room_id,account_id,seat_no,status,joined_at) VALUES(?,?,0,'JOINED',CURRENT_TIMESTAMP(3))")){s.setLong(1,room);s.setLong(2,command.accountId());s.executeUpdate();}return Boolean.TRUE;});
}
public Map<String,Object> confirmRoom(long account,long room){return transaction(c->{Room value=lockRoom(c,room);if(value.state().equals("CREATING") == false)throw HallError.conflict("HALL_ROOM_STATE_CONFLICT","room is not awaiting authority confirmation");try(PreparedStatement s=c.prepareStatement("UPDATE aoo_hall_room SET state='OPEN',updated_at=CURRENT_TIMESTAMP(3) WHERE room_id=? AND state='CREATING'")){s.setLong(1,room);if(s.executeUpdate()!=1)throw HallError.conflict("HALL_ROOM_STATE_CONFLICT","room confirmation lost its state transition");}if(value.clubId()>0)projectClubRoom(c,value,room,"OPEN");member(c,room,account);Map<String,Object> out=new LinkedHashMap<>(Map.of("roomId",room,"gameId",value.gameId(),"playVersion",value.playVersion(),"classificationRegionCode",value.region(),"route",value.route(),"state","OPEN","scopeType",value.scopeType()));out.putAll(resourceRoute(c,room));if(value.clubId()>0)out.put("clubId",value.clubId());return Map.copyOf(out);});}
public long allocateRoomId(long account,String requestId){
    requireKey(requestId);
    return transaction(c->{
        try(PreparedStatement existing=c.prepareStatement("SELECT account_id,room_id FROM aoo_room_idempotent_allocation WHERE request_id=? FOR UPDATE")){
            existing.setString(1,requestId);
            try(ResultSet r=existing.executeQuery()){
                if(r.next()){
                    if(r.getLong(1)!=account)throw HallError.conflict("HALL_REQUEST_ID_CONFLICT","requestId belongs to another account");
                    return r.getLong(2);
                }
            }
        }
        // 房间号属于对外展示标识，不能用账号/时间推导；数据库唯一键负责并发兜底，
        // 这里只对唯一冲突重试，避免把冲突误当成成功或覆盖已有房间。
        for(int attempt=0;attempt<16;attempt++){
            long candidate=100_000L+random.nextInt(900_000);
            try(PreparedStatement insert=c.prepareStatement("INSERT INTO aoo_room_idempotent_allocation(request_id,account_id,room_id,created_at) VALUES(?,?,?,CURRENT_TIMESTAMP(3))")){
                insert.setString(1,requestId);insert.setLong(2,account);insert.setLong(3,candidate);insert.executeUpdate();
                return candidate;
            }catch(SQLIntegrityConstraintViolationException conflict){
                // 并发请求只会在 room_id 或 request_id 唯一键上冲突；下一轮生成新候选。
            }
        }
        throw new IllegalStateException("六位房间号分配冲突次数超限");
    });
}
public void compensateCreate(long account,String key,long room){transaction(c->{Room value=room(c,room,false);try(PreparedStatement q=c.prepareStatement("SELECT owner_account_id FROM aoo_hall_room WHERE room_id=? FOR UPDATE")){q.setLong(1,room);try(ResultSet r=q.executeQuery()){if(!r.next())return Boolean.TRUE;if(r.getLong(1)!=account)throw new HallError(403,"HALL_FORBIDDEN","only the room owner can compensate creation");}}try(PreparedStatement t=c.prepareStatement("DELETE FROM aoo_hall_game_ticket WHERE room_id=?")){t.setLong(1,room);t.executeUpdate();}try(PreparedStatement m=c.prepareStatement("UPDATE aoo_hall_room_member SET status='LEFT',left_at=COALESCE(left_at,CURRENT_TIMESTAMP(3)) WHERE room_id=? AND status='JOINED'")){m.setLong(1,room);m.executeUpdate();}try(PreparedStatement r=c.prepareStatement("UPDATE aoo_hall_room SET state='DISSOLVED',updated_at=CURRENT_TIMESTAMP(3) WHERE room_id=? AND state<>'DISSOLVED'")){r.setLong(1,room);r.executeUpdate();}if(value.clubId()>0)projectClubRoom(c,value,room,"DISSOLVED");return Boolean.TRUE;});}
public Map<String,Object> closeRoom(long room,String key,String reason,String traceId){requireKey(key);return transaction(c->{Room value=lockRoom(c,room);if(!"DISSOLVED".equals(value.state())){try(PreparedStatement t=c.prepareStatement("DELETE FROM aoo_hall_game_ticket WHERE room_id=?")){t.setLong(1,room);t.executeUpdate();}try(PreparedStatement m=c.prepareStatement("UPDATE aoo_hall_room_member SET status='LEFT',left_at=COALESCE(left_at,CURRENT_TIMESTAMP(3)) WHERE room_id=? AND status IN('JOINING','JOINED')")){m.setLong(1,room);m.executeUpdate();}try(PreparedStatement r=c.prepareStatement("UPDATE aoo_hall_room SET state='DISSOLVED',updated_at=CURRENT_TIMESTAMP(3) WHERE room_id=? AND state<>'DISSOLVED'")){r.setLong(1,room);r.executeUpdate();}if(value.clubId()>0)projectClubRoom(c,value,room,"DISSOLVED");}return Map.of("roomId",room,"state","DISSOLVED","requestId",key,"reason",reason==null?"AUTHORITY_REMOVED":reason,"traceId",traceId);});}
public Map<String,Object> authorityLeave(long account,String key,long room,String traceId){requireKey(key);require(traceId,"traceId");return transaction(c->{Map<String,Object> prior=idempotent(c,account,key,"LEAVE");if(prior!=null)return prior;lockRoom(c,room);String status;try(PreparedStatement q=c.prepareStatement("SELECT status FROM aoo_hall_room_member WHERE room_id=? AND account_id=? FOR UPDATE")){q.setLong(1,room);q.setLong(2,account);try(ResultSet r=q.executeQuery()){if(!r.next())throw new HallError(403,"HALL_ROOM_ACCESS_DENIED","room membership required");status=r.getString(1);}}if(!"LEFT".equals(status)){try(PreparedStatement s=c.prepareStatement("UPDATE aoo_hall_room_member SET status='LEFT',left_at=COALESCE(left_at,CURRENT_TIMESTAMP(3)) WHERE room_id=? AND account_id=? AND status IN('JOINING','JOINED')")){s.setLong(1,room);s.setLong(2,account);if(s.executeUpdate()!=1)throw HallError.conflict("HALL_MEMBER_STATE_CONFLICT","member cannot leave from current state");}}try(PreparedStatement t=c.prepareStatement("DELETE FROM aoo_hall_game_ticket WHERE room_id=? AND account_id=?")){t.setLong(1,room);t.setLong(2,account);t.executeUpdate();}Map<String,Object> result=Map.of("roomId",room,"accountId",account,"status","LEFT","traceId",traceId);saveIdempotent(c,account,key,"LEAVE",result);return result;});}
    public Map<String,Object> join(long account,String key,long room,String traceId){return join(account,key,room,traceId,Map.of());}
    public Map<String,Object> join(long account,String key,long room,String traceId,Map<String,Object>admission){
        admission=Map.copyOf(Objects.requireNonNull(admission));
        requireKey(key);require(traceId,"traceId");
        Map<String,Object> prior=transaction(c->idempotent(c,account,key,"JOIN"));
        if(prior!=null)return prior;
        JoinReservation reservation=transaction(c->{
            Room value=lockRoom(c,room);
            if(!"OPEN".equals(value.state()))throw HallError.conflict("HALL_ROOM_ENDED","room is no longer joinable");
            authorizeJoinScope(c,value,account);
            enforceUniqueRoomMembership(c,account,room);
            int seat;
            boolean alreadyJoined=false;
            try(PreparedStatement existing=c.prepareStatement("SELECT seat_no FROM aoo_hall_room_member WHERE room_id=? AND account_id=? AND status IN('JOINING','JOINED') FOR UPDATE")){
                existing.setLong(1,room);existing.setLong(2,account);
                try(ResultSet found=existing.executeQuery()){
                    if(found.next()){seat=found.getInt(1);alreadyJoined=membershipStatus(c,room,account).equals("JOINED");}
                    else{
                        try(PreparedStatement q=c.prepareStatement("SELECT COALESCE(MAX(seat_no),-1)+1 FROM aoo_hall_room_member WHERE room_id=? AND status IN('JOINING','JOINED') FOR UPDATE")){
                            q.setLong(1,room);
                            try(ResultSet r=q.executeQuery()){r.next();seat=r.getInt(1);}
                        }
                    }
                }
            }
            try(PreparedStatement s=c.prepareStatement("INSERT INTO aoo_hall_room_member(room_id,account_id,seat_no,status,joined_at) VALUES(?,?,?,'JOINING',CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE seat_no=VALUES(seat_no),status=IF(status='JOINED','JOINED','JOINING'),joined_at=CURRENT_TIMESTAMP(3),left_at=NULL")){
                s.setLong(1,room);s.setLong(2,account);s.setInt(3,seat);s.executeUpdate();
            }
            return new JoinReservation(seat,value.playVersion(),value.state(),value.route(),alreadyJoined);
        });
        Map<String,Object> authority;
        try{authority=membershipAuthority.join(room,account,reservation.seat(),reservation.playVersion(),key,traceId,admission);}
        catch(RoomAuthorityRejected rejected){releaseFailedJoin(account,room,reservation.alreadyJoined());if("ROOM_ENDED".equals(rejected.code())){closeStaleRoom(room);throw HallError.conflict("HALL_ROOM_ENDED","room is no longer joinable");}if("ROOM_FULL".equals(rejected.code()))throw HallError.conflict("HALL_ROOM_FULL","房间人数已满");if("ROOM_JOIN_REJECTED".equals(rejected.code()))throw HallError.conflict("HALL_ROOM_JOIN_REJECTED","不满足该房间的加入条件");throw new HallError(rejected.status(),"HALL_AUTHORITY_REJECTED","room authority rejected membership");}
        catch(RuntimeException failure){releaseFailedJoin(account,room,reservation.alreadyJoined());throw failure;}
        if(((Number)authority.getOrDefault("roomId",0)).longValue()!=room||((Number)authority.getOrDefault("accountId",0)).longValue()!=account||((Number)authority.getOrDefault("seatNo",-1)).intValue()!=reservation.seat())throw new IllegalStateException("room authority returned mismatched membership");
        return transaction(c->{
            Map<String,Object> replay=idempotent(c,account,key,"JOIN");
            if(replay!=null)return replay;
            lockRoom(c,room);
            try(PreparedStatement s=c.prepareStatement("UPDATE aoo_hall_room_member SET status='JOINED',joined_at=CURRENT_TIMESTAMP(3),left_at=NULL WHERE room_id=? AND account_id=? AND seat_no=? AND status IN('JOINING','JOINED')")){
                s.setLong(1,room);s.setLong(2,account);s.setInt(3,reservation.seat());
                if(s.executeUpdate()!=1)throw new IllegalStateException("reserved Hall membership disappeared before authority confirmation");
            }
            Map<String,Object> result=Map.of("roomId",room,"accountId",account,"seatNo",reservation.seat(),"state",reservation.state(),"route",reservation.route());
            saveIdempotent(c,account,key,"JOIN",result);
            return result;
        });
    }
    private void enforceUniqueRoomMembership(Connection c,long account,long requestedRoom)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT m.room_id,m.status,r.state,a.lifecycle_state,s.state_payload FROM aoo_hall_room_member m JOIN aoo_hall_room r ON r.room_id=m.room_id LEFT JOIN aoo_room_authority_route a ON a.room_id=r.room_id LEFT JOIN aoo_room_snapshot s ON s.room_id=r.room_id WHERE m.account_id=? AND m.room_id<>? AND m.status IN('JOINING','JOINED') FOR UPDATE")){s.setLong(1,account);s.setLong(2,requestedRoom);try(ResultSet r=s.executeQuery()){while(r.next()){long priorRoom=r.getLong(1);String memberState=r.getString(2),roomState=r.getString(3),authorityState=r.getString(4);Map<String,Object> snapshot=r.getString(5)==null?Map.of():json.readValue(r.getString(5),new TypeReference<>(){});if("JOINING".equals(memberState)||!ActiveRoomRecoveryPolicy.isRecoverable(roomState,authorityState,snapshot))markMemberLeft(c,priorRoom,account);else throw HallError.conflict("HALL_ALREADY_IN_ANOTHER_ROOM","account is already in room "+priorRoom);}}}}
    private String membershipStatus(Connection c,long room,long account)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT status FROM aoo_hall_room_member WHERE room_id=? AND account_id=?")){s.setLong(1,room);s.setLong(2,account);try(ResultSet r=s.executeQuery()){return r.next()?r.getString(1):"";}}}
    private void markMemberLeft(Connection c,long room,long account)throws Exception{try(PreparedStatement t=c.prepareStatement("DELETE FROM aoo_hall_game_ticket WHERE room_id=? AND account_id=?")){t.setLong(1,room);t.setLong(2,account);t.executeUpdate();}try(PreparedStatement s=c.prepareStatement("UPDATE aoo_hall_room_member SET status='LEFT',left_at=COALESCE(left_at,CURRENT_TIMESTAMP(3)) WHERE room_id=? AND account_id=? AND status IN('JOINING','JOINED')")){s.setLong(1,room);s.setLong(2,account);s.executeUpdate();}}
    private void releaseFailedJoin(long account,long room,boolean alreadyJoined){if(alreadyJoined)return;transaction(c->{markMemberLeft(c,room,account);return Boolean.TRUE;});}
    private void closeStaleRoom(long room){transaction(c->{try(PreparedStatement t=c.prepareStatement("DELETE FROM aoo_hall_game_ticket WHERE room_id=?")){t.setLong(1,room);t.executeUpdate();}try(PreparedStatement m=c.prepareStatement("UPDATE aoo_hall_room_member SET status='LEFT',left_at=COALESCE(left_at,CURRENT_TIMESTAMP(3)) WHERE room_id=? AND status IN('JOINING','JOINED')")){m.setLong(1,room);m.executeUpdate();}try(PreparedStatement r=c.prepareStatement("UPDATE aoo_hall_room SET state='DISSOLVED',updated_at=CURRENT_TIMESTAMP(3) WHERE room_id=? AND state IN('OPEN','PLAYING')")){r.setLong(1,room);r.executeUpdate();}return Boolean.TRUE;});}
    public Map<String,Object> room(long account,long room){try(Connection c=dataSource.getConnection()){Room value=room(c,room,false);member(c,room,account);List<Map<String,Object>> members=new ArrayList<>();try(PreparedStatement s=c.prepareStatement("SELECT account_id,seat_no,status,joined_at,left_at FROM aoo_hall_room_member WHERE room_id=? ORDER BY seat_no")){s.setLong(1,room);try(ResultSet r=s.executeQuery()){while(r.next())members.add(row(r,"account_id","seat_no","status","joined_at","left_at"));}}Map<String,Object> out=new LinkedHashMap<>(Map.of("roomId",room,"gameId",value.gameId(),"playVersion",value.playVersion(),"classificationRegionCode",value.region(),"state",value.state(),"route",value.route(),"members",members,"scopeType",value.scopeType()));out.put("rules",roomRules(c,room));out.putAll(resourceRoute(c,room));if(value.clubId()>0)out.put("clubId",value.clubId());return out;}catch(RuntimeException e){throw e;}catch(Exception e){throw storage(e);}}
    public Map<String,Object> leave(long account,String key,long room){requireKey(key);return transaction(c->{Map<String,Object> prior=idempotent(c,account,key,"LEAVE");if(prior!=null)return prior;lockRoom(c,room);String status=membershipStatus(c,room,account);if(status.isBlank())throw new HallError(403,"HALL_ROOM_ACCESS_DENIED","room membership required");markMemberLeft(c,room,account);Map<String,Object> result=Map.of("roomId",room,"accountId",account,"status","LEFT");saveIdempotent(c,account,key,"LEAVE",result);return result;});}
    public Map<String,Object> ticket(long account,String key,long room,String device){requireKey(key);require(device,"deviceFingerprint");return transaction(c->{Map<String,Object> prior=idempotent(c,account,key,"TICKET");if(prior!=null)return prior;Room value=lockRoom(c,room);member(c,room,account);byte[] entropy=new byte[32];random.nextBytes(entropy);String ticket=Base64.getUrlEncoder().withoutPadding().encodeToString(entropy);try(PreparedStatement s=c.prepareStatement("INSERT INTO aoo_hall_game_ticket(ticket_hash,room_id,account_id,device_fingerprint,route_endpoint,expires_at,created_at) VALUES(SHA2(?,256),?,?,?,?,DATE_ADD(CURRENT_TIMESTAMP(3),INTERVAL 30 SECOND),CURRENT_TIMESTAMP(3))")){s.setString(1,ticket);s.setLong(2,room);s.setLong(3,account);s.setString(4,device);s.setString(5,value.route());s.executeUpdate();}Map<String,Object> result=Map.of("ticket",ticket,"roomId",room,"route",value.route(),"expiresInSeconds",30);saveIdempotent(c,account,key,"TICKET",result);return result;});}
    /** Game-service boundary: atomically consumes the durable ticket exactly once. */
    public Map<String,Object> consumeTicket(String ticket,String device){require(ticket,"ticket");require(device,"deviceFingerprint");return transaction(c->{try(PreparedStatement s=c.prepareStatement("SELECT room_id,account_id,route_endpoint,device_fingerprint,expires_at,consumed_at FROM aoo_hall_game_ticket WHERE ticket_hash=SHA2(?,256) FOR UPDATE")){s.setString(1,ticket);try(ResultSet r=s.executeQuery()){if(!r.next()||r.getTimestamp("consumed_at")!=null||!clock.instant().isBefore(r.getTimestamp("expires_at").toInstant())||!device.equals(r.getString("device_fingerprint")))throw new HallError(401,"HALL_TICKET_REJECTED","game ticket invalid, expired, or already consumed");long room=r.getLong("room_id"),account=r.getLong("account_id");String route=r.getString("route_endpoint");try(PreparedStatement u=c.prepareStatement("UPDATE aoo_hall_game_ticket SET consumed_at=CURRENT_TIMESTAMP(3) WHERE ticket_hash=SHA2(?,256) AND consumed_at IS NULL")){u.setString(1,ticket);if(u.executeUpdate()!=1)throw new HallError(401,"HALL_TICKET_REJECTED","game ticket already consumed");}return Map.of("roomId",room,"accountId",account,"route",route);}}});}

    private Map<String,Object> validateRules(Connection c,long game,String region,String play,Object rules)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT rule_validator FROM aoo_compiled_room_create_index i JOIN aoo_compiled_index_active a ON a.game_id=i.game_id AND a.region_code=i.region_code AND a.play_version=i.play_version AND a.index_generation=i.index_generation WHERE i.game_id=? AND i.region_code=? AND i.play_version=? AND i.lifecycle_state='ACTIVE'")){s.setLong(1,game);s.setString(2,region);s.setString(3,play);try(ResultSet r=s.executeQuery()){if(!r.next())throw new HallError(503,"HALL_RULE_SCHEMA_UNAVAILABLE","published room rule schema is unavailable");return RoomRuleSchemaValidator.validate(document(r.getString(1)),rules);}}}
    private Map<String,Object> resourceRoute(Connection c,long room)throws Exception{String sql="SELECT i.ui_schema FROM aoo_hall_room h JOIN aoo_compiled_room_create_index i ON i.game_id=h.game_id AND i.region_code=h.classification_region_code AND i.play_version=h.play_version AND i.index_generation=h.index_generation AND i.release_id=h.release_id WHERE h.room_id=?";try(PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,room);try(ResultSet r=s.executeQuery()){if(!r.next())throw new HallError(503,"HALL_RESOURCE_ROUTE_UNAVAILABLE","published game resource route unavailable");Object value=document(r.getString(1));if(!(value instanceof Map<?,?> raw))throw new HallError(503,"HALL_RESOURCE_ROUTE_INVALID","published game resource route is invalid");Object bundleValue=raw.get("bundle"),sceneValue=raw.get("scene");String bundle=bundleValue instanceof String bundleText?bundleText.strip():"",scene=sceneValue instanceof String sceneText?sceneText.strip():"";require(bundle,"bundleName");require(scene,"sceneName");return Map.of("bundleName",bundle,"sceneName",scene);}}}
    private Map<String,Object> roomRules(Connection c,long room)throws Exception{try(PreparedStatement q=c.prepareStatement("SELECT rules_json FROM aoo_hall_room WHERE room_id=?")){q.setLong(1,room);try(ResultSet r=q.executeQuery()){if(!r.next())throw HallError.notFound("room not found");Object value=document(r.getString(1));if(!(value instanceof Map<?,?> raw))return Map.of();Map<String,Object> out=new LinkedHashMap<>();raw.forEach((key,item)->out.put(String.valueOf(key),item));return Map.copyOf(out);}}}
    private String activeRegion(long game,String play){String sql="SELECT a.region_code FROM aoo_compiled_index_active a WHERE a.game_id=? AND a.play_version=? AND EXISTS(SELECT 1 FROM aoo_game_service_route r WHERE r.game_id=a.game_id AND r.play_version=a.play_version AND r.status='ACTIVE') ORDER BY CASE WHEN a.region_code='GLOBAL' THEN 0 ELSE 1 END,a.region_code LIMIT 1";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,game);s.setString(2,play);try(ResultSet r=s.executeQuery()){if(!r.next())throw new HallError(503,"HALL_GAME_ROUTE_UNAVAILABLE","published game route unavailable");return r.getString(1);}}catch(SQLException e){throw storage(e);}}
    private Index lockIndex(Connection c,long game,String region,String play)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT a.release_id,a.index_generation,p.compatibility_floor FROM aoo_compiled_index_active a JOIN aoo_play_version p ON p.game_id=a.game_id AND p.play_version=a.play_version WHERE a.game_id=? AND a.region_code=? AND a.play_version=? FOR UPDATE")){s.setLong(1,game);s.setString(2,region);s.setString(3,play);try(ResultSet r=s.executeQuery()){if(!r.next())throw HallError.notFound("active game index not found");return new Index(r.getLong(1),r.getLong(2),r.getString(3));}}}
    private String route(Connection c,long game,String play)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT endpoint FROM aoo_game_service_route WHERE game_id=? AND play_version=? AND status='ACTIVE' ORDER BY priority,route_id LIMIT 1 FOR UPDATE")){s.setLong(1,game);s.setString(2,play);try(ResultSet r=s.executeQuery()){if(!r.next())throw new HallError(503,"HALL_GAME_ROUTE_UNAVAILABLE","no active game service route");return r.getString(1);}}}
private void authorizeCreateScope(Connection c,RoomCreateSaga.Command command)throws Exception{if(!command.scope().club())return;try(PreparedStatement s=c.prepareStatement("SELECT member_role FROM aoo_club_member WHERE club_id=? AND player_id=? AND member_status='ACTIVE' FOR UPDATE")){s.setLong(1,command.scope().clubId());s.setLong(2,command.accountId());try(ResultSet r=s.executeQuery()){if(!r.next())throw new HallError(403,"HALL_CLUB_MEMBERSHIP_REQUIRED","active club membership required");String role=r.getString(1);if(!Set.of("OWNER","MANAGER","ADMIN").contains(role))throw new HallError(403,"HALL_CLUB_MANAGER_REQUIRED","club manager role required to create rooms");}}}
private void authorizeJoinScope(Connection c,Room room,long account)throws Exception{if(room.clubId()<=0)return;try(PreparedStatement s=c.prepareStatement("SELECT 1 FROM aoo_club_member WHERE club_id=? AND player_id=? AND member_status='ACTIVE'")){s.setLong(1,room.clubId());s.setLong(2,account);try(ResultSet r=s.executeQuery()){if(!r.next())throw new HallError(403,"HALL_CLUB_MEMBERSHIP_REQUIRED","active club membership required");}}}
private void projectClubRoom(Connection c,Room room,long roomId,String status)throws Exception{try(PreparedStatement s=c.prepareStatement("INSERT INTO aoo_club_room_projection(club_id,room_id,template_code,room_status,display_name,created_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE template_code=VALUES(template_code),room_status=VALUES(room_status),display_name=VALUES(display_name)")){s.setLong(1,room.clubId());s.setString(2,String.valueOf(roomId));s.setString(3,room.templateCode());s.setString(4,status);s.setString(5,room.displayName());s.executeUpdate();}}
private Room lockRoom(Connection c,long id)throws Exception{return room(c,id,true);}private Room room(Connection c,long id,boolean lock)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT h.game_id,h.classification_region_code,h.play_version,h.state,h.route_endpoint,h.scope_type,h.club_id,h.club_template_code,g.display_name FROM aoo_hall_room h JOIN aoo_game_catalog g ON g.game_id=h.game_id WHERE h.room_id=?"+(lock?" FOR UPDATE":""))){s.setLong(1,id);try(ResultSet r=s.executeQuery()){if(!r.next())throw HallError.notFound("room not found");return room(r);}}}
private static Room room(ResultSet r)throws SQLException{return new Room(r.getLong("game_id"),r.getString("classification_region_code"),r.getString("play_version"),r.getString("state"),r.getString("route_endpoint"),r.getString("scope_type"),r.getLong("club_id"),r.getString("club_template_code"),r.getString("display_name"));}
    private void member(Connection c,long room,long account)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT 1 FROM aoo_hall_room_member WHERE room_id=? AND account_id=? AND status='JOINED'")){s.setLong(1,room);s.setLong(2,account);try(ResultSet r=s.executeQuery()){if(!r.next())throw new HallError(403,"HALL_ROOM_ACCESS_DENIED","active room membership required");}}}
    private Map<String,Object> idempotent(Connection c,long account,String key,String operation)throws Exception{try(PreparedStatement s=c.prepareStatement("SELECT operation,response_json FROM aoo_hall_idempotency WHERE account_id=? AND idempotency_key=? FOR UPDATE")){s.setLong(1,account);s.setString(2,key);try(ResultSet r=s.executeQuery()){if(!r.next())return null;if(!operation.equals(r.getString(1)))throw HallError.conflict("HALL_IDEMPOTENCY_CONFLICT","idempotency key was used for another operation");return json.readValue(r.getString(2),new TypeReference<>(){});}}}
    private void saveIdempotent(Connection c,long account,String key,String operation,Map<String,Object> result)throws Exception{try(PreparedStatement s=c.prepareStatement("INSERT INTO aoo_hall_idempotency(account_id,idempotency_key,operation,response_json,created_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP(3))")){s.setLong(1,account);s.setString(2,key);s.setString(3,operation);s.setString(4,json.writeValueAsString(result));s.executeUpdate();}}
    private <T>T transaction(SqlWork<T> work){try(Connection c=dataSource.getConnection()){c.setAutoCommit(false);try{T out=work.run(c);c.commit();return out;}catch(Exception e){c.rollback();if(e instanceof RuntimeException r)throw r;throw new IllegalStateException(e);}}catch(SQLException e){throw storage(e);}}
    private Object document(String value){try{return json.readValue(value,Object.class);}catch(Exception e){throw new IllegalStateException("invalid catalog JSON",e);}}
    static Map<String,Object> settlementUi(String familyCode,Object raw){
        if(!(raw instanceof Map<?,?> source))throw HallError.bad("HALL_INVALID_UI_SCHEMA","ui schema must be an object");
        Map<String,Object> out=new LinkedHashMap<>();source.forEach((key,value)->out.put(String.valueOf(key),value));
        String big=optionalText(out.get("bigSettleTemplate"));
        if(!big.isEmpty()&&!big.matches("^BigSettleTpl_[0-9]{2,}$"))throw HallError.bad("HALL_INVALID_SETTLEMENT_TEMPLATE","invalid big settlement template");
        String small=optionalText(out.get("smallSettleTemplate"));
        if(!small.isEmpty()){
            String family=canonicalFamily(familyCode),alias=switch(family){case "poker:pao-de-kuai"->"pdk";case "poker:compare-hand"->"zjh";case "poker:betting"->"nn";case "poker:landlord"->"ddz";case "poker:510k"->"510k";case "poker:climbing"->"climbing";case "poker:generic-card-round"->"generic_card_round";case "poker:trick-taking"->"trick_taking";default->"";};
            String pattern=alias.isEmpty()?"^SmallSettleTpl_[0-9]{2,}$":"^SmallSettleTpl_"+alias+"_[0-9]{2,}$";
            if(!small.matches(pattern))throw HallError.bad("HALL_INVALID_SETTLEMENT_TEMPLATE","small settlement template does not belong to play family");
        }
        return Collections.unmodifiableMap(out);
    }
    private static String optionalText(Object value){return value==null?"":String.valueOf(value).trim();}
    private static String canonicalFamily(String value){String family=optionalText(value).toLowerCase(Locale.ROOT).replace('_','-');if(family.contains(":"))return family;int split=family.indexOf('-');return split>0?family.substring(0,split)+":"+family.substring(split+1):family;}
    private static Map<String,Object> row(ResultSet r,String... names)throws SQLException{Map<String,Object> out=new LinkedHashMap<>();for(String n:names)out.put(camel(n),r.getObject(n));return out;}private static String camel(String n){StringBuilder b=new StringBuilder();boolean up=false;for(char c:n.toCharArray()){if(c=='_'){up=true;}else{b.append(up?Character.toUpperCase(c):c);up=false;}}return b.toString();}
    private static boolean compatible(String client,String floor){return floor==null||floor.isBlank()||compareVersions(client,floor)>=0;}private static void requireCompatible(String client,String floor){require(client,"clientVersion");if(!compatible(client,floor))throw new HallError(426,"HALL_CLIENT_UPGRADE_REQUIRED","client version is below compatibility floor "+floor);}
    static int compareVersions(String a,String b){String[] x=a.split("[.-]"),y=b.split("[.-]");for(int i=0;i<Math.max(x.length,y.length);i++){String l=i<x.length?x[i]:"0",r=i<y.length?y[i]:"0";int c;if(l.matches("\\d+")&&r.matches("\\d+"))c=new java.math.BigInteger(l).compareTo(new java.math.BigInteger(r));else c=l.compareToIgnoreCase(r);if(c!=0)return c;}return 0;}
    private static String text(Map<String,Object> m,String name){Object v=m.get(name);String s=v==null?null:String.valueOf(v);require(s,name);return s;}private static long number(Map<String,Object> m,String name){try{long v=Long.parseLong(String.valueOf(m.get(name)));if(v<=0)throw new Exception();return v;}catch(Exception e){throw HallError.bad("HALL_INVALID_REQUEST",name+" must be positive");}}private static void require(String s,String name){if(s==null||s.isBlank())throw HallError.bad("HALL_INVALID_REQUEST",name+" is required");}private static void requireKey(String s){require(s,"Idempotency-Key");if(s.length()>128)throw HallError.bad("HALL_INVALID_REQUEST","Idempotency-Key is too long");}private static IllegalStateException storage(Exception e){return new IllegalStateException("hall persistence failure",e);}
    private record Index(long releaseId,long generation,String compatibilityFloor){}private record Room(long gameId,String region,String playVersion,String state,String route,String scopeType,long clubId,String templateCode,String displayName){}private record JoinReservation(int seat,String playVersion,String state,String route,boolean alreadyJoined){}@FunctionalInterface private interface SqlWork<T>{T run(Connection c)throws Exception;}
}
