package com.aoo.bcg.hall.room;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import javax.sql.DataSource;import java.sql.*;import java.time.Duration;import java.util.*;
public final class JdbcRoomCreateSagaStore implements RoomCreateSaga.Store{
 private final DataSource ds;private final ObjectMapper json;public JdbcRoomCreateSagaStore(DataSource ds,ObjectMapper json){this.ds=Objects.requireNonNull(ds);this.json=Objects.requireNonNull(json);}
 public RoomCreateSaga.State begin(RoomCreateSaga.Command c){try(Connection x=ds.getConnection();PreparedStatement s=x.prepareStatement("INSERT INTO aoo_room_create_saga(request_id,request_hash,request_json,account_id,room_id,game_id,play_version,state_version,step,trace_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,'STARTED',?,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE request_id=request_id")){s.setString(1,c.requestId());s.setString(2,c.requestHash());s.setString(3,json.writeValueAsString(c.requestBody()));s.setLong(4,c.accountId());s.setLong(5,c.roomId());s.setInt(6,c.gameId());s.setString(7,c.playVersion());s.setString(8,c.traceId());s.executeUpdate();return get(x,c.requestId());}catch(Exception e){throw new IllegalStateException("room saga persistence failure",e);}}
 public RoomCreateSaga.State find(String id){try(Connection x=ds.getConnection()){return get(x,id);}catch(Exception e){throw new IllegalStateException("room saga lookup failure",e);}}
 public RoomCreateSaga.State advance(String id,long version,RoomCreateSaga.Step step,Map<String,Object>response){update(id,version,step,response,null);return find(id);}
 public void fail(String id,long version,RoomCreateSaga.Step step,RoomCreateSaga.Step origin,String reason){try(Connection x=ds.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_create_saga SET step=?,compensation_origin_step=?,state_version=state_version+1,failure_code=?,attempt_count=attempt_count+1,next_retry_at=CASE WHEN ?='COMPENSATION_PENDING' AND attempt_count<9 THEN DATE_ADD(CURRENT_TIMESTAMP(3),INTERVAL LEAST(60,POW(2,attempt_count)) SECOND) ELSE NULL END,updated_at=CURRENT_TIMESTAMP(3) WHERE request_id=? AND state_version=?")){s.setString(1,step.name());s.setString(2,origin.name());s.setString(3,reason);s.setString(4,step.name());s.setString(5,id);s.setLong(6,version);if(s.executeUpdate()!=1)throw new IllegalStateException("stale room saga stateVersion");}catch(Exception e){throw e instanceof RuntimeException r?r:new IllegalStateException(e);}}
 public boolean acquire(String id,String token,Duration lease){try(Connection x=ds.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_create_saga SET processing_token=?,processing_until=DATE_ADD(CURRENT_TIMESTAMP(3),INTERVAL ? SECOND) WHERE request_id=? AND (processing_until IS NULL OR processing_until<CURRENT_TIMESTAMP(3) OR processing_token=?)")){s.setString(1,token);s.setLong(2,Math.max(5,Math.min(120,lease.toSeconds())));s.setString(3,id);s.setString(4,token);return s.executeUpdate()==1;}catch(Exception e){throw new IllegalStateException("room saga lock failure",e);}}
 public void release(String id,String token){try(Connection x=ds.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_create_saga SET processing_token=NULL,processing_until=NULL WHERE request_id=? AND processing_token=?")){s.setString(1,id);s.setString(2,token);s.executeUpdate();}catch(Exception e){throw new IllegalStateException("room saga unlock failure",e);}}
 public List<RoomCreateSaga.Pending>pending(int limit){String sql="SELECT account_id,request_id,request_json FROM aoo_room_create_saga WHERE request_json IS NOT NULL AND step NOT IN ('CONFIRMED','COMPENSATED') AND (processing_until IS NULL OR processing_until<CURRENT_TIMESTAMP(3)) AND ((next_retry_at IS NOT NULL AND next_retry_at<=CURRENT_TIMESTAMP(3)) OR updated_at<DATE_SUB(CURRENT_TIMESTAMP(3),INTERVAL 15 SECOND)) ORDER BY COALESCE(next_retry_at,updated_at),request_id LIMIT ?";try(Connection x=ds.getConnection();PreparedStatement s=x.prepareStatement(sql)){s.setInt(1,limit);List<RoomCreateSaga.Pending>out=new ArrayList<>();try(ResultSet r=s.executeQuery()){while(r.next())out.add(new RoomCreateSaga.Pending(r.getLong(1),r.getString(2),json.readValue(r.getString(3),new TypeReference<>(){})));}return List.copyOf(out);}catch(Exception e){throw new IllegalStateException("room saga recovery scan failure",e);}}
 private void update(String id,long version,RoomCreateSaga.Step step,Map<String,Object>response,String failure){try(Connection x=ds.getConnection();PreparedStatement s=x.prepareStatement("UPDATE aoo_room_create_saga SET step=?,compensation_origin_step=NULL,state_version=state_version+1,response_json=COALESCE(?,response_json),failure_code=?,next_retry_at=NULL,updated_at=CURRENT_TIMESTAMP(3) WHERE request_id=? AND state_version=?")){s.setString(1,step.name());s.setString(2,response==null?null:json.writeValueAsString(response));s.setString(3,failure);s.setString(4,id);s.setLong(5,version);if(s.executeUpdate()!=1)throw new IllegalStateException("stale room saga stateVersion");}catch(Exception e){throw e instanceof RuntimeException r?r:new IllegalStateException(e);}}
 private RoomCreateSaga.State get(Connection x,String id)throws Exception{try(PreparedStatement s=x.prepareStatement("SELECT request_hash,step,state_version,response_json,compensation_origin_step FROM aoo_room_create_saga WHERE request_id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("room saga missing");Map<String,Object>out=r.getString(4)==null?Map.of():json.readValue(r.getString(4),new TypeReference<>(){});String origin=r.getString(5);return new RoomCreateSaga.State(id,r.getString(1),RoomCreateSaga.Step.valueOf(r.getString(2)),r.getLong(3),out,origin==null?null:RoomCreateSaga.Step.valueOf(origin));}}}
}
